### ISSUE TITLE
navbar not working - android, mobile view

### ISSUE THREAD

**Issue by iiegn** [thednp/bootstrap.native#10]
on my android (4.1.2) phone with chrome 43.0.2357.78 (and also with the 'Internet' app) the navbar cannot be toggled, this means the menu items are not visible and navigating a site is impossible.

first experienced on my own site but it actually happens on http://thednp.github.io/bootstrap.native/, too.
 
 - only occurs on the actual device; inside the chrome developer tools things work just fine
 - while loading the page an ``Uncaught ReferenceError: Popover is not defined(anonymous function) @ scripts.js:5`` error occurs (via: [Remote Debugging on Android with Chrome](https://developer.chrome.com/devtools/docs/remote-debugging))

**Comment by thednp** [comment]
Hey, can you please do a test like this on your phone

```
var btn = document.querySelector('.myButtonMenu'); // give the selector a proper value here, create the button
var div = document.querySelector('.myDiv'); // give the selector a proper div, a demo only div, create the div

btn.addEventListener('click',function(){
  div.innerHTML = 'clicked'
},false);
```

I need to know if the click is triggered, or it's a CSS glitch.
Thanks for reporting.

**Comment by thednp** [comment]
Closing this until further notice.

**Comment by iiegn** [comment]
for all intents and purposes, this seems to have been solved.
tried with 
 * android 5.1.1 and chrome 47.0.2526.83
 * android 4.2.2 and native browser app
on http://thednp.github.io/bootstrap.native/
(sorry, for not getting back earlier)

**Comment by thednp** [comment]
Thanks for the heads up.
