### ISSUE TITLE
simplest example of a working modal dialog?

### ISSUE THREAD

**Issue by Jeff17Robbins** [thednp/bootstrap.native#100]
Hi.  Naively, I tried to create a test Modal on jsfiddle using the first example at [http://thednp.github.io/](http://thednp.github.io/bootstrap.native/#examples)

I am new to bootstrap, so I am guessing I am missing some assumed background knowledge.  But, as the jsfiddle link below shows, I can't simply cut and paste the `<button>` and `<div> dialog onto a blank page and have something popup.`

[jsfiddle link](https://jsfiddle.net/o2ectmr1/)

Is there an example of the simplest possible HTML page that can launch a Modal?  Or, what's the least amount of HTML I have to add to my jsfiddle to make the Modal launchable?

**Comment by thednp** [comment]
The resolve is simple: you need to link the bootstrap.native script at the end of the body, not in the `<head>`, not at the beginning of the `<body>`, but at the END of the `<body>`.

Check the changes in my updated fiddle here:
https://jsfiddle.net/o2ectmr1/1/

**Comment by Jeff17Robbins** [comment]
That is simple!

So it seems that the code wants the DOM to all be there before it loads.  I am using webcompinents, some of which might not render into the DOM until later.  It would be a nice enhancement if I could either 

1) give bootstrap-native an event or even a Promise to wait on before inspecting the DOM
Or
2) expose a function that lets me decide when bootstrap-native ought to inspect the DOM

**Comment by thednp** [comment]
@Jeff17Robbins I am open to any suggestion on how to handle any `Promise` or webpack related work, it should probably have to deal with the way we init the script [here](https://github.com/thednp/bootstrap.native/blob/master/lib/modal-native.js#L211-L219).

**Comment by RyanZim** [comment]
@Jeff17Robbins Does the jquery version of bootstrap even support that?

**Comment by Jeff17Robbins** [comment]
I have no idea. I am not a Bootstrap user (because jQuery) but was intrigued by the potential benefits of Bootstrap's mature CSS framework without jQuery.

**Comment by RyanZim** [comment]
Given the fact that bootstrap native doesn't even support everything bootstrap does, I'm not in favor of adding this.

**Comment by Jeff17Robbins** [comment]
Yes, I agree it is reasonable to focus on parity with the jQuery functions.  But the "run the script last" approach seems brittle, and out of step with other frameworks.

**Comment by RyanZim** [comment]
@Jeff17Robbins You can always call bootstrap-native programatically later. The jQuery version works the same IIRC.

**Comment by Jeff17Robbins** [comment]
That is a good solution.  What function ought I call?

**Comment by RyanZim** [comment]
This is the code bsn actually runs on page load, you could easily run this yourself:

```js
var Modals = document.querySelectorAll('.modal');
for ( var m = 0, mdl = Modals.length; m<mdl; m++ ) {
  var modal = Modals[m], options = {};
  options.keyboard = modal.getAttribute('data-keyboard');
  options.backdrop = modal.getAttribute('data-backdrop');
  options.duration = modal.getAttribute('data-duration');
  new Modal(modal,options)
}
```

**Comment by Jeff17Robbins** [comment]
Sure, but each module has its own logic, and presumably could evolve over time.  Why not expose a public function for people working with frameworks that manipulate the DOM after page load?

**Comment by RyanZim** [comment]
As far as I'm aware `new Modal(modal,options)` isn't changing without a major version. All the same, not terribly opposed to a public function. @thednp ?

**Comment by thednp** [comment]
@RyanZim I was about to ask you: is there anything else we can do to give these people something to work with? I kinda agree `new Modal(..)` should do in most cases but I don't know much about these frameworks.

**Comment by RyanZim** [comment]
@thednp Frankly, I don't know much more than you. IIRC, webcomponents isn't totally standardized yet; I would leave things as they are for the time being and possibly revisit later. If we get a PR that tries to address this, we can discuss this then.

**Comment by thednp** [comment]
@RyanZim I agree.

**Comment by Jeff17Robbins** [comment]
In case anyone is using  [webcomponents](https://github.com/WebComponents/webcomponentsjs), and wants the great benefits of jQuery-free Bootstrap-native, here's [a simple example](https://jsfiddle.net/8geg9mbt/) of burying the bootstrap files in an HTML Import.

The file `bootstrap.html` contains these 3 lines:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/1.1.0/bootstrap-native.min.js"></script>
```

And is used like so, in the `<head>` of your page, so no need to place a script at the bottom of `<body>`.

```
<script src='https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.23/webcomponents-lite.js'>
</script>
<link rel='import' href='https://gist.githubusercontent.com/Jeff17Robbins/7c42e55cdb1f71de2e3fb4600d7fda25/raw/a7f4cd51ffd568878bddcafcd95f666cd4af5ee9/bootstrap.html'>
```

**Comment by thednp** [comment]
Thanks for the find @Jeff17Robbins.
