### ISSUE TITLE
Tooltip doesn't hide when parent element removed

### ISSUE THREAD

**Issue by mathieuleclaire** [thednp/bootstrap.native#101]
Hi,
I get exactly the same problem described in the following issue. It does not seem to exist any hide function to fix this. Is it doable ?
Thanks

https://github.com/twbs/bootstrap/issues/3084

**Comment by thednp** [comment]
Yes, the new code will have a usage guide on how to access methods.

**Comment by mathieuleclaire** [comment]
Cool, when do you think you could provide this ?

**Comment by thednp** [comment]
The code is ready but I haven't finished documenting it, stay in touch 2-3 days.

**Comment by RyanZim** [comment]
Quick example (haven't tried it):
```js
var item = document.getElementById('item')
var tip = new Tooltip(item)
tip.removeToolTip()
// Remove item:
item.parentNode.removeChild(item);
```

**Comment by thednp** [comment]
Nop, you need to use `tip.close();`

**Comment by mathieuleclaire** [comment]
nice, I am waiting !

**Comment by RyanZim** [comment]
@thednp Just a shot in that dark, glancing at the source code. :dart:  Sorry I missed.

**Comment by thednp** [comment]
@mathieuleclaire please check the new commit, doc/demo updated, codebase updated

https://github.com/thednp/bootstrap.native/commit/2a079b06c2304a1cebdc16a385f5049024911857

**Comment by mathieuleclaire** [comment]
Hi,
I made some tries with the 2.0.2. The following use case does not work: I build a span with 
- a tooltip on it and 
- a function removing the span when clicking on it as well as a call before the deletion to the Tooltip ```hide()``` function.

The span is deleted but not the tooltip. Using ```removeToolTip()``` leads the same result. The best behaviour by the way would be that the tooltip vanishes when its parents is deleted.
Do you reproduce the same behaviour ?

**Comment by thednp** [comment]
Your span holds the Tooltip initialization like so:

```js
var myInit = mySpan.Tooltip;
```

Now if you remove the span, before that you need to do

```js
myInit.hide();
```
