### ISSUE TITLE
Use with React (Class based component)

### ISSUE THREAD

**Issue by kenshinman** [thednp/bootstrap.native#103]
Hello, Thanks for this wonderful is there a way to rewrite. I'm trying to use it with React (Class based components), and I'm having troubles implementing it. Is there a way to do this thanks

**Comment by thednp** [comment]
If you use the proper markup and make sure visibility toggling CSS is in place, you can use with anything.

Now I am not going to tell you how to do that, you need to investigate yourself, currently I am working on a new version release.
