### ISSUE TITLE
static is a reserved word in JS

### ISSUE THREAD

**Issue by RyanZim** [thednp/bootstrap.native#104]
At [lib/modal-native.js#L17](https://github.com/thednp/bootstrap.native/blob/2a079b06c2304a1cebdc16a385f5049024911857/lib/modal-native.js#L17), you are declaring a variable with the name `static`. That is a reserved word in JS, so that is invalid JS. My module bundler refuses to bundle bootstrap.native. Please rename the variable, or remove it altogether. (Not sure what the benefit of it is.)

**Comment by thednp** [comment]
Yes, please do a test and report anything you can find, I will fix them all ASAP.
