### ISSUE TITLE
Popover position

### ISSUE THREAD

**Issue by c01nd01r** [thednp/bootstrap.native#105]
Hi!
I looked modal component on the demo site and I think Popover have wrong positioning. 
Look at this screencast https://youtu.be/crzMnjpX7-w

**Comment by thednp** [comment]
I tested on my phone and it's working as expected. Either the Chrome emulator is wrong OR the Chrome emulator injects the document into another kind of invisible `<iframe>` and the component will compute the position based on the root document and not the one in the `<iframe>`.

Next time, test on your phone first.

**Comment by c01nd01r** [comment]
Ok, I tested it on my Android 7.1 and Chrome 55.0.2883.91
https://drive.google.com/file/d/0BwZyHEp890XdMG5pNzJBYTI1S2c/view?usp=sharing
Nothing has changed

**Comment by thednp** [comment]
Oh I see. Well, our Popover and Tooltip components have no handler for touch events.

I am now thinking of 2 possible ways:
* we either close the tooltip on scroll/touchmove
* or we create a new handler to update the position on scroll/tochmove

**Comment by thednp** [comment]
This must be related to the changes needed to [make it work for SVGs](https://github.com/thednp/bootstrap.native/commit/caaac8b45ca1b2460999de4a465359f06afd6933)

**Comment by thednp** [comment]
OK I will look into it and hopefully provide a fix ASAP.

Thanks for reporting.

**Comment by thednp** [comment]
Ok please test the new code, demo and docs updated and report back any other issues.
