### ISSUE TITLE
Feature request - bootstrap 4

### ISSUE THREAD

**Issue by djforth** [thednp/bootstrap.native#107]
I did try to plug it into a bootstrap 4 project, but looks like structure and api has changed a bit, so didn't work in the few areas I checked. As fair as I can see there is no bootstrap 4 version, is there one in the pipeline? Would be happy to take a look/help out. 

I know there is a big push on bootstrap 4, so would be great to have a bootstrap 4 version.

**Comment by thednp** [comment]
I haven't tried this yet, but I think it should be fine so I will do some tests today with the code from our current master.

I will let you know the result in a couple of hours.

**Comment by thednp** [comment]
It's just a matter of CSS class rename here and there, I got the Carousel to work already.

**Comment by dgt41** [comment]
modal is using different markup (one more nesting div before modal-body)

**Comment by thednp** [comment]
> modal is using different markup (one more nesting div before modal-body)

I know, it's something for Apple stuff.

**Comment by thednp** [comment]
@dgt41 I see no difference between [v3](http://getbootstrap.com/javascript/#modals-examples) and [v4](https://v4-alpha.getbootstrap.com/components/modal/#live-demo) in terms of markup.

**Comment by dgt41** [comment]
@thednp you're right, probably confused with something else

**Comment by thednp** [comment]
OK I managed to have it all for BS4, anyone interested in a test?

Components
* Carousel 
* Collapse
* Tooltip
* Popover
* Tab
* Dropdown
* ScrollSpy
* Alert
* Modal
* Button (except the state toggle method, only for checkboxes and radios for now)
* Affix has been removed

**Comment by thednp** [comment]
> @thednp you're right, probably confused with something else

Tooltip, Popover and ScrollSpy have changed the way they work as of markup structure.

**Comment by dgt41** [comment]
@thednp what's the branch?

**Comment by thednp** [comment]
Same branch, the `/lib` folder is split in two: V3 and V4, also a new root folder `/dist-v4`.

Coming soon, I am preparing a small demo atm.

**Comment by dgt41** [comment]
@thednp for v4 I think you need to remove all the polyfills, bs4 supports IE>10

**Comment by thednp** [comment]
@dgt41 indeed, however, users can choose exactly what they need.

I would need some suggestions on how to name the files for BS4.

**Comment by thednp** [comment]
@dgt41 and @djforth please test

http://thednp.github.io/bootstrap.native/v4.html

**Comment by thednp** [comment]
@dgt41 IE10+ still need `Event`, `CustomEvent` and `dispatchEvent` polyfills, so polyfills are there to stay.

**Comment by djforth** [comment]
That was quick! Will check tomorrow when I'm in front of a computer

**Comment by thednp** [comment]
We can close this for now.

**Comment by djforth** [comment]
Yes sorry been caught up on projects!  Did test on Chrome & FF and all good
