### ISSUE TITLE
Modal accessibility issues

### ISSUE THREAD

**Issue by danielnixon** [thednp/bootstrap.native#109]
The bootstrap.native modal has some accessibility regressions compared to vanilla Bootstrap 3. In particular, it doesn't trap keyboard focus within the modal and it doesn't restore keyboard focus to the element that triggered the modal after it is closed.

Compare https://thednp.github.io/bootstrap.native/#modalExamples to https://getbootstrap.com/javascript/#live-demo

**Comment by thednp** [comment]
I haven't had the chance to keep track of every improvement of the original plugins over time, this one is probably a new feature with v3.1+, where `bootstrap.native` started around the 3.0 series.

Feel free to add your contribution or suggestion on how it should work.

**Comment by thednp** [comment]
@danielnixon please test latest master and let me know how it works.
