### ISSUE TITLE
No default value set for options.backdrop && TypeError: this.init is not a function?

### ISSUE THREAD

**Issue by andrewdavidcostello** [thednp/bootstrap.native#11]
1133TypeError: undefined is not an object (evaluating 'options.backdrop')

this.options.backdrop = options.backdrop === 'false' ? false : true;
this.options.keyboard = options.keyboard === 'false' ? false : true;
this.options.content = options.content;

It doesn't appear to have any default values set, is this intentional? I see it tries to populate these via the data attribute on load? (Maybe VueJS is causing issues)

I am trying to use an already existing modal template in the dom using (VueJs):

modal = this.bootstrap.modal(document.getElementById('#uploadModal'), {
                backdrop: true,
});
modal.open();

Which I thought would simply open the existing modal?

After sorting the above and passing in options.backdrop I simply receive:

TypeError: this.init is not a function. (In 'this.init()', 'this.init' is undefined)

**Comment by thednp** [comment]
Kinda, priority is the `data-` option.

**Comment by andrewdavidcostello** [comment]
Hey,

Sorry for the late reply. Basically I have a modal in the DOM already (nothing special about it generic bootstrap 3 markup).

I am using browserify and assigning bootstrap.native to this.boostrap.

So as above:

var modal = this.bootstrap.modal(document.getElementById('#uploadModal'), {
backdrop: true,
});

Then I need to call:

modal.open();

But I was getting the error above, was there anything specifically you wanted to know beyond that?

**Comment by thednp** [comment]
You should do `new Modal(modal,options)` in order to work, in your setup maybe something like `new this.bootstrap.modal(modal,options)` which would mean that you do something called `invoke` yourself on your specific setup. Basically override the basic invoke via the `data` code shown here
https://github.com/thednp/bootstrap.native/blob/master/lib/modal-native.js#L180-L186

**Comment by andrewdavidcostello** [comment]
showModal: function() {
        var modal = new this.bootstrap.modal(this.$$.uploadModal, {
            backdrop: true,
        });
        modal.open();
}

Worked perfectly, thanks!

**Comment by thednp** [comment]
Great :)
