### ISSUE TITLE
dist-v4 missing installing via npm

### ISSUE THREAD

**Issue by quantix-studio** [thednp/bootstrap.native#110]
is there a branch or version to specify ?

Thanx for the job !

**Comment by thednp** [comment]
I haven't decided on it yet, first I must talk to the CDN hosts on how to publish V4.

BUT before all that , we all need to test everything, I don't want to patch versions over and over.

**Comment by thednp** [comment]
@quantix-studio, while things get settled down you can meanwhile install from Github directly

https://docs.npmjs.com/cli/install

**Comment by thednp** [comment]
OK Now you should have it on npm, closing it.
