### ISSUE TITLE
Dropdown clickHandlerTypeError

### ISSUE THREAD

**Issue by KuroThing** [thednp/bootstrap.native#114]
When you click the the `body` element, [this line of code](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/dropdown-native.js#L30) produces this error: `TypeError: eventTarget[parentNode][getAttribute] is not a function`

Tested on v2.0.3 and v2.0.4 (Commit: cf981a6)

A (imo) dirty hack i found to solve this would be to do something like `typeof eventTarget[parentNode] === HTMLDocument` and if so, setting `hasData` to false.

Edit: It should be noted that this error occurs irrelevant of if the dropdown is open or not.

**Comment by thednp** [comment]
Cannot reproduce. Do you have a screenshot?

**Comment by KuroThing** [comment]
Using the [Fixed Navbar Example](https://v4-alpha.getbootstrap.com/examples/navbar-top-fixed/) for the v4 version of bootstrap, if you _had_ a dropdown on that page and clicked under the `div.container` element, it would be clicking the `body` element directly. This is what re-produces the error.

The requested image with the area i'm talking about highlighted in a thin red border w/ some text in it.
![image](https://cloud.githubusercontent.com/assets/18753877/22883657/4e8c0a82-f245-11e6-8db3-7fb341d0d4d3.png)

Does that help?

**Comment by thednp** [comment]
No. The script won't initialize if you inject it on the Bootstrap demo pages on the fly, you need to have it there when the DOM is parsed.
![bsn-dropdown-working-properly](https://cloud.githubusercontent.com/assets/6761246/22884407/710965c0-f1fd-11e6-8337-b09103cdadf2.png)

**Comment by KuroThing** [comment]
I was providing an example using the bootstrap documentation, of course locally i'm including the script straight away, but rather then trying to giving you the segmented parts of my layout i figured using one of the examples from the bootstrap documentation.

If you click on the area below the `div.container` you'll get a TypeError. Modifying the v4 javascript file in dist to output `eventTarget[parentNode]` said it was a `HTMLDocument`.

Here, let me use your own sites documentation then.

Add an absurd `height` property to the body element, and scroll to the bottom of the page. Open the dev console and go to the inspect area, insure you are over the `body` element and click a few times. You'll get the error.

Here, have a screenshot of the errors, along with the body being highlighted
![image](https://cloud.githubusercontent.com/assets/18753877/22884661/353c8a5c-f24a-11e6-8d7e-1d14188ae91e.png)

**Comment by thednp** [comment]
Please download latest master and test. Thank you.

**Comment by thednp** [comment]
@KuroThing all good?

**Comment by rafaph** [comment]
Same here, using the master version solved the problem. Thanks guys!

**Comment by yurimdh** [comment]
I'm still having this error. It can be reproduced doing what @KuroThing said above: in your own documentation (http://thednp.github.io/bootstrap.native), add an absurd height property to the body element, and scroll to the bottom of the page. Open the dev console and go to the inspect area, insure you are over the body element and click a few times. You'll get the error.

**Comment by thednp** [comment]
OK now, please check the latest master, if we come clean, we publish the new version to the clouds right after.

**Comment by AustinBrunkhorst** [comment]
I'm using Aurelia with this library, which makes use of document fragments quite a bit. When a fragment is the parent node, this error occurs.

The latest push to master fixes the issue for me, @thednp. Cheers!
