### ISSUE TITLE
Cannot build using the latest source code

### ISSUE THREAD

**Issue by thinkpozzitive** [thednp/bootstrap.native#116]
I'm getting the following error whenever I'm trying to run the `node build.js` command for bootstrap 3:
```bootstrap.native/build.js:34
.coerce(['ignore', 'only'], getModuleNames)
 ^
TypeError: require(...).usage(...).options(...).coerce is not a function
```
Am I missing something?

**Comment by RyanZim** [comment]
Works fine for me, are you passing any arguments to the script?

Also, try `rm -rf node_modules && npm install`.

**Comment by thednp** [comment]
I cannot confirm @thinkpozzitive 's issue, but I trust @RyanZim to be accurate with his comments.

**Comment by RyanZim** [comment]
Sorry, haven't tested it much yet.

**Comment by dgt41** [comment]
@thednp you need to add MS and opera:
```
transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd
```
Also the `aria-expanded` on the first panel of the accordion doesn't change state

**Comment by thednp** [comment]
@dgt41 as of 2016 the only events needed are `transitionend webkitTransitionEnd`, [details](https://www.w3schools.com/jsref/event_transitionend.asp), and yes I know [the Bootstrap CSS](https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css#L5881-L5884) and BS4 still uses `o-transition` for BS3, but I don't see why `MSTransitionEnd`.

About the `aria-expanded` I will look into it.

**Comment by thinkpozzitive** [comment]
@RyanZim npm install fixed the issue. I was missing a  module. 

Thanks.
