### ISSUE TITLE
Access to pause function

### ISSUE THREAD

**Issue by malcocerGit** [thednp/bootstrap.native#117]
There is a way to access to pause function? I'm trying to stop the carousel when a event is fire, but I can't stoped, the carousel is still ride. 

Regards.

**Comment by thednp** [comment]
You can hook into the `slid.bs.carousel` and check if the carousel element has the `paused` class, it should do what you need in that specific case.

**Comment by malcocerGit** [comment]
Thanks for you answer, I added `paused` class, but when you add the class the timeOut to go to next slide is ready, the slide is paused but in the next slide not the first.

**Comment by thednp** [comment]
You mean you want to disable auto slide?

**Comment by malcocerGit** [comment]
Yes, but on demand not on hover, it's possible?

**Comment by thednp** [comment]
Then try to add the `paused` class with the `slide.bs.carousel` event.

**Comment by malcocerGit** [comment]
It works but on the next slide, not the slide where I clicked

`var carousel = document.getElementById("Carousel");
carousel.addEventListener('click', function(){
	carousel.addEventListener('slide.bs.carousel', function(){
		carousel.classList.add('paused');
	});	});`

**Comment by thednp** [comment]
```js
var carousel = document.getElementById("Carousel"); 

carousel.addEventListener('slide.bs.carousel', function(){ 
  carousel.classList.add('paused'); 
}); 

carousel.addEventListener('click', function(){ 
  // do some other stuff, like breaking the paused state
  if ('your condition is met') {
    carousel.Carousel.cycle();
  }
});
```
