### ISSUE TITLE
SCRIPT5022: Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by world33** [thednp/bootstrap.native#119]
Hi,

When using the Chrome or IE developer console I get the following error message:

SCRIPT5022: Bootstrap's JavaScript requires jQuery

Can I just ignore this error/warning when using bootstrap.native ?

Thanks

**Comment by RyanZim** [comment]
@world33 You must be including bootstrap's JS in your HTML. Remove that, and only include bootstrap native. That should fix your issue.
