### ISSUE TITLE
drop down menu in internet explorer 11 not working

### ISSUE THREAD

**Issue by world33** [thednp/bootstrap.native#120]
The drop down menu when using IE11 does not seem to be working. In chrome it works.
Test page (top navigation menu): http://www.4icu.org/index2.htm

**Comment by world33** [comment]
Also is it possible to add async in the script tags just before the </body> tag?
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.6/bootstrap-native.min.js" **async**></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" **async**></script>

**Comment by thednp** [comment]
You need to read the doc/demo page regarding browser support regarding using the polyfill.

**Comment by world33** [comment]
Thanks.
 I meant the closing body tag. The question was focusing on the async addition to the tag.
Would adding async cause any problem?

**Comment by thednp** [comment]
Try and let us know, I haven't tested this in particular.
