### ISSUE TITLE
Accordion - "collapsed" Class not added to the toggle link when opening a different Panel.

### ISSUE THREAD

**Issue by mgrixti** [thednp/bootstrap.native#122]
Using Version: 2.0.7 (Bootstrap 3)

When there is an open panel and you click a different panel's toggle link, it will close the open panel but it does not add the "collapsed" class to the toggle link. When you click the toggle link of the current open panel it does add the collapsed class to the toggle link.

The official Bootstrap Collapse/Accordion does add the "collapsed" class when clicking a different panel's toggle link.

You can inspect/compare the accordions in the documentation for Bootstrap Native and Official Bootstrap to see an example of the bug in action. When you click an unopened panel, you can see it does not add the "collapse" class to the toggle link of the open panel that gets closed upon opening a different panel.

Bootstrap Native Accordion: https://thednp.github.io/bootstrap.native/#accordion
Bootstrap Official Accordion: http://getbootstrap.com/javascript/#accordion

**Comment by thednp** [comment]
I'll have a look into it asap. Thanks

**Comment by thednp** [comment]
@mgrixti Please test latest master and let me know how it goes.

**Comment by mgrixti** [comment]
@thednp That fixed it. Thanks for fixing it so quickly.
