### ISSUE TITLE
.modal-open class not removed when closing modal quickly

### ISSUE THREAD

**Issue by adibbz** [thednp/bootstrap.native#125]
I have multiple modals on a page and whenever I open one and close it quickly by either the `.close` button or clicking outside the modal the `.modal-open` class does not get removed from the `body` preventing me form scrolling my page. 

I've also added `data-backdrop="static"` to the modal so it can only be dismissed by the `.close` button but this also is not removing the `.modal-open` class. It also appears it is not removing the inline `display: block`  from the modal and simply changing the opacity back to 0. 

Any ideas of what I might be having an issue with?

**Comment by thednp** [comment]
Thanks for the find, will look into it asap.

**Comment by thednp** [comment]
@adibbz ?

**Comment by adibbz** [comment]
@thednp Do you have a email or way to contact you privately? Don't want to share dev link publicly.

**Comment by thednp** [comment]
dnp.digital @ gmail.com

**Comment by thednp** [comment]
@adibbz the `fade` class is now optional for Modal, working as expected. Will also implement this feature for Alert, Tab, Tooltip and Popover components. Both V3 and V4.

**Comment by adibbz** [comment]
@thednp so were you able to build and push this up today?

**Comment by thednp** [comment]
I am almost there, this got me to a point I found some new unresolved cases, incredibly, with the tabs...

**Comment by thednp** [comment]
@adibbz please download latest master and do some testing.

**Comment by adibbz** [comment]
@thednp Removing fade class resolved the body scroll issue. Thank you!

**Comment by thednp** [comment]
Also make sure to test the other components I mentioned, they've been changed to support this functionality.
