### ISSUE TITLE
Collapsible Accordion Bug

### ISSUE THREAD

**Issue by tgBryanBailes** [thednp/bootstrap.native#126]
I was receiving an error when using a Collapsible Accordion where the collapsible item had a data-target instead of an href.

Line 95 of V4/collapse.native.js reads as follows:
`correspondingCollapse = allToggles[u][getAttribute][dataTarget] || allToggles[u].href;`

Since getAttribute is a function, not an object, it should read as follows:
`correspondingCollapse = allToggles[u][getAttribute](dataTarget) || allToggles[u].href;`

**Comment by thednp** [comment]
Thanks for the report.

**Comment by thednp** [comment]
@tgBryanBailes please download latest master and do some testing.

**Comment by tgBryanBailes** [comment]
The issue is resolved with the latest bootstrap-native-v4.js. Thank you so much!

**Comment by thednp** [comment]
NO. I thank you !!
