### ISSUE TITLE
Add option to import individual components

### ISSUE THREAD

**Issue by fBosch** [thednp/bootstrap.native#128]
It would be great to be able to do this:

``` javascript
import { Modal } from 'boostrap.native/modal';
```

To help keep down bundle sizes.

**Comment by RyanZim** [comment]
@fBosch You'll have to make a custom build to do this https://github.com/thednp/bootstrap.native#custom-builds

**Comment by nlemoine** [comment]
@RyanZim I'm also interested in consuming individual BS components. 

Custom builds provide a way to handle this but it's not very handy. You need to clone the project, copy the built file to your working directory. And you can't rely on npm/yarn to handle updates. 

Any plans to move BS native to real modules?

**Comment by thednp** [comment]
@nlemoine that may be harder to achieve due to the current code structure. I believe with a wider ES6 adoption we might consider reorganizing the code to meet these requirements.
