### ISSUE TITLE
Documentation - V4 NPM instructions

### ISSUE THREAD

**Issue by cabalopolis** [thednp/bootstrap.native#129]
http://thednp.github.io/bootstrap.native/v4.html

In the quick guide section of the installation instructions for v4, the documentation suggests that people should edit the NPM `package.json` file to include it so the following code would work:

```javascript
var nbs = require('boostrap.native');
```

I believe this is a bad practice as this means that each contributor would have to do this every time they work on their project. Might I suggest that the documentation use this:

```javascript
var nbs = require('bootstrap.native/dist/bootstrap-native-v4');
```

As this would allow people to use the v4 without having to change the `package.json` file.

**Comment by thednp** [comment]
Thanks for the tip, I didn't know this is possible.
