### ISSUE TITLE
Different behaviour for responsive design

### ISSUE THREAD

**Issue by WhiteTrashLord** [thednp/bootstrap.native#13]
Thanks for this. I like the idea of this project very much. I hope that I can use it more often in future.
Unfortunatley I found a little problem when I tested it with a smaller resolution.

In my case I see a scrollbar on Firefox and Chrome with Bootstrap v3.3.5 at the navbar.
With JQuery and the official JS code there is no scrollbar.

Maybe somebody can look into this?

The code looks like this:

div id="navbar" class="navbar-collapse collapse in" area-expanded="true" style="height: 137px;">
</div

**Comment by thednp** [comment]
There is no problem with that, it's what is supposed to do on smaller
resolutions to make the entire menu available.
OR
Are you saying that the scroll is there even if the menu is smaller size
than the screen height?

**Comment by WhiteTrashLord** [comment]
I cannot test with a real smartphone. I only test it on my desktop system by reducing the Browser window size.

But with the same resolution and conditions there is a difference. Bootstrap Native shows a scrollbar and hides some menu items. Normal Bootstrap shows all menu items and no scrollbar. I prefer the behaviour of the normal Bootstrap.

**Comment by thednp** [comment]
What is the CSS version for your Bootstrap setup? I ask because bootstrap.native here is only about JS, has little to do with how it looks.

ALSO
Do you use a fixed navbar? Give me some details, I cannot guess or feel what your problem is.

**Comment by thednp** [comment]
I cannot reproduce the issue. I tested in both Chrome and Firefox, both Windows and Linux.
You can reopen this with a link to your site. Please before you do so, make sure your HTML is valid.

**Comment by WhiteTrashLord** [comment]
You can see it with this example:

http://getbootstrap.com/examples/navbar-static-top/

I can also make you some screenshots if necessary.

**Comment by thednp** [comment]
Works for me, tested with Windows and Ubuntu Linux.

**Comment by thednp** [comment]
I think I got to this error myself, working on improving some code. 
Can you try to provide more details?
- do you use polyfills? what exactly?
- does your desktop browser show any error in the console? (it does for me now)

**Comment by thednp** [comment]
I think I fixed this one. The update is coming soon.

**Comment by thednp** [comment]
Check out the new version, this issue is fixed as well.
