### ISSUE TITLE
react usage?

### ISSUE THREAD

**Issue by MichaelLSmith** [thednp/bootstrap.native#130]
Less an issue, but a question: Is it possible to use this with react?

**Comment by thednp** [comment]
I don't know, have you tried?

**Comment by RyanZim** [comment]
@MichaelLSmith You're going to have nothing but pain using this with react. bootstrap.native uses the browser DOM, which is going to wreck havoc with React's virtual DOM. In short: Don't do it!

**Comment by thednp** [comment]
@RyanZim what would you suggest to solve this?

**Comment by RyanZim** [comment]
@thednp React is a whole different way of doing things. React support is out of scope for bootstrap.native. It would require a completely separate codebase. I vote to close.
