### ISSUE TITLE
Dropdown does not open with DATA API markup - Boostrap v4

### ISSUE THREAD

**Issue by rodolfojnn** [thednp/bootstrap.native#131]
On Bootstrap v4, dropdown only works via JavaScript

https://jsfiddle.net/t4t9Laqs/

**Comment by thednp** [comment]
Copy from docs:
> To load the library from CDN, drop one of these lines below before your ending </body> tag. Latest releases come here on jsdelivr and here on cdnjs. Other CDN links are also available.

jsfiddle links all scripts into the `<head>`

**Comment by tomshane** [comment]
Same issue here. BS 4 Data API doesn't work when imported with webpack. Only way to make it work is to add it to <head>.

**Comment by thednp** [comment]
It depends on the order of your scripts @tomshane if you put it all in `<body>` and BSN if first, it will never fire, but if you put it last, before your everything is rendered, it should go like a breeze.
