### ISSUE TITLE
 Support for multiple modals - BS4

### ISSUE THREAD

**Issue by rodolfojnn** [thednp/bootstrap.native#132]
Hey guys, there are plans for multiple modal support without closing the previously opened modal? The 

https://github.com/thednp/bootstrap.native/blob/master/lib/V4/modal-native.js#L188

The overlay could be maintained until the last modal was closed.

This would be useful for maintaining the state of previous modals. Currently the state is lost when the modal closes.

**Comment by thednp** [comment]
No plans for now. Sorry.
