### ISSUE TITLE
Add unit tests to verify equal functionality

### ISSUE THREAD

**Issue by inspiredbytes** [thednp/bootstrap.native#133]
It would make me feel a lot more comfortable with this if there were a way to verify equal functionality with the minor bits of funcionality.

Should pass the same unit tests (minus any jquery specific things) as Bootstrap.
https://github.com/twbs/bootstrap/tree/v4-dev/js/tests/unit

**Comment by thednp** [comment]
Feel free to contribute, I personally don't have the experience/time to code the tests.
