### ISSUE TITLE
Navbar data-target accepts only selectors starting with id (broken compatibility with upstream Bootstrap JS)

### ISSUE THREAD

**Issue by mirzal** [thednp/bootstrap.native#136]
Bootstrap.native Collapse data API requires `data-target` attribute value to start with `#` (i.e. selector to start with id), whereas upstream bootstrap JavaScript will accept any valid selector. As a result, some pages that do work with bootstrap JS will not work correctly with bootstrap.native JS.

## Steps to reproduce

1. Open [upstream bootstrap JSFiddle example](https://jsfiddle.net/fhod0Lnb/). Make sure that page view box is narrow enough to display hamburger icon in navbar.
2. Click hamburger icon and verify that menu items are displayed.
3. Open [bootstrap.native JSFiddle example](https://jsfiddle.net/gpxgqrcn/1/). Make sure that page view box is narrow enough to display hamburger icon in navbar.
4. Click hamburger icon and verify that nothing happens. Error message is:
    ```
    Uncaught TypeError: Cannot read property 'contains' of undefined
        at hasClass (bootstrap-native.js:159)
        at HTMLButtonElement.Collapse.toggle (bootstrap-native.js:886)
    ```
5. In bootstrap.native JSFiddle change `<button>` `data-target` value from `.navbar-collapse` to `#navbar.navbar-collapse`. Run it and repeat step 4. Menu items will be displayed this time.

## Analysis

The problem lies in `lib/V3/collapse-native.js` line 68. `getTarget` function will return element if `id` is truthy; id will use `href` value or `data-target` value, but the latter only if it matches `targetsReg` regular expression. That expression, defined in `lib/V3/utils.js` line 203, will match everything that starts with `#`. Class or element-based data-target selectors (which may be as unique as id-based selector) will not match, and Collapse will not work with them.

I am unsure about correct way of solving this. Changing `targetsReg` seems to be obvious, but trying to match any valid CSS selector can quickly spin out of control; on the other hand, verifying that selector value is non-empty seems to not be specific enough.

`targetsReg` seems to be only used in few places (`collapse`, `scrollspy` and `tab`), and `queryElement` function is used immediately in two of them. Maybe regular expression could be dropped and `queryElement` could verify if selector matched anything and return some sane value if it does not?

**Comment by thednp** [comment]
Initially the script was also doing class selectors, but due to code optimizations and improvements, that functionality didn't work anymore, and I think original Bootstrap plugins also dropped everything in favor for the ID. It's a much better trade in all cases.

**Comment by thednp** [comment]
So yea, the [Bootstrap demo](http://getbootstrap.com/) uses `data-target="#bs-navbar"` for the Navbar, while the code actually does jQuery selector `$(target)`, but a non-ID selector for Navbar is highly not recommended, for performance, consistency and other considerations. 

As an example, if you have 2 navbars in the same parent wrapper how are you going to distinguish the two, with a specific class? Why not an ID? 

So yea, closing this down.
