### ISSUE TITLE
collapse on mobile only

### ISSUE THREAD

**Issue by umarrg97** [thednp/bootstrap.native#137]
Hi im currently in need of some in depth of knowledge of bootstrap native. im in need of my collapse to always be open on desktop. When it gets to mobile i can open and collapse. the next bit ive been struggling with...regardless of what state the collapse is in on mobile when i resize to desktop it should be open again. ive read the docs on the collapse but not sure what to do? any pointers

**Comment by thednp** [comment]
Our library here no nothing different than the original in terms of JavaScript functionality.

I would advise to use the specific classes utility `visible-mobile` and so on.
