### ISSUE TITLE
Collapse component on Demo page stop working in Firefox

### ISSUE THREAD

**Issue by chenjau** [thednp/bootstrap.native#138]
Version: Latest commit 7527d1d
Browser: Firefox 54, 56a1
Behave like #115.

After testing with hundreds of click HREF and data-target button on  [demo page](http://thednp.github.io/bootstrap.native/#collapseExamples), I think this bug still exist in firefox.

**Comment by thednp** [comment]
I think it's a problem with Firefox itself, but who in the right mind would click the collapse a hundred times?

**Comment by chenjau** [comment]
Hi, not hundreds click to make one happen, sometime just several clicks,  seems randomly.  and, if a page has multiple collapse menus in it, make it much easier to happen.

**Comment by chenjau** [comment]
Can't reproduce in codepen.io, don't know why, I'll update if I find anything.
Thanks.
