### ISSUE TITLE
Unnecessary IIFEs pervasive in v4 implementation

### ISSUE THREAD

**Issue by isiahmeadows** [thednp/bootstrap.native#139]
I was just looking at the source out of curiosity, and found a lot of seemingly unnecessary IIFEs in the collapse ([1](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/collapse-native.js#L34), [2](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/collapse-native.js#L53)) and tab ([1](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L35), [2](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L53), [3](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L55), [4](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L107), [5](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L110), [6](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/tab-native.js#L115)) implementations. Is there a particular reason for these, or should they be removed?

**Comment by thednp** [comment]
The method is used because there is no cross-browser `setImmediate` method, and that fixes [something](https://github.com/thednp/bootstrap.native/issues/115) reported over and over.

**Comment by isiahmeadows** [comment]
@thednp I'm not referring to the `setTimeout` calls, but the plain IIFEs themselves, things like this:

```js
(function () {
    // code...
})();
```

As for that bug fix, all you really did beyond adding the unnecessary IIFEs was move code into `setTimeout` callbacks and increasing their delay.

As for backwards compatibility, just inlining their bodies *should* have zero impact, even as far back as Netscape. Any differences would be obvious browser breakers, leaving almost all common sites with scripting unusable.

**Comment by thednp** [comment]
@isiahmeadows as I said, I am open to any code suggestion, I really tried them all I know.

**Comment by isiahmeadows** [comment]
@thednp Check out #140. That should explain what I mean (it's also a nicely packaged PR).

**Comment by thednp** [comment]
Wowow, wait a sec and [check this](https://github.com/thednp/bootstrap.native/issues/115) first before committing.

Have you tested multiple clicks and it works perfect? I've spent about 2 days working to fix that issue, you think that would simplify and solve the issue for good?

**Comment by isiahmeadows** [comment]
It's equivalent to what's already there, and I have tested it to verify it does not break.

**Comment by thednp** [comment]
I am now testing your code in all browsers. It seems to work, but I don't know...

**Comment by isiahmeadows** [comment]
In case you're curious (I can tell you're not super familiar with the difference), [here's the Wikipedia article on the idiom](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression).

**Comment by thednp** [comment]
OK. I remember now. FYI: I am not targeting G Chrome only, I am interested in IE8+ for BSN V3 and IE10+ for BSN V4. I also have a very old Safari for Windows....

So, you know why those IIFEs are used? It's because the API on `event.transitionEnd` is poorly implemented in many browsers and it always messes up... sometimes things that need to happen when the animation ends, never happen, or the event is not even triggered.

So FYI, please take the time to test differences with all functionalities in regards to components custom events, browsers, etc ;)

**Comment by thednp** [comment]
@chenull I hope you take a look at @isiahmeadows commit as well. Thank you.

**Comment by isiahmeadows** [comment]
@thednp IIFE's are just a lanugage idiom, unique to JS the language, without respect to the environment. They do literally nothing apart from creating a new scope for `var` variables.

**Comment by thednp** [comment]
@isiahmeadows I will certainly do a mega test with your suggestion as soon as I get some time. Thank you.
