### ISSUE TITLE
Dropdown won't stay open when click any input in dropdown

### ISSUE THREAD

**Issue by Azeranex** [thednp/bootstrap.native#143]
There is a problem when you click any input (login form in this case). Dropdown just closed. I'm using latest pull version from git.

**Comment by thednp** [comment]
You sure checked the documentation on how to use the feature?

**Comment by Azeranex** [comment]
Oop sry, bootstrap v4

**Comment by thednp** [comment]
BSN for V3 and V4 have same functionality.

**Comment by Azeranex** [comment]
2.0.12

**Comment by thednp** [comment]
http://thednp.github.io/bootstrap.native/#dropdownOptions
