### ISSUE TITLE
[Questions] How to make each tab enabled/disabled

### ISSUE THREAD

**Issue by kochizufan** [thednp/bootstrap.native#144]
Hi, thanks for nice library.

I use tab function like this:

>  &lt;ul class="nav nav-tabs nav-justified" role="tablist">
>    &lt;li class="active">&lt;a href="#tab_a" data-toggle="tab" role="tab">Tab A&lt;/a>&lt;/li>
>    &lt;li>&lt;a href="#tab_b" data-toggle="tab" role="tab">Tab B&lt;/a>&lt;/li>
>    &lt;li class="disabled">&lt;a href="#tab_c" role="tab">Tab C&lt;/a>&lt;/li>
>  &lt;/ul>

This works well (Tab C is disabled).
But if I want to change enabled/disabled by JavaScript, it doesn't work.

* Even if I make tab_b with adding disabled from &lt;li> and removing data-toggle from &lt;a>, it still works.
* Even if I make tab_c with removing disabled from &lt;li> and adding data-toggle to &lt;a>, it still doesn't work.

How can I handle each tabs enabled/disabled dynamically?

**Comment by kochizufan** [comment]
Hi 

I found the solution by myself.

Just adding

> li.disabled {
>    pointer-events: none;
> }

Then it works well.

**Comment by thednp** [comment]
@kochizufan my friend, the `disabled` toggling has nothing to do with the `Tab` component of the library or the original plugin, it's something of a custom work, but I'm glad you figured a solution.
