### ISSUE TITLE
Error when opening 2nd modal. 

### ISSUE THREAD

**Issue by ref1c** [thednp/bootstrap.native#147]
I experience an error when trying to open 2nd modal using javascript on line 1184. 

`currentOpen && currentOpen !== modal && currentOpen.modalTrigger[stringModal].hide(); `

currentOpen.modalTrigger is undefined, therefore once it gets hit here, it throws an error. It tries to call "currentOpen.modalTrigger["Modal"]". 

When I comment out the code, I can finally open my 2nd modal fine.

**Comment by ref1c** [comment]
Also, I have an eventListener, that on 'hidden.bs.modal', it empties out all contents of the modal. So, when I open the 2nd modal, even if it worked, it would cause me a problem in my scenario. Is there a way I can open another modal on top without hiding the last one? It seems to work fine for me (opening a another modal on top, if I keep that code commented out). However, the only problem is, when I hide the 2nd modal, the first modal loses the overlay as well. Basically, when I open 2nd modal, there are 2 overlay, which is great. However, when 2nd modal is gone, it removes both overlay. 1st modal should have 1 overlay remaining.

**Comment by thednp** [comment]
You have a test site? I'm thinking you might be using nested modals, which is something that surely shouldn't work.

**Comment by ref1c** [comment]
Nothing that's running, but I do have the codes. 

```
            var modalOptions =
            {
                backdrop: allowCloseOnBackgroundClick,
                keyboard: false
            }

            if (targetId == "secondModal")
            {
                main.Settings.secondModalObject = new Modal(modalObject, modalOptions);
                main.Settings.secondModalObject.show();
            }
            else 
            {
                main.Settings.mainModalObject = new Modal(modalObject, modalOptions);
                main.Settings.mainModalObject.show();
            }
```

I first load the first modal using targetId: "mainModal", then the 2nd one gets loading (on top) using targetId: "secondModal". 

HTML codes:
```
<div id="mainModal" class="modal fade" data-toggle="modal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <div class="modal-title"></div>
                        </div>
                        <div class="modal-body"></div>
                        <div class="modal-footer"></div>
                    </div>
                </div>
            </div>

            <div id="secondModal" class="modal fade" data-toggle="modal" tabindex="-1" role="dialog" aria-labelledby="secondModal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <div class="modal-title"></div>
                        </div>
                        <div class="modal-body"></div>
                        <div class="modal-footer"></div>
                    </div>
                </div>
            </div>
```

**Comment by thednp** [comment]
Nested modals aren't supported.

**Comment by bkuzma** [comment]
Hi there,

First and foremost I wanted to say thanks for the great library.

I'm having an issue with programmatically opening a second modal while a first one is open, similar to what ghost was seeing. I tried to recreate the issue here: https://jsfiddle.net/jr32f00j/2/. I pasted in https://github.com/thednp/bootstrap.native/blob/master/lib/V4/utils.js and https://github.com/thednp/bootstrap.native/blob/master/lib/V4/modal-native.js in the fiddle, with my code at the very bottom.

If I open the first modal and subsequently click to open the second, I see `Uncaught TypeError: Cannot read property 'Modal' of undefined` in the console. It appears that the `modalTrigger` property is never set. The modals aren't nested.

Would you have any insight as to whether this is a bug or I'm doing something wrong? Thanks and happy holidays.

**Comment by bkuzma** [comment]
I made a second fiddle using the example from the docs where it says: 
> If you are looking for the functionality that grants you full control over your modal without the need of a triggering element, you can initialize that modal and get access to public methods right away:

https://jsfiddle.net/jr32f00j/3/

It seems to me that what's happening is that without a triggering element, the `clickHandler` method is never called and thus `modalTrigger` is never set, which causes the failure when trying to access `modalTrigger` to hide a previously opened modal.

**Comment by thednp** [comment]
@bkuzma if you have no `triggeringElement` set, but you initiated ***Modal*** targeting a `.modal` element, then that element will hold the initialization object. EG: `myModal.Modal` the object you can access methods from.

**Comment by bkuzma** [comment]
I see. So in that case I should check for any open modals myself and close them via `.hide`?

**Comment by thednp** [comment]
Something like that, but check if they have the `Modal` object attached.
