### ISSUE TITLE
Press the down arrow key and open the current dropdown

### ISSUE THREAD

**Issue by Gonzalo2683** [thednp/bootstrap.native#148]
Hi, very interesting project,
In the dropdow component I do not see the functionality of when I press the down arrow key and the current dropdown opens.

How is it possible to add it?

**Comment by midzer** [comment]
Hi @Gonzalo2683
in Chromium return key opens dropdown menu for me. Looks like down arrow key is reserved for scrolling down websites in any case.

**Comment by thednp** [comment]
@Gonzalo2683 you can fork the code and change the key handlers to work your way.
