### ISSUE TITLE
classlist issue still present on tabs

### ISSUE THREAD

**Issue by ref1c** [thednp/bootstrap.native#150]
Classlist issue still present for tabs that are loaded in via ajax and initialized via JavaScript. I load the following tab in partial view (Ajax Get), and upon loadSuccess, I call the following javascript code: `new Tab('#testTab');` This has my tabs working correctly and as expected. However, when I click on the white spaces to the right of the tab, my tab breaks and I get a classlist error. 

![image](https://user-images.githubusercontent.com/25371236/29938027-3af635c2-8e3c-11e7-81ee-9da2929f225e.png)

```
<div class="row marginBottom20">
    <div class="col-xs-12">
        <div class="default-block">
            <div class="header"><h2>Amazing Tabs with useless contents</h2></div>
            <div class="content">
                <ul id="testTab" class="nav nav-tabs marginBottom20" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#home" data-toggle="tab" data-height="true" aria-controls="home" role="tab">Home</a>
                    </li>
                    <li role="presentation">
                        <a href="#profile" data-toggle="tab" data-height="true" aria-controls="profile" role="tab">Profile</a>
                    </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content ">
                    <div role="tabpanel" class="tab-pane active" id="home">Finally home!</div>
                    <div role="tabpanel" class="tab-pane" id="profile">Look at your profile</div>
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by thednp** [comment]
Get a demo somewhere so we can reproduce and analyze the issue. Meanwhile, you can think of whether you've used proper markup in proper structure, I feel this has happened here before.

**Comment by ref1c** [comment]
I believe the markup is proper. That is the full code above, 

I'll release my website by Monday I believe. You can see the demo then. Thanks.

**Comment by thednp** [comment]
![image](https://user-images.githubusercontent.com/6761246/29954579-a3989020-8ee1-11e7-9c00-49b6f3158275.png)
Here's your markup pasted to the demo page, no error, all good.
