### ISSUE TITLE
IE 11 - collapsible items - "Object doesn't support his action"

### ISSUE THREAD

**Issue by johjacb** [thednp/bootstrap.native#153]
Thanks for your work on this project - its very handy. 

Everything works as expected, except in IE 11. (I saw polyfills for IE8-10, so I'm assuming 11 is covered). 

On collapsible items in IE 11, I get an error:
```SCRIPT445: Object doesn't support this action```

which points to the *second* line in this JS in the console: 
```
bootstrapCustomEvent = function (eventName, componentName, related) {
      var OriginalCustomEvent = new CustomEvent( eventName + '.bs.' + componentName);
      OriginalCustomEvent.relatedTarget = related;
      this.dispatchEvent(OriginalCustomEvent);
    },
```
I am including the file via:
`var bsn = require('bootstrap.native/dist/bootstrap-native-v4');`

am I missing a step? thanks!

**Comment by thednp** [comment]
IE11 does not support `CustomEvent`, I'm assuming Edge as well, use the polyfil.

**Comment by csimpi** [comment]
I think this should have been solved some way, not just tell IE11 doesn't support CustomEvent. 
Hereby a workaround:
https://stackoverflow.com/questions/19345392/why-arent-my-parameters-getting-passed-through-to-a-dispatched-event/19345563#19345563

**Comment by thednp** [comment]
@csimpi this library is supposed to be simple but having options:
* legacy compatibility via polyfills, again 3 options here
* allows you to create custom builds
* provide functionality just as reliable as the original plugins
* size matters so new/custom functionality is very much up to debate (do we really need the X feature)

All of that said, please check the wiki page in regards to [browser support](https://github.com/thednp/bootstrap.native/wiki/Browser-support).
