### ISSUE TITLE
Calculation of Outer Height in Collapse

### ISSUE THREAD

**Issue by Ixonal** [thednp/bootstrap.native#155]
Noticed the Collapse toggle for my menu wasn't expanding to the correct height. After some digging, I found that the problem lies in a combination of how outer height is being computed and the fact that one of the items in the collapse parent was a custom element with no display type predefined. 

``` javascript
  getOuterHeight = function (child) {
    var childStyle = child && (child.currentStyle || globalObject.getComputedStyle(child)), 
      btp = /px/.test(childStyle.borderTopWidth) ? Math.round(childStyle.borderTopWidth.replace('px','')) : 0,
      btb = /px/.test(childStyle.borderBottomWidth) ? Math.round(childStyle.borderBottomWidth.replace('px','')) : 0,
      mtp = /px/.test(childStyle.marginTop) ? Math.round(childStyle.marginTop.replace('px','')) : 0,
      mbp = /px/.test(childStyle.marginBottom) ? Math.round(childStyle.marginBottom.replace('px','')) : 0;
    return child[clientHeight] + parseInt( btp ) + parseInt( btb ) + parseInt( mtp ) + parseInt( mbp );
  },
```

The problem seems to stem from clientHeight returning 0 in that case. When I called child.getBoundingClientRect(), however, the height property contained the correct value. 

I can fix the issue from my end by setting the display for the custom element to inline-block, but it may be worth using getBoundingClientRect instead of clientHeight.

**Comment by thednp** [comment]
Does this happen with my demo as well? I kinda of feel you might probably not use the proper markup.

**Comment by Ixonal** [comment]
I mean, the markup IS different from examples due to the custom element, but it doesn't seem to be a matter of what markup is there. Here's an example of what I'm talking about 

https://gist.run/?id=13f358bcb68f124c4c14b63cfd2da79d

Also, this displayed properly when I used regular Bootstrap (before I set the display to inline-block), so best guess is they're using getBoundingClientRect at some point there too.

**Comment by thednp** [comment]
The thing is, your probably figured, if the element isn't in the DOM and properly rendered with it's entire box-model styling, no matter what method/browser you try, you will never get the accurate height.

**Comment by Ixonal** [comment]
well, it seems to be more an issue of inline elements, specifically. But yeah, it seems the default display type for elements is inline, and I'm not seeing a way to reliably get the height of inline elements. Odd, since that has to be known at some point for the browser to display it properly, but ¯\_(ツ)_/¯. It reporting the proper size in Chrome must just be a happy accident.

**Comment by Ixonal** [comment]
Been thinking further, since the regular Bootstrap library is able to do this without issue. Do you suppose they just go from height (or width) 0 to auto instead of a defined value?

**Comment by thednp** [comment]
Not ideal, a number is needed for the CSS3 tween animation.

**Comment by Ixonal** [comment]
Looks like they're using scrollHeight/scrollWidth on the element that Collapse is applied to.

https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L94

As far as I can tell, dimension should be either "width" or "height", so scrollSize should be either "scrollWidth" or "scrollHeight". Lemme play around with it a bit and see if it's reliable at all.

**Comment by thednp** [comment]
IMO, if you're trying to fix a Firefox bug, don't bother.

**Comment by Ixonal** [comment]
not a Firefox bug, it's trying to get the behavior to match that of Bootstrap.

**Comment by thednp** [comment]
I think they're doin something like `Math.max(el.offsetHeight,el.scrollHeight)`  to determine height, it might do the thing.

**Comment by Ixonal** [comment]
interesting... Looks like the max between those two would be reliable, as long as the "el" element has hidden overflow. Ran a JSFiddle in Chrome, Firefox, and Edge (IE isn't installed on this computer) and they're showing the target value.

https://jsfiddle.net/7jc4d5gd/1/

the offsetHeight and scrollHeight of the individual elements within the container are incorrect, but the offsetHeight and scrollHeight of the container are correct.

**Comment by thednp** [comment]
The BSN version of `Collapse` is doing the exact same thing, it's hard to imagine it would fail in that regard.

**Comment by Ixonal** [comment]
it's toggling the collapsing class, but it's adding up the height of the contents of the container (at least, last I looked), instead of the height of the container itself. In my fiddle, the scrollHeight and offsetHeight of the element inside of the container is incorrect, but the scrollHeight and offsetHeight of the container itself is correct.

**Comment by thednp** [comment]
There is a reason why we count the height of the children instead of the container itself, and that is because by default it's height is 0.

**Comment by Ixonal** [comment]
Right, which is why they use scrollHeight instead of offsetHeight. Check out that fiddle again, set the height of the container element to 0, and run again. scrollHeight is still correct.

**Comment by thednp** [comment]
True.

**Comment by Ixonal** [comment]
Might be worth it to look into using that method. It'd be smaller and most likely faster (though, that depends on browser implementations).

**Comment by thednp** [comment]
Committed new code, please test.

**Comment by Ixonal** [comment]
Will try to set up a fiddle when I get home. The only possible issue I can think of off hand is that scrollHeight will not return the right value unless overflow-y (or just overflow) is "hidden" or "auto". That's handled by the "collapsing" class with Collapse, but I'll have to check and make sure that's applied with the tabs too.

**Comment by thednp** [comment]
Unfortunately the `element.scrollHeight` doesn't work fine with ***Tab*** component animation, the height animation that's missing in the original plugin.

**Comment by Ixonal** [comment]
Odds are it's an issue with either the "overflow" or "display" properties.

**Comment by Ixonal** [comment]
Working on getting a fiddle set up and came upon an issue, thought I'd just bring is up here for convenience.
https://github.com/thednp/bootstrap.native/blob/master/lib/V3/utils.js#L7
If the script is included in the head (as it is in JSFiddle), then it sets the body variable before the document has a body element, so when it tries to access body later, it gets a null reference exception. In particular, it threw when it tried to do the IE8 check.

**Comment by thednp** [comment]
Yes, because of that, we always link the library in the footer, we don't use jQuery and we don't put everything under `DOMContentLoaded` event, so save performance, because of that this library should be the fastest around.

**Comment by Ixonal** [comment]
hmmm, well, that does make it impossible to make a fiddle with it :/

**Comment by thednp** [comment]
There's codepen and tons others.

**Comment by thednp** [comment]
@lxonal please test latest master and let me know how everything works.

**Comment by Ixonal** [comment]
Interesting... with regular content in the tabs, it does appear to function correctly. I had put wells in the content to see what's going on a little better. In that case, it appears to be some kind of jump at the end of the animation.

https://gist.run/?id=6b26c82ad118399aa3e8d8406b634800

**Comment by thednp** [comment]
I'm happy I managed to simplify the *Collapse* functions, and almost done with the *Tab*. On your edits: it seems browsers have a problem with containers in getting their `scrollHeight`, IE and Firefox are both wrong if the container is not floating. I am open to any suggestion.

**Comment by thednp** [comment]
Interesting to see that having `fade` enabled for tabs, it doesn't seem to work properly. The animation is quite chubby.

**Comment by Ixonal** [comment]
I noticed the flow of logic was starting to look a little more transparent, which is nice :D. Do you have any links to information about the IE and Firefox errors in scrollHeight? Still seems like Firefox is animating correctly for me.

I just enabled fade for the tabs and that part of things appeared to work correctly for me. Not sure what you mean by chubby.

**Comment by thednp** [comment]
The `scrollHeight` reported in all browsers is wildly different. Here's a screenshot so you can picture:
![scrollheight](https://user-images.githubusercontent.com/6761246/30601379-77b8c73a-9d6a-11e7-9b34-15e575f99dfe.png)

The code you knew previously was the result of days of trial and error, some other people's input as well, but it wasn't working properly in IE10. With the new code it seems to almost work now, but Firefox stops animating height at some point and I can't seem to make a proper code decision. 

Overall I believe we're heading in the right way. Seems that using `float` helps big time.

**Comment by Ixonal** [comment]
I don't know about "wildly" different, but yeah, there's a difference in chrome that's causing the animation to be screwy for me. I also noticed that if I turn off the margin-bottom rule for the well class, the animation displays properly. It's like the margin is being counted for the container, rather than the child in Chrome.

**Comment by Ixonal** [comment]
Not sure I'm seeing what you're seeing. When you test in FF and IE, the animation doesn't display correctly? I updated my pen to have a duplicate tab at the end, so the last two tabs are the same height. I'm looking at it in FF and looks to be working as intended.

**Comment by thednp** [comment]
So in Chrome everything is OK, because it reads the proper `scrollHeight` value, while the other two are reporting different values for elements with the same exact height.

**Comment by Ixonal** [comment]
But for me, the animation is borked in Chrome, so wouldn't that make that the issue, and not FF and IE?

**Comment by thednp** [comment]
Give me a minute or two, I will commit a new code so you will have a better idea.

**Comment by thednp** [comment]
OK now, go ahead and test, please make sure you have two tabs with exact same content. You will see the difference I'm talking about in the browser console.

**Comment by Ixonal** [comment]
ahhh, now it's animating like I was seeing in Chrome (in FF), with the addition of getting stuck on the same sized content

**Comment by thednp** [comment]
Yes, Chrome works properly as it reads proper `scrollHeight`, while the others don't.

**Comment by thednp** [comment]
Also, this assumes `div.tab-content` has `clearfix` class or is wrapped by an element with that class. See my forked gist here https://gist.run/?id=a7712e69a6e5b98cacd7940b7eee07d1

**Comment by Ixonal** [comment]
It looks like you're checking to see whether the height of the container element is the same as the height of the next content element to be shown. That seem about right?

**Comment by thednp** [comment]
That's the idea with the height animation after all.

**Comment by Ixonal** [comment]
Not exactly, need to get the height of the container with the current content shown, and then the height of the container with the next content shown. The height of the content of the container will be different from the height of the container itself.

**Comment by thednp** [comment]
Please test latest master, in my [gist](https://gist.run/?id=a7712e69a6e5b98cacd7940b7eee07d1) looks good to me.

**Comment by Ixonal** [comment]
Tested in Chrome, Edge, and Firefox, and all of them look to be animating correctly (with clearfix applied, anyways). Still getting that same custom event error in IE, though.

**Comment by thednp** [comment]
IE needs polyfill.

**Comment by Ixonal** [comment]
Not going to use the createEvent/initCustomEvent stuff from the earlier link, then?

**Comment by thednp** [comment]
I don't know what you're talking about, I would suggest you should download the master and check the demos locally, codepen and/or gist may not work properly.

**Comment by Ixonal** [comment]
Talkin bout this: 
https://stackoverflow.com/questions/19345392/why-arent-my-parameters-getting-passed-through-to-a-dispatched-event/19345563#19345563

**Comment by thednp** [comment]
We do pass parameters, but IE can only handle a limited number. Also the polyfill can only enable IE browsers with very little, they're really old browsers.

**Comment by Ixonal** [comment]
Well, I am supporting back to IE9 in this app, but don't want to bring in a full polyfill library because I already have a set of polyfills I'm using and don't want to be redundant, so I guess I'll just write out a minimal polyfill to fix this specific issue...

**Comment by thednp** [comment]
New release is out now, please make sure you're OK in regards to your concerns ;)

**Comment by Ixonal** [comment]
Didn't notice today, so I'll have to check it out on Monday

**Comment by Ixonal** [comment]
Just looked, and the collapse on my navbar appears to be working correctly in IE9 now, so score :D

**Comment by thednp** [comment]
Excellent, thanks.
