### ISSUE TITLE
Carousel v4 - Event binding

### ISSUE THREAD

**Issue by nlemoine** [thednp/bootstrap.native#157]
Using the carousel component in a project, I ran into several issues. 

My main issue here is that I can't use carousel indicators outside carousel container. 

- Unlike [BS4](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L496-L497), BSN is binding events [directly on the indicators elements within the carousel scope](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L496-L497), you can't place your navigation outside the carousel container. 
- Unlike [BS4](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L496-L497), BSN is using the [carousel indicators class](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L43-L44) to bind the `click` events whereas it should target the `[data-slide]` and `[data-slide-to]` attributes. 

I managed to make it work binding the events myself but had to implement back the direction logic that's repeated in every handler ([indicators](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L69-L74) / [controls](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L85-L102) / [keyboard](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L112-L121)). `slideDirection` not being public property, I had to make it public by modifying core BSN files. 

Same goes for carousel controls (next/prev).

**Comment by thednp** [comment]
This use case is a very specific one and a way to handle events that is outside the scope of the library. Basically with jQuery you can easily delegate events to the global scope at the expense of performance, we don't do that and many others here, I personally dislike this practice.

So you basically did what you had to do: fork, change to your need, case closed.

**Comment by nlemoine** [comment]
Thanks for your feedback. I thought this library was meant to provide the same features (and API) that jQuery BS. Sorry. 

I'm ok handling stuffs that's not in your scope but could you at least provide convenient ways to achieve this without having to rewrite BSN code? 

For example, you have no control over slide direction when using `slideTo`. I don't think this belongs to a specific case. Or the API you provided is useless (because `slideDirection` [have been set](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L147) in a private method), it will always slide to right. 

Providing `next` and `prev` would also be nice. 

Could you consider this?

**Comment by thednp** [comment]
@nlemoine I'm not the only one using and developing here, I am currently busy trying to improve **Collapse** and **Tab** and other issues are on the list.

Feel free to play with the code, and commit your changes once it's super stable, this is an open source project after all.

**Comment by nlemoine** [comment]
I'll try as soon as I have some spare time.

**Comment by thednp** [comment]
> For example, you have no control over slide direction when using slideTo. I don't think this belongs to a specific case. Or the API you provided is useless (because slideDirection have been set in a private method), it will always slide to right.

For these cases you don't really need to have access to `slideDirection`, as this one is strictly internally used to add proper classes required for the transitions. You can basically create your own methods of control outside the `Carousel` prototype and scope, based on the internal event handlers.

For instance you may want to create something like `myCarousel.next()` and `myCarousel.prev()` by invoking `myCarousel.slideTo(index)` method to do the hard work. For one use case, we don't need these incorporated into the component without a very strong argument.

**Comment by nlemoine** [comment]
> For these cases you don't really need to have access to slideDirection, as this one is strictly internally used to add proper classes required for the transitions.

You don't need to access to `slideDirection` if the `slideTo` takes care of setting it for you but `slideTo` only goes forward, no matter the index you're passing to it. Because the library doesn't internally check the current index against the index passed in `slideTo` to determine the appropriate direction (this is done before in the event handlers). 
See [this use case](https://codepen.io/hellonico/pen/NagRwL) for example. 

> For one use case, we don't need these to be incorporated into the component without a very strong argument or high community demand.

This goes further IMHO. This is a wrong API design. The example above should just work as it is. 

BTW, just found out official BS seems to move away from jQuery : https://github.com/twbs/bootstrap/pull/23586

I thought it was something to know before the people maintaining this project spend to much time on it.

**Comment by thednp** [comment]
@nlemoine thanks for the info on the soon Bootstrap without jQuery.

BSN is a personal turned community driven project, if you have a good idea on how to improve things, instead of criticizing people, make sure to explore, explain context and/or commit you code suggestions, as all the others who contributed.

I'm going to go forward maintaining the project regardless, I don't want to be influenced by the BS project, I think my code will still be lighter and have it's own good stuff.

**Comment by thednp** [comment]
> You don't need to access to slideDirection if the slideTo takes care of setting it for you but slideTo only goes forward, no matter the index you're passing to it.

You're right, I'm gonna try and improve this in the future update.

**Comment by nlemoine** [comment]
> if you have a good idea on how to improve things, instead of criticizing people, make sure to explore, explain context and/or commit you code suggestions, as all the others who contributed.

I sincerely apologize if you took that way. I'm not criticizing anyone here.

Before posting an issue, I always explore and try to provide as much details as possible. Read the thread again, I think I was pretty specific in the description of the problem with links pointing to code with specific line numbers, I submitted a use case. I think I'm pretty far from the "It doesn't work" issue. I usually won't spend time submitting a PR before making sure that the author agrees and is ready to fix the problem (and obviously, you don't seem to see there's a problem here).

If you think `slideTo` only going forward in a carousel component is ok, no problem. I still think this a wrong behavior. There's nothing personnal in that. 

> I'm going to go forward maintaining the project regardless, I don't want to be influenced by the BS project, I think my code will still be lighter and have it's own good stuff.

Sure it has! BSN is still a great library.

**Comment by thednp** [comment]
@nlemoine no offence taken, I just suggested a constructive course of action IMO.

I have a quick update for you: I found I can optimize the size of the **Carousel** by deciding the `slideDirection` inside the `slideTo()` method, how would you like the following custom code you can use without altering the future version of the component?

```js
Carousel.prorotype.next = function(){
  var activeIndex = this.getActiveIndex();
  this.slideTo(activeIndex++)
}
Carousel.prorotype.prev = function(){
  var activeIndex = this.getActiveIndex();
  this.slideTo(activeIndex--)
}
```

The future version will take care of the rest.

**Comment by thednp** [comment]
Please test latest master and check https://github.com/thednp/bootstrap.native/commit/39d3868805acb99b4c88da268113576cab31999c

**Comment by thednp** [comment]
@nlemoine ?

**Comment by nlemoine** [comment]
Thanks for this nice addition.

There's a last issue. Everything works great if you're not pushing too hard on the prev/next buttons. See the screen record: 
![screencast 2017-10-02 10-16-52](https://user-images.githubusercontent.com/2526939/31069101-36feaf5c-a75b-11e7-9690-50f05c8bf9c7.gif)

I think the problem comes from `isSliding` that's not checked within `slideTo`.

**Comment by thednp** [comment]
OH let me check that.

**Comment by nlemoine** [comment]
This is how BS deals with this: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L190-L193

**Comment by thednp** [comment]
OK now, check that again.

**Comment by nlemoine** [comment]
👍  Great! This fixes the issue. Thanks a lot for considering this request.

**Comment by thednp** [comment]
Alright, we are ready for 2.0.16 you think?

**Comment by nlemoine** [comment]
Sounds good to me.
