### ISSUE TITLE
[QUESTION] What do you think about the Popper.js functionality?

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#158]
As you know, Bootstrap V4 is going [Popper.js](https://popper.js.org/) and I've been thinking of adding that kind of functionality into our library as well.

Please feel free to contribute with code, ideas and sample codes.

**Comment by midzer** [comment]
I think it would be suitable to serve the same functionality as Bootstrap v4 Javascript. As long as custom build continues to be possible without this component, there should be no disadvantages (except some more kb library size).

Right now i'm still using v3 but might take a look when i migrate to v4.

**Comment by Vuurvlieg** [comment]
If this means I have to include a extra *.js file into my project then its a no for me

**Comment by thednp** [comment]
@Vuurvlieg That's exactly the point.

**Comment by FezVrasta** [comment]
Just to give some context. Popper.js doesn't make use of jQuery or and other dependencies.

If you figure out how to create a smaller version of it without losing any of the functionalities please send a PR because it would be awesome.

**Comment by artemsky** [comment]
Guys, poper.js is awesome, and it takes only 6kb gziped.
In our days its nothing when we have 1m+ js bundles

**Comment by neuropass** [comment]
should be optional. Just like the original bootstrap library did.
Build support for it, and if the user wants it needs to install popper.js.

@artemsky popper.js is 18.5kb.

**Comment by artemsky** [comment]
@neuropass look what I said - 6kb gziped (actually 7169bytes)

And as i know. popper.js is required by bootstrap javascript and it's not optional at all.

> Be sure to place jQuery and Popper.js first, as our JavaScript plugins depend on them.

**Comment by Vuurvlieg** [comment]
It is still a no for me but if you really want to add it, please make it optional.

**Comment by artemsky** [comment]
@Vuurvlieg How it can be optional when all dropdown/popover/tooltip code would be based on it.
The only way is to make this 3 deps optional too.

In that case, your workflow should include webpack where you can manage tree shaking (like boostrap original did)
 
And/or maybe dist should include something like `bs-native.js` and `bs-native.slim.js`

**Comment by thednp** [comment]
I like what we have so far, a build script allowing you to create custom builds, our **Popover** doesn't require **Tooltip**, and both don't require **popper.js**.

The only thing I could think of is ES6, your thoughts?.

**Comment by artemsky** [comment]
@thednp
Yor lib is nice. **ES6** is nice.
**Bootstrap native** switched to **popper** because **popper** has very nice features like auto positioning, element following, and so many others.

I'm not sure that **popper** is the best way to achieve that. Of course, you can do it yourself as well.

**Comment by thednp** [comment]
We didn't switch yet. We only use part of it's functionality.

**Comment by midzer** [comment]
I'm unsure whether it's worth to rewrite the whole library for ES6. For performance reasons it might be useful in (server) applications where certain ES6 features are necessary, see http://incaseofstairs.com/six-speed/
Yeah, source code looks often a bit prettier :)

As far as i haven't used any Tooltips/Popovers (yet), those additional Popper.js features mentioned look amazing.

Including it for v4 general /dist/ but allow custom setup with or without additional Popper.js lift for respective components would be my way preferred way to go.

**Comment by thednp** [comment]
For anyone following this thread, please let me know if you find this functionality [here](https://github.com/cyrilreze/bootstrap-tooltip-extended) interesting, we would only need to update out `styleTip()` utility for that.

What do you think?

**Comment by thednp** [comment]
@midzer @Vuurvlieg @FezVrasta @artemsky @neuropass please test latest master and do some tests with **Popover** and **Tooltip**.

Let me know if you find any bug.

**Comment by thednp** [comment]
Nobody interested in testing?

**Comment by midzer** [comment]
@thednp I've introduced some tooltips in a site and everything is working fine on first look.

**Comment by artemsky** [comment]
@thednp had no time yet. I wanna test it in coming weekend

**Comment by Vuurvlieg** [comment]
I'm busy these days but found some time to test the latest master.

It seems to work nicely is most cases. Altough, at smaller window/container size, sometimes when I hover the button, some tooltips and popovers are not shown. Not sure if this is intended behaviour, or a bug or just because of my quick and dirty fiddle.  This is only related to the latest version of Chrome. ie11 has another issues; The tooltips are not being removed after hovering. See [here](https://postimg.org/image/2rk55vahjf/)

Check [fiddle](http://jsfiddle.net/9z7uoptf/). Used windows 7 64 bit latest updates, latest browsers

**Comment by thednp** [comment]
@Vuurvlieg I believe jsfiddle is handling something wrong, somehow it takes 400-500ms to handle some pointer/mouse events, which are long enough to not trigger `transitionend` and make the tooltips/popovers go away. jsfiddle IMO is not a reliable way to test "beta" versions.

**Comment by thednp** [comment]
The features are mostly implemented except `mousemove` events. We now close this but we might have to wait for more people to test before we release next version.
