### ISSUE TITLE
Button to trigger modal links to the wrong modal ID (bs v4)

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#159]
First of all thanks for this amazing project! Finally I can drop the jQuery library.

On the [example page](https://thednp.github.io/bootstrap.native/v4.html)  the `data-target` of the Modal is linking to the wrong ID.

**Comment by thednp** [comment]
Ah yes, thanks. Will make required changes asap.

**Comment by thednp** [comment]
Updated, please check the new demo page and the new [Wiki](https://github.com/thednp/bootstrap.native/wiki) pages!
