### ISSUE TITLE
Permanent popup (scripted)

### ISSUE THREAD

**Issue by IngwiePhoenix** [thednp/bootstrap.native#16]
After roasting and smoking my brain for a good while, trying to implement this, I finally can't go any further.

I have a little color picker library that I'd like to utilize. For that to work nicely, I wanted to implement a "permanent" popover, that would not go away untill it was closed using it's `.close()` method, or `.toggle()`.

I can trigger the popup, but as soon as I have clicked, it closes again. Why is that? I have made sure, but there is only a single `click` event, from what I can tell.

Here is the code:

```javascript
            e._popover = new Popover(e, {
                trigger: "click",
                template: '<div class="popover" role="tooltip">'
                    + '<div class="arrow"></div>'
                    + '<div class="popover-content color-picker"></div>'
                    + '</div>',
            });
            // Re-implementing Popover open and close to allow
            // the color picker to work as expected.
            e._popover.open = function() {
				if (this.popover === null) {
					this.createPopover();
					this.stylePopover();
					this.updatePopover();

                    // Color picker
                    var content = $(this.popover).find(".popover-content")[0];
                    e._picker = new piklor(content, palette);
                    console.log(e._picker);
                    e._picker.colorChosen(function(col){
                        console.log("Color: ",col);
                    });
                    e._picker.open();
				}
			}.bind(e._popover);
			e._popover.close = function() {
				if (this.popover && this.popover !== null && this.popover.classList.contains('in')) {
                    e._picker.close();
					this.popover.classList.remove('in');
                    this.removePopover();
				}
			}.bind(e._popover);
```

Any idea? The only source I have not checked yet, but which I highly doubt, is the Piklor instance itself (maybe its clinging to `click` too, which I doubt.)

**Comment by thednp** [comment]
The tooltips/modals get dismissed on any click event inside/outside the
trigger. We need to implement a prevention for that.

I think this would give you a clue.

**Comment by thednp** [comment]
How are you doing mate? I wanna talk to you about this and other stuff.

**Comment by IngwiePhoenix** [comment]
Im doing good!
You can reach me through Skype (wlaningwie) or E-Mail (ingwie2000@gmail.com) :) So if you wish to chat some, feel free to contact me!
Oh and if both do not work, then you can also use this gitter: https://gitter.im/Deskshell-Core/PhoenixEngine?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

I am also still stuck on the color picker. I took some sleep and will see which event is triggering the close.

**Comment by thednp** [comment]
Sure thing. I already added you on Skype and waiting to talk to you. I edited your previous post for understandable privacy reasons.

**Comment by IngwiePhoenix** [comment]
Alright. I accepted the request. shows you as offline atm though. Give me a poke when you wanna =)

**Comment by thednp** [comment]
Implemented, see the lib folders.
