### ISSUE TITLE
Overlay disappears when creating a modal during the hidden event of an existing modal

### ISSUE THREAD

**Issue by dtognazzini** [thednp/bootstrap.native#162]
I am opening a new modal in the event handler for the 'hidden' event of a closing modal. This works fine, however, there is a race with the overlay/backdrop whereby the new modal shows without the backdrop.

The race is the same as described in #30. The order of events:

1. existing modal is hidden
2. hidden event is fired
3. new modal is created
  - new modal doesn't create overlay due to the check [here](https://github.com/thednp/bootstrap.native/blob/c8febd37cec2ab864c84b81ef894c11e56a31f26/lib/V4/modal-native.js#L94). This check ensures there aren't two overlays created.
4. the timeout in `hide` from the existing modal removes the overlay ([here](https://github.com/thednp/bootstrap.native/blob/c8febd37cec2ab864c84b81ef894c11e56a31f26/lib/V4/modal-native.js#L148)).

PR coming shortly.

**Comment by thednp** [comment]
Great work, thanks for the contribution.
