### ISSUE TITLE
unbind events / destroy component?

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#165]
Hi there,

For some reason I need to remove all the event listeners which where added by bootstrap.native, when the modal closes.
I was wondering if there is a build-in function for that? If not, it would be nice to have.

Right now I am using the following code, but the events are **not** removed somehow.

This function is executed when someone clicks a button.
```js
function initModal()
{
  var modal = document.getElementById("my-modal");
  myElement = new Modal(modal, {backdrop: true, keyboard: false});
  myElement.show();

  modal.addEventListener("hide.bs.modal", function(event)
  {
    removeEventListener("click", this, false); // also "modal" instead of "this" does not work
    removeEventListener("hide.bs.modal", this, false);
   }, false);
}
```

**Comment by midzer** [comment]
I'm not 100% sure what you are intending, but i guess you can simply allocate a new `Modal` via
`var myElement2 = new Modal(modal, {backdrop: true, keyboard: false});`
and let Garbage Collector handle previous `myElement`

**Comment by Vuurvlieg** [comment]
Thanks for your reply.

The problem with your solution if that the bootstrap.native events are fired twice in that way (see pic) because the event handlers are not removed by Bootstrap.native.

So my intention is to remove the event listeners when the modal closes. In the current situation the event listeners are still there when the modal closes (see picture)

http://i68.tinypic.com/2vv3zvn.png

**Comment by thednp** [comment]
[These lines](https://github.com/thednp/bootstrap.native/blob/master/lib/V3/modal-native.js#L244-L246) basically do (or at least try it's best) what you are talking about.

Also [these lines](https://github.com/thednp/bootstrap.native/blob/master/lib/V3/modal-native.js#L124-L130) will try to toggle event listeners based on open/closed status of the modal.

I know the code is nowhere perfect when it comes to events, but at least you can see I've done my best to manage that case which was much discussed before. So I am open to any suggestion.

**Comment by Vuurvlieg** [comment]
I did some debugging and I'm close to a solution. Maybe not a nice and good one, but it seems to work for now on my local pc. (Not sure if I break other modal-functionalities)

The problem is:
 
1. https://github.com/thednp/bootstrap.native/blob/d0e148d9fe80b0ff72685415a72691f408daefcb/lib/V4/modal-native.js#L223

2. **After** removing the `show` class, the `triggerHide` function is executed which executes the function `dismissHandlerToggle`. In there, it checks for the `show` class, but ofcourse its removed in step 1 so the `click` event handler will be **added again** instead of being removed.

3. So the solution for this could be checking if the modal has the CSS display property to 'block'. If so we could say the modal is opened.
For example, use the following code instead of `if (!hasClass(modal,showClass)) {}`

>    isModalOpen = function()
      {
	  	return (window.getComputedStyle(modal, null).getPropertyValue('display') == 'block' ? true : false);
	  },

4. For now I use the `isModalOpen` function from above and it seems to work with a few extra changes. No more multiple `click` event listeners, just 1 which is removed after the modal was closed.

**Comment by Vuurvlieg** [comment]
Also, i was able to remove the duplicated `hide.bs.modal` event listeners, by reading [this](https://developers.google.com/web/updates/2016/10/addeventlistener-once) awesome tutorial.

I have to add `{once: true}` when adding an event listener.
For example:

> 	modal.addEventListener('hide.bs.modal', function(ev)
	{
	 	modal.removeEventListener('hide.bs.modal', this, false);
	}, {once: true});

**Comment by thednp** [comment]
Thanks for sharing your findings, I will probably update the docs with these findings.

Regarding the events, some stuff can be executed inside anonymous functions, something I used to do with **Collapse** and **Tab**, just to make sure the Bootstrap custom events trigger once.

**Comment by Vuurvlieg** [comment]
No problem, glad I could help!

> I used to do with Collapse and Tab, just to make sure the Bootstrap custom events trigger once.

I never tested the Collapse and Tab components for multiple unwanted event listeners, but for the Modal component the code you implemented in the current version of this library is unfortunately not working since each time the Modal is opened, a new handler is added in the way I showed in the very first post.

However, I managed to fix this issue. With a few tweaks, no more double event listeners/handlers are added to the modal.

Please check the difference between the original file and my tweaked file at [Diffnow](https://www.diffnow.com/?report=a7hiv).

Maybe you could use my tweaks with your own prefference to fix this event listener/handler issue.

**Comment by thednp** [comment]
Interestingly, we actually don't need the `isModalOpen` utility, we just have to check `inClass`/`showClass` AFTER the modal class was added / removed, plus change the togglers to start check if the modal HAS the `inClass`/`showClass` and no the other way around.

**Comment by thednp** [comment]
@Vuurvlieg please take a minute and test latest master.

Thanks

**Comment by Vuurvlieg** [comment]
I tested it and it does work now. Many thanks for fixing!

**Comment by thednp** [comment]
It seems the **Dropdown** component abuses `click` on `document`, I'm changing that currently, interested in a test on that?

**Comment by thednp** [comment]
@Vuurvlieg ping :)

**Comment by Vuurvlieg** [comment]
I see a lot of changes, well done :)

Just tell me exactly what I should test and I will do it!

**Comment by thednp** [comment]
* **Popover** with `focus` and `click` trigger
* **Dropown** works a bit different now, you will like it very much regarding events

I'm thinking of ways to improve `resize` event bound components, I still don't like'em.

**Comment by Vuurvlieg** [comment]
I am able to test it when I'm back from work.

Why do we need the resize handler anyway? I mean, why do we need this?

**Comment by thednp** [comment]
Talking about **Affix**, **ScrollSpy** these components currently suck.

**Comment by Vuurvlieg** [comment]
So I tested it and indeed I like it! The attached events are properly removed at the right time. Thanks!

**Comment by edufranzoni** [comment]
Hello guys, Sorry for commenting on a closed topic.
But I can't cancel the hide.bs.modal event.

I need this to alert the user that he will lose changes to the form if he closes the modal.

What i'm trying to do
`document.getElementById('dynmodal').addEventListener('hide.bs.modal', function (e) {                    
                    e.preventDefault();
                    e.stopImmediatePropagation();                  

                  if (hasChangeAnyValue) { //var who crontrols form changes
                        var r = confirm("Do you loss form data if you leave dear user!!! Continue?");
                        if (r == true) {                         
                            return true;
                        } else {
                            debugger;
                            removeEventListener("click", this, false); 
                            removeEventListener("hide.bs.modal", this, false);                            
                            return false;
                        }
                    } 
                    return false;
                });`

**Comment by thednp** [comment]
You need to make a custom close button action for the modal with a custom handler:

```
function yourCustomHandler (){
  if ( confirm( ERROR_MESSAGE ) ) {
    yourModal.close(); // the bsn component public method
    // do the dew you want
    return false;
 } // if user does not confirm the modal will stay visible
}

yourNewButtonAction.addEventListener('click',yourCustomHandler, false);
```

I think you can't exactly change the way the modal component works unless you fork it.

**Comment by thednp** [comment]
@edufranzoni a new issue with a feature request should do, I've been thinking about it and will come up with a plan later this week.

**Comment by thednp** [comment]
@edufranzoni please check #302 thanks.

**Comment by thednp** [comment]
@Vuurvlieg have a look at the latest master and let me know how it works.

**Comment by momentous6** [comment]
@thednp https://jqcode.space/questions/what-sets-apart-addeventlistener-and-on-when-it-comes-to-including-an-event-in-bootstrap-5
