### ISSUE TITLE
Including the script in the <head>

### ISSUE THREAD

**Issue by domchristie** [thednp/bootstrap.native#166]
I'm currently using Turbolinks which requires that scripts be placed in the `<head>`. Bootstrap native throws an exception when the script is included in this way. This is because the `body` variable is set to `document.body` when the script loads, which in this case will be `null`.

It might be possible to fix this if:

- the IE8 check used the `documentElement` rather than the body (`isIE8 = !('opacity' in doc[style])`)
- `body` was either set on `DOMContentLoaded`, or `body` was replaced with `document.body`, or `body` was a function which returned a memoized `document.body`

**Comment by thednp** [comment]
Nop. Fork it and make it work your way.

**Comment by domchristie** [comment]
I agree that in most cases scripts should be in the body, but what are the arguments against the proposed changes? Its seems like a relatively small tradeoff to make the library more versatile.

**Comment by thednp** [comment]
Why use it in head?

**Comment by domchristie** [comment]
> Why use it in head?

For the performance benefits of evaluating a script just once across multiple page loads.

[Turbolinks](https://github.com/turbolinks/turbolinks) captures link clicks, makes the request via ajax, and replaces body, and keeps the head intact. This means that a browser does not have to parse/evaluate the CSS/JS for each page load, which therefore improves the performance. By including the script in the body, the browser will unnecessarily evaluate the script each time.

As I mentioned, I agree that in most cases, developers should be encouraged to place their scripts  at the bottom of the body, but to develop a library that can _only_ be included that way seems needlessly limiting.

What are your reasons against making this `<head>`-friendly?

**Comment by thednp** [comment]
Have you changed the library and tested it in the `<head>`? Can you confirm it's working? I would guess not. Here's why I think so.

It's not that I'm against it but we would have to make the library much like jQuery and specifically the Bootstrap original plugins:
* most events are bound to `document` and delegated to elements
* jQuery `data` keeps everything in the memory in a way that the library can "magically" work with later added elements, and probably cover the case with Turbolinks as well
* eventually, I don't think with your proposed changes it will be enough to make it work in the `<head>`, we would have to implement some similar jQuery functionality for that, as I pointed above

My main reasoning is this: get maximum performance out of the box, as each developer has the power to change the library to each use case, as each use case has so much specific stuff going on, it's really hard to put it all together in a single, universal and unified library. So you have the prototypes, you can create your own helpers to do what you need, for every use case.

Everything I said is not permanently however, who knows, maybe everybody will adopt a new trend and there we have a new way to load pages with XHR and use all scripts in the head, somehow bypassing the scripting errors to avoid having complete blank pages.

**Comment by domchristie** [comment]
> Have you changed the library and tested it in the `<head>`?

Yes, I created a minimal use case with the dropdown component.

> Can you confirm it's working?

Yes, it works with manual instantiation. (I have since tested it with the modal component and that also works.) I think it would be acceptable for auto-instantiation to only work if included at the end of the body. But at the moment, manual instantiation is broken because of when `body` is set. Referencing `document.body` in each component would be a simple change, and probably wouldn't cause a noticeable change in performance.

> as each developer has the power to change the library to each use case, as each use case has so much specific stuff going on, it's really hard to put it all together in a single, universal and unified library

I appreciate this, but I think in this case there's an opportunity to make the script usable without having a noticable impact in other areas.

**Comment by thednp** [comment]
Only dropdown would work. It's the only one that uses `document` as the event target for the click handler.

**Comment by domchristie** [comment]
> In fact the entire library is written to be used in the body.

As far as I can tell, currently the only part which requires the body is the IE8 check (which can be changed to use `document.documentElement`). Granted, the `initializeDataAPI` functions won't do anything in the `head` because the DOM queries won't return any elements, but replacing the `body` variable with `document.body` _inside_ the components will let the components be initialised manually at any point.

Here is a demonstration of the fixes with both a dropdown and a modal: https://jsbin.com/fejexet/2/edit?html,js,output

(Just so we're discussing the same thing here, I'm currently working with the v3 script.)

**Comment by thednp** [comment]
The `isIE` check stuff makes sense but I don't understand what you mean here

>body was either set on `DOMContentLoaded`, or body was replaced with `document.body`, or body was a function which returned a memoized `document.body`.

**Comment by domchristie** [comment]
This refers to the `body` variable set here: https://github.com/thednp/bootstrap.native/blob/master/lib/V3/utils.js#L8 This part is run immediately, so when the script is in the `head` it will be `null`.

It might be better to demonstrate this with a pared-down version of the script:

```js
var body = document.body

function Modal (element) {
  // …
  body.appendChild(someElement)
}

// Initialise a modal:
new Modal(document.querySelector('[data-toggle=modal]'))
```

When this is included in the `head`, the `body` variable will be `null`, so when the `Modal` is initialised (at any time), it will throw an error.

The possible fixes are:

**1. Reference `document.body` directly rather setting `body` variable**: replace instances of `body` with `document.body`. This is what I have done in the demo. It is the simplest, but probably the slowest.

**2. Set `body` on `DOMContentLoaded`**: this would require a bit of refactoring, because the `initializeDataAPI` would also need to be called on `DOMContentLoaded`. It might look something like:

```js
var body

// …

document.addEventListener('DOMContentLoaded', function () {
  body = document.body
  initializeDataAPI(…)
})
```

I'm not sure how this would impact the overall performance, but given that it's set as a variable, accessing `body` will be just as quick. This is the version I'm least sure about.

**3. Convert `body` to function** which sets a "private" variable on its first call, then returns the variable on subsequent calls (memoization):

```js
var _body
function body () { return _body || (_body = document.body) }

// Then to use it in a component
function Modal (element) {
  // …
  body().appendChild(someElement)
}
```

This is probably the best option.

**Comment by thednp** [comment]
Oh that's what you mean, ok thanks for the suggestion. I will think about it and come up with something.

**Comment by thednp** [comment]
@domchristie please take a minute and test latest master.

Thanks

**Comment by domchristie** [comment]
Works as expected 👍

**Comment by thednp** [comment]
@domchristie starting with BSN version 2.0.20, you can use the library in your site <head> without any additional scripting required, so please download latest master and give it a swirl. Check out updated wikies.
