### ISSUE TITLE
[V4] After updating to the newest version tabs do not work properly if "fade" class is used.

### ISSUE THREAD

**Issue by Veesparion** [thednp/bootstrap.native#168]
After updating to the newest version tabs do not work properly if "fade" class is used.

First switch to lets say second tab works okay but then i cant switch back to the 1st tab unless i wait around 20-30 seconds then it works so basically switching between tabs works once per 20-30 seconds.

If fade class is not used it works fine.

**Comment by thednp** [comment]
[The demo](http://thednp.github.io/bootstrap.native/v4.html) is using the latest code and the `fade` class. But will check further.

**Comment by Veesparion** [comment]
Its the height animation while its happening it blocks the tab switch, if you try to switch tabs fast even in the demo you sometimes cant switch the tab.

**Comment by thednp** [comment]
That is the point, wait for height animation to finish first.

**Comment by thednp** [comment]
@Veesparion please test latest master. It now works perfect with/without `fade` class and with/without the height animation in all browsers.

**Comment by thednp** [comment]
Just to give you some insights: the issue was present some versions back but forgot to take care of them, so I'm sorry. Also was present with both V3 and V4 versions.

The current master has this issue fixed finally and we an go forward now.
