### ISSUE TITLE
Carousel (v4) interval bug

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#169]
Hi there!

I want to stop automatic sliding for the `Carousel` component, so I set the `interval` to `false`. However, the library ignores this and grabs the default `5000`.

I created a quick fix by changing

`if ( !( options[interval] || intervalData ) ) { // determine slide interval`

to

`if ( !options[interval] || !intervalData ) { // determine slide interval`

**Comment by thednp** [comment]
That is correct, however, if you set `data-interval="false"` it's not going to automatically cycle.

**Comment by Vuurvlieg** [comment]
Well, the library ignores (and thus cycle automcatically) when using Javascript directly, like

`var myCarouselInit = new Carousel(myCarousel, {
		interval: false,
		pause: false,
		keyboard: false
	});`

**Comment by thednp** [comment]
@Vuurvlieg I'm working on something but I won't forget this. Closing this out.

**Comment by thednp** [comment]
@Vuurvlieg I commited new code last night, I also added a [new feature](https://github.com/thednp/bootstrap.native/issues/171).

Please download the master and do some checks, thanks.

**Comment by Vuurvlieg** [comment]
@thednp I checked it roughly and it seems to work now. Many thanks!
