### ISSUE TITLE
easier building selected scripts

### ISSUE THREAD

**Issue by troyk** [thednp/bootstrap.native#17]
This library looks awesome.  Not only do I want to drop the jQuery dependency, but I'd also like to drop a bunch of features I'm not going to use.

I'm not that familiar with gulp, but after a quick browse of the API it seems that if  `gulp.src('lib/*.js')` was changed to an array of the lib files it would make it easier for folks to fork and comment out unwanted components.   Would you be interested in a pull-request that breaks out the src files into an array?

Thanks again!

**Comment by IngwiePhoenix** [comment]
Looks like a case for me. :) I did the Gulpfile here.

I used the glob (`lib/*.js`) to easily catch all the components. But, what is your main concern? If you fork and only edit the file you want to edit, nothing else's gonna change.

**Comment by thednp** [comment]
Well, thanks for the input. Unfortunately @IngwiePhoenix here is the only one who actually contributed for this feature and I would like to have more people involved in the discussion on this matter. 

Of course for the best of us.

**Comment by thednp** [comment]
Oh I see you already forked and improved the file, why don't you mane a PR, I will have Mr. @IngwiePhoenix here test it out.

**Comment by troyk** [comment]
@thednp yup, I needed it last night so just did it incase you were interested.  I'll send the PR now, btw for my build last night I only included `alert, dropdown, popover, tab, tooltip` and ended up with a 13k file (so 1/3 the size) -- soooo super damn awesome to make a mobile landing page with 13k of js ;)  Thanks again for making this.

I think I'll take a quick look at modifying the sources via args passed to gulp before submitting

**Comment by thednp** [comment]
Alright, so before you PR, please make sure to triple check everything works properly.

**Comment by troyk** [comment]
@thednp quadruple checked, pull-request at #19

**Comment by IngwiePhoenix** [comment]
@thednp Looked at #19 - looks solid. Added my little comment to it too. :)

**Comment by thednp** [comment]
Alright now, closing it down. Thanks for the PR @troyk
