### ISSUE TITLE
v4 Modal backdrop is not removed on close

### ISSUE THREAD

**Issue by dkbnguyen** [thednp/bootstrap.native#170]
`<div class="modal-backdrop fade show"></div>` is added when modal is on `show`, but it only turns to `<div class="modal-backdrop fade"></div>` on `hide` while it's supposed to be removed.
This creates an issue where after closing a modal, nothing on the page can be clicked.

**Comment by thednp** [comment]
The demo has latest code, no issue there, perhaps you're using an incorrect markup?

**Comment by thednp** [comment]
@dkbnguyen well?

**Comment by dkbnguyen** [comment]
Sorry for the late reply. It was my bad, I commented out the bootstrap `transitions` scss module. It should be included in css file in order to run modal script.
Thank you for getting back quickly.
