### ISSUE TITLE
New feature for Dropdown: keyboard navigation for accessibility compatibility

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#171]
New accessibility features for **Dropdown**
* when open, pressing **up**/**down** arrow keys will allow users to select menu items;
* **Esc** key now closes last open nested dropdown menu;
* while open, pressing up/down arrows the component will prevent the default scroll behavior
* opening the dropdown, the browser will focus the first menu item (if any) OR the first focusable element when something like a form is inside the menu
* closing the dropdown, the browser will focus the triggering element (element with `data-toggle="dropdown"` attribute)

Please test latest master both V3/V4 and report any issue.

**Comment by thednp** [comment]
Update, the `Esc` does not close the form dropdown. Working on a fix.

**Comment by thednp** [comment]
Fixed the issue, I will wait for some confirmation before we go forward with the next release tag.

**Comment by midzer** [comment]
Great work, @thednp 
I just checked out master and really like those changes except

>> * opening the dropdown, the browser will focus the first menu item (if any) OR the menu itself when something like a form is inside the menu

I dislike first menu item having focus after opening (navbar) dropdown for me. It's mainly a styling issue which doesn't fit my taste tbh.
How about first menu item gets (accessibility) focus with a single key "down" press?

Looking forward to others joining the conversation as well :)

**Comment by thednp** [comment]
@midzer, you don't have to use focus styling for your menu items on `@media all`, you can use them only for screen readers.

**Comment by Vuurvlieg** [comment]
Well let me join this discussion.

First of all I like this new feature, thanks @thednp for improving this library each time!

I you ask me I would say focussing the first dropdown item is not a good idea. I don't like the styling either and I think it is confusing for the user and for me as well. Altough there is a differnce, I'm in doubt the first item is active or just focussed.

But, when I take the [example dropdowns](https://thednp.github.io/bootstrap.native/v4.html) of the homepage, I like the automatically focus on the input email using the `form Dropdown`

**Comment by thednp** [comment]
@Vuurvlieg & @midzer I found that when the Enter key is pressed, browsers will automatically focus first menu item, seems to be the default behavior, so we only need to focus an `INPUT` if any. If you open the dropdown with click, it will only focus the first input if any, but if it's a regular menu, it will only allow to go up and down with arrow keys.

Please test the latest master.

**Comment by midzer** [comment]
Interesting find about browser behaviour on those dropdowns. Got to keep this one in my mind.

Latest changes LGTM :+1:

**Comment by Vuurvlieg** [comment]
Latest changes does work for me, thanks!

**Comment by midzer** [comment]
Sorry to bring this up again.
But for me Keydown is not working any more after opening Dropdown with Enter key.
Only Tab seems to work.

Do we have a regression here?

Cheers
midzer

**Comment by thednp** [comment]
@midzer, after pressing Enter on a dropdown you need to Tab inside, then use arrows to navigate up/down. We don't change how browsers behave in regards to focus except when we have a form inside the dropdown-menu. So we're not doing anything special here.

**Comment by midzer** [comment]
Okay. If this behaviour is intended then no problem.

I just had a review for accessability of a website by a person who uses a screenreader.
He argued, having the possibility to navigate down after Enter key would be better for him.

But there is no standard for this i guess.

**Comment by thednp** [comment]
That was our initial code design, but many devs here argued against it, because w3c standards leave open to users to navigate at will the dropdown.

**Comment by midzer** [comment]
I'm just learning to improve accessibility on my sites.

Please check out https://inclusive-components.design/menus-menu-buttons/#keyboardandfocusbehavior

Maybe we can start a new discussion with the community about it.

**Comment by thednp** [comment]
That looks to me like a great idea for out component, but it's still an opinion. My concern born with this thread is that we code a new behavior, w3c changes the expected behavior, Chrome and Firefox will quickly follow and we're stuck in the swamp.
