### ISSUE TITLE
Bug: tooltip, popover, tab

### ISSUE THREAD

**Issue by nicola-spb** [thednp/bootstrap.native#174]
1) When I touch button with tooltip and popover tooltip isn`t opened. (android 4.2.2, chrome 35)
I think you should add touch events for tooltip and popover (touchstart, touchend)

2) When I touched on tabs Home | Profile (about 10 times) sometime tab is hovered but isn`t opened. (on mobile phones and desktop) When I do it fast.

I tested on your demo page.

**Comment by thednp** [comment]
Must be due to the latest changes in the Chrome for Android. The Windows version also changed some stuff recently regarding the touch events

**Comment by nicola-spb** [comment]
I tested it in bootstrap original and native. I found different results.
https://getbootstrap.com/docs/3.3/javascript/#tabs
https://getbootstrap.com/docs/3.3/javascript/#tooltips

**Comment by thednp** [comment]
Yea, I'm updating Chrome on the phone and will do some tests.

**Comment by thednp** [comment]
Nope, works for me.

**Comment by nicola-spb** [comment]
:-) I tested on thee mobile phone. On android 4.2.2 I have 2 bugs, on android 6 and iphone I don't have bug with tooltips and popovers. I think on these devices mouseenter = touchstart.
But bug with tabs I reproduce on all devices and on desktop chrome browser.
Later I can add screenshots from mobile

**Comment by thednp** [comment]
Android 4 series is too old, I wouldn't go so far to throw another event listener for that. On the other issue with tabs perhaps you don't know that we wait for the animation to finish first then, release the listeners to kick in again.

**Comment by nicola-spb** [comment]
Ok. ::(
No matter. I think bootstrap native should work like original without other problems and will be faster. Thats why I wanna delete jquery. When I replace library I didn't wait extra problems. I think you should support all devices that original has suppprted. But you owner. I will fix it for myself.

**Comment by thednp** [comment]
You have to understand something. We support IE8+ browsers because they can do it with minimal size polyfills. We cannot do the same for older Android because they have even less support for JavaScript API.
