### ISSUE TITLE
carousel autoplay

### ISSUE THREAD

**Issue by adjejansen** [thednp/bootstrap.native#175]
I just find out this project.But i am wondering how to set the carousel to autoplay. You have to click the icons for a new slide.

**Comment by thednp** [comment]
http://thednp.github.io/bootstrap.native/#carouselOptions

**Comment by adjejansen** [comment]
sorry, i cannot find the solution to get it it to autoplay.The two sliders in the index.html does not loop. tryed to set some options to false, but no change. Maybe there is an example for a working slider.

**Comment by thednp** [comment]
> interval	number	5000	
Option the component's delay between transitions in miliseconds. Can be set via JavaScript or the data-interval="INTERVAL" attribute. If you want to disable the automatic transition, you can set this option to false. Starting with version 2.0.19 the component will not automatically slide if the element is not visible in the viewport.

**Comment by adjejansen** [comment]
Problem solved, had loaded jquery in my example page. after deleting the file all went oke.

Thank You
