### ISSUE TITLE
New feature: Button toggle via Space key

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#176]
Some info:
* the switching to each button is done traditionally via `Tab` and `Shift` + `Tab` keys, where original script implements navigation via arrow keys
* we prevent scrolling when the element in focus is the target of `keydown` event
* additional markup required in order for the script to work properly in a real world form
* Documentation [updates regarding usage](http://thednp.github.io/bootstrap.native/index.html#buttonExamples)
* Commit details [here](https://github.com/thednp/bootstrap.native/commit/e1a151c16359c6e964b16b2fb49c20c3db2e430f)

Please test latest master and post your issue here.
Thank you

**Comment by midzer** [comment]
Although i don't use any toggle buttons in my projects right now, those documentation examples are working smoothly for me regarding `space` key usage.

**Comment by thednp** [comment]
Thanks guys. Published to npm and pushed the new release tag.
