### ISSUE TITLE
Carousel doesn't autoslide anymore

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#177]
Just upgraded to 2.0.20 and experience my carousel doesn't slide any more.

For both, v3 and v4, and on demo pages, too.

**Comment by thednp** [comment]
Why didn't this report come before the release?

**Comment by midzer** [comment]
Probably because i didn't realize any big changes for carousel and therefore didn't doublecheck. Sorry.

**Comment by thednp** [comment]
@midzer  No matter, I found another issue with nested Dropdowns, fixed both.

Please do test the latest master before we go again with another release.

**Comment by midzer** [comment]
Yeah, it's working again. Can't check nested dropdowns though. Thanks for your effort!

**Comment by thednp** [comment]
The issue with Dropdowns was that it was ignoring child elements of the triggering element, such as icons and such.
