### ISSUE TITLE
issues using ARIA

### ISSUE THREAD

**Issue by tobwen** [thednp/bootstrap.native#179]
There seems to be a problem with ARIA when using bootstrap.native in v3 and v4.

This example works on jQuery and Bootstrap v3: https://codepen.io/Sp00ky/pen/aZJWLa
When using bootstrap.native, it stops working (check the upper chevron): https://codepen.io/1100101/pen/RjXqeg

**Comment by thednp** [comment]
Thanks for reporting, please test latest master.

**Comment by thednp** [comment]
@tobwen please test latest master.

**Comment by tobwen** [comment]
https://codepen.io/1100101/pen/RjXqeg

Updated & Working. Thanks!
