### ISSUE TITLE
Unable to use dynamically added elements to control things like modal or carousel

### ISSUE THREAD

**Issue by osdlge** [thednp/bootstrap.native#18]
When adding dynamic elements to a page they are unable to interact with elements they were already present. For example add this into scripts.js and refresh the index page

```
document.addEventListener('DOMContentLoaded', function waitForDomToFullyLoad(event) {
   var newButton = document.createElement("div");
   newButton.innerHTML = '<button id="TEST1" type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#myModal">DYNAMIC BUTTON</button>';
   var modalExample = document.getElementById('exampleModal');
   exampleModal.appendChild(newButton);
});
```
go to the bottom of the modal examples and click dynamic button

Expected results:
the modal myModal opens

Actual results:
Nothing happens

**Comment by thednp** [comment]
The modal's click handlers currently don't support later added modals (modals added after domReady triggered). But I would solve your issue differently. 

* Add this script in the `<body>` BEFORE the `bootstrap.native` script link and tell me how it goes. 
* Also, don't use the `DOMContentLoaded` listener, it's already ready if you link scripts at the end of the `<body>`.

**Comment by osdlge** [comment]
Looks like that will work, thanks!

**Comment by thednp** [comment]
Alright, closing this down then.

**Comment by IngwiePhoenix** [comment]
@thednp You could add a `.detect()` function that initializes things that weren't initialized yet. Just a random thought, really.

**Comment by thednp** [comment]
Naa, no need :)

I prefer speed.

**Comment by IngwiePhoenix** [comment]
Need for speed.
Huehuehue.
Alright then, was just an idea anyway. :)
