### ISSUE TITLE
Cannot use independent modules within ES6 based components

### ISSUE THREAD

**Issue by travist** [thednp/bootstrap.native#180]
We are looking to include this library in the [Form.io](https://form.io) core renderer @ https://github.com/formio/formio.js, but ran into a couple of problems that I believe others may have ran into as well.

1. We cannot target a specific component to apply this library. Every time we call ```require('bootstrap.native')```, it seems to trigger a global registration on the ```window``` object by calling ```initializeDataAPI```. This basically means that anyone who includes our renderer may get some pretty serious side effects that could affect their whole page. I would really like to see a way to disable the global registration of ALL of the components with ```initializeDataAPI```.

2. We cannot include a specific module. We would love to do the following.

    `import { Collapse } from 'bootstrap.native/lib/V3/collapse-native.js'`

    but this does not work. This requires your libraries to create their modules like as follows.

   ```js
   export class Collapse {

   }
   ```

    you would then just need to run it through Babel to create your distribution. Another option is to just use ```module.exports = Collapse``` which we could then call ```const Collapse = require(bootstrap.native/lib/V3/collapse-native.js');```

    This library seems to have a pretty custom build process which I think is keeping it from being used in a standard way.

Please advise.

Travis.

**Comment by travist** [comment]
Beside ES6 support, the real pain is #1. We cannot include this library without it searching the whole DOM to attach itself to all relevant components. I have debugged to look fo a way around it doing that, but to no avail. It should be possible to solve that without an ES6 rewrite.

Unfortunately for now, it seems working around the issue is going to be to not use this library and implement what I need manually.

I do appreciate you offering this library, but until that issue gets resolved, we won't be able to use it as a dependency to our library.

Thanks again,

Travis

**Comment by travist** [comment]
What do you mean "no DATA API"?  Are you referring to using the "data-toggle", etc attributes on the DOM nodes? If that is the case, then I cannot control what people have on their page when they embed my library, and if they just happen to have data attributes attached to some of their DOM elements, then this library will hijack them and cause unwanted behaviors.

Let me know if that is not what you were referring to, and if there is some other type of configuration I am missing. I am currently using the CommonJS import into my application, and from the looks of it, as soon as I require this library, it starts scanning the WHOLE page for "data-*" attributes and modifies their behavior to adhere to this library. That is a behavior that I would like to avoid since my preference it to be explicit which elements this library attaches itself to.

**Comment by thednp** [comment]
SO basically you need ES6 like functionality without actually rewriting the library. I think the best thing for you is to fork it, and make it work your way.

**Comment by travist** [comment]
No that isn't what I was saying. When I include this library using ```require```, it triggers a global registration on the whole Document https://github.com/thednp/bootstrap.native/blob/master/dist/bootstrap-native.js#L1903.  

What would be awesome is if I could include independent pieces like this.

```js
const Collapse = require('bootstrap.native/lib/V3/collapse-native');
```

This would skip over the global registration stuff, but I cannot do that because you do not have a 

```js
module.exports = Collapse;
```

at the bottom of the file.

This does not require an ES6 rewrite and would solve a lot of heartache for people wishing to use your library as a dependency for their own libraries.

**Comment by thednp** [comment]
I really don't know how to solve this right now and don't afford the time to fix it without an ES6 rewrite.

**Comment by travist** [comment]
Trust me, I understand that sentiment. I wouldn't worry to much about it. Thanks for the library. I will subscribe to it to keep an eye on any refactoring that come in the future.

**Comment by marcelpanse** [comment]
@travist I have the same issue. I added a simple option to exclude the utils-init code and created a PR. In the meanwhile you could use it directly here: https://github.com/marcelpanse/bootstrap.native
