### ISSUE TITLE
A suggestion that is an issue in some ways.

### ISSUE THREAD

**Issue by WHBitbucket** [thednp/bootstrap.native#181]
Ive been having a play with this library tonight on some code that is working fine with the jquery method already.

Shouldn't this library really be a direct replacement for the original setup. It seem from what Ive been testing that its sort of a 50% without a lot of messing.

Just picking on one component "collapse". This works fine when the DOM is statically loaded. When you alter the DOM dynamically with vuejs, react or just manually etc etc it doesn't work. 

In the documentation it does show some code for dynamically loaded content but it mostly errors for me when your not doing something simple.

Yes I could fix this write some extra code but the fact that the original jquery version does this without me doing anything is really what this should do. 

You maybe have good reasons for not doing this I don't know but Ive found that when you start having to write extra / patch / bodge other peoples libraries you might as well ditch them and write what you need yourself.

Its a shame because I like this replacement but most apps now alter the DOM after the initial loading. And a lot of the more basic developers wont know how to code around this.

It easy to moan about a FREE replacement developed by other peoples time so take it as it is. But if it isn't useful and doesn't save more complication and development you will find that I like most will simply dismiss this which is a shame as its good where it does work.

**Comment by thednp** [comment]
You didn't find [this](https://github.com/thednp/bootstrap.native/wiki/Acknowledgements#some-features-are-even-better)?

**Comment by Ruffio** [comment]
can this be closed?
