### ISSUE TITLE
Tooltips appear to be off-center after an update.

### ISSUE THREAD

**Issue by Veesparion** [thednp/bootstrap.native#182]
After updating it seems that my tooltips appear around 2px off their previous position ( before the update ) so if the positon is top tooltip's arrow is too far around 2px to the right if its right then its 2px too far to the bottom.

**Comment by Veesparion** [comment]
At this moment i'm using something like this to correct it

      if (position === top || position === bottom) {
          arrowLeft = arrowLeft - 2;
      } else {
          arrowTop = arrowTop - 2;
        }

**Comment by thednp** [comment]
Thanks for reporting, the algorithm isn't the best but it does the job done. I will have a look asap.
Happy holidays!

**Comment by Ruffio** [comment]
Cool

**Comment by AdamMarsden** [comment]
Any update on this?

**Comment by thednp** [comment]
UPDATE: I'm feeling kinda annoyed by this, I had to hack the code with every beta version and with this final (non-beta) version it just sucks, especially if this trend continues.

We're all in the bad side here, whenever Popper.js changes how it calculates the positions, the Bootstrap core developers will have to make CSS adjustments, and I think Popper.js should have been removed by now.

**Comment by thednp** [comment]
Please test the latest master.

**Comment by thednp** [comment]
@Veesparion can you please confirm?
