### ISSUE TITLE
Tooltip delay on show 

### ISSUE THREAD

**Issue by mariusdoros** [thednp/bootstrap.native#183]
For V3, instead of Tooltip delay option / attributte it is possible to have delayShow and delayHide options / attributes. 
`this[delayShow] = parseInt(options[delayShow] || delayDataShow) || 200;`
`this[delayHide] = parseInt(options[delayHide] || delayDataHide) || 200;`

`this.show = function() {
      clearTimeout(timer);
      timer = setTimeout( function() {
        if (tooltip === null) {
          placementSetting = self[placement]; // we reset placement in all cases
          createToolTip();
          updateTooltip();
          showTooltip();
          bootstrapCustomEvent.call(element, showEvent, component);
          !!self[animation] ? emulateTransitionEnd(tooltip, showTrigger) : showTrigger();
        }
      }, self[delayShow] );
    };`

`this.hide = function() {
      clearTimeout(timer);
      timer = setTimeout( function() {
        if (tooltip && tooltip !== null && hasClass(tooltip,inClass)) {
          bootstrapCustomEvent.call(element, hideEvent, component);
          removeClass(tooltip,inClass);
          !!self[animation] ? emulateTransitionEnd(tooltip, hideTrigger) : hideTrigger();
        }
      }, self[delayHide]);
    };`

Or could you suggest me another solution? Thx.

**Comment by thednp** [comment]
Fork it and make it work your way, as easy as that.
