### ISSUE TITLE
Modal overlay not disappearing

### ISSUE THREAD

**Issue by jekelija** [thednp/bootstrap.native#184]
I am 100% certain that I am doing something wrong, but could not tell you what. So this is less of a bug and more of a question. My modal overlay is not disappearing on an element. In order to get it to disappear, i had to comment out the setTimeout in the modal hide function, i.e.:
`//      setTimeout(function(){`
`        hasClass(modal,'fade') ? emulateTransitionEnd(modal, triggerHide) : triggerHide();`
`//      }, supportTransitions ? 150 : 0);`

I'm not an expert, but it seems like adding the transition end after 150ms won't work b/c the transition itself only takes 150ms, which means depending on order of operation, the transition end listener won't get added until after the transition completes and the transition end event was already fired.

However, I assume I'm doing something wrong, since I can't seem to find anyone else having this issue. Please advise.

**Comment by thednp** [comment]
You might have to check HTML validation and consistency with Bootstrap markup.

**Comment by jekelija** [comment]
I believe its valid, b/c it was working with bootstrap. All i did was switch an existing modal over from jquery to bootstrap native. And the overlay stopped disappearing. Would you like me to post a sample?

**Comment by thednp** [comment]
Sure.

**Comment by jekelija** [comment]
And i'm a damn fool. I think. Now I can't reproduce. Ignore me.

**Comment by thednp** [comment]
It's ok, happens all the time.
