### ISSUE TITLE
Initial activeIndex and next/prev controls

### ISSUE THREAD

**Issue by CybMeta** [thednp/bootstrap.native#185]
Next/prev controls start always to cycle from index zero, no matter the initial activeIndex value.

**Comment by thednp** [comment]
The initial `activeIndex` is set by the item with the `active` class, or zero if none.

**Comment by CybMeta** [comment]
Yes, I know `activeIndex` is set to the intem with `active` class, but the carousel it is not working as expected. While the intial `activeIndex` is correctly set, the next/prev starts cicling always from zero. I mean, if initial `activeIndex` is 5, for example,, `getActiveIndex()` method correctly return `5`, but if you clic next button, the carousel slides to item with index 1, not to item with index `6`.

**Comment by CybMeta** [comment]
Not only the next/prev controls, the auto slide also fails. Tested with this littel example (b4):

```
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="true">
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=0" alt="">
      <div class="carousel-caption">
      <h3>This is another carousel</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=10" alt="">
      <div class="carousel-caption">
      <h3>This is a caption</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=210" alt="">
      <div class="carousel-caption">
      <h3>This is another caption</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=211" alt="">
      <div class="carousel-caption">
      <h3>This is another caption</h3>
      </div>
    </div>
    <div class="carousel-item active">
      <img src="https://unsplash.it/837/300?image=212" alt="">
      <div class="carousel-caption">
      <h3>This is another caption</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=213" alt="">
      <div class="carousel-caption">
      <h3>This is another caption</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://unsplash.it/837/300?image=214" alt="">
      <div class="carousel-caption">
      <h3>This is another caption</h3>
      </div>
    </div>
  </div>

    <!-- Controls -->
    <a class="carousel-control-prev" href="#swipeableviews" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span>Previous</span>
    </a>

    <a class="carousel-control-next" href="#swipeableviews" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span>Next</span>
    </a>

</div>
```

**Comment by thednp** [comment]
I think this is of very little importance, again to be fixed to your liking in your own fork.

**Comment by CybMeta** [comment]
It is not a matter of my liking, It is a clear bug from my point of view as it is something not wokring as it should. If you are not willing to fix it, you don't have to, but it is not a matter of my liking at all. I will try to fix at my own. Thanks anyway.

**Comment by thednp** [comment]
The option accepts a number or the string `false`. And that's it.

**Comment by CybMeta** [comment]
Change this definition:

`index = element.index = 0`

To:

`index = element.index = slides[indexOf](getElementsByClassName(element,carouselItem+' active')[0]) || 0`

Seems to be fix this issue.

**Comment by Vuurvlieg** [comment]
I agree, its nice to have that fixed.

**Comment by CybMeta** [comment]
The code change I posted is just a quick fix to ilustrate where the problem is, but it is not, I think, a fix ready to be integrated in the code base. @thednp are you stilll not wiiling to accept this issue as bug? Could you please reconsidere it?
