### ISSUE TITLE
Clicking on the active tab hides tab content in v4.

### ISSUE THREAD

**Issue by jpapillon** [thednp/bootstrap.native#187]
I noticed that when you click on an active tab, the tab panel will hide (I'm using Chrome and `bootstrap.native@2.0.21`). This behavior is also present on the [demo page](http://thednp.github.io/bootstrap.native/v4.html).

![tabs-issue](https://user-images.githubusercontent.com/3585712/35753281-161acfa4-082d-11e8-8699-e23f29cff575.gif)

**Comment by midzer** [comment]
I can reproduce this bug in my projects.
