### ISSUE TITLE
Click on tab link doesn't activate tab's content if no previous active tab exists

### ISSUE THREAD

**Issue by CybMeta** [thednp/bootstrap.native#191]
If none of the tabs are currently active, you can not activate any of them by clicking on tabs links.

**Comment by thednp** [comment]
So you can activate one on initialization.

**Comment by CybMeta** [comment]
The use case is that there is no active tab until user selcts one; i can
intercept the click event at my own and active the tab, of course, but It
should be handled by the tabs plugin. I think. It os the correct and
expected behaviour.

**Comment by thednp** [comment]
No, that alone is an example of broken HTML. I cannot imagine a case where no tab content is shown and no tab is active, it would be a menu there hanging with no purpose at the first sight.

I'm closing this, the current state is where I think is the right behavior.
