### ISSUE TITLE
Element in Popover

### ISSUE THREAD

**Issue by mathieuleclaire** [thednp/bootstrap.native#194]
Hi,
I was wondering if we could somehow or other set an HtmlElement in a Popover (rather than only a string) ?
Thanks

**Comment by thednp** [comment]
You can if you encode your HTML inside the `data-content` / `data-title` attributes and same for JS init.

**Comment by mathieuleclaire** [comment]
What do you mean "encode" ? Provide an html string ?

**Comment by thednp** [comment]
Meaning 
`data-title="<div style='some stuff'>"`
becomes
`data-title="&lt;div style=&quot;some stuff&quot;&gt;"`

**Comment by mathieuleclaire** [comment]
I see. If I do so, here is what I get in html (which sounds good):
```html
data-content="&lt;div&gt;&lt;button class=&quot;btn btn-primary&quot;&gt;Popover on hover on left&lt;/button&gt;&lt;/div&gt;"
```
and in my browser:
![popover](https://user-images.githubusercontent.com/800035/36674691-08ed3406-1b07-11e8-98f7-1238fa7ad945.png)

**Comment by thednp** [comment]
You should play around and see what works for you.

**Comment by mathieuleclaire** [comment]
Now, it works for me. Thanks.

**Comment by mathieuleclaire** [comment]
It appears that events of element inserted in the content are not fired. Any idea why ?

**Comment by thednp** [comment]
Yeah, get yourself some JavaScript Documentation and read.

**Comment by thednp** [comment]
@mathieuleclaire it's very hard to guess what is your context all about and JavaScript events is a complex API, the best (from my experience) is to look for answers on closed issues here, or StackOverflow if your issue is different and involves extra/different functionality.

It's not that I won't help you, it's about time/focus.
