### ISSUE TITLE
Bootstrap V4 dropdown variants

### ISSUE THREAD

**Issue by AndreasHerss** [thednp/bootstrap.native#196]
Version: 2.0.21

It would be nice to see the bootstrap V4 dropdown variants supported.
[http://getbootstrap.com/docs/4.0/components/dropdowns/#dropright-variation](http://getbootstrap.com/docs/4.0/components/dropdowns/#dropright-variation)

**Comment by thednp** [comment]
Have you tried it on that markup and didn't work?

**Comment by AndreasHerss** [comment]
yes, i had a working dropright in bootstrap, then replaced bootstrap with bootstrap.native and it wasn't working, got it "working" by replacing the .dropright class with a .dropdown, only that now it drops down instead of right of course :(

**Comment by AndreasHerss** [comment]
as far as i can see, it has been added october 29. but yes, as far as i read the bootstrap.native code, i don't think it takes much, but not sure, i'm much more of a backender, which is also why i'm not into trying to do a pull-request, i'd rather just wait 😀
![image](https://user-images.githubusercontent.com/6894019/37875041-0382fe72-303a-11e8-9982-a895e06ee1bd.png)

**Comment by thednp** [comment]
@AndreasHerss we're not interested in the core implementation of the Dropdown for the multi-position menus, as it relies in Popper.js, something again we're not interested in. We are also not interested in expanding our component to match the original plugin.

The following markup copied from the original demo pages works for me, except it will need some CSS adjustments for you liking/specific-position.

```markup
<!-- Default dropup button -->
<div class="btn-group dropup">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropup
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
  </div>
</div>

<!-- Split dropup button -->
<div class="btn-group dropup">
  <button type="button" class="btn btn-secondary">
    Split dropup
  </button>
  <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
  </div>
</div>
```

It does toggle properly, without any code changes and I hope this is good enough for now.

**Comment by midzer** [comment]
For my projects I use bootstrap.native to keep additional JS code as small as possible.

Even with Bootstrap 4 now in the progress of dropping jQuery, I'm still going to stick to bootstrap.native because I don't need additional functionality with extra dependencies via Popper.js for example. I hope this project is being kept alive by the community :+1:

**Comment by thednp** [comment]
@AndreasHerss if you inspect the demos closer, you will find that you only need some additional CSS to do whatever kind of  position you want, what about that?

**Comment by robjbrain** [comment]
Came here trying to figure out how to get `dropdown-menu-right` on dropdowns.

Based on various replies to issues here it seems like it's not going to be implemented.

However I found changing the dropdown to `display:inline-block;` fixed the issue (although of course you have to remember it is now inline everywhere you may be using it.

Here is a jsFiddle for anyone else having this same problem: http://jsfiddle.net/pjvzt098/3/

**Comment by thednp** [comment]
@robjbrain [here](http://jsfiddle.net/8foyam7L/1/) is a better version, with the latest BSN and latest BS4. You just have to use the right markup with the right classes.

**Comment by thednp** [comment]
@AndreasHerss if you could please check the latest [V4 demo](http://thednp.github.io/bootstrap.native/v4.html), your answers have come from core developers, they finally made it to work with CSS, somehow inline with my initial reaction.
