### ISSUE TITLE
Touch support for carousel

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#197]
Bootstrap 4 is going to support touch gestures for it's carousel component via Hammer.js soon.

Without an additional dependency I think this feature would fit into bootstrap.native as well.

Here is a tiny lightbox with good touch implementation example https://github.com/rqrauhvmra/Tobi/blob/master/js/tobi.js
Surely there are other suitable native implementations around.

What do you think about this?

**Comment by thednp** [comment]
I have something working without Hammer.js or jQuery but I don't think we really need to keep the line with the original plugin imo.
________________________________

**Comment by thednp** [comment]
I will update this issue as to what I plan to do in the future. As I said, I have something working, not with our **Carousel** component here, but a very light and stable code to enable this functionality for it, something **I will include** in a future version probably for both V3/V4 version.
