### ISSUE TITLE
Use rollup as build system

### ISSUE THREAD

**Issue by stalniy** [thednp/bootstrap.native#198]
By using [rollup](https://rollupjs.org/guide/en) your build config will be much simpler. Also it will allow to shake out unused helper functions (e.g., if I need only modal, then I don't want to include functions like `styleTip`)

**Comment by thednp** [comment]
That's my original idea, a cool one, however the community came up with this solution.

**Comment by thednp** [comment]
Feel free to contribute to the project, I'm closing this for now.
