### ISSUE TITLE
Is it to programmatically display a modal? 

### ISSUE THREAD

**Issue by osdlge** [thednp/bootstrap.native#20]
I forgot to mention in my last ticket but this project is awesome 

I was wondering if it was possible to programmatically display a modal similar to how I can do $('#modalid).modal('show');

I use this to display nice looking messages if things like post events to insert data didn't work

I found one work around which is to have a hidden button that calls the modal and then call a click() event on the hidden button. I was wondering if there was a better way of handling this 

Thanks again for your hard work on this

**Comment by IngwiePhoenix** [comment]
Hey. Glad you like it!

Well the answer is kind of a yepnope. You can totally generate a Modal, but not the way you'd really expect it. I do it in my own project, but it is not as easy as ABC. I'll provide you a nudge in the right direction though.

What I did was use a templating engine (ejs) and generated a uuid as the id (i.e. `#m_0000-0000-0000-0000`). Then I created the containing modal div, and put everything else inside that, then created a new Modal instance.

- The template I use: https://github.com/DragonsInn/BIRD3/blob/master/web_modules/frameworks/Dialog/template.ejs
- The function to render this: https://github.com/DragonsInn/BIRD3/blob/master/web_modules/frameworks/dialog.oj#L6-L39

Maybe this will help!

Also, for EJS, I use `<?` and `?>` as delimiters, and `.oj` files are [JavaScript in Objective-C dialect](https://github.com/musictheory/oj) files.

**Comment by thednp** [comment]
You override how the script works by easily deleting the `data-toggle="modal"` attribute from your trigger then initialize as you wish.

```
var modal = document.getElementByID('myModal'), myModalOptions = {};
myModalOptions.keyboard = modal.getAttribute('data-keyboard');
myModalOptions.backdrop = modal.getAttribute('data-backdrop');
myModalOptions.duration = modal.getAttribute('data-duration');
var myModalObject = new Modal(modal,myModalOptions);
```

The I think you should be able to do such, not sure, haven't tested

```
myModalObject.close();
myModalObject.open();
```

And so on.

**Comment by IngwiePhoenix** [comment]
@thednp hah, beat you by 20sec! (:

**Comment by thednp** [comment]
Check my solution first :P

**Comment by osdlge** [comment]
@thednp's solution worked like a charm, thanks!

**Comment by neothemachine** [comment]
Modal.open() is not documented here. Would be good to add that since the original bootstrap also allows to open modals programmatically.

**Comment by thednp** [comment]
Thanks for the suggestion.
