### ISSUE TITLE
Problem with sliding carousel

### ISSUE THREAD

**Issue by mishelen** [thednp/bootstrap.native#202]
If you turn the carousel too fast, then at some point you get an error

```
TypeError: element is undefined
addClass http://localhost:3000/main.js:165:7
Carousel/this.slideTo http://localhost:3000/main.js:611:9
Carousel/this.cycle/timer< http://localhost:3000/main.js:576:47
```

In normal mode, autosliding, such an error also occurs. But not often

Carousel initialization: 
```js
document.addEventListener("DOMContentLoaded", () => {
    new Carousel(document.getElementById('gamesCarousel'));
});
```

------------

bootstrap.native: 2.0.22

**Comment by thednp** [comment]
Never heard of it. Are you on a MAC?

**Comment by mishelen** [comment]
ubuntu 16.04.04

**Comment by thednp** [comment]
I would assume Firefox was used.

**Comment by mishelen** [comment]
yes and chromium, vivaldi too. And on windows7 too

**Comment by thednp** [comment]
The master version has some changes to how `transitionend` is handled, would you care for a test and confirm the result?

**Comment by mishelen** [comment]
what I need to do? rollback to 2.0.21?

**Comment by mishelen** [comment]
sometimes the slider enters an incomprehensible mode. it can be seen that he is hungry to resources.

For example, sometimes the picture disappears altogether and it collapses. Or vice versa, two pictures are shown at once, one under one.

Yes, it's probably event management problem.

Twice:
![doubling](https://user-images.githubusercontent.com/5958104/38731535-5d3ccaa4-3f23-11e8-86e4-8cb00b77631d.png)

Collapse:
![collapsing](https://user-images.githubusercontent.com/5958104/38731540-64a88198-3f23-11e8-9e0d-204f27684381.png)

**Comment by jdsans** [comment]
Having the same problem. Did a bit of debugging and it seems like at some point the **active** class on the **carousel-items** seems to disappear thus collapsing the whole slider. I think the automatic state transitions seem to conflict with the manual transition.

**Comment by thednp** [comment]
Both of you didn't answer my question: does it happen with the latest MASTER version?

**Comment by mishelen** [comment]
@thednp  , thanks
ok, I will try. Before I dont properly understand you and suggest that last tag is equal your master.

**Comment by mishelen** [comment]
So... interaction with slider now is more smooth. Cases of collapse occur much less often

But I still got the same error, but with bit another stacktrace

```
TypeError: element is undefined
addClass http://localhost:3000/main.js:156:7 
Carousel/this.slideTo http://localhost:3000/main.js:450:9
controlsHandler http://localhost:3000/main.js:383:9
```

**Comment by thednp** [comment]
I forgot to merge the recent PR by someone fixing the `transitionend` handler, so can you please take a minute to test the latest master now?

**Comment by mishelen** [comment]
I tried. Any changes

**Comment by thednp** [comment]
I tested with latest Ubuntu 17.10 and Mozilla (probably the latest Linux version) and I tested the left-right arrows for a few minutes and had no issue at all, at this point I believe this is an user issue so I must close this for now.

**Comment by thednp** [comment]
@mishelen I fixed some issues with the code regarding the above, please make sure to give the latest master a try and report back any problem.

If the problem persist, it's somewhere in your code, try to eliminate them one by one.

Good luck.

**Comment by thednp** [comment]
@mishelen there have been some more commits to address some of the issues probably related to yours, please take a minute to test.
