### ISSUE TITLE
Performance for Tabs

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#203]
Hi all,
on mobile time for tab content to be visible after click is pretty bad for large amounts of data. Right now on an older Android 4 phone it doesn't show up at all. I'm pretty sure it worked several months ago.

Demo: https://feuerwehr-eisolzried.de/media/

I wonder whether there are possibilites to improve current implementation.

Cheers and have a nice weekend
midzer

**Comment by thednp** [comment]
There seems to be something in the way, I got an error on my first visit on the site.

**Comment by midzer** [comment]
Thanks for your hint. There were two different warning messages in Firefox ESR for me which i fixed just now. Stated issue is still there though.

I don't see an error. What browser are you using, @thednp ?
