### ISSUE TITLE
Modal window does not work correctly in version 4

### ISSUE THREAD

**Issue by filipe-torres** [thednp/bootstrap.native#204]
I try to use a modal window from **Bootstrap Native version 4**, but there is a bug when the modal window is closed clicking on "X" button (near title) or clicking outside the window (backdrop).

**Version:** 2.0.23
**Line number:** unknown - there is no error in the browser console
**Test sites: **
- Original with bug: 
[http://bootstrap.filipetorres.net/v4.html](http://bootstrap.filipetorres.net/v4.html)
- Modified version perfectly working (linked with the**bootstrap-native-v4.js** script from the official demo site):
[http://bootstrap.filipetorres.net/v4-alternative.html](http://bootstrap.filipetorres.net/v4-alternative.html)

**Browsers tests result:**
- Safari 5.1.7: OK
- Internet Explorer 11: OK
- Chrome 66.0.3359.117: Fail
- Firefox 59.0.2: Fail

**Steps to reproduce the bug:**
1. Download master.zip file from [Github](https://github.com/thednp/bootstrap.native/archive/master.zip);
2. Unzip files on a local or online server;
3. Access v4.html file (http://localhost/v4.html);
4. Roll down the page to Modal section and click on the button "Launch demo modal";
5. Close the modal window clicking on "X" button (near title) or on the outside the window (backdrop);
6. Click again on the button "Launch demo modal". Now the modal window open and close rapidly, and backdrop layer is displayed, preventing the user from clicking anywhere else on the page. The backdrop only hides if press ESC button on the keyboard.

The demo page doesn't have this bug, because the file [http://thednp.github.io/bootstrap.native/dist/bootstrap-native-v4.js](http://thednp.github.io/bootstrap.native/dist/bootstrap-native-v4.js) is very different from file distributed in the master.zip file from this repository. I compared these files using Winmerge and the differences start at line number 210.

**Comment by thednp** [comment]
Yes there have been some recent PR regarding a better method of handling the `transitionend`, that's what it's different, I forgot to test that and give it my polish, of course it must be bullet proof and cross browser.

Remember that the MASTER and the GH-PAGES are always a nightly build.

**Comment by thednp** [comment]
Please test the latest Master. Thanks

**Comment by thednp** [comment]
The issues should be fixed with https://github.com/thednp/bootstrap.native/commit/e4a73865740351b2255e7b89d5b6397d3fa7d11d

**Comment by thednp** [comment]
@filipe-torres are we ok now?

**Comment by filipe-torres** [comment]
Works like a charm!
Thank you.
