### ISSUE TITLE
2 small issues

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#207]
First of all, I'm very happy to use this library. I'm creating nice and lightweight websites with it!

- The first issue is a small issue again with the Carousel interval via **Javascript initialization**. Setting interval to `0` works like a charm but setting the interval to `false` does not work; It still slides after the default amount of seconds. See https://github.com/thednp/bootstrap.native/issues/192#issuecomment-377568414

- The second issue is a small typo in the docs.  Go to the [docs](http://thednp.github.io/bootstrap.native/) and go to "Carousel events". 1 event name is missing a "e"-character: `slid.bs.carousel` should be `slide.bs.carousel`. But then, the same event is listed twice, see https://preview.ibb.co/jyhwrx/docu.png

EDIT: I didn't know "slid" was a English word but apparently it is, so maybe the second issue is not a typo?

**Comment by thednp** [comment]
The `slide` event is before the animation and `slid` event is when the animation finished, we are inline with the original plugin. 

I will look into Carousel issue tomorrow, thanks for bringing it up.

**Comment by thednp** [comment]
Carousel issue fixed, closing this now.

**Comment by thednp** [comment]
Commit is now online, you can test the latest MASTER anytime you have the time.

**Comment by Vuurvlieg** [comment]
@thednp I tested it and it works like a charm, thank you very much!
