### ISSUE TITLE
Carousel example question

### ISSUE THREAD

**Issue by phil-w** [thednp/bootstrap.native#208]
Just playing with the example Carousel:
 http://thednp.github.io/bootstrap.native/

You probably know, but I thought it was broken until I realized that's probably BS3 markup, not BS4.

Otherwise, I was unsure if I needed popper or the BS js itself, but I think that the this works stand alone, except for the polyfills.

**Comment by midzer** [comment]
@phil-w you can switch between v3 and v4 in top navbar on document page.

Nope, you just need bootstrap native for your JS part and (if need be) the polyfill for IE served separately.

**Comment by phil-w** [comment]
Doh - thanks, I missed that.

And it's working really well. For some reason (which doesn't need figuring out) if I used it via NPM I had some weird polyfill error (on addClass, which my browser supports). I downloaded the source and installed it locally to debug that... but at that point the problem went away, so it's all good. Thanks.
