### ISSUE TITLE
Carousel: carousel-indicators only select 'li' elements?

### ISSUE THREAD

**Issue by dkbnguyen** [thednp/bootstrap.native#209]
The current v4 [`carousel-native.js`](https://github.com/thednp/bootstrap.native/blob/master/lib/V4/carousel-native.js#L44) only select `li` tag as children elements, perhaps we could use a universal way to find those elements? so that we can extend to some certain designs, such as using button group toggle as indicators for carousel slides.

Eg: https://codepen.io/anon/pen/NMbEqa
Current doesn't work with the beloved bootstrap.native but works with jquery bootstrap

**Comment by thednp** [comment]
I don't see the problem with that, as `li` supports everything CSS/CSS2/CSS3 so you can use whatever you want.

**Comment by dkbnguyen** [comment]
I agree `li` is one of best tags for navigation, so is `a` in [`<nav><a>...</a></nav>`](https://getbootstrap.com/docs/4.0/components/navs/#working-with-flex-utilities)
It's just an open suggestion (I never meant to open any issues or bugs with your code), between developers we both taken consideration to the complexity. Sorry if this has bothered you.
