### ISSUE TITLE
Unconsistent behavior with ScrollSpy

### ISSUE THREAD

**Issue by antoine1000** [thednp/bootstrap.native#210]
_I'm working with bootstrap.native v 2.0.22, on MacOS Sierra, and I don't have any errors in the console as it's just a weird behavior difference._

Hi,

I work on a project with bootstrap.native, and I use the ScrollSpy component for a sticky navbar. My problem is quite strange : **in local environment**, ScrollSpy add the `active` class to `<a>` elements, but on a **production server** the `active` class is added on `<li>` elements. The markup is exactly **the same** on both pages.

My HTML markup looks like this : 

```
<!-- Sticky Navbar -->
<nav id="sticky-navbar" class="...someclass">  <!-- this is our element's target -->
  <ul class="sticky-nav"> 
      <li>
        <a class="nav-link" href="#ref">My Section</a>
      </li>
     <! -- <li> are repeated for each section -->
  </ul>
</nav>
```

and my JS : 

```
const scrollspyContainer = document.querySelector('.scrollspy-container')

const scrollspyTarget = document.getElementById('sticky-navbar')

const myScrollSpyInit = new bsn.ScrollSpy(scrollspyContainer, {
      target: scrollspyTarget,
      offset: 32
    })
```

Do you have an idea why ScrollSpy behaves differently between two exact same pages, one based in local, the other online ?

Thank you !

**Comment by antoine1000** [comment]
Thanks for your anwser.

They both use V4 and they both **works**. They just works *differently* while it's the exact same markup & JS, that's what I can't understand.

The "fix" I found for now is to add a CSS class to target both the `li a.active` and the `li.active a` (so i'ts working on my local env and my prod env) but that is not very elegant and don't fix the issue...

**Comment by thednp** [comment]
There might be some changes to the original library in regards to this issue, I would assume this to be mostly some markup changes, I'll have a look into it asap.

**Comment by thednp** [comment]
If you look at the [official example](http://getbootstrap.com/docs/4.1/components/scrollspy/) which is equivalent with my example in terms of markup, you will notice both `<UL>-<LI>-<A>` and `<DIV>-<A>` for dropdown items.

Why it works on your local site but doesn't work on the other could come to incorrect markup or even invalid markup, something in the way for our script to locate items and work with them. A local environment is always different and less punishing for HTML compliance.

I've updated my demo to latest Bootstrap 4.1 CSS, and there's no change in regards to Scrollspy, in fact everything is working perfect as far as I'm concerned.
