### ISSUE TITLE
Dropdown issues

### ISSUE THREAD

**Issue by ERROPiX** [thednp/bootstrap.native#211]
Hi,

great idea, but it's having some issues on the dropdown component:

### It doesn't support `flip`:
When there is a lot of dropdown menu items, the jquery vrsion of bootstrap try to change the position of the menu so it can be visible within the viewport, but with this version, is just go beyond the visible viewport
> Allow Dropdown to flip in case of an overlapping on the reference element. For more information refer to Popper.js's flip docs.

### Doesn't support `reference`:
In bootstrap, the default reference position is set to the toggle, that mean, the dropdown will be positioned relative to the button that triggered it. not the buttons group!

I don't know about the other dropdown params:

- offset
- boundary
- display

Anyway, thank you

**Comment by thednp** [comment]
WE're not interested in expanding to include Popper.js or any of it's functionality.
