### ISSUE TITLE
Custom animations and container on tooltip don't work

### ISSUE THREAD

**Issue by C0deboy** [thednp/bootstrap.native#212]
Specifying data-animation causes that tooltips are not hidden after mouse out.

Specyfing data-contrainer to parent of a child with tooltip causes incorrect positioning of tooltip (like left postition still relative to body).

**Comment by thednp** [comment]
> Specifying data-animation causes that tooltips are not hidden after mouse out.

This is something I will look into it.

> Specyfing data-contrainer to parent of a child with tooltip causes incorrect positioning of tooltip (like left postition still relative to body).

This is something we may not be interested investing time in, as it's stated somewhere in the FAQs, we don't support nesting functionality for the components, and the **Tooltip**/**Popover** nesting in any way makes no sense.

**Comment by C0deboy** [comment]
> This is something we may not be interested investing time in, as it's stated somewhere in the FAQs, we don't support nesting functionality for the components, and the Tooltip/Popover nesting in any way makes no sense.

It does make sense sometimes. This is implemented in JQuery tooltips by defualt (tooltips goes to parent component). And this make sense in my case. Your implementetion doesn't work together with hover defined on a parent element. So if I have nice styling of elements inside on hover, the tooltip cannot be affected, because it is outside of this element.  Why the tooltips in your implementation doesn't go to parent element (like in JQuery) in the frist place?

If you still decide not to fix this, then atleast fix providing custom animation so I can define same behavior (as on hover) in animation.

Thanks for your response.

**Comment by thednp** [comment]
I may not fully understand what you want/need but using the right mark-up would eliminate your "issue", which as far as I can see it's an user issue.

**Comment by thednp** [comment]
You can use the `data-toggle="tooltip"` on that `LI` element and problem solved.

**Comment by thednp** [comment]
I've closed this out, but will look into the custom animation issue.

**Comment by thednp** [comment]
I tested the following:

```markup
<style>
  .custom-anim {transform: rotate(15deg); opacity: 0; transition: all 0.5s ease 0s}
  .custom-anim.in {transform: rotate(0deg); opacity: 1}
</style>
<a href="#" data-toggle="tooltip" data-animation="custom-anim" class="navbar-brand" title="Demo text">BSN</a>
```

Everything working as expected, the second issue is also invalid.

**Comment by C0deboy** [comment]
Oh I didn't know that .in class is required. Where this is documented?

Anyway thanks for your time.

**Comment by thednp** [comment]
This isn't documented, you should know how to use it, I gave you a working example that I tested.
