### ISSUE TITLE
problem with focus on dropdowns and probably other components.

### ISSUE THREAD

**Issue by raddko15** [thednp/bootstrap.native#218]
It takes two clicks instead of one to unfocus from a dropdown or a button which is problematic.

Is there any chance, you guys will fix it ?

**Comment by midzer** [comment]
I can reproduce the issue and it is not very nice, but only a minor issue.
Regular Bootstrap JS is affacted, too.

**Comment by thednp** [comment]
This is actually an accessibility feature, go ahead and play with your keyboard.

**Comment by raddko15** [comment]
It can make your life unpleasant, especially when you want to add some styles on the dropdown which is focused, you end up with extra styled button for one click and you need to go for workarounds. Anyways thank for the library.

**Comment by thednp** [comment]
This was a requested feature, to make it work like the original plugin, at that time.
