### ISSUE TITLE
Close the menu in mobile

### ISSUE THREAD

**Issue by hansnolte** [thednp/bootstrap.native#219]
Looking for a solution to close the menu in mobile view when clicking outside of the menu.
http://www.experimente.bplaced.net/native/

I hope someone has a tip or a small (vanilla) script.

Many thanks in advance
Hans

**Comment by thednp** [comment]
Looks like a stakoverflow question to me.

**Comment by hansnolte** [comment]
Hi thednp ,

many thanks for your answer.

Is my question so unusual?
I already found some solution approach, but unfortunately they all need jQuery.
And since I use your native script, I had hoped to find a solution here.

Many greetings
Hans

**Comment by thednp** [comment]
You can do something like this:

```js
document.addEventListener('click', function(e){
  if (myMenuIsOpen && isNotMenuChild(e.target) ) { 
     myMenuInit.hide() } // where myMenuInit is your collapse element initialization
  }
},false);
```

**Comment by hansnolte** [comment]
Hi thednp ,
thank you very much for your tip.
Unfortunately I am a JavaScript beginner.
Let's see if I can do this somehow.

Thank you
Hans
