### ISSUE TITLE
Making the options parameter optional 

### ISSUE THREAD

**Issue by HelloGravity** [thednp/bootstrap.native#22]
When creating an instance of a widget (for example a Modal), why isn't the options parameter optional?

This is my use case:
```js
var modalElement = document.getElementById("myModal");

// this works:
new Modal(modalElement, {}).open();

// this won't work:
new Modal(modalElement).open();
```
 (jsfiddle: http://jsfiddle.net/0w8s27a5/)

my suggestion is to have something like this in each of the constructor functions:
```js
options = options || {};
```

**Comment by thednp** [comment]
Thanks for the input. I don't know if that's gonna affect the current DATA API or not, but you can try, test and submit a PR, I will have a look at it as soon as I can.

I also intend to fix some issues with IE8 very soon, so stay close.

**Comment by thednp** [comment]
Thanks for the PR. Now gonna go ahead and run local tests and improvements.
