### ISSUE TITLE
No way to set tooltip delay to zero

### ISSUE THREAD

**Issue by Muchiachio** [thednp/bootstrap.native#222]
Because when it [gets parsed](https://github.com/thednp/bootstrap.native/blob/2.0.23/lib/V4/tooltip-native.js#L42) javascript interprets it as false, I'm using 1 as a workaround.

Maybe this should be fixed by changing default delay to zero? Because original bootstrap defaults to zero.

**Comment by thednp** [comment]
Because the nature of JavaScript and more particularly the inconsistency of `setTimeout` we don't/can't do ZERO, some things have to be executed in a particular order and ZERO sometimes isn't actually ZERO.

Hope this makes sense and btw you found the right solution.
