### ISSUE TITLE
Attributes not changed

### ISSUE THREAD

**Issue by SFlame** [thednp/bootstrap.native#225]
Hi,

First - Great work! It's much more fast than the jQuery version :)

Now, for the issue (Bootstrap v.4):

Bootstrap component like "Collapse" may have multiple triggers (buttons, links, etc.)
But the current version only update the attributes of the clicked trigger (and not all of the triggers).
In this case, I might have 2 buttons for the same collapse but only one of them will be updated with aria-expanded="true".

* The native bootstrap library updates all relevant triggers across the document.

Another recommendation (I don't know if currently supported): the native bootstrap library won't let you access the clicked trigger - so, it might be a great improvement if we could (via the show/hide event).

I would like to help out and fix it by myself, but I'm afraid I might not understand the internal functions of the library.

**Comment by thednp** [comment]
This development isn't very important/interesting for me, but rather more like a specific user niche case. 

If I were you, I would make use of the built in events to trigger/handle whatever you need.
Check the docs.
