### ISSUE TITLE
Carousel docs typo

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#226]
According to the [docs](https://thednp.github.io/bootstrap.native/index.html#componentCarousel) you have to add a `item` class. This is wrong, that class should be `carousel-item`.

**Good:**

>  `<div class="carousel-item"></div>`

**Wrong:**

>  `<div class="item"></div>`

**Comment by thednp** [comment]
V3 or V4?

**Comment by Vuurvlieg** [comment]
Sorry, my bad, the docs are correct. For V3 its indeed `item` and for V4 its 'carousel-item'.
