### ISSUE TITLE
Carousel - Running SlideTo on active item results in hiding data

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#227]
Hi, its me again.

This issue is similiar like the Tabs in https://github.com/thednp/bootstrap.native/issues/187, but this time its affecting the Carousel component. When sliding to a already active item, the active item becomes hidden, which is wrong.

To reproduce:
1. Create a HTML Carousel markup <b>without</b> data attributes
2. Use JavaScript to initialize a Carousel instance. Disable automatically sliding using `interval: false`
3. Use the build-in function <b>`slideTo`</b> and gives its current active item index.
4. The result is that the currently active item will be hidden, which shouldn't

Check this [example](https://codepen.io/anon/pen/jpOpdL). Click the button to open the modal and then click the `reset button`. The result is that the active carousel item will be hidden.

At least this is for V4 (not tested for V3).

**Comment by thednp** [comment]
I don't think I understand the issue.

**Comment by Vuurvlieg** [comment]
The issue is that the active carousel disappears, just like the mentioned tab issue..
When sliding to a already active caoursel item, this item should not be hidden.

In my codepen example, the default carousel item index is `0`. When you click the reset button, the carousel item with index 0 should stay visible instead of hidden.

**Comment by thednp** [comment]
OK I begin to understand. If you go next slide it always goes nicely but if you do `slideTo(0)` when you're already at the slide 0 it will hide. TRUE. It's broken and will not be able to handle.

However, this is a case where other carousel scripts try and duplicate slides for various reasons like swipe or simply making it able to work with anything you throw at it.

We won't do that. We understand the context and manage these cases in most efficient manner to avoid breaking the basic functionality. For instance in this particular case here's what to do: we need to filter that specific case like so:

```javascript
function resetSlides() {
   if ( myCarouselInit.getActiveIndex() !==0 ) { // this is now required
     myCarouselInit.slideTo(0);
   }
}
```

So like many others, this is a case of user related issue, nothing to do with our script, so I'm going to close this, hoping the above will help you understand how to manage these cases.

**Comment by thednp** [comment]
Perfectly acceptable solution. That's the spirit!

Thanks

**Comment by Vuurvlieg** [comment]
Thanks, but are you going to include this fix into the library, would be awesome!?

**Comment by thednp** [comment]
Yes @Vuurvlieg

**Comment by Vuurvlieg** [comment]
Awesome, thank you so much!

**Comment by thednp** [comment]
@Vuurvlieg please check latest master and the [changes](https://github.com/thednp/bootstrap.native/commit/f587bb7fe5567297951eb952d00c3b58a4e25575)

**Comment by Vuurvlieg** [comment]
@thednp I've tested the latest master and everything works fine, thank you so much!
