### ISSUE TITLE
Tooltip/Popover does not work on SPA (Single Page App)

### ISSUE THREAD

**Issue by Refdroid** [thednp/bootstrap.native#229]
Steps to reproduce
1. Load your entire single page app. Load bootstrap.native
2. Call fetch or other xhr and load more html (this is after DOM is already initially loaded.)
```
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="left" data-title="Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas.">Left</button>
```
Call the JavaScript function
```
// find all elements with title attribute
var elementsTooltip = document.querySelectorAll('[data-title]');
// attach a tooltip for each
for (var i = 0; i < elementsTooltip.length; i++){
  new Tooltip(elementsTooltip[i], {
    placement: 'top', //string
    animation: 'slideNfade', // CSS class
    delay: 150, // integer
  })
}
```

Tooltip does not show. 

Do the same thing for Popover. Popover shows, but does not HIDE. dismissible: false, does not hide. dismissible: true, shows X button, but X button does not close popover.

**Comment by thednp** [comment]
Give me some demo page with the issue.

**Comment by thednp** [comment]
I think you need to check this [piece of wiki](https://github.com/thednp/bootstrap.native/wiki/Acknowledgements#some-features-are-even-better).
