### ISSUE TITLE
Latest version on npm is only v2.0.23

### ISSUE THREAD

**Issue by shaal** [thednp/bootstrap.native#230]
The latest version on npm is v2.0.23
https://www.npmjs.com/package/bootstrap.native

bootstrap.navtive v2.0.24 - includes bug fixes that I need for my project.

Is it possible to submit the latest version (*v2.0.24*) to npm?

**Comment by Ostap34JS** [comment]
https://github.com/thednp/bootstrap.native/issues/193#issuecomment-368131664

**Comment by thednp** [comment]
https://github.com/thednp/bootstrap.native/releases/tag/2.0.24
