### ISSUE TITLE
Use MutationObserver to avoid needing to use page load events

### ISSUE THREAD

**Issue by simmerz** [thednp/bootstrap.native#232]
It would be great to load in bootstrap.native and let it get on with itself without having to instantiate it on new html coming in to the page either via turbolinks, xhr or templating tools.

Using MutationObserver removes the need to add any event listeners at all. There are polyfills for older browsers available too. It's the same way that stimulus.js (https://github.com/stimulusjs/stimulus) does things.

**Comment by thednp** [comment]
As [discussed before](https://github.com/thednp/bootstrap.native/issues/102) we came to the conclusion that this kind of functionality is for each user to decide on how to implement.
