### ISSUE TITLE
Popover breaks when multiline template literal is used.

### ISSUE THREAD

**Issue by fleck** [thednp/bootstrap.native#233]
When I initialize a popover with a multiline string:

```javascript
      const template = `
        <div class="popover" role="tooltip">
          <div class="arrow"></div>
          <h3 class="popover-title"></h3>
          <div class="popover-content"></div>
        </div>` ;

      this.popover = new Popover(ribbonElement, {template, placement: 'left'});
```

I get the error 'Cannot read property 'offsetWidth' of null' from this line of code:
`arrowWidth = arrow[offsetWidth]; arrowHeight = arrow[offsetHeight];`

**Comment by thednp** [comment]
Perhaps you didn't NAME the option?

```js
this.popover = new Popover(ribbonElement, {template: template, placement: 'left'});
```

**Comment by fleck** [comment]
This is in the chrome console which supports property shorthand. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Property_definitions So our 2 examples are functionally the same.

**Comment by fleck** [comment]
Upon further inspection, must have something to do with how we're transpiling our code. As this jsfiddle example works. https://jsfiddle.net/jonfleck/obskwpta/13/

**Comment by fleck** [comment]
here's a fiddle reproducing the bug https://jsfiddle.net/jonfleck/obskwpta/14/

**Comment by thednp** [comment]
I will have a look at this asap. Thanks for reporting.

**Comment by thednp** [comment]
OK so I've done some changed to your fiddle example, it's set (and I think it was) to pure JS, and it's [working as expected](https://jsfiddle.net/obskwpta/19/):

* I replaced `&#768;` (accent grave) with `'` (single quotation)
* I properly wrapped each row in `'` (single quotation)
* I added a title and desc to the template
* all new lines are concatenated properly into the template string via `+`

All looks good to me now. The previous notation wasn't proper JavaScript, the `&#768;` (accent grave) is meant for something else and not contain strings. So we're now closing this.

**Comment by fleck** [comment]
The backtick is valid syntax. It was introduced to JavaScript to make templating easier. From the docs: “The default function just concatenates the parts into a single string.” https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by thednp** [comment]
If that's the case, you're free to do any contribution you consider fit to solve that particular issue.

**Comment by FelschR** [comment]
This issue comes up for me when the string stars with a linebreak.
So OP's issue could be fixed by using the following template literal instead:
```js
const template = `<div class="popover" role="tooltip">
    <div class="arrow"></div>
    <h3 class="popover-title"></h3>
    <div class="popover-content"></div>
  </div>` ;
```
Alternatively using `.trim()` on the string would fix the issue as well.

**Comment by thednp** [comment]
@FelschR @fleck please test latest master and confirm issue is fixed. Need your input before pushing to npm. 

Thanks

**Comment by jcorporation** [comment]
```contentString = contentString.trim();``` breaks, if the content option is not set. I use only the template option.

**Comment by thednp** [comment]
@jcorporation what do you suggest?

**Comment by jcorporation** [comment]
trim only, if contentString != null

**Comment by jcorporation** [comment]
@thednp: works for me, thanks
