### ISSUE TITLE
Replace scrollBar adjustments

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#237]
Hi all,

in a future time we might consider replacing JS hacks for modal to adjust scrollBar behaviour by native CSS https://wicg.github.io/overscroll-behavior/

This is just for the records now, as support isn't widely supported (yet).

more info: https://developers.google.com/web/updates/2017/11/overscroll-behavior

Cheers
midzer

**Comment by thednp** [comment]
If that's the solution to be adopted by the original library developers, we will implement it too, we don't want to be left outside and frankly it sounds like lesser code for our modal component.

**Comment by midzer** [comment]
Yeah, true.

Actually, I forgot this property has to be set in CSS in the first place. Nevermind :)
