### ISSUE TITLE
How to only include individual scripts like Collapse?

### ISSUE THREAD

**Issue by awgul** [thednp/bootstrap.native#239]
How to do it?
It doesn't work like:

import '....../V4/collapse-native.js'

**Comment by midzer** [comment]
@awgul this cannot work right now, more info https://github.com/thednp/bootstrap.native/issues/180

**Comment by thednp** [comment]
Also check the wiki on [how to create custom builds](https://github.com/thednp/bootstrap.native/wiki/How-to-use#custom-builds).
