### ISSUE TITLE
dist/ is not up to date.

### ISSUE THREAD

**Issue by HelloGravity** [thednp/bootstrap.native#24]
When building the library with gulp, I noticed there is a difference between the code in lib/ and in dist/ in the repository, and it is in the behavior of collapse: 
in lib/ - https://github.com/thednp/bootstrap.native/blob/ddd5d7b/lib/collapse-native.js#L120-L124 
in dist/ -https://github.com/thednp/bootstrap.native/blob/ddd5d7b/dist/bootstrap-native.js#L783-L785

**Comment by thednp** [comment]
Thanks, will check that too.

**Comment by thednp** [comment]
This change is due to the plans to remove `resize` handlers for IE8. I will update that ASAP.

**Comment by thednp** [comment]
I'm now gonna check this too, and closing this down.

**Comment by thednp** [comment]
Please tell me, is this the only difference you found?

**Comment by HelloGravity** [comment]
Yes, this was the only code difference. There were also differences in comments.
But now it will also differ because of #23
