### ISSUE TITLE
Accordion Bootstrap not working

### ISSUE THREAD

**Issue by mzubairharoon** [thednp/bootstrap.native#246]
I am using Bootstrap native accordion, I've copied the HTML of it from its page, but it is generating some error with this code.

[https://thednp.github.io/bootstrap.native/v4.html](BS Native v4)

`var bsn = require('bootstrap.native/dist/bootstrap-native-v4');
let collapse    = new bsn.Collapse(document.getElementById('accordion'));`

http://i.imgur.com/IoiViZZ.png

Is there a reported issue on it? or it is my mistake.

Thank you

**Comment by thednp** [comment]
You need to make a test somehow I cannot replicate what you have there.
