### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by szepeviktor** [thednp/bootstrap.native#248]
Hello!

Do you plan to add SASS support?
Professional sitebuilders may need that.

**Comment by midzer** [comment]
Hi @szepeviktor 
this library is an alternative JS installment for regular Bootstrap (which has SCSS support already). You find more details about this project in `README.md` or its wiki.

**Comment by szepeviktor** [comment]
Thank you.
We will learn to read!

https://github.com/thednp/bootstrap.native/blob/master/README.md
