### ISSUE TITLE
Demo site to gh-pages

### ISSUE THREAD

**Issue by szepeviktor** [thednp/bootstrap.native#249]
@thednp Could you move CSS, HTML etc to gh-pages branch to separate lib from other mixed stuff?

**Comment by thednp** [comment]
It's there already, but I want the trunk to have everything I need to do the edits and testing. 

Why is it important to move them?

**Comment by szepeviktor** [comment]
I know it seems to be easier to maintain a mixed repo (I have huge mixed ones) but a clean repo contains only **1** thing.

A library user may not be interested in HTML etc.

A clean repo looks professional.

**Comment by szepeviktor** [comment]
> to have everything I need to do the edits and testing

Try automate these processes!!
