### ISSUE TITLE
Carousel - Error while sliding when there is only 1 item present

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#250]
Hi, its me again. There is a little problem with the v4 Carousel. It may happen that there is only 1 item in the Carousel present. If this is the case and you click the "next" button or the interval is not zero, the Carousel throws an error and the Carousel will be messed up.

The solution is simple, just move the order of the following code into this order:

      // find the right next index 
      if ( next < 0 ) { next = total - 1; } 
      else if ( next >= total ){ next = 0; }

      // first return if we're on the same item #227
      if ( activeItem === next ) {
        return;
      // or determine slideDirection
      } else if  ( (activeItem < next ) || (activeItem === 0 && next === total -1 ) ) {
        slideDirection = self[direction] = left; // next
      } else if  ( (activeItem > next) || (activeItem === total - 1 && next === 0 ) ) {
        slideDirection = self[direction] = right; // prev
      }

Please check [this example](https://codepen.io/anon/pen/YJgOVm) and click the next button and see what will happen. Please let me know if its not clear.

**Comment by midzer** [comment]
I can reproduce the bug in your demo, @Vuurvlieg (missing slide) 
There is no error thrown for me in console though

**Comment by Vuurvlieg** [comment]
@midzer  Thanks for taking a look. When you enter a random value for the interval, like 5000, then open the dev. console an wait a few seconds. You will see an error "Uncaught TypeError: Cannot read property 'classList' of undefined".

**Comment by thednp** [comment]
Why didn't this come like 3 days ago before we launched 2.0.24?

**Comment by Vuurvlieg** [comment]
I just saw yesterday that a new version was available so I downloaded this new version and tested my website. Then I ran into this issue.

**Comment by Vuurvlieg** [comment]
Awesome, thanks for fixing and releasing a new version!
Btw, would be better to hide the arrow indicators `.carousel-control-prev` & `.carousel-control-next` when there is only 1 slide?

**Comment by thednp** [comment]
@Vuurvlieg I think that is something for you to handle via PHP or whatever environment you're in.
