### ISSUE TITLE
Issue with dropdown?

### ISSUE THREAD

**Issue by devpaps** [thednp/bootstrap.native#252]
If i go to this page, https://scania.github.io/corporate-ui-docs/ i got an error on line 965. 
`Cannot read property 'length' of undefined`.

I'm using Chrome v.71, and they are using v2.0.21 of Bootstrap Native.

```js
      menuItems = (function(){
        var set = menu[children], newSet = [];
        for ( var i=0; i<set[length]; i++ ){
          set[i][children][length] && (set[i][children][0].tagName === 'A' && newSet[push](set[i]));          
        }
        return newSet;
      })(),
``` 

**I'm no expert but shouldn't it be like this?**

```js
      menuItems = (function(){
        var set = menu[children], newSet = [];
        for ( var i=0; i<set.length; i++ ){
          set[i][children].length && (set[i][children][0].tagName === 'A' && newSet[push](set[i]));          
        }
        return newSet;
      })(),
```

**Comment by thednp** [comment]
If there is an error, it's not a syntax issue for sure, please make sure you update to [latest version](https://github.com/thednp/bootstrap.native/releases/tag/2.0.24) and let me know how it goes.

**Comment by devpaps** [comment]
I'll update to the latest version. Maybe it 's something with my version of Chrome. Because when i use Firefox the error dosen't show up. I'll look into it.

**Comment by thednp** [comment]
Cool website ;)

**Comment by thednp** [comment]
I believe this has something to do with incompatible/invalid markup, perhaps you might wanna go ahead and check that, I will close this meanwhile.
