### ISSUE TITLE
Carousel does not work

### ISSUE THREAD

**Issue by nettdotkomm** [thednp/bootstrap.native#255]
Carousel does not work in Firefox since version 63.0.1

**Comment by nettdotkomm** [comment]
No, I use Windows 7

**Comment by nettdotkomm** [comment]
The problem first occurred with the Firefox Developer Edition,
as there are always updates for this earlier

**Comment by midzer** [comment]
On mobile Firefox 63.0.2 Carousel v4 is working for me smoothly

**Comment by nettdotkomm** [comment]
I have done some tests on other devices an it works.
So I searched for the difference.
And the difference is: on my notebook i use firefox in the 64Bit version.
Possibly, this could be the problem??

**Comment by midzer** [comment]
@nettdotkomm I highly doubt 64bit browser version is making a difference here. But you never know...
Do you have you all browser extensions disabled and surfing in private mode just for testing/reference purposes?

**Comment by thednp** [comment]
@nettdotkomm for best test purposes I know: can you please check your browser console and confirm it's clear when the issues pops up? Because if the issue is in another script that's ABOVE our script, that's your problem right there.

**Comment by nettdotkomm** [comment]
> Do you have you all browser extensions disabled and surfing in private mode just for testing/reference purposes?

Yes ... same Problem



>  can you please check your browser console and confirm it's clear when the issues pops up?

its clear ... no errors are displayed

**Comment by nettdotkomm** [comment]
test it on Firefox Portable 32Bit
same issues
So firefox 64bit is probably not the problem
