### ISSUE TITLE
Closing modal with escape key prevents it from showing again

### ISSUE THREAD

**Issue by Gazler** [thednp/bootstrap.native#256]
It appears that there is an issue with closing the modal using the escape key on version 4. I know there are a few issues related to modal display issues, so perhaps it is a regression of some sort?

To trigger the issue, open a modal, press escape, then try opening the modal again. The modal should display, then immediately disappear.

For convenience, here is a script to replicate it on the demo application:

http://thednp.github.io/bootstrap.native/

```javascript
var el = document.querySelector('button[data-target="#myModal"]'); 
el.click(); 
setTimeout(() => {
  var e = new Event("keydown"); 
  e.keyCode = 27; 
 document.dispatchEvent(e)
}, 300); 
setTimeout(() => {el.click()}, 1000)
```

We have also observed this behaviour with clicking on the backdrop to dismiss, and via a `data-dismiss` attribute.

**Comment by thednp** [comment]
I cannot duplicate the issue, works for me on EDGE, Opera, Chrome and Firefox.

**Comment by Gazler** [comment]
I'm on Linux (Ubuntu), a colleague also on Linux (Arch Linux) was able to replicate. Will try a different OS to see if I can replicate.

**Comment by midzer** [comment]
Can't duplicate, too. I close via ESC key and can open modal again.

(using debian testing, latest chromium)

**Comment by ktec** [comment]
Able to replicate the behaviour on a Mac using Chrome by the following:

1. Visit http://thednp.github.io/bootstrap.native/
2. Click the modal button, it works as expected.
3. Open dev tools. Run the script:
```
var el = document.querySelector('button[data-target="#myModal"]'); el.click(); setTimeout(() => {var e = new Event("keydown"); e.keyCode = 27; document.dispatchEvent(e)}, 300);
```
4. Now when you click the Modal button it consistently shows then disappears.

HTH

**Comment by ktec** [comment]
Able to replicate on Arch / Chrome too.

**Comment by thednp** [comment]
Do you guys have a console error?

**Comment by Gazler** [comment]
Here's a recording of it triggering including the console (using the code snippet from the original issue.)

![bootstrap](https://user-images.githubusercontent.com/477511/48728687-90185f80-ec2d-11e8-8df9-511dd4e88ddd.gif)

**Comment by Gazler** [comment]
I was also able to replicate on EDGE, chrome and Firefox on Windows 10 with the script above.

![bootstrap-native](https://user-images.githubusercontent.com/477511/48729366-57798580-ec2f-11e8-83ae-708dbe7b6f56.png)

**Comment by thednp** [comment]
@Gazler please test the latest master, demo page also updated.
