### ISSUE TITLE
Build V4 fails when --minify

### ISSUE THREAD

**Issue by skunkbad** [thednp/bootstrap.native#258]
I successfully build a file when I do not use --minify:

```
node build-v4.js --only modal collapse > /path/to/my/js/bs.native.js
```

But when I --minify

```
node build-v4.js --minify --only modal collapse > /path/to/my/js/bs.native.min.js
```

The only thing in the file is this:

```
// Native Javascript for Bootstrap 4 v2.0.24 | © dnp_theme | MIT-License
undefined

```

This is on Ubuntu 16.04. I actually was just trying to upgrade from an older version, so building worked in the past.

--UPDATE:

Turns out that fromString is not an option for uglify-js. Maybe it was in the past? So, in build-module-v4, if you simply do this --minify works again:

```
bundle = uglify.minify(bundle).code;
```

Now if I can just figure out why IoS iPad Chrome chokes on my modals, Id be golden :)

**Comment by skunkbad** [comment]
With my modification the build for v4 does work on Linux.

**Comment by thednp** [comment]
OK, will that work on other OS, say MAC or WIN?

**Comment by thednp** [comment]
@skunkbad please advise how should we change the build scripts to fix the issue on Linux. 

Thank you

**Comment by RyanZim** [comment]
It depends whether you're using uglifyjs v2 or v3. v2 requires `fromString`, v3 doesn't need it.

**Comment by thednp** [comment]
@RyanZim I've updated my local environment and still getting the issue. I don't know what and/or why.

**Comment by ryanrain** [comment]
i'm seeing this on debian 10 with uglify-js 3.4.10.
