### ISSUE TITLE
Tabs Disabled

### ISSUE THREAD

**Issue by Fh-abeyer** [thednp/bootstrap.native#259]
If you are using bootstrap 4 and have disabled tabs the native js allows the user to click the tabs and it opens the pane still. Is there something special you have to do with this to get the disabled to work with this plugin? If I do not use the plugin it works perfectly fine.

**Comment by thednp** [comment]
Currently our script doesn't check if the tab is disabled. You can of course work around this issue by not using the `data-toggle="tab"` for those that are designated to be `disabled`.
