### ISSUE TITLE
small fix for nav collapse height 

### ISSUE THREAD

**Issue by ChisholmKyle** [thednp/bootstrap.native#26]
The `getMaxHeight`Collapse method on line 810 of the source javascript only finds the height of the first child element of collapsible nav container with class `navbar-collapse`. However, there may be more than one child, especially for right-aligned navigation items (The [bootstrap example](http://getbootstrap.com/components/#navbar-default) default navbar has 3 children). This breaks functionality where it's expected to have a fully-expanded menu on the hamburger button click. 

I made a simple fix with replaces lines 810-812:

    this.getMaxHeight = function(l) { // get collapse trueHeight and border
        return getOuterHeight(l.children[0]);
    },

with this:

    this.getMaxHeight = function(l) { // get collapse trueHeight and border
        var h = 0;
        for (var k = 0; k < l.children.length; k++) {
            h += getOuterHeight(l.children[k]);
        }
        return h;
    },

Can you make the fix?

**Comment by thednp** [comment]
Can you show me a demo with and without the fix please? I would gladly apply the fix in no time :)

**Comment by ChisholmKyle** [comment]
I just uploaded two examples - one broken and one fixed:
[Broken CDN version](http://kylechisholm.ca/dev/bsnativeissue/nav-broken.html)
[Fixed latest downloaded version](http://kylechisholm.ca/dev/bsnativeissue/nav-fixed.html)

**Comment by thednp** [comment]
Thanks so much. I'll have a look at this asap. 
Meanwhile, you can do a PR if you like.

**Comment by thednp** [comment]
I changed how collapse works, it should work better for navbar as well. Please test and let me know.

Cheers.
