### ISSUE TITLE
Undefined TypeError with tabs

### ISSUE THREAD

**Issue by NightYoshi370** [thednp/bootstrap.native#262]
So I'm trying to transition from the normal bootstrap 4 to bootstrap.native-v4 and I have run into a problem with tabs. My code is as follows:

```		<div class="nav nav-tabs nav-tabs-wrapper"><ul id="profile-nav" class="nav nav-tabs dragscroll horizontal" role="tablist">
			{foreach $pages as $pageid=>$pname}
				<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#{$pageid}">{$pname}</a></li>
			{/foreach}
		</ul></div>
```
(the $pname, $pageid and foreach thingy are due to smarty. If you want to see a browser render of the code:

```<div class="nav-tabs-wrapper"><ul id="profile-nav" class="nav nav-tabs dragscroll horizontal" role="tablist">
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#general">General</a></li>
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#profiles">Profiles</a></li>
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#personal">Personal</a></li>
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#account">Account settings</a></li>
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#postlayout">Post layout</a></li>
							<li class="nav-item"><a data-toggle="tab" class="nav-link" href="#theme">Theme</a></li>
					</ul></div>
```

However, when attempting, there is an error listed in the javascript console: `TypeError: x(...) is undefined[Learn More] bootstrap-native-v4.min.js:formatted:959`

The line in question reads as follows:
```
      C = function () {
        return dn(x() [Ct]('href'))
      },
```
There is no site which you can verify this as of right now, because I have not yet uploaded the latest version of the website. I'd like to try and get this fixed before I upload this to the website, persay.

Thank you, and if you need me any further, please reply to this issue and I will get back to you as soon as I can
~NightYoshi370

**Comment by thednp** [comment]
We don't actually afford the time to do this test, I think you have to check the final HTML markup before you try and do the dynamic JS, make sure it's valid and in compliance with our component.

**Comment by NightYoshi370** [comment]
It's not dynamic JS. It's smarty HTML. And besides, it doesn't even matter, as what matters is the output (shown above).

**Comment by NightYoshi370** [comment]
(The output shown above is in compliance with your component)

**Comment by thednp** [comment]
@NightYoshi370 make sure your code executes BEFORE our component init, or better, make sure the library is the last library queued to be loaded.

**Comment by thednp** [comment]
@NightYoshi370 

Here is what your markup should look like:

https://jsfiddle.net/fd3nsra2/
