### ISSUE TITLE
Carousel auto-slide transition breaks

### ISSUE THREAD

**Issue by sergeymorkovkin** [thednp/bootstrap.native#263]
If carousel container (or it's parent container) is hidden in the middle of slide transition, the "transitionend" event doesn't fire and slide cycling stucks. Classical use-case is when carousel is placed inside a modal dialog.

**Comment by thednp** [comment]
The component will check if the target carousel element is in viewport first before deciding to slide to the next content slide.

**Comment by sergeymorkovkin** [comment]
You're talking about another case, while I'm concerned about the situation when transition is **already in progress** and we're closing dialog before it's complete. In Bootstrap it seems to work with no issues: https://bootsnipp.com/snippets/featured/carousel-inside-modal

**Comment by thednp** [comment]
Understanding what this library is all about is key to using it in the future. The fact that modal implies to a certain degree that the user interacts to view more content, the carousel inside doesn't need to be automatic, so for simplicity reasons the best thing you can do is to set `interval=0` for this specific case.

One of the reasons for this that we will **not** implement a jQuery like feature `isHidden`, the above explains exactly why. The more simple and further away from traditional jQuery, the better.

**Comment by sergeymorkovkin** [comment]
Ok, will try to monkey-patch then.

**Comment by sergeymorkovkin** [comment]
> the carousel inside doesn't need to be automatic

What about the case when user slides and then hits escape right away? That would still result in this error. I know it's a rare case, but it's still possible.

What do you think about using emulateTransitionEnd() from utils instead of one() for handling transitionend? That would solve this issue completely.

**Comment by sergeymorkovkin** [comment]
This worked, but required to patch original file:

`
        // one(slides[next], transitionEndEvent, function(e) {
        emulateTransitionEnd(slides[next], function(e) {
          var timeout = e && e[target] !== slides[next] ? e.elapsedTime*1000+100 : 20;
`

This way, carousel doesn't get stuck in permanent isSliding state.

**Comment by thednp** [comment]
Thanks for the input, will have a look at it.

**Comment by sergeymorkovkin** [comment]
Thanks! I'm now patching built file, but would highly appreciate if you culd include it into the library.

**Comment by sergeymorkovkin** [comment]
Looking at your commits, it seems that you're missing the "e" check. The thing is emulateTransitionEnd won't provide "e" and code will throw an error. Kindly check the last line of my code.
