### ISSUE TITLE
Carousel cannot slide back

### ISSUE THREAD

**Issue by sergeymorkovkin** [thednp/bootstrap.native#264]
Create a carousel with only 2 slides and set LAST SLIDE as active. Open page and try sliding back to previous first slide.

**Comment by thednp** [comment]
You really love the library don't you. You really wanna get all possible quirks fixed ei?

**Comment by thednp** [comment]
OK I replicated your test setup and confirm the issue, our component wasn't developed to handle this exact case, however I don't see the purpose of having last active item and only 2 slides, it makes no sense with content consumption in general.

I'm closing this down as not important/critical.

**Comment by sergeymorkovkin** [comment]
> You really love the library don't you. You really wanna get all possible quirks fixed ei?

The library is great. And I mistakenly though you want that too. So, just tried to be helpful.

**Comment by thednp** [comment]
Never stop trying! We will not ignore any suggestions that make sense for the community.
