### ISSUE TITLE
Modal auto-hide breaks

### ISSUE THREAD

**Issue by sergeymorkovkin** [thednp/bootstrap.native#265]
Create two modals, do NOT use data API, call show() on the first modal, the call show() on the second. The script will break.

**Comment by thednp** [comment]
You mean call both at the same time?

**Comment by sergeymorkovkin** [comment]
No, I mean consequently, not both at a time.

**Comment by thednp** [comment]
The [first example](http://thednp.github.io/bootstrap.native/#modalExamples) showcases the use of consequently opening modals, no issues there. You mean you call the second modal via JS `myModal.show()`?

**Comment by sergeymorkovkin** [comment]
Exactly. Same example, with pure JS and no Data API, as I mentioned.

**Comment by sergeymorkovkin** [comment]
Not yet, sorry.

**Comment by thednp** [comment]
@sergeymorkovkin please download latest master and give it a spin. Thanks for reporting and have fun.

**Comment by sergeymorkovkin** [comment]
Confirm. Worked perfectly!
