### ISSUE TITLE
Redundant variables (coding style)

### ISSUE THREAD

**Issue by mustafa0x** [thednp/bootstrap.native#269]
I've noticed a lot of cases of `x = 'x'` in the code (e.g. `backdrop = 'backdrop'`), and couldn't figure out what the use of such a coding style is. I also found that it made the code harder to understand and debug, but could be a matter of taste.

Thanks.

**Comment by thednp** [comment]
That's a better way to compress strings.

**Comment by mustafa0x** [comment]
Ah interesting. Does it have an impact when gzipping?

**Comment by thednp** [comment]
If your file is properly built it should be ok.

**Comment by mustafa0x** [comment]
Sorry, I meant does it still affect file size when gzipping?

**Comment by mustafa0x** [comment]
Sorry, I was curious whether the compression improvement you mentioned also applies if the file is gzipped.

I'm actually curious in any case in which such a style improves string compression. Especially as I've been trying to reproduce the improvement but couldn't.

**Comment by thednp** [comment]
You can do this test yourself I don't have the time to do this. From 70Kb unminified to 7.65Kb minified and gzipped, I think that's a huge deal, right?

**Comment by mustafa0x** [comment]
I no longer use BSN in my projects, but came across something relevant to this discussion, and thought I'd share in case it's found beneficial:

https://github.com/mishoo/UglifyJS2/issues/185#issuecomment-16974360

> For now, it seems that improvements are unlikely due to gzip's more efficient string tokenization (gzip's pointers are smaller byte-wise that we could write in javascript), and any improvement would be marginal.

**Comment by thednp** [comment]
I don't understand what would be the reason. but thanks for bringing that up. Again the main idea is to have something we have control over before gzip or other scripts do their stuff.

**Comment by mustafa0x** [comment]
AFAIK it's because gzip (i.e. deflate) compresses recurring strings very efficiently, so it's pretty difficult to do a better job than it.

**Comment by thednp** [comment]
So did you test yourself?

**Comment by mustafa0x** [comment]
Here's a small sample:

Minified with tokenizing:
```js
(function(){var n=document,e=n.documentElement,i="style",t="toLowerCase",o="Transition",a="Duration",d="Webkit",r=d+o in e[i]||o[t]()in e[i],u=d+o in e[i]?d[t]()+o+"End":o[t]()+"end",c=d+a in e[i]?d[t]()+o+a:o[t]()+a})();
```
- 221 bytes, 175 bytes gzipped.

Minified without tokenizing:
```js
(function(){var n=document,t=n.documentElement,i="WebkitTransition"in t.style||"Transition".toLowerCase()in t.style,e="WebkitTransition"in t.style?"Webkit".toLowerCase()+"TransitionEnd":"Transition".toLowerCase()+"end",o="WebkitDuration"in t.style?"Webkit".toLowerCase()+"TransitionDuration":"Transition".toLowerCase()+"Duration"})();
```
- 334 bytes, *163 bytes* gzipped.

So yes, this very basic sample supports that even though the latter has more characters, it ends up being smaller gzipped. Thus, manual tokenizing isn't worth it — the compressor does a better job than us puny humans. =]

**Comment by thednp** [comment]
That is interesting and strong argument indeed and I thank you for your time. 

Around 7% deficit on manual tokens vs gzip, my library minified is very small compared to original plugins and jQuery all together. It's hard to want to use something similar with larger size.

**Comment by thednp** [comment]
@mustafa0x I've been thinking about this lately, here is my thinking. I won't have a problem reverting to the previous coding style, especially because I seriously consider rewriting the code in ES6 format and this manual tokenization is making it all likely more tedious.

Somehow I still wish 7zip/Gzip devs would take into account existing code tokenization before doing it's own. This would serve greatly to those massive chunks of folks who would like to have their script delivered in super minimized size but would rather not bother with server/cms/other settings to enable and configure compression.

**Comment by mustafa0x** [comment]
gzip is supported everywhere and is almost always on by default, so I don't think optimizing for a non-gzip environment is that productive.
