### ISSUE TITLE
Modal dialog closes when select some text and releasing mouse button on the backdrop dialog

### ISSUE THREAD

**Issue by WillianSMOliveira** [thednp/bootstrap.native#272]
Based on the issue https://github.com/twbs/bootstrap/issues/13816, the behavior of Modal close might be the same of the bootstrap.js.

If I select some text on the modal dialog and release the mouse button outside of que the dialog (on the backdrop) the modal is closed.
I think the solution is to create a new event, like "mousedownEvent = 'mousedown'" in the "// event names" sessions and replace the "clickEvent" variable on the dismissHandlerToggle method for the new one.

**Comment by thednp** [comment]
This is an interesting find, and I have the same concern as @mdo but I don't think this is really an issue, it's more like a quirks we might ignore.

**Comment by WillianSMOliveira** [comment]
@thednp can i send a pull request? This might be an good implementation for the this use in my company without any customization in our project.

**Comment by thednp** [comment]
I don't see a wide use for the community. I also don't consider this quirks to be any critical.

**Comment by Vuurvlieg** [comment]
I think a PR for this wouldn't be a problem right?

**Comment by thednp** [comment]
I have other priorities right now, I think we can leave this for later.
