### ISSUE TITLE
Carousel is incompatible with BS 4.2+

### ISSUE THREAD

**Issue by sergeymorkovkin** [thednp/bootstrap.native#273]
This commit breaks compatibility of the simple slide carousel: [5aed968](https://github.com/twbs/bootstrap/commit/5aed968750177ec35f99dc03e71eec3632beb844#diff-61a2c7d627355b98263c81ad79ae98f5)

Using BSN with 4.1.3 is okay, though.

**Comment by thednp** [comment]
Please test with the latest master.

**Comment by sergeymorkovkin** [comment]
Tested. Their SCSS needs patching in order to work.

`.carousel-fade {
.carousel-item {
transition: opacity .6s, transform .6s !important; // Do not forget !important
float: none;
}
}`
