### ISSUE TITLE
Carousel - function getActiveIndex() does not exists when there is only 1 slide present

### ISSUE THREAD

**Issue by Vuurvlieg** [thednp/bootstrap.native#274]
Hi there, I just discovered a bug with the `Carousel` component of the latest version 2.0.25, at least in v4.

When the Carousel has just **1 item**, I get the error "function 'getActiveIndex()' does not exists".
When I add 1 or more slides, the functions does exists again somehow.

Open the modal and click the button "Get active slide index" in the following example to see the error. https://codepen.io/anon/pen/jJMBQr

**Comment by thednp** [comment]
For a single slide-item I won't need the Carousel component at all.

**Comment by Vuurvlieg** [comment]
There is a reason why I use the Carousel for single items. Besides that, this is an issue that should be fixed no matter how many items I need in the Carousel.

**Comment by thednp** [comment]
I disagree. The **Carousel** component is meant to be used with interactive content where you have 3 or more slides.

I think for this quirks alone, you should do a fork.
