### ISSUE TITLE
Error thrown in Dropdown dismissHandler

### ISSUE THREAD

**Issue by jhunschejones** [thednp/bootstrap.native#278]
When the Dropdown dismissHandler is called it is possible for `eventTarget[parentNode]` to evaluate to null, causing the following error when using v2.0.26 of the library on safari and chrome (desktop and mobile):

Chrome 73.0.3683.103:
```
Uncaught TypeError: Cannot use 'in' operator to search for 'Dropdown' in null
    at HTMLDocument.dismissHandler (bootstrap-native.2.0.26.js:914)
```

Safari 12.1:
```
TypeError: null is not an Object. (evaluating 'stringDropdown in eventTarget[parentNode]')
```

Interestingly, the issue does not occur in v2.0.19 or 2.0.20 of the library but starts occurring after that point. I was able to resolve the issue in my site by replacing this code that starts at `dropdown-native.js` line 46:

```
hasData = eventTarget && (stringDropdown in eventTarget || stringDropdown in eventTarget[parentNode]);
```

With this code, lifted from v2.0.19 of the library: 
```
hasData = eventTarget && (eventTarget[getAttribute](dataToggle) 
                   || eventTarget[parentNode] && getAttribute in eventTarget[parentNode] 
                   && eventTarget[parentNode][getAttribute](dataToggle));
```

**Comment by thednp** [comment]
Thanks for the contribution, can you please make a test setup/guide on how to replicate, and also confirm the issue apply to V3 as well?

Thanks so much.

**Comment by jhunschejones** [comment]
Here is a test app with repro steps for v4. I can't replicate for v3, but I do not have much experience with Bootstrap 3 and there may be a different way Dropdowns are handled/toggled.

[v4_test.html.zip](https://github.com/thednp/bootstrap.native/files/3095304/v4_test.html.zip)

**Comment by thednp** [comment]
@jhunschejones that isn't a proper Bootstrap Dropdown markup. If you would work with the default dropdown markup there shouldn't be any issue.

**Comment by jhunschejones** [comment]
Interesting. What about it is standing out as non-standard? This example app works with no errors when using Bootstrap's normal library/plugins.

**Comment by thednp** [comment]
That's because jQuery pollyfills the heck out of that code to make it work with anything you throw at it. At the cost of performance, space and long term maintenance time. So we try to do things different.

But I have an idea to make some test these days, we might roll back to the previous working revision.

**Comment by jhunschejones** [comment]
Thanks for taking the time to explain all this, I really appreciate it. v2.0.26 fixed some modal behavior issues I was having, so I was happy to make the upgrade *(after working through this dropdown blocker.)* Let me know if there is anything else I can do to help!
