### ISSUE TITLE
Hiding in Modal-events breaks Modal

### ISSUE THREAD

**Issue by kolbma** [thednp/bootstrap.native#281]
There is some problem when calling `Modal.hide()` in the event-listener at least for `shown.bs.modal` and the Modal is already hidden.

```JavaScript
var overwritten = {};
function showModal(modal, notimer) {
    overwritten[modal] = notimer || false;
    if (!modal.Modal) {
        new Modal(modal);
        modal.addEventListener('hide.bs.modal', function (evt) {
            overwritten[modal] = true;
        });
        modal.addEventListener('shown.bs.modal', function (evt) {
            setTimeout(function () {
                if (!overwritten[modal]) {
                    modal.Modal.hide();
                }
            }, 1500);
        });
    }
    modal.Modal.show();
}
```

**Without** the workaround with `overwritten` and the **additional** event listener for `hide.bs.modal`, at the next `Modal.show()`, the dialog shows up very short and will disappear immediately and the body-class stays set. So the UI is broken, because half of the Modal is left and you can not close the Modal anymore.
This happens when the `Modal` got hidden by some other call (e.g. escape key) before and the timeout-function is running and calling `Modal.hide()` afterwards.
There are no JS errors in console.
I've no tested if the problem is with hiding a hidden Modal or with the timeout-event or both in combination.

**Comment by thednp** [comment]
Give me a pen or fiddle so I can understand what you mean ;)

**Comment by Vuurvlieg** [comment]
I have the same problem; When trying to hide a openend modal, the backdrop is still active while the modal is not.

**Comment by jhunschejones** [comment]
@kolbma and @Vuurvlieg, what version of the library are you using? I had what I believe is the same problem on v2.0.19 but upgrading to v2.0.26 resolved the issue.

**Comment by kolbma** [comment]
I'm at v2.0.26

**Comment by Vuurvlieg** [comment]
@thednp  @jhunschejones I am using the latest release, which is version 2.0.26. 
I created a [example](https://codepen.io/anon/pen/PgdLJz) and also video recorded. It is important to note that closing the modal often works perfectly, but in like 30% of the times the Modal bug appears.

![bug](https://user-images.githubusercontent.com/24532416/56602673-4e397e00-65fe-11e9-8b04-b6e82c2c7f6c.gif)

**Comment by kolbma** [comment]
With this modified pen https://codepen.io/anon/pen/QPVPZo I've it always on the 2nd button click.

**Comment by thednp** [comment]
This seems to be the perfect test case to make it bulletproof. I will have a look at it asap.

**Comment by thednp** [comment]
@Vuurvlieg @kolbma your examples are very very hard to make it work. It almost feels like an unfair challenge when in my mind this component was meant to be a good alternative to the original jQuery plugin with light and fast code execution.

In the long run this would eventually get fixed as I know something like a `setImediate` or `setTimeout` alternative will come forward to come in handy solving this. Right now, a "gated" setup on each step of the execution could probably solve the issue, but I'm also open to any solution you might come with.

**Comment by Vuurvlieg** [comment]
@thednp 

Some previous versions ago this bug did not occur. I think this bug was introduced in 
https://github.com/thednp/bootstrap.native/issues/266.  I believe before this we were using `SetTimeout` which was working fine for me.

> but I will need your help in testing and validating the proposed code changed to come.

No problem. Just let me know when you are ready and I will test as much as needed.

**Comment by thednp** [comment]
Currently working on something that seems to make sense.

**Comment by thednp** [comment]
@Vuurvlieg @kolbma and anyone else, please test the latest master with your hardest test and let me know how it goes asap.

Keep in mind:
* wait for animations to complete
* or force actions while animation is running
* want to know any suggestion on how to improve the code and the best on how to manage this case you've showcased above

**Comment by Vuurvlieg** [comment]
@thednp  Please dont close this issue as its not fixed yet.

I'd love to test your solution but unfortunately I ran into a new issue, which is a HTML form can not be submitted inside a Modal. Before `may 28` did this work perfectly.
See https://codepen.io/anon/pen/qGvWGY: open the modal and try to submit the form. Nothing happend.

**Comment by thednp** [comment]
It was closed automatically as referenced in my commit.

**Comment by thednp** [comment]
Let's take this step by step. First I need to know if our original issue is fixed. Then we can handle the new one ok?

**Comment by thednp** [comment]
@Vuurvlieg solved, check master code.

**Comment by Vuurvlieg** [comment]
@thednp  Thanks, submitting the form does work again!

So I've tested your solution from https://github.com/thednp/bootstrap.native/issues/281#issuecomment-497927542 and it seems to work for the example given by @kolbma. However, it does not work for the codepen example given by me [earlier](https://github.com/thednp/bootstrap.native/issues/281#issuecomment-485900709). Once I open a second model when the first modal is still openend, the backdrop is being removed completely.



Im not sure but my suggestion is to get rid of all SetTimeOut events and implement the [transitionend_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event) functions. So I mean, when the Modal uses (fade) animation, the bootstrap events `shown.bs.modal` & `hide.bs.modal` should  be fired, only if the `transitionend_event` does occur.

Let me clarify this by some code. (Again I'm not sure if this ever would work but it might be a solution to put inside the core of the Bootstrap native Modal component with some tweaking)

```
const el = document.querySelector('.modal.fade');

el.addEventListener('transitionstart', function() {
  // fire the "show.bs.modal" event
});`

el.addEventListener('transitioncancel', function() {
  // fire the "hide.bs.modal" event
});

el.addEventListener('transitionend', function() {
  // fire the "shown.bs.modal" or "hidden.bs.modal" event, depending on modal state
});
```

**Comment by thednp** [comment]
@Vuurvlieg why use a native script as it was jQuery? Why initialize modal inside the handler of another button click event? You are creating more and more memory addresses, meaning you use more memory, you mess up the private constants and variables, it's inconsistent, it's not good development practice. 

Why not initialize modal, attach events, whatever, all before adding the click handler to only do the `show()` method?

Try and brake this [re-written example](https://codepen.io/thednp/pen/arxOYp) in less than 100 times.

**Comment by Vuurvlieg** [comment]
@thednp 

> Why add even more event handlers on every click? You are creating more and more memory addresses, meaning you use more memory, you mess up the component private constants and variables, you are constantly bloating the DOM with new handlers (yes you set to once: true, but GC happens when it happens), 

I'm sorry but I do not agree with this. Indeed I do use `once: true`, and if Bootstrap Native does work correctly and follow the correct standards, every handler should be removed (from DOM) when closing the Modal. I have tested this in my website and indeed every handler is removed when the Modal is closed. It does not have any performance issues doing it this way. Everything runs very smooth and fast as long the handlers are being removed from DOM when needed.

Anyway, the only problem I have right now with the latest master is that the `backdrop` is removed when I open the `second` modal while the first modal is still being open. Check this [example](https://codepen.io/anon/pen/RmOJwV).

I think once this backdrop issue is fixed, the modal is working as it should.

**Comment by thednp** [comment]
I put a lot of effort in solving this, tried everything I know, even if it doesn't affect me or a larger portion of the community, I was expecting you would confirm.

As I said, this library doesn't do jQuery, it doesn't replace original library functionality word for word, if you want to use it, you use it the way I show you working on my modified version of your example because unfortunately I don't have anything else to help you.

Meanwhile I'm going to close this until we have a solution or at least someone else struggling with the same situation.

**Comment by Vuurvlieg** [comment]
For the missing backdrop there is a very easy fix.

Inside the `this.show = function() {}` of the Modal component
```
if (document.querySelector('.modal-backdrop')) {
   removeOverlay();
}
```
Working [example](https://codepen.io/anon/pen/VONOXz), adjustment is done in JS at line #1244

**Comment by thednp** [comment]
Will check that asap.

**Comment by thednp** [comment]
That's not a good resolution for some reasons:
* we already have `removeOverlay()` queued for the above part closing currently open modal;
* the demo already showcases opening a modal from another modal on V3 and main site, working perfect, and I tested it successfully with and without the `fade` class.

I suggest you fork the project and use your "fix".

**Comment by Vuurvlieg** [comment]
> the demo already showcases opening a modal from another modal on V3 and main site, working perfect, and I tested it successfully with and without the fade class.

Well, then you should test it again carefully because the showcase doesn't work either. Same problem at other level.

I digged into the core code and its very logical that the backdrop is not shown. Its all about the timeouts with its intervals: When a second modal is being opened while the first one is already open, the current code executes the `this.show()` function first, then the `this.hide()` function, which hides the first model AND sets too late `modalOverlay` to zero, which results in the backdrop of the second modal is never created.

Simply adding a `setInterval` in the `this.show()` function of the Modal component solves this problem. For anybody with the same problem, take a look at this quick crafted working [example](https://codepen.io/anon/pen/gJJNbK), at JS line #1245.

**Comment by thednp** [comment]
@kolbma is your original issue solved in the master please?

**Comment by thednp** [comment]
@kolbma and @Vuurvlieg I've updated the wiki in regards to this issue.

https://github.com/thednp/bootstrap.native/wiki/FAQs#does-it-support-jquery-style-instance-hooks

**Comment by tamb** [comment]
I'm getting this issue too.

**Comment by thednp** [comment]
@tamb what is your use case?
