### ISSUE TITLE
Dropdown issues with SVG icon

### ISSUE THREAD

**Issue by rfbortolini** [thednp/bootstrap.native#282]
The following code throws an exception using  v2.0.26:

![image](https://user-images.githubusercontent.com/2019992/56608080-5b477480-65e0-11e9-830f-d43752d351d5.png)

On line 899 the following code mistakes the anchor href attribute with the svg/use href attribute.

`      preventEmptyAnchor = function(anchor){
        (anchor.href && anchor.href.slice(-1) === '#' || anchor[parentNode] && anchor[parentNode].href 
          && anchor[parentNode].href.slice(-1) === '#') && this[preventDefault]();    
      }
`
It would be necessary to test with anchor.href.slice exists (also anchor[parentNode].href.slice)

![image](https://user-images.githubusercontent.com/2019992/56607982-2affd600-65e0-11e9-977c-4a18b66711db.png)

**Comment by thednp** [comment]
Please give the 2.0.19 version a try and let me know, another user reported something similar with Dropdown.

**Comment by rfbortolini** [comment]
Yes, working fine in 2.0.19! Should I use it?

**Comment by thednp** [comment]
If nothing else bothers you yea, but I suggest you give it a few days, we gonna revert that change into npm, hopefully with some more fixes.

**Comment by thednp** [comment]
Please check the latest master. Sorry for the delay.

Thanks

**Comment by thednp** [comment]
Tested with latest master, works for me, closing.
