### ISSUE TITLE
Issues with IE 9/10/11

### ISSUE THREAD

**Issue by mattmillen888** [thednp/bootstrap.native#285]
For some reason JS is just not working correctly in IE browsers. I can select say a radio or drop down but then cant deselect https://tekky.partners/native-bs/example_webpack_result8888888992.html

**Comment by thednp** [comment]
[Polyfill](https://github.com/thednp/bootstrap.native/blob/master/dist/polyfill.js) loaded?

**Comment by thednp** [comment]
My demo works flawless BSN V3 on IE8+ and BSN V4 on IE10+. I think you have a problem markup validity or structure. At the first sight, I noticed your inputs have no `name` attribute, required to have valid HTML, something we always need to have it all working properly.
