### ISSUE TITLE
can swiper integrate or carousel multiple items 

### ISSUE THREAD

**Issue by kucukhost** [thednp/bootstrap.native#286]
carousel multiple items responsive

**Comment by thednp** [comment]
What do you mean?

**Comment by kucukhost** [comment]
used in large sites. ecommerce sites (ebay, amazon, express.google.com vs) use multi item carausel. google speed problem two js (https://idangero.us/swiper/) . bootstrap does not bring the solution.

**Comment by thednp** [comment]
You mean nesting carousel? Implement swiper? I don't know what you're talking about.

**Comment by kucukhost** [comment]
http://prntscr.com/nrd8vf

sample application
https://idangero.us/swiper/demos/380-responsive-breakpoints.html

We want responsive carausel multi items.
var swiper = new Swiper('.swiper-container', {
      slidesPerView: 5,
      spaceBetween: 50,
      // init: false,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      breakpoints: {
        1024: {
          slidesPerView: 4,
          spaceBetween: 40,
        },
        768: {
          slidesPerView: 3,
          spaceBetween: 30,
        },
        640: {
          slidesPerView: 2,
          spaceBetween: 20,
        },
        320: {
          slidesPerView: 1,
          spaceBetween: 10,
        }
      }
    });

**Comment by thednp** [comment]
So you want that functionality into our Carousel component?

**Comment by kucukhost** [comment]
yes. swipper will not need.

**Comment by thednp** [comment]
You can make a custom BSN build to exclude Carousel component and use swiper or anything else instead.
