### ISSUE TITLE
Touch bug in Chrome/Firefox

### ISSUE THREAD

**Issue by sergeymorkovkin** [thednp/bootstrap.native#288]
Here's how to reproduce:

1. Open Chrome / Firefox, navigate to page with BSN carousel
2. Open dev tools and enter mobile view
3. Click carousel active slide

You'll receive following error in console:

In FireFox:

```
 TypeError: e.touches[0] is undefined[Подробнее] index.js:2722:7
    touchEndHandler http://localhost:8080/index.js:2722
    sendTouchEvent resource://devtools/server/actors/emulation/touch-simulator.js:274
    handleEvent resource://devtools/server/actors/emulation/touch-simulator.js:211
```

In Chrome:
```

index.js:2722 Uncaught TypeError: Cannot read property 'pageX' of undefined
    at HTMLDivElement.touchEndHandler (index.js:2722)
touchEndHandler @ index.js:2722
```

Well, it's only an emulation of the real touch devices and I haven't tested it on iPad/iPhone yet. However, Chrome and Firefox bug is consistent, which indicates possible problems on real touch devices.

**Comment by thednp** [comment]
The Bootstrap devs don't look/answer for emulation bugs, you want us to fix those bugs ourselves?

**Comment by sergeymorkovkin** [comment]
This is not 100% sure only an emulation bug and it should be checked. I was able to reproduce same error in IE10 couple of hours ago.

**Comment by thednp** [comment]
No it shouldn't be checked. I also don't see the connection between testing apple devices and IE emulation, but to put it super clear: testing on mobile should be like this:

* make a `<div id="test-div">` in your document
* make a function to execute around a certain variable and throw the error into that div (smth like try catch)
* see if the value is correct/undefined/NaN on the device 

We don't care about in-browser device emulation for several reasons:
* the emulation is MOSTLY to check if the layouts are consistent, with responsive design in mind
* the JavaScript/HTML5 API is implemented into the OS+browser is a different matter for mobile devices, most of them lack support for many features for "performance" reasons
* the emulation in any browser (I don't care which one) has no real idea what iPhone/iPad XYZ implements for JavaScript/HTML API

So if you wanna report a mobile device issue, you have an idea on how to do it.
