### ISSUE TITLE
Dropdown focus management leads to inadvertent Tab-trap

### ISSUE THREAD

**Issue by emilbjorklund** [thednp/bootstrap.native#289]
Using version 2.0.26. As far as I can tell, this affects both v4 and v3 flavors.

Reproducing:
1. Go to the [demo page](https://thednp.github.io/bootstrap.native/v4.html)
2. Open one of the Dropdown components using the keyboard
3. Hit shift + Tab to (try to) back up to the trigger button. Focus immediately shifts back to first menu item.

After some light digging in the source, I *think* this is what's going on: When trying to back out of the menu by tabbing backwards (shift-tab) and focusing the trigger element again, the `keyHandler` kicks in, `isSameElement` evaluates to `true`, throwing focus back to the first item, trapping the user in a focus loop where they are unable to move backwards (unless they close the Dropdown using other means). As far as I can tell, this is reproducible across browsers.

Suggested fix is, for me personally, that the automatic focusing of items is ditched altogether  (apart from when using arrow navigation once inside the menu) – I understand the rationale and trying to help the user, but I just think it's just a tad _too_ helpful.

My hunch is that it's not something I think users are expecting, and it's not something I feel I've come across in other dropdown components, including the [version from official Bootstrap](https://getbootstrap.com/docs/4.0/components/dropdowns/).

**Comment by thednp** [comment]
I don't see that as an issue, I coded that on purpose, if you wanna get back to parent dropdown, you just hit Esc.

**Comment by emilbjorklund** [comment]
Kudos for reconsidering this.

This issue is currently blocking a release for a client project of ours, as it's considered a violation of keyboard accessibility (WCAG2.1, 2.1.2, [No keyboard trap](https://www.w3.org/TR/WCAG21/#no-keyboard-trap)), so I've [forked it for now and implemented a couple of fixes](https://github.com/emilbjorklund/bootstrap.native/commits/master) that I needed to see: 

1. **No automatic focusing of menu items** on open (or shift-tabbing backwards to the trigger) - matches original Bootstrap functionality and follows keyboard accessibility conventions for dropdowns.
2. **Uses event delegation of `focus` event to dismiss the dropdown** if focus moves outside of menu - matches original Bootstrap functionality, required minor change to how `on()` and `off()` works (allowing the use of an `options` argument, as delegating `focus` requires the `useCapture` flag, pretty much. (This change to event delegation can likely be ditched if we would switch to the `focusin` event, which does bubble, but it's not supported in Firefox < 55.)
3. And, finally, **fixes another issue where dismissing the dropdown always focuses the trigger element**, which clashes with being able to focus other items on the page. As an example, try opening a dropdown on the [v4 demo page](http://thednp.github.io/bootstrap.native/v4.html) (using either keyboard or mouse), and then click one of the collapsible sections for example. Focus is stolen back to the dropdown trigger as it closes. I've changed the `hide()` method to check for `document.activeElement` inside the menu, and only focus the trigger if that is true. This one should probably be opened as an issue of its own, if one doesn't already exist.

I'd be happy to open a PR for this (as soon as I get this project out the door) if you feel these are fixes that you'd be OK with.

**Comment by thednp** [comment]
I've checked your changes and seems to be OK at the first sight, for me personally I really want to keep the ability to navigate nested dropdown menus.

**Comment by thednp** [comment]
@emilbjorklund I've added this into the master, soon to add the modal intentional trap as well, please keep an eye on the master repository. 

Thanks

**Comment by emilbjorklund** [comment]
LGTM. Cheers! 👍

**Comment by emilbjorklund** [comment]
Re: modal trap - have found some issues with the current approach in Safari, will try to investigate, but might be worth to hold off on that for now.
