### ISSUE TITLE
[BUG] issues and improvements for modal

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#29]
Issues:
* need to implement a better addClass / removeClass, as currently we are adding 10+ `open-modal` classes to the body
* the body need a padding right/left when `modal-open`, just like the new version of the original plugin
* also modal seems to have an overflow issue, we might need to rework the HTML structure
* I'll try to rework this one https://github.com/thednp/bootstrap.native/issues/30

**Comment by osdlge** [comment]
would you also be able to add similar support to bootstraps data-keyboard and data-backdrop http://getbootstrap.com/javascript/#modals-options ? Currently you can keep the modal visible if the user clicks outside of it but the backdrop disappears. Also it'd be nice to prevent the escape key from closing the modal but only for specific dialogs

**Comment by thednp** [comment]
We already support [those options](https://github.com/thednp/bootstrap.native/blob/master/lib/modal-native.js#L182-L183). I mean I don't understand perfect what you mean.. are you using multiple opened modals at the same time?

**Comment by osdlge** [comment]
They don't really work, or I am doing something wrong. Here is a super simple testcase
Edit line 228 on the provided index.html file
https://github.com/thednp/bootstrap.native/blob/master/index.html#L228
Change it to be
<div id="myModal" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

Click the "Launch Simple Modal" button and then click escape. The modal stays but the backdrop disappears. I can reproduce this in both Chrome 46 and FireFox 38. 

You can also mouse click outside of the modal and it will disappear

**Comment by osdlge** [comment]
Sorry HTML got stripped out
div id="myModal" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"

is what you change it to

**Comment by thednp** [comment]
If you change the `data-backdrop` or `data-keyboard` after Modal was initialized would produce no effect. I should have shown a demo where they showcase these options I guess.

**Comment by osdlge** [comment]
Not sure I follow, I'm not changing the values after initializing, I'm just adding them to the example modal on the demo page. The keyboard one is partially taking effect because the modal stays but the backdrop disappears when pressing escape

**Comment by thednp** [comment]
So you downloaded the demo, edited the `index.html` file with these options on the modal example and you spotted the issue? Please, what is your OS and browser?

**Comment by osdlge** [comment]
Correct I downloaded a zip from github, extracted the files to a new directory, made the one change to index.html on line 228 to add data-backdrop="static" and data-keyboard="false", saved, then opened index.html and clicked on launch simple modal. When I click outside of the modal it disappears which is not what data-backdrop="static" does for bootstrap. When I click escape on my keyboard the modal background disappears but the modal is left in place

I'm on windows 7 and can reproduce in Chrome 46 and FireFox 38

Are you not able to reproduce this problem?

**Comment by thednp** [comment]
I don't have much time to test (I know if I start testing I usually start working on it and thus takes even more time), so I noted here a little to do for the next release. I also noted your report, so thank you, I will solve the issue asap.

**Comment by thednp** [comment]
@osdlge I think your issue is a content related issue, I cannot reproduce the issue at all.

**Comment by osdlge** [comment]
So when you enable data-backdrop="static" and press the esc key on the modal the backdrop and modal stay in place? The only change I made was to the provided sample and adding data-backdrop="static" data-keyboard="false" tabindex="-1"

**Comment by thednp** [comment]
Modal currently doesn't know what `data-backdrop="static"` is. Only the options and their values that you see in the demo.

**Comment by thednp** [comment]
Done the rework https://github.com/thednp/bootstrap.native/commit/7985fae26d9eb692ce38aff4ab416bdfddbc51aa
