### ISSUE TITLE
Collapse show/hide

### ISSUE THREAD

**Issue by evandiamond** [thednp/bootstrap.native#291]
Hi there, I can't seem to get this working. I know the functionality is supposed to be similar to how Bootstrap works, but maybe I am missing something...

```
document.getElementById("customPanel").collapse('show');
document.getElementById("customPanel").collapse('hide');
```
Shouldn't something like this work? what am I missing?

**Comment by thednp** [comment]
Yea, the documentation on the demo.

**Comment by evandiamond** [comment]
Ah, there it is. Not sure how I missed that section :) Thanks!

**Comment by thednp** [comment]
Have fun ;)

**Comment by evandiamond** [comment]
Actually running into another problem.

```
Uncaught TypeError: Cannot set property 'isAnimating' of null
```

```
var optionsStyle = document.getElementById('optionsStyle');
document.getElementById("test").addEventListener("click",function () {
    var myCollapseInit = new Collapse(optionsStyle);
    myCollapseInit.show();
});
```

What am I missing here?

**Comment by evandiamond** [comment]
Nevermind, I figured it out. I need to take a nap, long night. Thanks for pushing me in the right direction. :)
