### ISSUE TITLE
use with vuejs 2?

### ISSUE THREAD

**Issue by m16u31D** [thednp/bootstrap.native#292]
Hi guys how can i use this library with vuejs 2?

**Comment by thednp** [comment]
Check the [wikis](https://github.com/thednp/bootstrap.native/wiki) and give it a try, them let us know how and whats best to do about that.

**Comment by cliffordh** [comment]
@elsuper-migueld let me know if you figured this out. I'm also interested. I am using plain vanilla bootstrap inside my Vue template and need collapse.

**Comment by elsuper-migueld** [comment]
> Check the [wikis](https://github.com/thednp/bootstrap.native/wiki) and give it a try, then let us know how and whats best to do about that.

thanks for reply, of course I tried but .... no luck. any suggestions? i tried with boostrap v3 and v4.

**Comment by cliffordh** [comment]
I was able to get it working in my Vue project by loading the script in index.html. The "require" way of doing this in main.js doesn't seem to work. I'm nervous about using this with Vue since Vue likes to fully control the DOM. I looked at the code for this project and it's not really a ton of code, which is great... but that means it might be "easy" to port the components of interest into Vue components and essentially make a super-lightweight version of Bootstrap-Vue.

**Comment by elsuper-migueld** [comment]
Welll it works if I place the script like:
 <script src="{{ asset('js/app.js') }}"  ></script>
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.15/bootstrap-native-v4.min.js"></script>

but if I use inside app.js (is my main file where include everything)

import VueLazyload from 'vue-lazyload';
import BoostrapNative from 'bootstrap.native/dist/bootstrap-native-v4';
// require('bootstrap.native/dist/bootstrap-native-v4');

**Comment by elsuper-migueld** [comment]
> @elsuper-migueld let me know if you figured this out. I'm also interested. I am using plain vanilla bootstrap inside my Vue template and need collapse.

check my last comment

**Comment by cliffordh** [comment]
@elsuper-migueld yeah, if I load it with the script tag then it works... but again, worried about collisions with the way Vue handles the DOM. I tried all manner of importing it, and in fact I'm able to do this:
import BootstrapNative from 'bootstrap.native/dist/bootstrap-native-v4';
Vue.prototype.$BSN = {BootstrapNative};
and then I can grab access to BSN Alert, Collapse, etc. programmaticallly... but the initialization functions don't execute and I can't figure out how to hook into those. But, if not using a native Vue component wrapper that updates the DOM state in a Vue compatible way I don't think it really matters... Might just embed the script tag for now and see how it goes.

**Comment by m16u31D** [comment]
@cliffordh Thanks, Im new in vueJs i'm trying to migrate a project made with jquery to vuejs. ill try in a few hours and check if works

**Comment by thednp** [comment]
Sup, how you guys doing, is this solved or need more help?

**Comment by midejesus** [comment]
I also wanted to use the Collapse for a Vue component, but as @cliffordh mentioned, the initialization functions don't execute. 
I figured that I could do the following: 
```
    methods: {
        initCollapse() {
            const collapseButton = document.getElementById('envelope-button');
            const myCollapseInit = new Collapse(collapseButton);
        },
    },
    mounted() {
        this.initCollapse();
    },
```

**Comment by thednp** [comment]
@m16u31D @cliffordh 
Please confirm and close issue :)

**Comment by m16u31D** [comment]
Hi guys im here again. 
in my project theres a nav menu If I use boostrap/native like this at the end of the file

```
<script src="{{ asset('js/app.js') }}" ></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.15/bootstrap-native-v4.min.js"></script>
```
 
the navbar-nav works fine the dropdown items shows and hides.
but if a use boostrap.native in my app-main.js

 
```
window.Vue = require('vue'); 
import BootstrapNative from 'bootstrap.native/dist/bootstrap-native-v4';
Vue.prototype.$BSN = BootstrapNative;

// trying to make it works
// <a id="navbarDropdown"  class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" rel="nofollow"   aria-haspopup="true" aria-expanded="false" v-pre>
//var myDropdown = document.getElementById('navbarDropdown');
//var myDropdownInit = new Vue.prototype.$BSN.Dropdown(myDropdown);
// myDropdownInit.toogle(); // works but always is open
 
Vue.component('episodes-list', require('./components/EpisodesListComponent.vue').default);
// .... more components

const app = new Vue({
    el: '#app',
});
```
the dropdown items not work.(not show or hide)
is there  any way to initialize DROPDOWN or the other bootstrap components from a main file?



I have not problem using bootstrap native in vue js components. in this way
```
 document.getElementById('modalContainer').innerHTML = modalHtmlAuth;
 new Vue.prototype.$BSN.Modal(document.getElementById('modalAuth')).show();
```

**Comment by thednp** [comment]
Closing the issue as it looks to be solved.
