### ISSUE TITLE
Use collapse in Javascript without link/button

### ISSUE THREAD

**Issue by jeroenkampinga** [thednp/bootstrap.native#297]
Is it not possible to trigger a `collapse.show(); `without having a link or button trigger?

In my case I want to collapse a div after a successful AJAX call. I already tried multiple solutions but you always seem to need a `data-target` in your HTML.

**Comment by thednp** [comment]
Modal is the only component we "forked" to be able to handle independent [trigger<->target] public methods access, and that was a kinda popular demand, understandably.

Right now there are no plans to expand this kinda of functionality to other components, so the solution for you is to fork it, make it work the way you want, and later on, if it's to be considered a popular issue, we might accept a PR from you.
