### ISSUE TITLE
Popover trigger hover default does not match Bootstrap 4

### ISSUE THREAD

**Issue by bestguy** [thednp/bootstrap.native#298]
Popover trigger defaults to hover event, which does not match Bootstrap 4's click event default :

https://getbootstrap.com/docs/4.3/components/popovers/#options
https://github.com/thednp/bootstrap.native/blob/master/lib/V4/popover-native.js#L47

**Comment by thednp** [comment]
Thanks for the heads up. I decided to go with `hover` event as default from the start and I can't find a use case where `click` should be the default event from something I expect to pop. As a user I expect info BEFORE clicking a certain button that might take me somewhere I don't need to go.

But thinking about this, I might consider in the future a default trigger event `auto` which would set  the trigger event depending on the element: `focus` for `<input>`, `click` for `<button>` and `hover` for anything else. How about that?

**Comment by bestguy** [comment]
I think the reasoning is that Popovers are not just styled Tooltips, they are 'optional' content that can pop over other content.  The usages I've seen at least use click for that which makes sense.

Your suggestion sounds fine, however the difference between BS4 defaults and this library makes it a little more difficult to use as a drop in-replacement.

**Comment by thednp** [comment]
Our purpose here isn't to provide a drop-in replacement, but to make it our way, since we're doin' it from day 1 with vanilla JavaScript. This, along many others documented in the WIKI and the demo, this could be an acceptable exception simply because I like the better idea, the less for more trade off.

**Comment by thednp** [comment]
I've updated the [FAQs](https://github.com/thednp/bootstrap.native/wiki/FAQs#does-this-library-work-as-a-drop-in-replacement-for-the-original-jquery-plugins) to prevent further unnecessary thumbs down.
