### ISSUE TITLE
New Feature: checking for event.defaultPrevented for custom events

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#302]
As discussed in #165  we added the ability to stop execution for most components when using `event.preventDefault()` for the custom events.

Main focus:
* first the feature is added to V3, if all goes well, the exact same will be added to V4 as well
* I don't see the point of using `event.preventDefault()` on events like `shown.bs.modal` or `slid.bs.carousel`, the functionality could break in some cases, while in other cases like `affixed-top.bs.affix` event makes no sense
* we're looking into ways to improve code
* additional suggestions/PR should come with strong arguments

Please test latest master, lemme know what you think.

**Comment by thednp** [comment]
@edufransoni how we doin?

**Comment by edufranzoni** [comment]
> @edufranzoni how we doin?

Hello @thednp , looks nice.
i will try to test today.

i appreciate it

**Comment by thednp** [comment]
Right from my demo:

```js
var myModal = document.getElementById('myModal'); 
myModal.addEventListener('show.bs.modal', function(e) { 
        e.preventDefault(); // this works for me just right, the modal is not shown
	e.target && console.log('show.bs.modal triggered for #'+e.target.id);
	e.relatedTarget && console.log('event.relatedTarget is '+e.relatedTarget.tagName+'.'+e.relatedTarget.className.replace(/\s/g,'.'));
}, false);
```

**Comment by edufranzoni** [comment]
@thednp It worked now, thank you very much.
Can this also be implemented in bootstrap-native-v4 please?

Thank you very much

**Comment by thednp** [comment]
It will come as soon as we have more confirmations on good functionality for the current build.

**Comment by thednp** [comment]
@edufranzoni please check latest master, I've added the changes to V4. 

Would love to have a full review as soon as you please.

**Comment by edufranzoni** [comment]
> @edufranzoni please check latest master, found some time and I've added the changes to V4.
> 
> Would love to have a full review as soon as you please.

@thednp Working perfectly, I didn't detect problems with other components either.

Thank you so much for your attention and agility in helping the community.

**Comment by thednp** [comment]
No problem man, some things just make a lot of sense. I mean why have events that won't allow you to control.
