### ISSUE TITLE
[FEATURE REQUEST] - Add 'template' as an option for tooltip

### ISSUE THREAD

**Issue by classicmike** [thednp/bootstrap.native#303]
Apparently official Bootstrap JS has added support of changing the template of your tooltip meaning you can do things such as add additional css classes to further customize the tooltip, called ```template``` and you can pass HTML into it. 

https://getbootstrap.com/docs/4.3/components/tooltips/#options.

So an example would be is that I've created a ```tooltip-danger``` variant for 'error like' tooltips. 

I can simply inject the following HTML into the ```template``` option.

```
<div class="tooltip tooltip-danger" role="tooltip"><div class="arrow"></div><div class="tooltip-inner"></div></div>
```

I currently have use cases where I need to change the tooltip's background colour and I have been able to do it successfully with the original Bootstrap JS.

So far looking at the code I haven't seen any support for this option in this library. Popovers seem to have support. Would love this to be ported over to bootstrap.native.

Thanks for your efforts.

**Comment by thednp** [comment]
I'm busy with other development work, if no community PR coming in, will have a look at this later.

**Comment by classicmike** [comment]
Sure thanks for letting me know.

**Comment by thednp** [comment]
@classicmike I'm looking at this at the moment, I wanna know if a color, `data-color` option would be better than a template system.

**Comment by thednp** [comment]
@classicmike & @cvaize

Please test latest master and let me know how it goes.
