### ISSUE TITLE
Feature: build-time class prefix option

### ISSUE THREAD

**Issue by mattboldt** [thednp/bootstrap.native#311]
I'm using the [react-bootstrap](https://react-bootstrap.github.io/) library, which only imports Bootstrap css, but drops all js dependencies and reimplements them in React.

However, I'm using it alongside Rails via `react-rails` & `webpacker`; This means we can use bootstrap CSS in rails views AND have a full suite of react components. Only problem is, we're missing support for all native bootstrap js components.

So I was wondering if I could pull in this library, and perhaps prefix the classes it targets with something like
```html
<div class="alert alert-dismissable bn-alert">...
```

This way the native event handlers won't conflict with React, and only target `bn-*` classes. Think that's doable? I'd be happy to submit a PR.

**Comment by thednp** [comment]
All BSN components create init objects for all elements with appropriate `data-toggle` attribute, so it's up to you to decide whether you want to automatically initialize using data attributes or via JavaScript with your preferred classes.

**Comment by mattboldt** [comment]
Oh wow. Thank you for such a detailed response! I had a hunch my feature idea wouldn't even be necessary. And re [About#moving-forward](https://github.com/thednp/bootstrap.native/wiki/About#moving-forward), this is awesome! Thank you. It's great this project will stay alive because, in my unique case, I probably won't even be able to pull in non-jquery bootstrap unless I have these special build tools.
