### ISSUE TITLE
Disable radio button group

### ISSUE THREAD

**Issue by teran-mckinney** [thednp/bootstrap.native#316]
Hi,

I'm not sure how I can disable a radio button group. I have a button that submits a form (minus the literal form tags) and normally lock out controls by setting them all to disabled. This isn't working for me with Bootstrap 4 + BNP4.

The disabled class still makes a clickable element as well.

Do you have any recommendations?

Thanks,

Teran

**Comment by thednp** [comment]
The **Button** component works with radio inputs, it wasn't developed having other cases or functionality in mind.

**Comment by teran-mckinney** [comment]
Ah, I haven't. I ended up removing the event listener, adding disabled, and a disabled class. Seems to have done the trick but maybe not the cleanest way to do it.

Thanks for getting back to me.

**Comment by teran-mckinney** [comment]
Now I'm a bit stuck trying to figure out how to toggle a button, heh.

I'm sorry, I'm not good at CSS or JS.

**Comment by thednp** [comment]
@teran-mckinney it's all about design and purpose. The **Button** component is designed to replace the impossible to style [radio input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) and [checkbox input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) with [buttons](https://getbootstrap.com/docs/4.3/components/buttons/#checkbox-and-radio-buttons) where you can apply additional styling for various form purposes.

Changing this basic functionality makes little sense.

**Comment by teran-mckinney** [comment]
Gotcha. I guess I can just have buttons and make them exclusive in code. Thanks for the help. I'll close this one out.

I like DNP a lot, seems overkill to have jQuery for basic Bootstrap things like closing alerts.
