### ISSUE TITLE
attach a modal to each card

### ISSUE THREAD

**Issue by fabads** [thednp/bootstrap.native#317]
Hello all,
I discovered bootstrap and bootstrap native and I would like to attach a modal to each card of my card deck. On each card, I have an icon allowing to show more details. When clicking on it, I would like to display a modal with some data specific to each card.
In the onload function, I was planning to read all my data and generate my modals but I'm stuck.
What is the best way to achieve this and especially update the modal with the right data.
Thanks a lot for your help.

**Comment by thednp** [comment]
Read my docs on the demo page and try harder.

**Comment by fabads** [comment]
Not helping so much! I tried your demo page but the only way I found to associate card to modal is by using event. target to know which button has been pushed. Is it the right way?

**Comment by thednp** [comment]
Even the original library doesn't have this functionality, it's up to you to make it your way.
