### ISSUE TITLE
Is it possible to import only particular component for example dropdown or tooltip?

### ISSUE THREAD

**Issue by michael-vasyliv** [thednp/bootstrap.native#319]
Question:
Is it possible to import only particular component for example dropdown or tooltip?

**Comment by michael-vasyliv** [comment]
https://github.com/thednp/bootstrap.native/issues/128

**Comment by thednp** [comment]
* Create a [custom build](https://github.com/thednp/bootstrap.native/wiki/How-to-use#custom-builds)
* Import the build

**Comment by michael-vasyliv** [comment]
@thednp thanks.

**Comment by michael-vasyliv** [comment]
@thednp one more question, after call `node build.js -v 4 -a false -o button` where is the file that I can import to my project?
