### ISSUE TITLE
(Bug) It is not possible to destroy the Tooltip when reinitializing again

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#324]
I wrote about this problem in pull request. https://github.com/thednp/bootstrap.native/pull/320
Test video: https://drive.google.com/file/d/1LT2FzHEt0ANcNCh3t903AjxnaM2hBGOp/view?usp=sharing

**Comment by thednp** [comment]
I'm looking into it a bit later today, right now I'm researching a way to convert the code base to ES6/ES7, but if you're available and/or willing please let me know.

**Comment by cvaize** [comment]
I left comments in pull request about this problem. https://github.com/thednp/bootstrap.native/pull/320

**Comment by cvaize** [comment]
Regarding s6/s7, I would do this: based on "rollup" I would create components that import all the necessary help functions and variables. I would create a single file in which I would import all the components and initialize them. Rollup will shake the tree and remove unnecessary dependencies. This allows other developers to select components for themselves, import them, and initialize them. Due to the ability to get rid of the extra code base, the package will become easier and more convenient to use and support.

**Comment by thednp** [comment]
Your language is still a bit "Chinese" to me, perhaps sharing a super simple guide and/or sample in the #306 thread. Thanks

PS: I'm now looking at the current issue and I'm a bit confused because everything worked perfect yesterday before I commit to git. The use of `destroy()` before re-init seems like a logical idea.

**Comment by thednp** [comment]
@cvaize I can confirm the destroy before re-init works best, I will update all components. As for ES6/ES7 I will commit a draft very soon.
