### ISSUE TITLE
(Bug) When reinitializing the Tooltip, an empty object is returned

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#325]
After reinitialization, the Tooltip returns an empty object with no methods or settings. This shouldn't be happening. The new Tooltip object must have methods and settings.
My pull request has resolved this problem. https://github.com/thednp/bootstrap.native/pull/320
![image](https://user-images.githubusercontent.com/26907947/71569660-7ca71b80-2af2-11ea-80cc-010f5069cd48.png)

**Comment by cvaize** [comment]
The complete object should look like this
![image](https://user-images.githubusercontent.com/26907947/71569755-27b7d500-2af3-11ea-913f-70e03a397658.png)

**Comment by cvaize** [comment]
https://github.com/thednp/bootstrap.native/commit/ecad85f02e75d0bef5048f15a1de9fc99a59c140 This is similar to my first option with destroy, which you rejected =) Its drawback is that the Tooltip should not be hidden when updating. For example: in the parameter filter, when you hover over a button, a tooltip is displayed, the user clicks on the button, and all tooltips are updated, but the tooltips should not be hidden, but only new Tooltips are initialized.

**Comment by cvaize** [comment]
My solution also has this flaw.

**Comment by cvaize** [comment]
https://drive.google.com/file/d/1tkwOrUTA7pZFR-iareryQShSy_OBumej/view?usp=sharing

**Comment by thednp** [comment]
You mean we shouldn't use `hide()` method on `destroy()`?

**Comment by cvaize** [comment]
Not exactly, we should not use the `hide()` method when reinitializing, but it is worth considering that the created tooltip element is re-bound and does not remain in the DOM.
![image](https://user-images.githubusercontent.com/26907947/71575685-b76b7c80-2b0f-11ea-8ba5-14df7d70b3b3.png)

**Comment by thednp** [comment]
I guess you're trying to update the tooltip content on re-init, that's why I say the `hide()` usage on `destroy()` is a good thing, you can always do `show()` on re-init. But what is on your mind?

**Comment by cvaize** [comment]
I will try to fix it, and later I will publish it in pull request, for example.

**Comment by thednp** [comment]
On a second thought, you really need the `hide()` in `destroy()` for Dropdown, Modal, Tooltip, Popover to also detach specific handlers from element and keep consistency, so the one thing left to fix is the empty object returned on re-init.

**Comment by thednp** [comment]
@cvaize I'm not getting your issue on my end, I can re-init with different options and the returned object is fine, have a look
![popover-test](https://user-images.githubusercontent.com/6761246/71588829-987ae380-2b2b-11ea-9b71-d4e03152c43c.png)

Now I want to know if you can assist in testing some ES6/ES7 code for me, I'm not experienced enough to do that.

**Comment by cvaize** [comment]
Thank you, now indeed you have fixed the current bug. But I wrote about something else. Tooltip should not change its state when reinitializing. If the Tooltip was opened, it should not be closed during reinitialization, if the title was changed, it is better to change the title in the open Tooltip, rather than close it. Yes I will help with ES6/ES7.

**Comment by thednp** [comment]
@cvaize in that case, you can do this: `new Tooltip(target,newOps).show()`, it should work nice, even if your current init tooltip is visible.

**Comment by cvaize** [comment]
You are right, but I think this is a bad option, since Tooltip will disappear and reappear. This undesirable factor can be circumvented by initializing only non-initialized Tooltip. 
But at the expense of changing the title in the open tooltip. I had a previous task to change the title when clicking on the button.
https://drive.google.com/file/d/1dgn9hosZ3qwsnx1HQFej3Q8Dh4JClaNi/view?usp=sharing

**Comment by thednp** [comment]
That looks like a custom development to me, different from our original design, BUT if you REALLY want the functionality, you can make a fork, expose `setContent(markup)` & `update() { styleTip }` methods to public and make it work exactly the way you want. I have something similar for `mousemove` to make the tooltip follow the mouse pointer.

**Comment by cvaize** [comment]
Okay, I'm implementing this at the reinitialization level. As soon as the ES6/ES7 is ready, let me know.

**Comment by cvaize** [comment]
By the way. "" === false
![image](https://user-images.githubusercontent.com/26907947/71592994-0b985000-2b54-11ea-8ae6-52aeed0d5ad7.png)
![image](https://user-images.githubusercontent.com/26907947/71592937-e572b000-2b53-11ea-8757-ebc83955b2e9.png)

**Comment by cvaize** [comment]
And here's another thing, I advise you to place private functions always at the top, because when they are called, the variables will already be overwritten and there will be no problems. But if you move them down, you can't use them to generate duplicate values. Here is an example, not perfect, but from it you can understand the essence:
![image](https://user-images.githubusercontent.com/26907947/71593277-3cc55000-2b55-11ea-8621-01e27e7c073f.png)
![image](https://user-images.githubusercontent.com/26907947/71593301-51094d00-2b55-11ea-92d6-cd9be11df9ae.png)

**Comment by thednp** [comment]
Got it!

> By the way. "" === false
> ![image](https://user-images.githubusercontent.com/26907947/71592994-0b985000-2b54-11ea-8ae6-52aeed0d5ad7.png)
> ![image](https://user-images.githubusercontent.com/26907947/71592937-e572b000-2b53-11ea-8757-ebc83955b2e9.png)

What do you suggest about that?

**Comment by cvaize** [comment]
@thednp 
![image](https://user-images.githubusercontent.com/26907947/71593521-48654680-2b56-11ea-8cb4-8ff34d90a3cf.png)

**Comment by cvaize** [comment]
I will make a pull request

**Comment by thednp** [comment]
I think you mean `if ( !titleString || titleString === "" ) return;`

**Comment by cvaize** [comment]
I mean `if ( !titleString ) return;` or `if ( !readTheTitleAgain() ) return;`

**Comment by cvaize** [comment]
`"" === false`

**Comment by thednp** [comment]
Hold on, don't PR just yet, I'm gonna use your private method, looks promising to me. Also for Popover.

**Comment by thednp** [comment]
I've moved `if ( !titleString ) return;` to bottom before init, and created a new private `getTitle()`, seems ok now, thanks for the suggestion.

**Comment by thednp** [comment]
@cvaize check master

**Comment by cvaize** [comment]
Here we missed it
![image](https://user-images.githubusercontent.com/26907947/71594759-f672ef80-2b5a-11ea-8fe8-792087496a72.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/71594801-1efae980-2b5b-11ea-915c-07bfe621b882.png)

**Comment by thednp** [comment]
I remember someone made that change some year or so ago, perhaps now most modern browsers should work only with `!titleString && return`, correct?

**Comment by cvaize** [comment]
You shouldn't do that. This is a mistake.
![image](https://user-images.githubusercontent.com/26907947/71594953-a6485d00-2b5b-11ea-8690-89520ab84c57.png)
![image](https://user-images.githubusercontent.com/26907947/71594963-aba5a780-2b5b-11ea-835a-ebdea7787b6b.png)
It is better this way.
![image](https://user-images.githubusercontent.com/26907947/71594989-c11ad180-2b5b-11ea-9634-2464fd107f07.png)

**Comment by thednp** [comment]
Check master again.

**Comment by cvaize** [comment]
Some programmers do this, but I think it's a bad solution, the brackets should always be there.
![image](https://user-images.githubusercontent.com/26907947/71595034-f45d6080-2b5b-11ea-8353-70705e894233.png)

**Comment by cvaize** [comment]
Double conversion is also not necessary, I believe. Yes, in this case, there will definitely be a boolean value, but is it so important if the "if" construction understands without double conversion correctly. 
![image](https://user-images.githubusercontent.com/26907947/71595086-2e2e6700-2b5c-11ea-8a0c-d1a0b8cd8794.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/71595247-a8f78200-2b5c-11ea-96cc-04db5996dd75.png)

**Comment by cvaize** [comment]
Double conversion should be used in other cases.
![image](https://user-images.githubusercontent.com/26907947/71595313-da704d80-2b5c-11ea-970b-0d73a9a50022.png)

**Comment by cvaize** [comment]
A few subtleties =)

**Comment by thednp** [comment]
OK man, I will oblige you on this one, it's not a big deal. Wanna see some ES6/ES7 work in progress?

**Comment by cvaize** [comment]
I think it should be postponed until the new year. I still have some things to finish.

**Comment by thednp** [comment]
Just to get an idea of what I have in mind, perhaps suggest some improvements, mostly right now I need to know the work I've done is a good start.

**Comment by cvaize** [comment]
All right, post it to the new branch, and I'll upload the results. Or give me a link to the code.

**Comment by cvaize** [comment]
I'll read it tomorrow, it's too late today.

**Comment by thednp** [comment]
Alright, I hope I finish the draft by then, GN and TY for the consistent troublemaking :D
