### ISSUE TITLE
(Bug) Destroy when it re-initialize

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#327]
I also wrote this earlier about Tooltip. But this applies to all components. In reinitialization, there should be no destruction. https://drive.google.com/file/d/1y9Hl3_krYapbehJyuKNiztgiPeVkSS-E/view?usp=sharing

**Comment by cvaize** [comment]
My apologies, incorrectly initialized. It was necessary to use `new `

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/71724121-ea37ac80-2e50-11ea-8b87-6e77b70ba4a2.png)

**Comment by thednp** [comment]
The alert should not use `clsoe()` on `dispose()`, correct?

**Comment by thednp** [comment]
Hold on, the situation seems more complex.

**Comment by thednp** [comment]
Solved. As long as you do `new Component()` to init/re-init, everything should go smooth, after all `Alert()` doesn't `return { 1+2 }` but an init object with complex DOM changes.
