### ISSUE TITLE
Case is wrong for requirejs use

### ISSUE THREAD

**Issue by neothemachine** [thednp/bootstrap.native#33]
In the readme all the names are starting upper case, but they are actually lower case. bsm.modal vs bsm.Modal. Doesn't make sense to me that this is different from the global variables case. Apart from that, in the global case, why aren't all the classes under a single namespace? It seems wrong littering the window objects with all those generic sounding classes like Button for example.

**Comment by thednp** [comment]
That's @IngwiePhoenix work right there, probably he would have a look at it asap, or, if you happen to know how to fix, you two can do a commit whenever you please.

**Comment by IngwiePhoenix** [comment]
Hey.

I just looked into it and spotted the black sheep; `all.js`. Sorry for that one! I'll actually hotfix this ASAP (i'm really sleepy and more error-y right now...).

Regarding the export to the global window, we could consider changing a line like

```javascript
window.Button = factory();
```

Into

```javascript
window.bsm = window.bsm || {};
window.bsm.Button = window.Button = factory();
```

Advantages:
- Backwards compatibility to scripts not using module loaders.
- Bootstrap Native is namespaced, but the components can be used freely no problem.

Disadvantages:
- Duplicate objects in the root level object, for now
- Probably confuses the users.

Regarding the fix to the `all.js` file, that exports all the components, I might use a similar aproach, to keep both property names - lower- and uppercase - for a while, to not immediately introduce breaking changes.

Nobody likes breaking changes. *cough* `babel@6`.

What do you think, @thednp ?

**Comment by thednp** [comment]
I think you're cool :)

**Comment by thednp** [comment]
@IngwiePhoenix do you think we should close this?

**Comment by IngwiePhoenix** [comment]
Yes. I just woke up, so I can now work on this - which was my plan. I have a few patches to write for other things, so its patchday today :)

**Comment by IngwiePhoenix** [comment]
#36 has landed. I'll implement the global `bsn` namespace later. ^^
