### ISSUE TITLE
(Bug) Destroy when it re-initialize Toast

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#332]
The same problem. https://github.com/thednp/bootstrap.native/issues/327
![image](https://user-images.githubusercontent.com/26907947/71753164-825e8180-2ea3-11ea-9704-fa6044d65462.png)

**Comment by thednp** [comment]
I'm not sure how to handle this, but I found one unused function `disposeComplete()` where I believe we should do `toast.parentNode.removeChild(toast)`.

**Comment by thednp** [comment]
Please test latest master and let me know if you can work with the new behavior.

**Comment by thednp** [comment]
To be honest I'm not sure if and in which case we would need to remove the toast element from the DOM.

**Comment by cvaize** [comment]
@thednp Toast this message, at reinitialization it is not necessary to delete it from DOM. But you definitely need to. Although it will most likely not be used due to its specifics. Usually for this purpose use library by type of this https://apvarun.github.io/toastify-js/

**Comment by thednp** [comment]
That's a hard decision to make, perhaps looking into original plugin will shed some light. I'll see what I can do as soon as I'm done with #334

**Comment by thednp** [comment]
Seems the original library doesn't remove the toast from the DOM, perhaps developers can re-use it, reinitialize it and then do `show()` anytime needed.

**Comment by cvaize** [comment]
I think we should do the same

**Comment by thednp** [comment]
Well, check latest master, we're now making use of the `disposeComplete()` private method.

**Comment by cvaize** [comment]
I am waiting.

**Comment by thednp** [comment]
Alright, go ahead and check now.
* `dispose()` will use `hide()` method
* on re-init will just be hidden, but you can do `new Tooltip(target).show()` to make it

**Comment by cvaize** [comment]
It's simple, act like with Alert, but don't delete from the DOM. And when reinitializing, don't hide Toast.

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/71766817-09543e00-2f26-11ea-8b92-76229beee385.png)
