### ISSUE TITLE
(Enhancement) And what if there are 2 close buttons in the Alert component, when you click on any of these buttons, the Alert should close

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#333]
And what if there are 2 close buttons in the Alert component, when you click on any of these buttons, the Alert should close.
This test is performed 2 times, once on each button.
When you click on the 2nd button, nothing happens.
`var el = document.querySelectorAll('[data-dismiss="alert"]')[0];
      var newEl = el.cloneNode(true);
      newEl.style.right = '30px';
      el.parentElement.insertAdjacentElement('afterbegin', newEl);
      new BSN.components.Alert(el);
      new BSN.components.Alert(newEl);`
![image](https://user-images.githubusercontent.com/26907947/71754426-e1be9080-2ea7-11ea-91e4-9abc7067d205.png)
![image](https://user-images.githubusercontent.com/26907947/71754437-f13dd980-2ea7-11ea-971f-18a3815103b3.png)

**Comment by thednp** [comment]
This probably works with the original plugins, simply because the event delegation is managed at the document level. Other than that, I don't see an useful enhancement for our component.

**Comment by cvaize** [comment]
I can not understand the reason for using only the first button, because if this button is in Alert, and it was clicked, it must close the current Alert, otherwise we have limited the functionality of one button in advance.
![image](https://user-images.githubusercontent.com/26907947/71761041-181c0000-2ee8-11ea-9e60-f1ea790ae103.png)
![image](https://user-images.githubusercontent.com/26907947/71761052-4994cb80-2ee8-11ea-8f58-cff0783efbc8.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/71761081-b0b28000-2ee8-11ea-9c0d-e035f6d21e4c.png)

**Comment by thednp** [comment]
You can do something even more simple: 

```javascript
<a href="#" onclick="this.closest(.alert).querySelector('[data-dismiss="alert"]').Alert.close()">Your content link</a>
```
It doesn't look very bad to me, and it should work without any modifications.

**Comment by cvaize** [comment]
You can, but why limit it to this code `(element === e.target || element.contains(e.target))`. My reasoning is this: if you click on the close Alert button, and above this button is an Alert, the listener exactly worked on the button on the Close button, since it could not work not on it, it means that the Alert needs to be closed.
The code sounds like this, if there is an Alert above the element that was clicked, and inside there is any first close button Alert, then check that any found, the first close button is the button that was clicked. I think this is unnecessary and I don't see the point in this check.
![image](https://user-images.githubusercontent.com/26907947/71762566-633b1080-2ef2-11ea-82f3-03e582366e1b.png)

**Comment by thednp** [comment]
Look I even made a small teak:

```markup
<button data-title="Close this alert via &lt;code&gt;close()&lt;/code&gt; method" data-tip="tooltip" class="border-0 p-0 bg-transparent text-primary" onclick="dismissAlert.call(this)">
 Your content Link
</button>
```

```javascript
function dismissAlert(){
	this.Tooltip && this.Tooltip.dispose();
	this.closest('.alert').querySelector('[data-dismiss="alert"]').Alert.close()
}
```
How do you like that?

**Comment by thednp** [comment]
> You can, but why limit it to this code `(element === e.target || element.contains(e.target))`. My reasoning is this: if you click on the close Alert button, and above this button is an Alert, the listener exactly worked on the button on the Close button, since it could not work not on it, it means that the Alert needs to be closed.
> The code sounds like this, if there is an Alert above the element that was clicked, and inside there is any first close button Alert, then check that any found, the first close button is the button that was clicked. I think this is unnecessary and I don't see the point in this check.
> ![image](https://user-images.githubusercontent.com/26907947/71762566-633b1080-2ef2-11ea-82f3-03e582366e1b.png)

The first reason is this: we have `on(element,'click',clickHandler)` not `on(alert,'click',clickHandler)`, we need to make sure user ONLY close alert via the designated dismiss button.

The second reason for the extensive check is this: many people want to use custom graphics, even SVG, say 

```markup
<button class="close" data-dismiss="alert"><svg><path d=".."></path></svg></button>
```

**Comment by thednp** [comment]
@cvaize what is your take on this please?

I really think we should shift focus into #332, complete tests for all components so we can move on to documentation.

**Comment by cvaize** [comment]
@thednp I'll look into it tomorrow
