### ISSUE TITLE
(Bug) Initialization Buttons[radio|checkbox] does not update the class "active"

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#334]
Initialization Buttons[radio|checkbox] does not update the class "active".
https://drive.google.com/file/d/1_Wgq5jPmAy9rZDOXXHZNhebt7mvhX1iv/view?usp=sharing

**Comment by thednp** [comment]
Very interesting find, I hope it's fixed now.

**Comment by cvaize** [comment]
Checked, the bug is fixed.
