### ISSUE TITLE
(Bug) Carousel - Initialization and reinitialization sets the current slider to 0, but does not change the state of the DOM.

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#335]
Initialization and reinitialization sets the current slider to 0, but does not change the state of the DOM. As a result, if you stop auto-switching on the last slide by initialization with the parameter "interval = 0" and click on the "prev" button, the slider disappears. 
https://drive.google.com/file/d/1OX72QBvdY2CeSWa_M0VZqThd3QLHwOUQ/view?usp=sharing

**Comment by thednp** [comment]
The initialization part of the code will try to activate first slide if none active, in my opinion that should be all we need to do at that point. It's true that cracks and breaks will happen when we re-init while animating, the functionality will 100% break apart. 

I think it's up to the developer to manage re-init on Carousel, which is one of the most complex components in the library. I already have some possible solutions in my mind but will only limit the developer's choices, something none of us wants.

I'm curious to what'son your mind.

**Comment by cvaize** [comment]
I have not considered this component deeply, the first solution I see is to take the number of the current slide from the frontend. Rationale: the current slider can be used for interactive pieces, not just for images, and if slides and content are added, then refusing to set the current slide to 0 is necessary, since every time the user wants to change the number of slides or move, or destroy the carousel, the carousel will roll back to slide 0, which is very bad.

**Comment by thednp** [comment]
Not if the carousel has a current ACTIVE item, nothing should happen, besides the switch between 2 items being active is in a split second.

**Comment by cvaize** [comment]
Perhaps I incorrectly expressed(google translate), implement your idea, and I will check it and if there are inconveniences in its use I will let you know.

**Comment by thednp** [comment]
For this case, I'm thinking of a "bulletproof" solution, perhaps we can `dispose()` Carousel in any case,  to put it simply: 

* make a private `dispose()` function
* inside the `dispose()` public method we can do 

`isAnimating ? emulateTransitionEnd(elem,dispose) : dispose()`

* the solution might work with any component that works with animations
* I'm am not sure how this could affect other developers or what implications it could bring

**Comment by cvaize** [comment]
Implement, let's look at the work.

**Comment by thednp** [comment]
I've tested this and it won't work for some reason. I'll investigate this further right away.

**Comment by thednp** [comment]
The `getElementTransitionDuration` and a `setTimout` will fix the problem.

I was thinking of implementing this into Tab, Collapse, Modal, but they don't have a `cycle()` timer so won't worth the trouble.

**Comment by cvaize** [comment]
Простите, я пока не могу вникнуть в проблему и найти решение, с этой задачей я полагаюсь на вас. Я смогу найти время в выходные, все же как вы и сказали это самый сложный компонент в библиотеке.

**Comment by thednp** [comment]
OK, you don't have to write Russian every time, unless you don't have time to translate it.

**Comment by cvaize** [comment]
OK

**Comment by thednp** [comment]
You can try to do `dispose()` while animating with latest master now, let me know how it goes.

**Comment by cvaize** [comment]
The bug remained, as well as a bug with the disappearance of the slider in the script: the Slider switches to the last slide, reinitialization occurs through the console, then click on the left arrow, and the carousel disappears.
Баг остался, а так же остался баг с исчезанием слайдера в сценарии: Слайдер переключается на последний слайд, происходит переинициализация через консоль, за тем происходит клик на левую стрелочку, и карусель исчезает.
