### ISSUE TITLE
(Bug) Collapse - Incorrect work with selectors, in consequence of which it is possible to work only with the ID of elements.

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#336]
Collapse - Incorrect work with selectors, in consequence of which it is possible to work only with the ID of elements.
https://drive.google.com/file/d/1cquQqntBovCy0xJpGq0KsajzKyouzlyp/view?usp=sharing

**Comment by thednp** [comment]
I really don't think it's a bug. Let me explain.

The current functionality makes sure to always target the right collapse target, regardless of both trigger button and collapse being contained within the same element or not, something that was in the original plugins of that time, some years ago.

The ability to work with multiple collapse targets per init object is something new with Bootstrap V4, not something I'm personally interested to do, I never thought of such a feature. While with sizzle you can quickly do `$('.target-class').collapse('toggle')`, with native code we have to manage alot of checks and issues. For this case, a simple function will do more to the developer in terms of flexibility. 

As of today I'm more than happy with the current state of the component and library in general, Collapse can do it's simple toggle efficiently while being able to work with accordion, by the way accordion targeted with `class` attribute thanks to `element.closest(selector)` we recently replaced our old `getClosest()` utility with.

I'm thinking maybe replacing `for()` with `forEach()` for instance in all component and utilities, and any ES6/ES7 new feature we can make use of.

**Comment by cvaize** [comment]
@thednp I agree with you
