### ISSUE TITLE
(Bug) Collapse - Boolean value is not processed collapse = getTarget();

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#337]
![image](https://user-images.githubusercontent.com/26907947/71781105-b1343f00-2fec-11ea-90f7-cf61967eee22.png)
![image](https://user-images.githubusercontent.com/26907947/71781106-ba251080-2fec-11ea-9a5e-e0d0fc4ae32c.png)

**Comment by thednp** [comment]
Is this a re-init issue again?

**Comment by cvaize** [comment]
No, the past issue was about working with selectors. This is an issue about handling an exception.

**Comment by cvaize** [comment]
Close issue if you think the exception should remain to signal an error.

**Comment by thednp** [comment]
Is this related to #336 we discussed before?

**Comment by cvaize** [comment]
No not related. A good function should return values of the same type. And if it returns a value similar to null or false, it should be processed on after its call. The problem is that when an exception occurs, the rest of the code stops working.

**Comment by cvaize** [comment]
https://drive.google.com/file/d/1EyGYdnSXkzy2w5obKARoXvRy5aXlF3_C/view?usp=sharing

**Comment by thednp** [comment]
You have the error because you still have the multi-target collapse example on.

**Comment by cvaize** [comment]
This code says that I will always have an error if the element is not found, or the selector does not contain "#", or "data-target"is not specified. At any small discrepancy an error will be caused and the library code will not work further. It's unreliable.
![image](https://user-images.githubusercontent.com/26907947/71801167-efc50a80-307b-11ea-87b9-5fad39d8d528.png)

**Comment by cvaize** [comment]
Just one error will knock out half the library

**Comment by thednp** [comment]
What do you suggest?

**Comment by cvaize** [comment]
This will solve the problem.
![image](https://user-images.githubusercontent.com/26907947/71807752-d5942800-308d-11ea-8e30-0f1eb3e29efa.png)

**Comment by cvaize** [comment]
https://drive.google.com/file/d/1HCbbT7oovf88ImzkemHS7AvF1WWilZIy/view?usp=sharing

**Comment by cvaize** [comment]
This solution should be implemented wherever an error may occur, but it is needed to signal a fault.

**Comment by thednp** [comment]
You can do `catch()` before `self.element = element` associations, but I'm not sure. Either way, feel free to PR this solution.

**Comment by thednp** [comment]
Listen, what if we do 

```javascript
collapse = queryElement(options.target) || queryElement(element.getAttribute('data-target')) || queryElement(element.getAttribute('href'));
```

What would the result and solution work for you?

**Comment by cvaize** [comment]
Regarding this solution, I would put "data-target "before" options.target". This is a solution to a past problem https://github.com/thednp/bootstrap.native/issues/336. For this problem, you need to handle the result "collapse = null|undefined|false", I suggest " try {} catch(e){console.error (e)} " thus the error will be in the console, but it will not affect the subsequent work.

**Comment by thednp** [comment]
Please tell me what is the output of the `console.error(e)`?

**Comment by cvaize** [comment]
Perhaps I did not understand you, if this is not the answer that you expected, please expand the question in more detail. https://developer.mozilla.org/en-US/docs/Web/API/Console/error

**Comment by thednp** [comment]
```javascript
try(){
  // set collapse
} catch(e){ // <= this error
  console.error(e)
}
```

**Comment by cvaize** [comment]
What do you mean by that?

**Comment by thednp** [comment]
Doesn't matter, probably we should just discontinue on `if (!collapse)`, this way we don't have an error if selector is incorrect.

**Comment by cvaize** [comment]
I would prefer to notify the developer that the selector is incorrect. But your decision will suit me, too.

**Comment by thednp** [comment]
> Regarding this solution, I would put "data-target "before" options.target". This is a solution to a past problem #336. For this problem, you need to handle the result `collapse = null|undefined|false`, I suggest `try {} catch(e){console.error (e)} ` thus the error will be in the console, but it will not affect the subsequent work.

I have to disagree there, people who re-init or just always init via JavaScript will want the `options.target` before anything else.

**Comment by thednp** [comment]
@cvaize what's up dude?

**Comment by cvaize** [comment]
@thednp A lot of work, sorry. In the evenings I find time Yes in breaks. I consider that through JS options concern all "collapse", and already on an element it is a special case. I don't mind using your version.

**Comment by thednp** [comment]
@cvaize I think you should write Russian, GTranslate is terrible :D

**Comment by cvaize** [comment]
Да, получилось ужасно. Я думаю опции передаваемые в конструктор компонентов действуют на коллекцию компонентов, а опции сохраненные в "data-" касаются только одного элемента. Поэтому и считаю, что опции из "data-" должны идти первыми. Тем не менее ваш вариант мне тоже подходит.

**Comment by thednp** [comment]
OK let me tell you why `options.target` should go before `data-target`: 
* with `data-target` is first if you want to re-init via JavaScript with new options values, the `data-target` attribute is impossible to bypass, so you will have to delete it
* the `options.target` works in any day of the week, with or without the data attribute, and you can easily bypass it, just don't set it and the data attribute (if present) takes over
* the `target` option example is a rather extreme case because it can't have a default value so it will require ONE of the above, but for the most part, most developers always do `options.target` first, most people I've talked to on GH, they all want it like that
* indeed the data attribute can be useful at the element level, I mean `data-slide-to`, `data-target="#ModalID"`, `data-target="#ScrollSpyTarget"` etc, I wish I could make a library that works with all `data-` attributes possible that everybody loves it and requires no JS knowledge at all, but we both know there's no such thing

**Comment by cvaize** [comment]
Согласен, ваши доводы меня убедили. Используем, предложенный вам вариант.

**Comment by cvaize** [comment]
Я проверю состояние всех issue чуть позже и продолжу тестирование, а пока думаю целесообразно закрыть это issue. Спасибо за разъяснение. =)

**Comment by thednp** [comment]
@cvaize btw, I've changed more components with live collections: 
* Button (add more label+input to a parent `<div data-toggle="buttons">`), 
* Carousel (add more `<div class="carousel-item">` and `<div class="data-slide-to">`) 
* ScrollSpy (add more `<div id="uniqueID">` and `<a href="#uniqueID">` items)

Check them out as soon as you can.
