### ISSUE TITLE
(Bug) All Components - Any error stops the script.

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#338]
I suggest wrapping each component in `try{}catch(e){console.log(e)}`
https://drive.google.com/open?id=11ObpwDvzD8096n9Gi-aiHSVZ1SRsTXwu
![image](https://user-images.githubusercontent.com/26907947/71831650-237b5100-30cb-11ea-829f-9c3c0866f492.png)

**Comment by thednp** [comment]
Check master.

**Comment by thednp** [comment]
I also tested on my server, all components working fine.

**Comment by cvaize** [comment]
Make an error at the beginning of the library, and you will see that the code below will not work.

**Comment by cvaize** [comment]
This can be corrected if we catch errors in components using try, catch

**Comment by thednp** [comment]
I will look into this asap.

**Comment by thednp** [comment]
@cvaize 

What do you think about encapsulating all init part (get target, attach event and associations) into `try()` & `catch()` or an `if (!target) return` filter? I would prefer the second simply because some components already do that.

**Comment by cvaize** [comment]
I would prefer `try` & `catch ` as this is the only option not to stop the entire script.

**Comment by thednp** [comment]
I have an idea: what if we use `try()` and `catch()` within the `initializeDataAPI`

```javascript
    var initializeDataAPI = function initializeDataAPI(Constructor, collection) {
      for (var i = 0, cl = collection.length; i < cl; i++) {
        try{
          new Constructor(collection[i]);
        } catch(e){
          console.error(e)
        }
      }
    };
```

I just tested it and it works great. I tested with Alert having a wrong selector, throws an error, but all other components work properly.

**Comment by cvaize** [comment]
The problem with your approach, if the programmer will manually initialize only the necessary components, then the problem remains. I do not know whether someone wraps the code in the components in "try, catch", for reliability, so that the error in the component does not affect other code, but for me this is the best option.

**Comment by thednp** [comment]
I agree with you but the original plugins don't do `try & catch` anywhere, yet people still use them. Like our library, the original plugins will eat whatever you throw at them.

**Comment by cvaize** [comment]
Any option would suit me. Do what you think is right

**Comment by thednp** [comment]
If you're happy with the outcome, feel free to close whenever you want.

**Comment by cvaize** [comment]
Думаю это должно работать, тесты проведу чуть позже.
