### ISSUE TITLE
Checked IE11, for normal operation it is only necessary to connect a polyfill on closest

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#339]
Checked IE11, for normal operation it is only necessary to connect a polyfill on closest. With polyfill, the components work properly in IE11.
https://github.com/idmadj/element-closest-polyfill/blob/master/index.js

**Comment by cvaize** [comment]
Will we support IE10, IE9?

**Comment by thednp** [comment]
We must cover support for what original plugins support.

**Comment by thednp** [comment]
We don't seem to need `.closest` polyfill, but I didn't test on actual IE 9-10, but on IE11 with emulation.

**Comment by thednp** [comment]
@cvaize you are right, after I cleared the browser cache, I can see IE11 going mad about `closest()`, so I will include it into the polyfill.
