### ISSUE TITLE
Alleged bug in the original Alert plugin

### ISSUE THREAD

**Issue by cvrebert** [thednp/bootstrap.native#34]
> [Unlike the original plugin, this script can successfully handle later added alerts into the DOM.](http://thednp.github.io/bootstrap.native/#exampleAlert)

FWICT, the original plugin handles this fine, making this claim inaccurate. Do you have a counterexample?

**Comment by thednp** [comment]
At the time the script was developed, I tried to work with the original plugin code and I wasn't sure that could handle later added alerts, so I came with the idea to make possible this feature. 

So if you confirm it's not the case, I'll update the demo, no problem.

**Comment by cvrebert** [comment]
Thanks.
