### ISSUE TITLE
Fix transition duration detection in carousel

### ISSUE THREAD

**Issue by albanyacademy** [thednp/bootstrap.native#340]
For carousel, the slid event fires immediately after the slide event if the following is true:
- The carousel target doesn't have the "slide" css class
- The carousel target has the "slide" css class, but doesn't have a transition duration property present in the CSS

The condition in question:
https://github.com/thednp/bootstrap.native/blob/6752d2d88db6b06b20576fcd87100da3e4767cdf/lib/V4/carousel-native.js#L215

The issue is that this ties the functionality much too closely to the CSS of the carousel, and customization is dependent on keeping the "slide" class intact. Without it, the "slid" event is useless. My case in particular requires some customization and an infinite loop, which screws up the usage of the slide class, specifically the emulateTransitionEnd function as the left/right classes seem to trip it up, but that's another issue.

This is part bug, part feature request. The bug, I think, is that the slid event is not more intelligent in its fallback in this case. The feature request would be to make this value more controllable in its implementation - consider a situation where a carousel and its children have different transition lengths or delays, necessitating the slid event to be fired once all of those are completed. It would be nice to have the slid event fired after a specific element is finished transitioning, or for the default behaviour to just choose whichever event fires last between the carousel proper and its slides, or carousel-inner element.

My temporary fix for this particular issue is:
````
} else {
        var duration = getTransitionDurationFromElement(element) || 100;
        addClass(slides[next],active);
        slides[next][offsetWidth];
        removeClass(slides[activeItem],active);
        setTimeout(function() {
          isSliding = false;
          if ( self[interval] && !hasClass(element,paused) ) {
            self.cycle();
          }
          bootstrapCustomEvent.call(element, slidEvent, component, slides[next]);
        }, duration );
      }
````

Caveats:
1. This still requires the carousel target to have a transition duration property, regardless if it actually has a transition.
2. The carousel slides themselves and -inner are ignored and not checked for transition durations.

**Comment by thednp** [comment]
Thanks for sharing the find. 

First, we're working in the `trunk/src` folder with ES6/ES7 standard.

Second, we're working closely with the `slide` class to follow the original plugin scripting, because it enables animation with the default Bootstrap 4 CSS3 setup. Even the fade example does.

So since `getElementTransitionDuration()` already checks `supportTransition`, a better fix would be 

```javascript
if ( getElementTransitionDuration(slides[next]) && hasClass(element,'slide') ) { 
```
Now check latest master and let me know how it goes.

**Comment by albanyacademy** [comment]
You're committed to having the slide class present for transition duration to be detected and influence the firing of the slid event? Maybe I'll just raise it as an improvement on the jQuery version then 😁 

Regardless, if that's the case that's fine, I'll just have to diagnose why carousel is misfiring on my infinite loop stuff and the jQuery version isn't.

**Comment by albanyacademy** [comment]
didn't mean to click close

**Comment by thednp** [comment]
Perhaps if we have a demo site to investigate the infinite loop issue we might find the rat in the computer.

**Comment by thednp** [comment]
Or this isn't an issue after all.

**Comment by thednp** [comment]
@albanyacademy we good?

**Comment by albanyacademy** [comment]
Sorry feel free to close this, I can come back with another issue once I have something more concrete
