### ISSUE TITLE
(Bug) Iphone 5 - Safary Carousel - Bug touch

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#344]
![image](https://user-images.githubusercontent.com/26907947/72000558-64a76880-3265-11ea-91f2-58d7ca2e752a.png)
![image](https://user-images.githubusercontent.com/26907947/72000604-7ab52900-3265-11ea-97d6-49cd7e8c7120.png)
![image](https://user-images.githubusercontent.com/26907947/72000661-94567080-3265-11ea-8c1d-414bab2135ce.png)

**Comment by thednp** [comment]
Lol Safari doesn't support `currentTouches` :D

**Comment by cvaize** [comment]
I confirm that the bug has been fixed
