### ISSUE TITLE
(Bug) Iphone 5 - Safary - Popover && Tooltip - Tooltip does not close when focus is lost

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#345]
Tooltip does not close when focus is lost. Compared with the original "bootstrap 4", everything works correctly in it, so in "bootstrap.native" I consider this a bug.
https://drive.google.com/file/d/1E6spqe92n79j1nXqG4TCQk7DWiKiroOd/view?usp=sharing

**Comment by cvaize** [comment]
@thednp Watch the video

**Comment by thednp** [comment]
Check latest master, I believe `queryElement` is responsible for this one too.

**Comment by thednp** [comment]
One more suggestion: please try the previous version of our polyfill.

**Comment by thednp** [comment]
This is strange indeed, the last build won't work on my Android phone as well, but I have another build working with `currentTouches`.

**Comment by thednp** [comment]
My bad, it's `changedTouches` and not `currentTouches`.

**Comment by thednp** [comment]
I solved the carousel swipe bug, but I don't know about Popover, Tooltip, please confirm with latest master?

**Comment by cvaize** [comment]
The problem remains, Popover and Tooltip do not close when you lose focus

**Comment by thednp** [comment]
Please tell does the demo on `gh-pages` do the same on iPhone?

**Comment by cvaize** [comment]
Yes, https://drive.google.com/file/d/1eyQuAGAM0CtkserG0Dlng75KGJSFkypX/view?usp=sharing

**Comment by thednp** [comment]
@cvaize it seems we don't have any filters/checks on the handlers or any handlers targeted at mobile devices, I believe we need to use `touchstart` on document while trigger option is set to `hover`, I will have a look into it as soon as I can.

Meanwhile, since I don't have any iPhone/iMac or any Apple, I need to know what events trigger on which device, so can you please gimme a screenshot from your iPhone&Mac for the following:

```javascript
// update if necessary
var button = document.getElementsByTagName('BUTTON')[0];

function testHandler(e){
  if (e.target === button){
    button.innerHTML = e.type;
    console.log(e.type)
  }
}
// iphone
document.addEventListener('touchstart',testHandler,false)

// mac
button.addEventListener('mouseout',testHandler,false)
button.addEventListener('mouseleave',testHandler,false)

button.addEventListener('focusout',testHandler,false)
button.addEventListener('blur',testHandler,false)
```

**Comment by cvaize** [comment]
Okay, here's a video of the test: https://drive.google.com/file/d/1f1n-UEIDJbKN88rz9lllq7n9xw1-if8U/view?usp=sharing

**Comment by thednp** [comment]
So it looks like the events barely fire, like I imagined they would.

**Comment by cvaize** [comment]
Bugs remained, here is confirmation: https://github.com/thednp/bootstrap.native/issues/346 https://github.com/thednp/bootstrap.native/issues/345
https://drive.google.com/file/d/13wAesUHqmNEp1_pDQtyNYt9-VAUoifgm/view?usp=sharing

**Comment by thednp** [comment]
Did you test the latest master? There have been some changes since that initial commit.

**Comment by cvaize** [comment]
In the video, I demonstrated the commits.
https://github.com/thednp/bootstrap.native/commit/49f14d603baae3e11e028d668b79ca31b120d493

**Comment by thednp** [comment]
Alright man, will check those asap. Thanks for the feedback.

**Comment by thednp** [comment]
@cvaize how we doin?

**Comment by thednp** [comment]
@cvaize I will start documenting V4 next week and I really need your feedback.

**Comment by cvaize** [comment]
Sorry for the delay. I'll run tests now

**Comment by cvaize** [comment]
I ran tests. Bug with Carousel fixed. The current bug in iphone 5 related to Popover and Tooltip remained, I think it is not critical and you can design documentation

**Comment by thednp** [comment]
@cvaize I put some time into the tooltip/popover issue and I still need help in finding a solution.

**Comment by cvaize** [comment]
@thednp Since I have an iphone 5 I will look for a solution, leave this issue to me. This problem is important,but it is not urgent. I will look for a solution to this problem on the weekend

**Comment by cvaize** [comment]
Here's what I found, an error in registering a touch listener
![image](https://user-images.githubusercontent.com/26907947/75099578-0f40d400-55e5-11ea-813f-a3592501773f.png)
![image](https://user-images.githubusercontent.com/26907947/75099587-241d6780-55e5-11ea-8769-8ad477991535.png)
![image](https://user-images.githubusercontent.com/26907947/75099592-2d0e3900-55e5-11ea-93a0-2c10d5afaeb7.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/75099623-7eb6c380-55e5-11ea-8280-8f210604e87f.png)

**Comment by cvaize** [comment]
After correctly binding the listener, the tooltip started closing correctly.
![image](https://user-images.githubusercontent.com/26907947/75099648-c4738c00-55e5-11ea-816e-83f08289e4ac.png)

**Comment by cvaize** [comment]
But, re-opening the tooltip on the same button does not happen, I am investigating

**Comment by cvaize** [comment]
https://drive.google.com/file/d/1gE2wciRp-oRm-C-n-sGYjM0rUfNhXMRC/view?usp=sharing

**Comment by cvaize** [comment]
I will prepare a pull request for correction

**Comment by cvaize** [comment]
Working on Popover, I noticed a difference in the work of Popover from the original library, Popover trigger=click https://drive.google.com/open?id=1FLgiZiXb1_USsaluczdzjteulRhAlZrg

**Comment by cvaize** [comment]
On iphone, the focus event doesn't work as it should. I want to use the voiced solution https://github.com/jquery/jquery-mobile/issues/3016#issuecomment-124575134 
Я проверил оно работает, но есть важный вопрос. 
I need detect mobile, но всего 1 раз. At bootstrap.native there are global variables, if not then how should they be implemented? Or should I make a pull request for existing edits with Tooltip and Popover for Hover and Click events?

**Comment by thednp** [comment]
That's an interesting find because on my Android, Chrome works as expected as is, without your modifications. Please send me your mobile `navigator` string, I will give you a solution to your issue.

**Comment by cvaize** [comment]
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1

**Comment by cvaize** [comment]
Of course, it can be determined by user agent, but there is no guarantee that this will not become a problem in the future. I have a solution for user agent`/(Android|BlackBerry|iPhone|iPod|Palm|Symbian)/.test(navigator.userAgent)`

**Comment by cvaize** [comment]
Should I use it?

**Comment by thednp** [comment]
Since our problem is strictly on Apple mobile, this is the line
```js
/(iPhone|iPod)/.test(navigator.userAgent)
```

**Comment by thednp** [comment]
Damn such a bad browser still at 17% market share.

**Comment by cvaize** [comment]
Do you have an Iphone 10 or Iphone 11 or Ipad of the latest version, please check if Focus Event doesn't work on them either? This is necessary to check whether all mobile safaris have this problem or not.

**Comment by thednp** [comment]
I wouldn't have asked for your help if I had, probably never will. I wish I had more community input.

**Comment by thednp** [comment]
Listen, have it work fine on your device, I believe the fix will work with other Apple Safari mobiles as well.

**Comment by cvaize** [comment]
Okay, I'll do a pull request

**Comment by cvaize** [comment]
@thednp Attention!!! Listeners are not deleted in the entire library

**Comment by thednp** [comment]
So we good to finally close this at long last?

**Comment by cvaize** [comment]
Yes
