### ISSUE TITLE
(Bug) Carousel - Bug when reinitializing on the last slide

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#346]
The Slider switches to the last slide, reinitialization occurs through the console, then click on the left arrow, and the carousel disappears.
Слайдер переключается на последний слайд, происходит переинициализация через консоль, за тем происходит клик на левую стрелочку, и карусель исчезает.
https://drive.google.com/file/d/1kmpukG1rS-t4ihd0Y7H11JCEoiaTXYWd/view?usp=sharing

**Comment by thednp** [comment]
@cvaize we good with latest change?

**Comment by cvaize** [comment]
I'm sorry, I can only check on the weekend. The lack of time will last until the end of February.

**Comment by thednp** [comment]
Well in my tests, I can't get any error on re-init, when animating/not, also on re-init the `cycle()` now knows the current active so it won't jump or go to a wrong slide.

I'm very interested in your tests with Tooltip and Popover, made some new handlers for them.

**Comment by cvaize** [comment]
If you think the issue is fixed, close them as soon as I find time to test them immediately and open them if I find something

**Comment by thednp** [comment]
No rush, I will begin documenting.

**Comment by thednp** [comment]
@cvaize how we doin?
