### ISSUE TITLE
Scrollspy doesn't set parent items active when nav is nested

### ISSUE THREAD

**Issue by iangregory** [thednp/bootstrap.native#347]
Bootstrap docs: 

> "Scrollspy also works with nested .navs. If a nested .nav is .active, its parents will also be .active. "

https://getbootstrap.com/docs/4.4/components/scrollspy/#example-with-nested-nav

With bootstrap native, only the child item is being set active.

Original bootstrap code at https://github.com/twbs/bootstrap/blob/dfc1149597774bb3549c2cb42c73cf89b98c6615/js/src/scrollspy.js#L274

**Comment by thednp** [comment]
Will look into it asap.

**Comment by thednp** [comment]
@iangregory we good?

**Comment by iangregory** [comment]
> 
> 
> @iangregory we good?

I'm afraid not. Resulting behavious is unchanged. 

I've created a simple example to demonstrate:

Original bootstrap js: https://codepen.io/tulluk/pen/yLyQBGo

Bootstrap Native master: https://codepen.io/tulluk/pen/VwYVZqN

**Comment by thednp** [comment]
@iangregory 
did you test the latest master?

**Comment by iangregory** [comment]
Yep - I'll try and step through the code later to see if I can see what's going on.

**Comment by iangregory** [comment]
The issue seems to be that the code only considers the case where the navigation is `<ul>` based with `.nav-item` elements defined. It doesn't consider the nested `<nav>` tag case.

The appropriate parent nav item in the second case can be selected as follows (may not be the most elegant approach):

```
thisNav = item.closest('.nav'),
parentNav = thisNav && thisNav.parentElement.closest('.nav'),
navLink = parentNav && parentNav.querySelector('.nav-link'),
```

However, this is only a partial solution as `removeClass` is being called on the parent in `updateItems()` causing the `active` class to be removed some of the time

**Comment by thednp** [comment]
Will look into it as soon as I can.

**Comment by thednp** [comment]
I just tested the markup from original plugins, and I cannot confirm, it works with `<nav>` menus with lvl 1 child items. I think that's good enough depth. I don't think searching the entire page for deeper items. Makes sense?

**Comment by thednp** [comment]
Finally found a fix for this, will update asap.

**Comment by thednp** [comment]
@iangregory can you please confirm the fix? (latest master)

**Comment by iangregory** [comment]
Fix for this specific issue seems to work, thank you.

Note that when I tested, the `active` class would only be applied when the specific target element was at the scroll point, not when the scroll point was between the current target element and the next one. I applied the following diff to resolve this. I can't be certain whether this problem was related to this issue or was a side effect of another aspect of the page (e.g. a sticky header)

```
diff --git a/bootstrap-native-v4.min.js b/bootstrap-native-v4.min.js
index 84c4776..8061f27 100644
--- a/bootstrap-native-v4.min.js
+++ b/bootstrap-native-v4.min.js
@@ -1414,7 +1415,8 @@
                 targetRect = self.vars.isWindow && targetItem.getBoundingClientRect(),
                 isActive = hasClass(item, 'active') || false,
                 topEdge = (self.vars.isWindow ? targetRect.top + self.vars.scrollOffset : targetItem.offsetTop) - self.options.offset,
-                bottomEdge = self.vars.isWindow ? targetRect.bottom + self.vars.scrollOffset - self.options.offset : self.vars.targets[index + 1] ? self.vars.targets[index + 1].offsetTop - self.options.offset : element.scrollHeight,
+                nextItem = self.vars.targets[index + 1],
+                bottomEdge = nextItem ? nextItem.getBoundingClientRect().top + self.vars.scrollOffset - self.options.offset : element.scrollHeight,
                 inside = activeSibling || self.vars.scrollOffset >= topEdge && bottomEdge > self.vars.scrollOffset;

             if (!inside && !isActive || isActive && inside) {
```
