### ISSUE TITLE
Unable to use button text switching data-loading-text 

### ISSUE THREAD

**Issue by ankiteciitkgp** [thednp/bootstrap.native#349]
I referred to the url: (https://thednp.github.io/bootstrap.native/) to set my save button to loading on click. But the following is not working. 

My button HTML is defined as:
` <button class="button save btn-blue" data-loading-text="Loading..." type="button" onclick="setButtonLoading()">
     Save
</button>`

JS:
`function setButtonLoading() {
    let btn = document.querySelector(".button .save");
     Button(btn,'loading');
}`

There is no error thrown during execution and I am able to use modals successfully.

**Comment by thednp** [comment]
Bootstrap 4?

**Comment by ankiteciitkgp** [comment]
Yes. 
 ` <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.27/bootstrap-native-v4.min.js"></script>`

**Comment by thednp** [comment]
Original Bootstrap 4 devs discontinued this functionality, so did us.
