### ISSUE TITLE
Not work anything!

### ISSUE THREAD

**Issue by nim** [thednp/bootstrap.native#35]
Here is sample dropdown and modal dialogs. It's all not working. 
```
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.native/0.9.9/bootstrap-native.min.js" charset="utf-8"></script>

</head>
<body>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    Hello world
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Dropdown
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>
</body>
</html>
```

**Comment by IngwiePhoenix** [comment]
The first listing does not seem to properly define a HEAD section, nor a BODY section of the HTML document. Are you properly writing these?

You can use your browsers JavaScript debugger to see if it is showing any errors.

**Comment by nim** [comment]
>> he first listing does not seem to properly define a HEAD 
It's a comment problem. 

See console screen http://joxi.ru/bmoxWJbSMMjYP2

**Comment by IngwiePhoenix** [comment]
Does the output update when you try to trigger the modal or dropdown?

**Comment by nim** [comment]
If script definition paste before body close tag, all work. But dynamical generated dropdowns and other have some problems.
'''
<script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.native/0.9.9/bootstrap-native.min.js" charset="utf-8"></script>
'''

**Comment by IngwiePhoenix** [comment]
In order to use dynamically created Dropdowns, you have to instantiate a dropdown instance,c ontaining the element containing it. There should be a note about that usage either in the source or the docs.

If you look at the source for each component, pay attention to the bottom part. You can see its "initialization" there.

As you noticed, if the script is "after" the dropdown, itll work. That is, because the dropdown will be available in the DOM at the time the script is executed. If you want to attach the script to head, youll have to initialize the dropdown by hand, or copypaste the logic found at the bottom.

But really, you should put scripts at the end of the document, simply because the DOM is "almost" parsed, and ready for the most part. Thus, your site loads first, the scripts load secondarily, allowing a faster overall page load and user experience. That, is what I learned. :)

**Comment by nim** [comment]
There documentation how i can init "by hand". ? :)

**Comment by thednp** [comment]
You must link the `bootstrap.native.js` at the end of your `&lt;body>.

**Comment by nim** [comment]
No work see example

```
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <label>Worked</label>
    <div class="dropdown" >
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Dropdown
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>


    <label>Not Worked <button onclick="test()">Test</button></label>
    <div id="layout">
        
    </div>

    <script>
        
        function test()
        {
            var div = document.querySelector("#layout");

            div.innerHTML = '    <div class="dropdown" >' +
                '<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">' +
                'Dropdown' +
                '<span class="caret"></span>' +
                '</button>' +
                '<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">' +
                '<li><a href="#">Action</a></li>' +
                '<li><a href="#">Another action</a></li>' +
                '<li><a href="#">Something else here</a></li>' +
                '<li role="separator" class="divider"></li>' +
                '<li><a href="#">Separated link</a></li>' +
                '</ul></div>';
        }

    </script>


    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.native/0.9.9/bootstrap-native.min.js" charset="utf-8"></script>
</body>
</html>
```

**Comment by thednp** [comment]
I've edited your post, check it out.

**Comment by nim** [comment]
Dynamically created DropDown stil not work. It seems that your script can not be used for dynamically created controls. I want to understand whether it is possible to control init after creating? You should close a task that he is still not resolved. Putting the script in the bottom of the page is very bad style. And all this is the same problem

**Comment by thednp** [comment]
The script obviously doesn't handle dynamically created dropdowns, that's only working for Alert component. After you create the component, you need to initiate the js like so:

```javascript
var myDropdown = new Dropdown(dropdownElement);
```

**Comment by nim** [comment]
Problem solved thanks. This method of initialization is not very useful when dealing with systems of generation control like angular.

**Comment by thednp** [comment]
It's Javascript after all, there is nothing else to expect from it.

**Comment by nim** [comment]
It's true. Thanks again for your help.
