### ISSUE TITLE
Support data-target for bootstrap 4 tab component

### ISSUE THREAD

**Issue by pacahon** [thednp/bootstrap.native#350]
Hello! 
I found that bootstrap.native use different default behavior for tab component. 
Here is an example with bootstrap 4 https://jsfiddle.net/ucyt3deg/6/ (copied from https://getbootstrap.com/docs/4.4/components/navs/#javascript-behavior and slightly modified)
If you click on `Profile` tab link it will open third tab because `data-target=#contact` has precedence over `href=#profile` value. 
With `bootstrap.native` (2.0.27) I get an error (e.g. `'/projects/?type=practice' is not a valid selector`) since I use real link for `href` attribute and rely on `data-target` for tab behavior:

```
<a class="nav-link" data-toggle="tab" data-target="#practice" href="/projects/?type=practice" role="tab" aria-controls="practice" aria-selected="false">Practice</a>
```

Is this behavior is intentional? 
Thanks.

**Comment by thednp** [comment]
@pacahon the original plugins for Bootsrap4 have some new features we haven't decided to include or not, since the original library tends to become more and more bloated.

**Comment by pacahon** [comment]
Thx for the reply!
