### ISSUE TITLE
SVG Use tag href doesn't have slice method.

### ISSUE THREAD

**Issue by fleck** [thednp/bootstrap.native#351]
Reproduction:

We're using bootstrap native version: 2.0.27 with Bootstrap V4 

If you visit https://www.webstaurantstore.com/ and make your window less than 500px to trigger a mobile layout and click on the user icon to open a drop down and then click on the user icon to close the dropdown

<img width="277" alt="Untitled 2" src="https://user-images.githubusercontent.com/1706321/74254736-db011580-4cbe-11ea-9fbb-ed2209234f43.png">

 you'll see this error:

```
Uncaught TypeError: t.href.slice is not a function
    at MouseEvent.d (bootstrap-native.js:619)
    at HTMLLIElement.p (bootstrap-native.js:650)
    at HTMLLIElement.r (helpers.js:70)
```

This happens because the Use element has href, but it's not a normal href with a slice method it's actually an instance of https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString which doesn't have slice.

Here's the source that's causing the issue:

```javascript
function preventEmptyAnchor(anchor) {
    (anchor.href && anchor.href.slice(-1) === '#' || anchor.parentNode && anchor.parentNode.href 
      && anchor.parentNode.href.slice(-1) === '#') && this.preventDefault();    
  }
```

The fix would be something like 

```javascript
function preventEmptyAnchor(anchor) {
    (anchor.href && anchor.href.slice && anchor.href.slice(-1) === '#' || anchor.parentNode && anchor.parentNode.href && anchor.parentNode.href.slice
      && anchor.parentNode.href.slice(-1) === '#') && this.preventDefault();    
  }
```

Should I open a PR for the legacy version of bootstrap native that could be released as 2.0.28?

**Comment by thednp** [comment]
Thanks for the fix, however, we're going forward with Bootstrap 4, so your own fork should do the trick.
