### ISSUE TITLE
Need to configure ScrollSpy

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#353]
![image](https://user-images.githubusercontent.com/26907947/74648787-26746180-51a0-11ea-8a37-23574c974a22.png)

**Comment by cvaize** [comment]
on the iphone 5 there is no such problem

**Comment by thednp** [comment]
I don't actually know how to handle this but I'm not concerned about it.

**Comment by cvaize** [comment]
Well, I'll look for a solution on the weekend, this problem is not important

**Comment by thednp** [comment]
This issue can be skipped, I don't see any way to change the component to work "wrong".
