### ISSUE TITLE
Dropdown closes dropdown-menu without opening the requested menu

### ISSUE THREAD

**Issue by jrief** [thednp/bootstrap.native#354]
I'm currently trying to implement nested `dropdown-menu` items. For a better understanding of my problem, I prepared a [Codepen demo](https://codepen.io/jrief/pen/mdJEryQ). The idea is to have a long list of links, grouped and nested by name.

Problem: If you click onto `Studium > Weiterbildung` and later onto any of the items above, say `Studienangebot`, everything works as expected. If however you click in the opposite order, say `Studium > Studienangebot` and later onto `Weiterbildung`, the complete menu disappears. I would expect that the submenu for `Studienangebot` disappears while the items for `Weiterbildung` appear.

I tested this with version 2.0.27 and 3.0.0. They have the same behaviour. I copy&pasted version 3 into Codepen, because I can't load it from an external source, ie. https://raw.githubusercontent.com/thednp/bootstrap.native/master/dist/bootstrap-native.js.

After debugging the code, I found out that in the first (working) test, the first submenu is hidden (using `hide()`); afterwards the event handler `clickHandler()` is triggered, which opens the second submenu (using `show()`). In the second (dysfunctional) test, the first submenu is hidden; afterwards the parent menu is hidden as well, the "click" event is never propagated to the `clickHandler()`.

Any idea what I'm doing wrong, or is this a bug?

**Comment by thednp** [comment]
It might be a miss-handled case, I will do more nesting demos and hopefully provide a fix.

Will update the post asap.

**Comment by thednp** [comment]
@jrief I've updated the demo, the parent having multiple nested dropdown menus should have `data-persist="true"` but you'll see on my updated demo that isn't necessary. 

Perhaps you have some issue with the markup.
