### ISSUE TITLE
[SUGGESTION] Support delay for show and hide on popover

### ISSUE THREAD

**Issue by hoektoe** [thednp/bootstrap.native#355]
Improvement to delay for popover to support same functionality in jQuery Bootstrap 

```
Delay showing and hiding the popover (ms) - does not apply to manual trigger type

If a number is supplied, delay is applied to both hide/show

Object structure is: delay: { "show": 500, "hide": 100 }
```

**Comment by thednp** [comment]
Do you really need this? Do you really find this feature useful to you / your project?

FYI: we already have a 50ms delay on show, but setting an option for it, just to have it in line with the original plugins seems rather a waste to me TBH.

**Comment by cvaize** [comment]
@thednp I fully agree with you, and I also think that we should think about the extension architecture so that users can extend the functionality with plugins

**Comment by thednp** [comment]
Correction, the delay is 20ms not 50ms. Closing for now.
