### ISSUE TITLE
Customs Builds

### ISSUE THREAD

**Issue by madeInLagny** [thednp/bootstrap.native#359]
Hello, I want to build the dropdown module only.
I downloaded the code and ran `node build.js --bs_version 4 --minify --only dropdown` from root. I got the following error: `Cannot find module 'C:\Users\...\bootstrap.native-master\build.js`
What am I missing ?

**Comment by cvaize** [comment]
I would do it the other way, if I already have a configured webpack then I would just import the module `import Dropdown from './components/dropdown-native.js'` or if I want to build a bundle, I would comment out all the other modules and run the `npm run build` command. And used the build result from the dist folder
![image](https://user-images.githubusercontent.com/26907947/75134985-dd715f80-5701-11ea-97f7-0be466f3de8e.png)

**Comment by thednp** [comment]
@madeInLagny we replaced all build tools with rollup and the wiki is out of date.

Stick around, the current build tools will have a new update very soon.

**Comment by thednp** [comment]
@madeInLagny I have a new build script, currently working on it's logic to make it more flexible.

I'm now currently working on a way to include ONLY util functions that are used by requested components and not ALL by default.

**Comment by thednp** [comment]
@madeInLagny and @cvaize the new build script is now online, check it out.

I've updated the above guide accordingly and will link to it as a temporary guide for future queries.

Talk to you soon.

**Comment by picasticks** [comment]
@thednp, thanks for the updated build script and explanation, it works great for me.
