### ISSUE TITLE
Set default js import or require to bootstrap v4

### ISSUE THREAD

**Issue by laodemalfatih** [thednp/bootstrap.native#361]

**Comment by thednp** [comment]
Where is that change needed?

**Comment by laodemalfatih** [comment]
> Where is that change needed?

You can change this in the `main` field in the `package.json` file. I do not know whether this change is needed. But it is irrelevant if the default homepage of [http://thednp.github.io/bootstrap.native/](http://thednp.github.io/bootstrap.native/) uses version 4 while the default `js` import or require uses version 3.

**Comment by laodemalfatih** [comment]
I just think it's better to set the latest version as the default version. But if that's what you choose, it doesn't matter.
