### ISSUE TITLE
How to integrate Bootstrap-Native into VueJS correctly?

### ISSUE THREAD

**Issue by Moongazer** [thednp/bootstrap.native#362]
I spend hours trying to figure out how to get BSN to work in a VueJS environment. It doesn't matter how I include, import or require it, it seems that its never becomes initialized by itself. But BSN sits inside the Vue app (the debugger console prints the funktion on typing `app.$bootstrapNative.Collapse`)

I know there is a similar issue (#292) which solved it by manually initializing the needed Bootstrap elements. **But is this really the way-to-go?** If so, the Wiki or Manual should say so, but I couldn't find such information.

Here is my main script which is working, with this weird manual workaround from #292:
```
// import vue
import Vue from 'vue';

// import bootstrap.native
import BootstrapNative from 'bootstrap.native/dist/bootstrap-native-v4';
Object.defineProperty(Vue.prototype, '$bootstrapNative', { value: BootstrapNative });

window.app = new Vue({
    el: '#app',
    methods: {
        initBootstrapNative() {
            var collapseElements = document.querySelectorAll('[data-toggle="collapse"]');
            if(collapseElements.length) {
                collapseElements.forEach(function(element, index) {
                    new Vue.prototype.$bootstrapNative.Collapse(element);
                });
            }
        },
    },
    mounted() {
        this.initBootstrapNative();
    }
});
```

**Comment by thednp** [comment]
@Moongazer the docs and wikies are for the older version, the version we now have on the legacy branch.

However, the [dynamic content](https://github.com/thednp/bootstrap.native/wiki/How-to-use#dynamic-content) should be handled similarly.

**Comment by Moongazer** [comment]
Hey, thank you very much for the fast response! I've added the current master branch to my project (3.0.0) and tried out different things. Not sure if I do all this right, as I'm quite new to npm, building, ES, Vue and stuff.

This line makes BSN available inside my Vue app, but still nothing is initialized automatically
```
import BSN from '../../node_modules/bootstrap.native/src/index.js';
```

But if I added this line to my Vue app, at least the Collapse starts working (Dropdown not, unfortunately)
```
    mounted() {
        BSN.initCallback();
    }
```
Just because I've seen selective component imports from other packages like this, I was wondering if it might work: but it seems not. Non of these objects are available in my Vue app.
```
import {componentsInit, initCallback, Collapse} from '../../node_modules/bootstrap.native/src/index.js';
```
I find your suggestion for the custom build (custom-index.js) from your post quite complex, is there no other possibility, like other packages do it, e.g. bootstrap-vue with the above syntax of `import { componentX, componentY }` or so?

Sorry if I might can't be so helpful in giving you productive feedback, as like I said I'm just starting somewhat to understand slowly how all this works together. The last time I was programming with JavaScript was over ~10 years ago, since than it seems like everything had changed (to the better I guess, but its complex to get into it again especially with all the building and package-managing stuff which didn't existed back than as far as I know)^^

**Comment by thednp** [comment]
@Moongazer TBH I don't know, I'm new to rollup/ES6 myself, I happen to have some friends who helped me with this stuff, perhaps searching through other issues you might find the answers.

**Comment by thednp** [comment]
Forgot to mention: you can drop some `console.log()` inside and outside your scope, there might be a type error.

**Comment by thednp** [comment]
@Moongazer you got any success? I'm curious to know, I want to update the wiki, so please check back :)

**Comment by sookoll** [comment]
If You have installed via npm (from github master, not from registry, as there is no recent version deployed), then You can
```
import BSN from 'bootstrap.native'
```
or if You want selective components, then
```
import Modal from 'bootstrap.native/src/components/modal-native'
```
because index do not export components separately.

**Comment by thednp** [comment]
@sookoll did you update your BSN from npm latelly or checked the releases yet?

**Comment by Eroan** [comment]
Hi, same here, trying to use BSN (custom build with only 4 components) with vuejs in production.

Whjat is the best way to access BSN functions inside vuejs component ?

Thanks.

**Comment by thednp** [comment]
@Eroan what is your environment? You're doin ES6/ES7? If so, [try the above](#issuecomment-636797888) and let me know.

**Comment by Eroan** [comment]
No ES6/ES7 for me no, I load vuejs and my components this way : 

`<script src="/assets/js/vue.min.js" defer></script>
<script src="/assets/js/vue-components.js" defer></script>`

**Comment by thednp** [comment]
@Eroan I don't know what that is :D

**Comment by sookoll** [comment]
@Eroan this is just normal javascript. Download it and use it as You use any other library:
```
<script src="/assets/js/bootstrap-native.min.js" defer></script>
<script src="/assets/js/vue.min.js" defer></script>
<script src="/assets/js/vue-components.js" defer></script>
```
In vue-component.js there should be BSN in global scope (window.BSN). On there, You can use
```
const modal = new BSN.Modal()
```

**Comment by Eroan** [comment]
Thanks for your answer.
That's the way I did it with previous version yes, I hoped there would be ways to integrate it better in vuejs environment.

**Comment by thednp** [comment]
@Eroan yes there is, if you're doin ES6/ES7, then you can do this kind of stuff

https://github.com/thednp/bootstrap.native/wiki/How-to-use#es6es7-basic-example

**Comment by Moongazer** [comment]
> @Moongazer you got any success? I'm curious to know, I want to update the wiki, so please check back :)

Hey, sorry for my late reply. I've made an update to the current master (v3.0.2) and checked in my test-project:

```
import Vue from 'vue';
import BSN from 'bootstrap.native';

window.app = new Vue({
    el: '#app',
    data: {
        name: ''
    },
    mounted() {
      BSN.initCallback() // this manual call seems to be needed at least to get something to work
    },
});
```
Without the `initCallback()` call BSN is not initialized by itself (I don't know if that is even possible, but it would be great if just the import-statement is needed if someone wants to initialize all BSN features).

With `BSN.initCallback()` in place, the navbar collapse is working, but dropdown-menu is not. No errors are thrown. So it seems it is the same behavior like before (see my comment on 28th March).

**Comment by thednp** [comment]
You guys suck :)

@Moongazer you stop thinking jQuery.

```js
mounted() {
  Array.from(document.querySelectorAll('[data-toggle="collapse"]')).map(collapse=>new BSN.Collapse(collapse))
  Array.from(document.getElementsByClassName('dropdown')).map(dropmenu=>new BSN.Dropdown(dropmenu))
}
```

but my method is best, already does that, lots more efficient, and apply to all components

```js
 mounted() {
   BSN.initCallback() // this manual call seems to be needed at least to get something to work
 }
```

**Comment by Moongazer** [comment]
> ```js
> mounted() {
>   Array.from(document.querySelectorAll('[data-toggle="collapse"]')).map(collapse=>new BSN.Collapse(collapse))
>   Array.from(document.getElementsByClassName('dropdown')).map(dropmenu=>new BSN.Dropdown(dropmenu))
> }
> ```
This is a shorter code version of my initial post, thanks for that^^

> but my method is best, already does that, lots more efficient, and apply to all components
> ```js
>  mounted() {
>    BSN.initCallback()
>  }
> ```

Is this working for you? Like I said, in the current master collapsing works by initializing like this, but dropdown is not (events are not attached to `.dropdown-toggle` elements).

**Comment by thednp** [comment]
Nop, they are attached to `'[data-toggle="dropdown"]'` selector

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/87030394-f8e58e80-c1fa-11ea-9f5f-89aff42999d6.png)
![image](https://user-images.githubusercontent.com/26907947/87030429-04d15080-c1fb-11ea-94ad-114c3226e0c2.png)
![image](https://user-images.githubusercontent.com/26907947/87030518-2af6f080-c1fb-11ea-93fc-1a35f6a57053.png)
Как же долго вы разбираетесь в этом =) Вот так я использую bootstrap.native в nuxt

**Comment by cvaize** [comment]
И у меня нет проблем с переходами, и с разрушением Dropdown
