### ISSUE TITLE
Bootstrap native equivalent of twbs #22049 and #21079

### ISSUE THREAD

**Issue by TheCodeExorcist** [thednp/bootstrap.native#363]
Hi and thanks for this wonderful piece of code.
I am opening an issue because Bootstrap Native prevents the click event from being propagated when an input triggers a collapse. In other words, when a checkbox is used for toggling a collapse using the data api, the collapse will toggle but the checkbox state remains the same: it can't be checked or unchecked.
As said, bootstrap had this exact same behavior before the fix #22272, as the issues #22049 and #21079 mentions.
It seems a similar fix could quickly be applied in the native side of the force.

Best regards.

**Comment by thednp** [comment]
I think you could do some CSS/JS to make it work your way, we don't really rush to bloat our codebase.

**Comment by TheCodeExorcist** [comment]
> I think you could fork and do some CSS/JS to make it work your way, we don't really rush to bloat our codebase.

Thanks for your fast response.
I will fork your project to pull theses changes then. I just discovered an other undesired behavior that blocks an element from triggering multiple collapses at once, i think i will take the time to correct this too.
