### ISSUE TITLE
How to using tooltip Bootstrap.native in VueJs?

### ISSUE THREAD

**Issue by PeterUSA123** [thednp/bootstrap.native#366]
Hello everyone. I have issued with tooltip when using in VueJs project
I have a code as below
```
methods: {
        initialTooltip() {
        let elementsTooltip = document.querySelectorAll('[data-toggle=tooltip]');

        for (let i = 0; i < elementsTooltip.length; i++) {
          new Tooltip(elementsTooltip[i], {
            placement: 'bottom',
            animation: 'fade',
            delay: 150,
            container: this.$el
          })
        }
      },
      },
mounted() {
        this.initialTooltip();
    },
```
It always show tooltips with wrong coordinate (not show bottom of element hover). Has anyone encountered this case yet?

**Comment by thednp** [comment]
Are you using `dist/boostrap.native.js` or `src/index.js`?

**Comment by PeterUSA123** [comment]
Thank you for fast response

I using `dist/boostrap.native.js`

`<script src="{% static 'lib/bootstrap-native.js' %}" type="text/javascript"></script>`

And call Tooltip inside define() of requireJS

**Comment by thednp** [comment]
Then you should do 

```js
        for (let i = 0; i < elementsTooltip.length; i++) {
          new BSN.Tooltip(elementsTooltip[i], { // HERE
            placement: 'bottom',
            animation: 'fade',
            delay: 150,
            container: this.$el
          })
        }
```

**Comment by PeterUSA123** [comment]
I have tried to add BSN.Tooltip, but It not even showed the tooltip

**Comment by thednp** [comment]
You sure `bootstrap.native` is loaded in your page BEFORE your `vue.js` code?
