### ISSUE TITLE
Toggle collapse via Javascript, not using data api

### ISSUE THREAD

**Issue by Luddinus** [thednp/bootstrap.native#367]
Hi.

I have a "global" function where I have this:

```
$.toggle(collapseId, event) {

      var buttonEl = event.target
      var collapsableElement = document.getElementById(collapseId);
      collapse = new Collapse(buttonEl, { target: collapsableElement });
      collapse.toggle();
}
```

And some button in the html (using Alpinejs in this case)

```
<button @click="$.toggle('collapse-1, $event)"></button>

<div id="collapse-1" class="collapse">Show content</div>
```

I receive similar error: https://github.com/thednp/bootstrap.native/issues/337 (target is null in my case)

Is it possible to pass a target? Or not passing a target, just making new Collapse(collapseEl).toggle()

Great package btw.

**Comment by thednp** [comment]
It's impossible to think of a way to understand your case, I need a test site so I can see your markup, how you use the library, either via ES6 import or build src and where you link it.

**Comment by thednp** [comment]
Also do you get any error in console?

**Comment by Luddinus** [comment]
@thednp Sorry for the bad explanation.

In a nutshell, I would know if is it possible to toggle a collapse from javascript, without a button with data-toggle attributes.

Here an example: https://codepen.io/luddinus/pen/qBOrvYN

**Comment by thednp** [comment]
I understand. While I understand this kind of workaround made possible via jQuery, our original library didn't take into account the possibility of initializing components inside event handlers for various reasons, mainly performance, but BSN v3.0 coming soon to CDN solves some of these issues.

The BSN v2.0.27 components are harder to access, which is something going to change

```js
// BSN 2.0.27 and BSN 3.0
function toggleCollapse(collapseId) {
  BSN.initCallback() // this will initialize any and all components via DATA API if proper markup
  document.getElementById(collapseId).Collapse.toggle(); // access public methods
}

// BSN 3.0
function toggleCollapse(collapseId) {
  BSN.Collapse(document.getElementById(collapseId)).toggle();
}
```

I would suggest you play around with the MASTER version of the `dist/bootstrap.native.js` which is V4 and the only Bootstrap version going forward once V3.0 is done with fixing and documenting, currently working on.

**Comment by thednp** [comment]
The difficulty comes from the change of the build scripts, see what [v2.0.28](https://github.com/thednp/bootstrap.native/blob/legacy/dist/bootstrap-native.js#L2120-L2132) version was exporting to global `BSN`, compared to the new [v3.0](https://github.com/thednp/bootstrap.native/blob/legacy/dist/bootstrap-native.js#L2120-L2132) global exports.

**Comment by Luddinus** [comment]
> 
> 
> The difficulty comes from
> 
>     * BSN 3.0 will be Bootstrap 4 only
> 
>     * the change of the build scripts, see what [v2.0.28](https://github.com/thednp/bootstrap.native/blob/legacy/dist/bootstrap-native.js#L2120-L2132) version was exporting to global `BSN`, compared to the new [v3.0](https://github.com/thednp/bootstrap.native/blob/legacy/dist/bootstrap-native.js#L2120-L2132) global exports.
> 
> 
> Hopefully when we have it all done and documented, all these issues gonna get resolved.

Nice, BSN 3.0 will resolve the thing I was asking. Thanks!
