### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by tamb** [thednp/bootstrap.native#369]
The documentation on how to use this is really lacking

I recommend just starting with Modals.
Show the autowired way with the entire library and also show the modular way with the webpack loader.

If I want to contribute to the documentation,
Is there a specific file you want me to add this to?

The README?

**Comment by thednp** [comment]
The WIKIES need updates, I'm working on testing and the demo.

**Comment by thednp** [comment]
Please check updated demo and wikies.
Closing.
