### ISSUE TITLE
Are there any plans for v4?

### ISSUE THREAD

**Issue by dgt41** [thednp/bootstrap.native#37]

**Comment by thednp** [comment]
Hey there, yes there are some, but will leave v4 for later, when we have it stable I think, but as far as I know, it should work, I mean I see no reason why they won't work as is now.

Have you tried it?

**Comment by dgt41** [comment]
Hi and thanks for sharing your hard work with us! Honestly I haven't found some spare time to actually play with the alpha, but I'll try to test run it this week and I will come up with some actual results
