### ISSUE TITLE
is the latest master OK to use?

### ISSUE THREAD

**Issue by Mrodent** [thednp/bootstrap.native#371]
Thanks for this project.

Normally I'd just use the last release... but this dates from Aug 2019 and there are said to be 87 commits since then. It also appears that [the website](https://thednp.github.io/bootstrap.native/v4.html) is directing us to download the master.

Is there any reason to suppose the latest master may be less stable than 2.0.27?

Are you applying a thorough testing methodology on this project? Why have you not done a release since last August?

**Comment by thednp** [comment]
Well it's the latest and greatest, but it's V4 only and not yet documented properly, but as of JavaScript API, the old documentation stands, except that all components have an additional `.dispose()` method.

So go ahead, as soon as the documentation is ready, we're ready to push to CDN and NPM.

**Comment by Mrodent** [comment]
Thanks for the quick reply. You're going to see what a low-level user I am because, following the instructions, I just put the CDN script line in my HTML file (in the head)... and when it runs your two examples using "btn-group btn-group-toggle" and "alert alert-warning alert-dismissible fade show" fail to work... aren't we meant to include some css file too?

PS also: should I just be able to use this sort of thing out of the box:

<div class="container-fluid">
        <div class="row w-100">
            <div class="col-lg-6 col-md-12">
?
... I mean is this a "superset" of JQ Bootstrap, or do I have to learn new tricks entirely? 

Sorry for the low-level questions!

**Comment by thednp** [comment]
Whatever you think it's right, right now the CDN link for V4 currently is `.../bootstrap-native-v4.js`, the future link will be `.../bootstrap-native.js`, so have it your way.

**Comment by Mrodent** [comment]
... Thanks. I was wondering about the _CSS_ file to use though. Unless you say differently I'm going to assume we just use the latest available from JQ Bootstrap.

**Comment by thednp** [comment]
Bootstrap 4 CSS CDN of course.
