### ISSUE TITLE
Popover isn't properly initialized with empty data-content

### ISSUE THREAD

**Issue by nekromoff** [thednp/bootstrap.native#372]
Even if title (`data-title`) is present.

It works fine without `data-title` present.

**Comment by thednp** [comment]
Are your issues related to the master version please?

**Comment by nekromoff** [comment]
Yes, latest, downloaded from the website. Once a empty whitespace (i.e.
space) is added to the `data-content`, it works, displaying empty content.
However, empty `data-content` will cause it not to initialize on that
element.

**Comment by thednp** [comment]
Is there a reason not to use the default markup specified in our documentation? It's our design decision as a developer to make it work that way and only that way, regardless of the original plugin design.

When used properly the component will initialize your popovers on the fly, as an opt-in method for DATA API, OR you can use the other way around, with JavaScript, your values, via `options.template`.

**Comment by nekromoff** [comment]
OK, I didn't know that. I understood this was rewrite of Bootstrap plugins
into pure Javascript. If it was intentional design change, alright.

**Comment by nekromoff** [comment]
However, is there a reason, why empty data-content causes library to not
initialize properly. The attribute is there, but it is empty.

**Comment by thednp** [comment]
Why would you show a popover with only the title? Wouldn't it look funny?

![image](https://user-images.githubusercontent.com/6761246/82919200-3ea90900-9f65-11ea-8edb-08169e5af373.png)

**Comment by thednp** [comment]
Also keep in mind, some users reported a previous wrong scripting and we ended up with the behavior we have today, but hey, feel free to fork and make it your way. I just don't consider this to be a breaking behavior or critical issue, nor consider bloating the component in any way.

**Comment by nekromoff** [comment]
Yes, it would in current version (one space allows for it to initialize
properly, but have empty content). But if you get data that sometimes have
both title and content and sometimes just title, it;'s easier to just use
popover than switch based on data from popover to tooltip. Also, I would
expect this to be mentioned in the docs or rather (foolproof) to initialize
it properly with empty data-content as well.

**Comment by nekromoff** [comment]
Sure, but if you target Bootstrap switching to your code at some point, it
will require it to be really foolproof. Otherwise, great job!

**Comment by thednp** [comment]
We never advertised anywhere a perfect drop in replacement, it's impossible. 
Think: jQuery Sizzle <> no jQuery at all.
