### ISSUE TITLE
Custom build into file?

### ISSUE THREAD

**Issue by sookoll** [thednp/bootstrap.native#375]
As I read from documentation, custom build will put output into stdout. With `>outfile  2>&1` I can write this into file, but it will also add these lines top of the file:
```
Building unminified package for Native JavaScript for Bootstrap 4 v2.0.27 ..
Included modules: Button, Alert, Modal, Dropdown, Popover, Tab
Build complete!
```
So it is not valid javascript. I had to remove these with sed. There should be -o or similar option to specify what kind of output is needed and one of them should be write into file (I have no clue, why the hell anybody needs stdout for custom builded javascript anyway, so this is stupid decision from start)

**Comment by thednp** [comment]
Hey there, the documentation / wikies are terribly out of date, the master version has nothing to do with v2.0.27. Check out the `package.json` for the new build scripts.

**Comment by thednp** [comment]
Also #306 is very much worth a read.

**Comment by sookoll** [comment]
Ok, thanks. I install it with npm from master branch. It would be nice if You publish also some alpha/beta release meanwhile, so users can update it if there is new version.
