### ISSUE TITLE
Convert jquery to es6

### ISSUE THREAD

**Issue by scalarerp** [thednp/bootstrap.native#376]
this repository is AWESOME, I'm already using, but.....

i have a jquery app to convert, can someone help me please?

I know I'm abusing, but asking doesn't hurt

Simple example where i stop:
 // Add Children Class
  $(".navigation")
    .find("li")
    .has("ul")
    .addClass("has-sub");

Attached:>>>>

[app.txt](https://github.com/thednp/bootstrap.native/files/4697081/app.txt)

**Comment by thednp** [comment]
http://youmightnotneedjquery.com/
