### ISSUE TITLE
Collapse on toogle change class

### ISSUE THREAD

**Issue by scalarerp** [thednp/bootstrap.native#378]
How can add/remove the class "open" from a collapse li element on A click event??

My init call:    var myCollapseInit = new BSN.Collapse(liHasA);

```markup
<li class="nav-item has-sub open">
          <a class="" data-toggle="collapse" href="#sub1" aria-expanded="true" aria-controls="sub1" data-parent="#sub1">Nav2</a>          
          <ul id="sub1" class="collapse show" style="" aria-expanded="true">
            <li class=""><a href="#">bT1</a></li>
            <li class=""><a href="#">bT2</a></li>
            <li class=""><a href="#">bT3</a></li>
            <li class=""><a href="#">bT4</a></li>
          </ul>
</li>```

**Comment by thednp** [comment]
```js
if (liHasClass.classList.contains('THAT-CLASS')) {
  var myCollapseInit = new BSN.Collapse(liHasA);
}
```

Please check JavaScript guides.

**Comment by scalarerp** [comment]
Uau, so fast response.
Sorry, the code works very well, I init with success,
but I will change the class after then init.
in a>onclick event.
i use :
myCollapseInit.addEventListener('show.bs.collapse', function(event){

But not working.

**Comment by thednp** [comment]
The TARGET of the Collapse events is the targeted `.collapse` element, the `collapseInit` is the initialization object.

**Comment by scalarerp** [comment]
[code.txt](https://github.com/thednp/bootstrap.native/files/4711760/code.txt)
![2020-06-01_11-21-40](https://user-images.githubusercontent.com/17085986/83418620-4d2a7100-a3fa-11ea-8cd1-8b8543303961.png)

Ok, thats my code, i only will change the class "open" when click the anchor "A" .
In BSN has a code to insert this function?

**Comment by thednp** [comment]
This is easy JavaScript, you have various options on how to do it.

```js
document.getElementById('sub0').addEventListener('show.bs.collapse',function(){
  this.parentNode.classList.add('open')
})

document.getElementById('sub0').addEventListener('close.bs.collapse',function(){
  this.parentNode.classList.remove('open')
})
```

But I would do something different:

```js
document.querySelector('li a[data-toggle="collapse"]').addEventListener('click',function(){
  if (this.parentNode.classList.contains('open')) {
     this.parentNode.classList.remove('open')
  } else {
     this.parentNode.classList.add('open')
  }
})
```

If you have more questions like these, please ask on [stackoverflow](https://stackoverflow.com)

**Comment by scalarerp** [comment]
Thanks.
