### ISSUE TITLE
Can alerts be used with bootstrap.native?

### ISSUE THREAD

**Issue by Mrodent** [thednp/bootstrap.native#380]
Just seeking a bit of clarity on this. With my experiments alerts seem to display but I can't manage to get them to dismiss.

This is with me just substituting the bootstrap.native JS for the jQ bootstrap, when the latter works.

**Comment by thednp** [comment]
Markup?

**Comment by thednp** [comment]
@Mrodent you need to check the markup of our demos, the DATA API is opt-in to auto-initialize which means you want to initialize yourself via JavaScript, or perhaps your content is dynamically generated?

**Comment by Mrodent** [comment]
Thanks. Sorry about the delay. I'm gradually getting to grips with things. Most answers out there involve using JQ of course. I seem to have overcome yesterday's problem. Now trying to figure out how to do a programmatic Bootstrap confirmation box without any JQ. I'll check out your demos... I am supposing you mean [here](https://github.com/thednp/bootstrap.native/wiki/How-to-use)... ?

**Comment by thednp** [comment]
That's how to use the library in general, the demo provides plenty of guides on how to use the components.

**Comment by Mrodent** [comment]
OK, found that now. I tried this, as per example for alert:
`var myWarningAlertInit = new BSN.Alert('#myButtonAlert');`
Gives "TypeError: BSN.Alert is not a constructor"
This BSN object has 3 properties: `initCallback`, `supports` and `version`.  `supports` is an Array, the first element being another Array, the first element of which is string "Alert".
Could you explain what I do?

**Comment by thednp** [comment]
I don't know what file you're using, do you have your own custom build?

**Comment by Mrodent** [comment]
Custom build ... you mean of Bootstrap Native!? No, just your JS file:

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap.native@2.0.27/dist/bootstrap-native-v4.min.js"></script>


    On Tuesday, 9 June 2020, 07:50:30 BST, thednp <notifications@github.com> wrote:  
 
 


I don't know what file you're using, do you have your own custom build?

**Comment by thednp** [comment]
https://cdn.jsdelivr.net/npm/bootstrap.native@3.0.5/dist/bootstrap-native-v4.min.js%22%3E%3C/script
