### ISSUE TITLE
Bootstrap-5-alpha - without jQuery

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#382]
https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

I think they can offer the code of this package as a basis. Maybe they will support this project with a donation.

**Comment by thednp** [comment]
I know. The boys have some good looking code, but as to my concern my implementation is better for security.

I will continue to maintain my code, perhaps some changes as well in the future:
* remove the try catch wrapper, I don't like the error reporting when used
* remove dependency on `shorter-js` for on / off events as well as for classList and others I will consider non-trivial
* add new features that I think will benefit most of us

**Comment by thednp** [comment]
Sup, what's on your mind?

**Comment by cvaize** [comment]
I'm using Bootstrap Native and will wait for Bootstrap 5 to compare them. I agree with you.
