### ISSUE TITLE
document.body is null

### ISSUE THREAD

**Issue by yannski** [thednp/bootstrap.native#383]
I'm using the latest bootstrap.native via webpack like this:

```
import BSN from 'bootstrap.native/dist/bootstrap-native.js'
```

When my js bundle file is at the end of the body, it works as expected.

When ym js bundle file is in the head of the document, the following error is raised:

```
Uncaught TypeError: document.body is null
    js bootstrap-native.js:13
    js bootstrap-native.js:9
    js bootstrap-native.js:10
```

I can circumvent this error by adding the "defer" argument to the `<script>` tag but still...

**Comment by midzer** [comment]
When your script bundle is in `<head>` HTML parsing is stopped and script is executed instantly. `<body>` of document is not available at this point.
So better include BSN at end of `<body>` or `defer` it.

**Comment by ribizli** [comment]
this issue is adopted from `shorter-js`, like here https://github.com/thednp/shorter-js/blob/master/src/strings/animationEndEvent.js

**Comment by thednp** [comment]
@ribizli & @yannski can you guys do a quick check for me?

**Comment by ribizli** [comment]
@thednp what exactly?

**Comment by thednp** [comment]
Please update `shorter-js` to latest 0.1.4, build a new BSN bundle, test and report back again.

**Comment by thednp** [comment]
UPDATE: with `shorter-js` v0.1.4 works for me.

**Comment by ribizli** [comment]
@thednp I just see, that they use `head` now, this should work. 

Anyway, actually I had an SSR issue with `document` not defined at all, this is how I got to this issue. I use `sapper` / `svelte` with just importing the components (no data API), and SSR is not working. But this is a different topic, I guess.

Workaround: global import (in top of body, so data API init is not messing up anything) and using `new BSN.<component>` calls.

**Comment by thednp** [comment]
@ribizli you might also create custom builds for various other purposes, you have all the build tools you need.

**Comment by ribizli** [comment]
@thednp sure I could, but I'm afraid the lack of SSR support in `shorter-js` is not solved by that. Anyway, I can live with my workaround now, and this is not your issue, rather `shorter-js`'s.

**Comment by thednp** [comment]
`shorter-js` is my issue so I'm open to any suggestion.

**Comment by ribizli** [comment]
maybe abstract `document` into a const object? If on server, it will be a mock version. But I'm not an expert on this topic, sorry.

**Comment by thednp** [comment]
Perhaps we can route other users to that resource when they encounter a similar SSR related issue?

**Comment by thednp** [comment]
I believe we can close this as solved for now. For SSR or similar issue, we should open a new issue, find the best solution, hopefully.

**Comment by yannski** [comment]
@thednp thanks for your quick support!
