### ISSUE TITLE
emulateTransitionEnd not firing on Modal

### ISSUE THREAD

**Issue by jesserosenfield** [thednp/bootstrap.native#384]
I have a custom implementation. I call `modal.hide()` but the `hidden.bs.modal` event was not being dispatched. (the `hide.bs.modal` event WAS being correctly dispatched)

I tracked the issue down to:

Line 834

```
      if(modal.classList.contains('fade') && force !== 1) {
			emulateTransitionEnd(modal, triggerHide);
```

and then changed line 26 to 30 from:

```
    duration ? element.addEventListener( transitionEndEvent, function transitionEndWrapper(e){
                !called && handler(e), called = 1;
                element.removeEventListener( transitionEndEvent, transitionEndWrapper);
              })
             : setTimeout(function() { !called && handler(), called = 1; }, 17);
```

to

```

    if(duration) {
	    	setTimeout(function transitionEndWrapper(e){
                !called && handler(e), called = 1;
                element.removeEventListener( transitionEndEvent, transitionEndWrapper);
              }, duration + 10);
	 } else {
		 	setTimeout(function() {!called && handler(), called = 1; }, 17);
	 }
  }
```

I'm not sure if this will cause issues down the line but it solved my specific problem. Please let me know if you have any insights here. The issue is that the ` element.addEventListener( transitionEndEvent, function ...` was not being fired when the modal was hidden.

Thanks!

**Comment by thednp** [comment]
Thanks, will have a look.

**Comment by thednp** [comment]
I cannot confirm your issue. I edited the [first example](https://thednp.github.io/bootstrap.native/#modalExamples), the example features a console.log with all events, by adding a closing button

```markup
<button class="btn btn-danger" onclick="this.closest('.modal').modalTrigger.Modal.hide()">Close</button>
```

The `.hide()` call triggers the `hidden.bs.modal` event properly.

Now regarding the code sample you've suggested, it might fix some issues with some browsers that don't 100% support `transitionend`, for instance browsers that still require prefix like `-webkit-`, probably Apple Safari still does, which is something we, and also original Bootstrap plugins, don't "actively" support. Now all browsers are expected to work 100% with the CSS3 standard without prefixes or other hacks.

I'm curious to know more about your issue, perhaps making a simple fiddle or something, it might shed some light on some cases we never encountered yet, but anyways, let me know what's on your mind.

**Comment by thednp** [comment]
@jesserosenfield can you please confirm?

**Comment by jesserosenfield** [comment]
hey! thanks for the quick reply––

When I either `console.log` my modal instance OR `console.dir` the modal DOM element, there is no `modalTrigger` property under either of those objects.

I'll make a reduced test case now.

**Comment by thednp** [comment]
@janpanschab are we closing this yet?

**Comment by thednp** [comment]
Since I got no reply and I cannot confirm issue, I strongly suspect it must be a markup issue, I'm closing this down.
