### ISSUE TITLE
collapse data target do not allow multiple elements

### ISSUE THREAD

**Issue by riccardodivirgilio** [thednp/bootstrap.native#385]
data-target in bootstrap allows you to specify a full selector that is selecting multiple elements. however the current implementation is selecting only the first match because it's using `import queryElement from 'shorter-js/src/misc/queryElement.js` that is only selecting the first one.

**Comment by thednp** [comment]
That is correct and intended. Unlike the original jQuery plugin, we may not be interested in implementing such additions, since they can be implemented with a simple fork and we want to keep the library simple, fast and bloatware free. Sweet?

**Comment by riccardodivirgilio** [comment]
Sure but then people can't use this as a drop-in replacement for existing apps.

**Comment by thednp** [comment]
Correct again, was never intended. You have all the necessary tools in order to fork and build your own version with your own custom functionality.

**Comment by riccardodivirgilio** [comment]
Ok, can I ask why you think that selecting all elements instead of just the first is "bloatware"? isn't this what you expect when you provide a selector? it doesn't seem a very complicated functionality to implement... is it possible to contribute upstream or do I need to do my own fork?

thanks.

**Comment by thednp** [comment]
The thing is bloatware for some reasons:
* the original plugins got bloated with popper.js like jQuery wasn't enough, and later implemented with dropdown as well, I mean what is this? is this something essential to web development?
* so far only you and maybe another guy, some months ago, asked about this, it's not a popular request
* the functionality is implemented to look for parent accordion, it might have a major performance drawback we want to avoid
* the original Bootstrap version 1.0 was simple yet effective considering it was a jQuery extension/plugin
* the functionality you are looking for is indeed very easy to implement, but again not very popular, I never needed it and devs using BSN like it as is: light, simple, faster and more secure

Sweet?
