### ISSUE TITLE
Toast stuck on `.showing`

### ISSUE THREAD

**Issue by justlevine** [thednp/bootstrap.native#387]
For some reason, when trying to initialize my Toasts, they get stuck on `.showing`, and never actually appear. 

Calling  `elem.Toast.show()` or `elem.Toast.hide()` in the console doesn't do anything while the class is `.showing`. If I manually change `.showing` to `.show` and then run `elem.Toast.hide()`, the toast is hidden; however, if I try to run `elem.Toast.show()` again, it gets stuck at `.showing`.

Using BSN v3.0.10....

my js:
```javascript
import Toast from 'bootstrap.native/dist/components/toast-native.esm';

const toasts = document.querySelectorAll('.toast');
toasts.forEach((toast) => {
	const toastInit = new Toast(toast);
	toastInit.show();
});
```
my html:
```html
<aside class="notifications toast-container toast_area--bottom notifications--bottom" aria-live="polite" aria-atomic="true">
	
	<div class="toast toast--error" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false" data-delay="">
		<div class="toast-header">
			<strong class="toast-header__text mr-auto">Test</strong>
		</div>
	
		<div class="toast-body">
			<span class="toast-body__text">This is a test error</span>
			<a class="btn" src="#">Learn More</a>
		</div>

		<button type="button" class="toast-close close" data-dismiss="toast" aria-label="Close">
			<span aria-hidden="true">×</span>
		</button>

	</div>
</aside>
```

Suggestions?

( BSN Version 3.0.10 )

**Comment by thednp** [comment]
Missing or incomplete CSS? Our `emulateTransitionEnd` actually checks the `transitionDuration` before executing anything that should follow animations.

**Comment by justlevine** [comment]
@thednp 
That solved it - Thanks !

I had to add `transition` manually to `.toast`, because its not part of Bootstrap  default stylesheet](https://github.com/twbs/bootstrap/blob/v4.5.2/scss/_toasts.scss). Did it live elsewhere?

As such, might I suggest  using a `transitionFallback` when there is no `transitionDuration` defined - or at least making a note in the documentation that adding a `transition-duration`  to the css is necessary?

**Comment by thednp** [comment]
Check out the [emulateTransitionEnd](https://github.com/thednp/bootstrap.native/blob/master/dist/components/toast-native.js#L24-L31) it already has a fallback.

**Comment by justlevine** [comment]
Sorry I assumed... Then why is it stalling if `transition` or `transition-duration` isn't manually defined?...

I tested this on a webpack build of both bootstrap and bootstrap.native. Going to see if I can replicate the issue in codepen and report back.

**Comment by thednp** [comment]
Because the CSS is missing or incomplete. If you have set `transition-duration:500ms` and nothing else in regards to transition, this could be the issue, I'm going to investigate and fix the `emulateTransitionEnd` to also check for incomplete CSS.

**Comment by thednp** [comment]
I think this falls to you to make sure the CSS is in good order.

**Comment by justlevine** [comment]
>Because the CSS is missing or incomplete. 
That's what I'm not understanding. Where in bootstrap's css is this defined?

I'm using bootstraps build process, and `_toasts.scss` (and most everything else) is included. And as I wrote, I combed through the bootstrap source (and the compiled bundle), and I don't see `transition` or `transition-duration` defined on any of the relevant css classes.

**Comment by thednp** [comment]
BS4 has changed their designations, some transition and related stuff is moved to another scss file.

But before you do anything, make sure you have the `fade` class.

**Comment by thednp** [comment]
@justlevine we good?
