### ISSUE TITLE
'npm install' is pulling old version

### ISSUE THREAD

**Issue by danrichman** [thednp/bootstrap.native#39]
Looks like the latest release is 1.0.0. but `npm install bootstrap.native` seems to be pulling [0.9.7-npmfix.1](https://www.npmjs.com/package/bootstrap.native).

**Comment by IngwiePhoenix** [comment]
Looks like I slept in... (: Publishing now. Thanks for the info!

**Comment by thednp** [comment]
Thanks for the report and fix :)
