### ISSUE TITLE
is there a way to solve conflict between BSN and bootstrap.min.js?

### ISSUE THREAD

**Issue by kevinhq** [thednp/bootstrap.native#392]
Here's what we want to achieve: we're migrating from Bootstrap jquery  to BSN.

There are some codes migrated to BSN. But, the rest of them still needs Bootsrap.min.js

But, as we found out, including both of libraries seems resulted in conlfict.

For example, clicking the bootstrap dropdown menu doesn't work on first click or tap. You need to click/tap it twice to show it.

**Comment by thednp** [comment]
I don't think it's possible to solve this conflict. You either use one of the libraries (both use same selectors) or create a custom BSN build with different selectors (EG: `data-function="tab"` or `data-tip="popover"`).

**Comment by kevinhq** [comment]
yes, we have been working on workaround.  thank you for such great project to drop jquery from bootstrap.
