### ISSUE TITLE
[Questions] does bsn still require popper.js 

### ISSUE THREAD

**Issue by joe-oli** [thednp/bootstrap.native#393]
I have searched and looked in the readme at [(https://www.npmjs.com/package/bootstrap.native)] and I have read the wiki guide at [https://github.com/thednp/bootstrap.native/wiki/How-to-use] but it is still unclear to me whether:
1) can bsn also work with bs3.x  ?
2) For bs4.x, does bsn replace all 3 libraries ( jquery.js + popper.js + bootstrap.js; )? what functionalities are not implemented that would still require popper.js ?

**Comment by thednp** [comment]
> does bsn still require popper.js
It never did.

> can bsn also work with bs3.x
There is a legacy branch that does BS v3

**Comment by joe-oli** [comment]
@thednp thanks for the info. Closing the questions.

I meant "does bsn still require" in the sense that bs4.x requires popper when using certain components, so for a new user that just came across bsn today, is it still a requirement to use popper. Perhaps this should be mentioned somewhere in the guide / readme.

**Comment by thednp** [comment]
Probably this?

https://github.com/thednp/bootstrap.native/wiki/Acknowledgements
