### ISSUE TITLE
Does this work with Bootstrap5 alpha 3?

### ISSUE THREAD

**Issue by krushi123** [thednp/bootstrap.native#396]
Does this work with bootstrap5 alpha 3? If not - do you have a plan to release a version for bs5?

**Comment by thednp** [comment]
I didn't test, but It should work as is today, but why not give it a try and provide feedback, would make a better day don't you think?

**Comment by midzer** [comment]
I have a site using bs5 alpha1 running with bsn running perfectly

**Comment by thednp** [comment]
@krushi123 there is no beta3 as of today, but....

@krushi123 @midzer I've added a new V5 source and demo, I'm inviting you both to #400 for discussion, I'm closing this down.
