### ISSUE TITLE
Nested links not clickable in collapse toggle

### ISSUE THREAD

**Issue by markhalliwell** [thednp/bootstrap.native#398]
When using non-link elements as the toggle, any links inside it are ignored:

https://codepen.io/markhalliwell/pen/GRjpddJ

Fairly certain this is due to:
https://github.com/thednp/bootstrap.native/blob/eadd117a169648f5c57d8340e6318e668a753689/src/components/collapse-native.js#L76

Perhaps it should be using `e.currentTarget` here instead?

```js
 if (e && e.currentTarget.tagName === 'A' || element.tagName === 'A') {e.preventDefault();} 
```

That being said, I get that this is likely to deal with links being used as the toggle and doing ^ may not be feasible.

Would it instead be possible to check if the link also has the `data-toggle` attribute to verify that this link should be prevented?

```js
 if (e && e.target.tagName === 'A' && e.target.dataset.toggle === 'collapse' || element.tagName === 'A') {e.preventDefault();} 
```

**Comment by thednp** [comment]
Sup @markhalliwell 

Compared to the original plugin, I'm don't think we're doing anything different here, my only concern is that the toggle element (the holder of the `data-toggle="collapse"` attribute) **is** the `e.target` so child icons/spans elements will also trigger the handler function when clicked.

Using the `e.currentTarget` would apply when different handler behaviour is expected on each target, so not in our case.

On other note, I'm not sure `e.target.dataset.toggle === 'collapse'` would work, perhaps my needs never reached that test case yet.

Or perhaps I don't understand exactly what your issue is?

**Comment by markhalliwell** [comment]
> Are you trying to have links to other content inside the collapse toggle?

Yes. I have a use case where we need to provide an "info" link for the section (i.e. user can click it to learn more about the topic).

I've updated the codepen: https://codepen.io/markhalliwell/pen/GRjpddJ

> On other note, I'm not sure `e.target.dataset.toggle === 'collapse'` would work, perhaps my needs never reached that test case yet.

AFAICT, the only time a link should be prevented, is when it's the toggle. Checking for this data attribute seems like a valid way to achieve this.

**Comment by thednp** [comment]
In that case, you are better served with a fork to handle your specific case. Our component here behaves as explained above, any additional functionality is probably redundant to the rest of us.

**Comment by markhalliwell** [comment]
> any additional functionality is probably redundant to the rest of us

It's not "additional", it's a simple check to ensure that the element it's about to prevent is indeed the intended target (the toggle); not other elements that may be there.

**Comment by markhalliwell** [comment]
FTR, this was a known bug that ultimately was fixed in newer versions (although I cannot seem to find the original issue/PR):

Broken (twbs/bootstrap@3.4.1): https://codepen.io/markhalliwell/pen/vYXNzxw

Fixed (twbs/bootstrap@4.5.0): https://codepen.io/markhalliwell/pen/PoGPdbo

**Comment by thednp** [comment]
Yes it's not "additional", in fact it's changing our intended behavior with icons/span child elements.

There is a way around any "limitation", in this case my suggestion is to use an absolute position for your other links to be displayed above the layer of your card header and included in the `<div class="card">` element.

```html
  <div class="card position-relative">
    <div class="card-header" id="headingOne">
      <h4>
        <div role="button" data-toggle="collapse" data-parent="#myAccordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </div>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse show" aria-labelledby="headingOne">
      <div class="card-body">
        Collapse CONTENT 1
      </div>
    </div>
      <span class="position-absolute top-2 right-2"><small>This is not:</small> <a href='http://google.com' target='_blank'>ℹ️</a></span>
  </div>
```

```css
.top-2 {top:1rem}
.right-2 {right:1rem}
```

How about that?

**Comment by markhalliwell** [comment]
> How about that? This should work in any situation.

No. Because the design/style requires the icon/link to be just after the header text. This means the element must be inside the header to account for the dynamic title lengths (and no, I'm not going to use JS to determine where to "absolute position" this element either).

> in fact it's changing our intended behavior with icons/span child elements

No. It's deviating from the upstream intended behavior, see https://github.com/thednp/bootstrap.native/issues/398#issuecomment-737493055

This was working just fine with the normal twbs/bootstrap collapse plugin prior to switching to this project (which was only in an effort to eliminate the need for jQuery).

**Comment by thednp** [comment]
Frankly I don't like the BS 4.5.0 implementation of the click handler and I don't think we need any change to ours, you can either use my solution, (at least try it) or fork the component to do your thing. This component is meant to be light, easy to maintain and bloatware free.

**Comment by markhalliwell** [comment]
> Frankly I don't like the BS 4.5.0 implementation

Wow... so this project is based on your specific personal preferences, not what people are expect (a native 1:1 replacement)? If this is any indication on how you treat this project, I can only imagine what other "gotchas" people will run into like this.

> you can either use my solution, (at least try it)

I already did (before opening this issue) and it doesn't work (as I mentioned above) because the icon needs to be next to the header text. Absolute positioning isn't always the right solution, especially if used in a "hack" like manner as this.

> fork the component to do your thing

For a one line change to fix an oversight? Mistakes happen, I get it, but to outright refuse to fix something just because you don't use it that way doesn't justify the response I've received here. I get that keeping parity is a difficult task, but keeping FOSS mentality isn't. Requiring user to "fork" something just because they were intentionally stonewalled in an issue is rather petty.

> This component is meant to be light, easy to maintain and bloatware free.

Again, literally just a single line change to validate that the link that was clicked was in fact the toggle. Not sure how that qualifies as "bloat".

---

I'm sorry if I said anything to make you so defensive. That wasn't my intent. My intent was to bring light to a blatant issue/disparity between this project and the upstream plugin this intended to replace. I get that you might not want to do this, but perhaps you should put a bigger disclaimer on your project/website that this project is not a true "replacement" to Bootstrap's JS components then.

**Comment by thednp** [comment]
https://github.com/thednp/bootstrap.native/wiki/Acknowledgements

**Comment by markhalliwell** [comment]
Not the point

**Comment by thednp** [comment]
@markhalliwell after a later read, I'm considering an improvement on this for the future BSN version for Bootstrap 5. Sometime next week, most probably, stay tuned.

**Comment by markhalliwell** [comment]
Not trying to sound mean, but too little too late.

The client reviewed this issue (after I explained to them why it couldn't be fixed) and determined this library couldn't be safely relied upon.

The lack of expected behavior parity and complete dismissal of the issue in the form of personal preference wasn't worth the hassle.

Good luck.
