### ISSUE TITLE
No response of the modal window to a click on a static background (data-bs-backdrop="static", data-backdrop="static").

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#402]
When you click on the static background, the modal window pulsates slightly. This is achieved by assigning the `model-static` class and the `overflow-y: hidden;` style.  

https://getbootstrap.com/docs/5.0/components/modal/#static-backdrop

In my opinion `overflow-y: hidden;` it is necessary before the animation, so that the animation does not cause the scroll bar when the modal window is enlarged, this can happen if the content almost completely fills the window.

![image](https://user-images.githubusercontent.com/26907947/106234189-18d1b380-621a-11eb-866f-a14ff36c619f.png)

**Comment by thednp** [comment]
I will update the Modal asap. Thanks
