### ISSUE TITLE
When reinitializing ScrollSpy, the right navigation bar broke.

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#403]
I'm sure this isn't a problem, as the ScrollSpy examples are perfectly reinitialized and work fine. Nevertheless, I report it. If you decide that this is not a problem, close the issue. 
```javascript
console.log(window.BSN);
console.log(window.BSNI);

let elements = document.querySelectorAll(window.BSNI.ScrollSpy.selector);
console.log(elements)
for (let i = 0; i < elements.length; i++) {
    let element = elements[i];
    new window.BSN.ScrollSpy(element);
    new window.BSN.ScrollSpy(element);
    new window.BSN.ScrollSpy(element);
}
```
![image](https://user-images.githubusercontent.com/26907947/107473036-d2714280-6b91-11eb-8474-c4166221bd09.png)

**Comment by thednp** [comment]
I cannot confirm this issue, all examples in the page initialize, dispose or re-initialize flawlessly. Perhaps we missed something I can't figure out right now. I'm thinking it could be a typo somewhere, but I will leave this open to have a look.

**Comment by thednp** [comment]
Yes, we have a problem with event handler toggles on/off. I'm looking into something like TinyEmitter, what do you think?

**Comment by cvaize** [comment]
Sorry, I can't help you right now, work...

**Comment by thednp** [comment]
I've reverted to our previous version, this won't be a problem anymore.

**Comment by cvaize** [comment]
I confirm that the problem is solved
