### ISSUE TITLE
Please update the library version in npm

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#406]
![image](https://user-images.githubusercontent.com/26907947/111770701-8e7a0780-88cc-11eb-8aca-21226af444f2.png)

**Comment by thednp** [comment]
@cvaize howzit goin? 

I want to push a new version with ESLint valid codebase and some ESLint tools. I see no other reason otherwise.

**Comment by thednp** [comment]
@cvaize latet build is now on npm, please have a look.

Thanks

**Comment by thednp** [comment]
Well, I've pushed latest code to NPM and clouds, I think we can close this.
