### ISSUE TITLE
Alert is closed only if contains "show" class

### ISSUE THREAD

**Issue by garak** [thednp/bootstrap.native#407]
See https://github.com/thednp/bootstrap.native/blob/master/src/components/alert-native.js#L49

I don't understand why there's a check for a "show" class.
Moreover, I can't find a mention for such class in [docs](https://thednp.github.io/bootstrap.native/)

**Comment by thednp** [comment]
Some checks have to be in place to prevent triggering events when not make sense.

**Comment by garak** [comment]
I see, but don't you think that such additions should be highlighted I documentation?

**Comment by thednp** [comment]
The `.close()` method should only work when alert is present in the DOM and visible to the user. Period.

This thing does exactly the same.
https://github.com/twbs/bootstrap/blob/main/js/src/alert.js#L58-L60

**Comment by garak** [comment]
> The `.close()` method should only work when alert is present in the DOM and visible to the user. Period.

The point is that alert can be visible to the user even when "show" class is **not** present.

> This thing does exactly the same.
> https://github.com/twbs/bootstrap/blob/main/js/src/alert.js#L58-L60

Indeed, Boostrap does not require any "show" class to close an alert.
This issue is just the result of struggling with an alert not closing until I realized this strange requirement.

**Comment by thednp** [comment]
> The point is that alert can be visible to the user even when "show" class is not present.

That is indeed not bootstrap.

**Comment by garak** [comment]
> That is indeed not bootstrap.

Well, it's you that mentioned "this thing does exactly the same" (by linking bootstrap source)
Anyway, my question stands: don't you think that documentation should report such requirement?

**Comment by thednp** [comment]
No I mean THIS IS NOT BOOTSTRAP

> The point is that alert can be visible to the user even when "show" class is not present.

**Comment by thednp** [comment]
The original bootstrap component only considers that checking presence of the element in the DOM is enough to prevent execution. My original concern was to prevent the `transitionend` event from never executing because there was no "show" class to remove and enable the transition. I think this behavior is more healthy for production websites.

Meanwhile I got busy with other stuff, don't afford the time to check every line of JS to write docs, so take it as is.

**Comment by garak** [comment]
Well. I see that you care enough to explain that differences exist with Boostrap, and that "for each component these details are fully explained" (written in the FAQs).
I guess that this is a difference it's worth mentioning, for all newcomers.

**Comment by thednp** [comment]
I [said clearly](https://github.com/thednp/bootstrap.native/wiki/Acknowledgements) "it's not a perfect drop-in replacement", should I make it bold?

Also [this from the FAQs](https://github.com/thednp/bootstrap.native/wiki/FAQs#does-this-library-work-as-a-drop-in-replacement-for-the-original-jquery-plugins).

Very loud and clear.

**Comment by garak** [comment]
> I [said clearly](https://github.com/thednp/bootstrap.native/wiki/Acknowledgements) "it's not a perfect drop-in replacement", should I make it bold?

I never questioned it.
My only concern is how easy is supposed to be such replacement process. 
If you agree that this case is worth to be mentioned in docs, I can propose a PR.

**Comment by thednp** [comment]
Might worth a try, why not.
