### ISSUE TITLE
Firefox > open Drowndown > leaving Tab: Uncaught TypeError: eventTarget.getAttribute is not a function 

### ISSUE THREAD

**Issue by ronald** [thednp/bootstrap.native#409]
```javascript
new Dropdown('#dropdown')
```
works as expected. But if you do this:
- leave Firefox to other app / change tab
- return to first tab

Console shows following error:
>  Uncaught TypeError: eventTarget.getAttribute is not a function
>     dismissHandler dropdown-native.esm.js:67
>     toggleDismiss dropdown-native.esm.js:62
>     show dropdown-native.esm.js:126
>     setTimeout handler*Dropdown/self.show dropdown-native.esm.js:124
>     clickHandler dropdown-native.esm.js:82
>     Dropdown dropdown-native.esm.js:180

Firefox triggers "focus" on document and calls dismissHandler. DismissHandler calls non existent getAttribute on document.

bootstrap.native 3.0.14f  
Firefox 86.0.1 (64-Bit)

**Comment by thednp** [comment]
Thanks for the find.
