### ISSUE TITLE
Collapsible navbar seems not supported

### ISSUE THREAD

**Issue by nadjibkrim** [thednp/bootstrap.native#410]
Hi,
it seems the Bootstrap navbar object is not supported in Bootstrap.Native.
Any call to hide(), show() or toggle() produces no result.

    this.navbar = document.getElementById('navbarCollapsible');

    if (this.navbar) {
      this.bsCollapse = new Collapse(this.navbar);
      this.bsCollapse.hide(); // Navbar stays expanded.
    }

Is there a workaround?

Thanks and best regards.

**Comment by thednp** [comment]
Yea, probably you need to check the markup make sure it's alright.

**Comment by nadjibkrim** [comment]
A working example on a navbar would be greatly appreciated.
Here is what I'm trying to do: 
```
<nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{header}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapsible"
      aria-controls="navbarCollapsible" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapsible">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" routerLink="register" routerLinkActive="active">Registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Appointment</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Offices</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      </form>
    </div>
  </div>
</nav>
```
```
import { Component, HostListener, OnInit } from '@angular/core';
import Collapse from 'bootstrap.native/dist/components/collapse-native.esm.js';
import BSN from 'bootstrap.native';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  header: string;

  private navbar: HTMLElement | null = null;
  private bsCollapse: Collapse | undefined;

  constructor() {
    this.header = 'My Angular App';
  }

  ngOnInit(): void {
    this.navbar = document.getElementById('navbarCollapsible');

    if (this.navbar) {
      this.bsCollapse = new BSN.Collapse(this.navbar);
    }

    const navLinks = document.querySelectorAll('.nav-item, .navbar-brand');

    navLinks.forEach((l) => {
      l.addEventListener('click', (event) => {
        if (this.bsCollapse) {
          this.bsCollapse.hide();
        }
      });
    });
  }
}

```

**Comment by thednp** [comment]
BS 5 https://getbootstrap.com/docs/5.0/examples/carousel/
BS4.x https://getbootstrap.com/docs/4.0/examples/carousel/

**Comment by nadjibkrim** [comment]
Thank you for the links. I'm already 24/7 on Bootstrap website.
The example I sent you is almost straight from Bootstrap website. The markup is alright as per Bootstrap documentation.
It is working as expected and I could do what I want with the Bootstrap lib but its @types definition still references JQuery.
I just wanted to use bootstrap-native to avoid having to keep JQuery.

So, if I understand well, you suggest to initialize on the button which is triggering the navbar toggle. 
I'll give it a try (I'm not sure I didn't already) and keep you poster, if you're interested at all.

Thanks.

PS: You don't have to be rude.

**Comment by nadjibkrim** [comment]
Just a heads up.
It works now by targeting the toggle button. But I had to replace **data-bs-toggle** and **data-bs-target** with **data-toggle** and **data-target**.
I found it out by debugging bootstrap-native code.
While the documentation here https://thednp.github.io/bootstrap.native/v5.html#componentCollapse says **data-bs-target**.
Did I miss something?

**Comment by thednp** [comment]
Yes, we have 2 separate distribution bundles:
* V4 - bootstrap-native.js
* V5 - bootstrap-native-v5.js

**Comment by thednp** [comment]
And with that I think we're ok.

**Comment by nadjibkrim** [comment]
Yes. I think so.
Thanks for your help and for this nice library and sorry for the confusion.

**Comment by thednp** [comment]
I would recomend checkin this out

**Comment by thednp** [comment]
@nadjibkrim FYI, since I remembered about this, I'm here to let you know that we're changing how out components get initialized via both DATA API and JavaScript, to be more inline with the original Bootstrap v5, so [read this please](https://github.com/thednp/bootstrap.native/issues/400), updated with every change.

So with that said, please keep in mind that BSN V5 will initialize **Collapse** on the `<div class="collapse">` and not the `<button data-toggle="collapse">`.

**Comment by nadjibkrim** [comment]
Thanks for letting me know. This is a great news.
Please tell me, how can I use BSN 5? Is there a switch somewhere to tell the module to use v5?
Currently, v4 is selected by default.

Thanks.

**Comment by thednp** [comment]
You can import the components directly, assuming you are also developing ES6+ apps.

`import Collapse from 'bootstrap.native/src/components-v5/collapse-native.js';`

This will all change when we have original Bootstrap 5 STABLE release. You will be able to 

`import Collapse from 'bootstrap.native/dist/components/collapse-native.esm.js';` which will be V5
