### ISSUE TITLE
V5 Accordion doesn't open

### ISSUE THREAD

**Issue by londenisland** [thednp/bootstrap.native#411]
@thednp I know you are very eager to refer to the documentation but once the documentation doesn't work it requires updates.

This issue if pretty similiar to https://github.com/thednp/bootstrap.native/issues/410, but this time it's about the `accordion`.

This code is literally taken from your documentation of BS `5`, which doesn't work.

https://jsfiddle.net/8wvjm09x/

**Comment by thednp** [comment]
Easy fix, you're using the module as inline JavaScript, will never work.

[Here](https://jsfiddle.net/u43o0m8L/)'s the same example with the right code from `dist/bootstrap-native.min.js`.

Have fun :)

**Comment by londenisland** [comment]
Well, turns out I was wrong. Everything works very well. I will do more test at V5 and I will let you know when I ran into problems.
Thanks for this great plugin, time to ditch old jquery and make Google satisfied.
