### ISSUE TITLE
All components are included when only requesting one

### ISSUE THREAD

**Issue by ograr** [thednp/bootstrap.native#414]
app.js:
```js
import '@babel/polyfill';
import Dropdown from 'bootstrap.native';  // eslint-disable-line no-unused-vars
```

When run through webpack with
```js
mix.js('resources/assets/scripts/app.js', 'scripts');
```

the resulting app.js contains all components and not only Dropdown (i.e. Alert, Button, Carousel and so on).

Am I doing something wrong?

**Comment by thednp** [comment]
Try

```js
import Dropdown from 'bootstrap.native/src/dropdown-native.js';
```

**Comment by ograr** [comment]
Perfect, thank you!

This did the trick:
```js
import Dropdown from 'bootstrap.native/src/components/dropdown-native.js';  // eslint-disable-line no-unused-vars
```

That adds 409 KB (unminified) to the JS though. X)

**Comment by ograr** [comment]
I think I'll go with this instead:

```js
import Dropdown from 'bootstrap/js/src/dropdown.js';  // eslint-disable-line no-unused-vars
```

Anyways, thanks for all your hard work on this package and for the kind help!
