### ISSUE TITLE
bootstrap v5 tab issues

### ISSUE THREAD

**Issue by newyhj** [thednp/bootstrap.native#418]
bootstrap v5,when i use  nav tab,ex:
[https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior](url)
i use bootstrap native,only support a tags.not support button,How to solve?

**Comment by thednp** [comment]
A proper markup will do. In our V3 version demo (deprecated and removed from github pages), we used to have buttons (`<ul class="nav nav-pills">`) as example.

Feel free to try and come back if you have any problem.
