### ISSUE TITLE
Release with tab dropdown fix

### ISSUE THREAD

**Issue by neothemachine** [thednp/bootstrap.native#42]
I just stumbled over the issue fixed in https://github.com/thednp/bootstrap.native/commit/35622a0ff3a0ea161f89c2a6921126256addb3b6 and I cannot use the library because of that. Is it possible to do a hot fix release 1.0.1? Would appreciate that a lot. Thanks! :)

**Comment by IngwiePhoenix** [comment]
@thednp Did you patch package.json yet? if so ill do a npm publish. ^^

**Comment by thednp** [comment]
@IngwiePhoenix does it use the lib files or the dist files? I don't quite remember. If so, I'll do an update to the json file for patch 1.0.1.

**Comment by IngwiePhoenix** [comment]
@thednp I use the libfiles in the require-calls.

**Comment by thednp** [comment]
Alright, you can push the 1.0.1 I think.

**Comment by IngwiePhoenix** [comment]
Done.

**Comment by neothemachine** [comment]
Thanks guys, that was quick! Don't forget the git tag.

**Comment by thednp** [comment]
@neothemachine 
What do you men with git tag? Are you referring to 1.0.1 release?

**Comment by neothemachine** [comment]
Yep, creating a 1.0.1 tag in git.

**Comment by thednp** [comment]
@neothemachine 
Read here https://github.com/thednp/bootstrap.native/releases/tag/1.0.1

also the 1.0.1 CDN will be available within a few hours.
