### ISSUE TITLE
Modal option backdrop = false displays dismissible backdrop.

### ISSUE THREAD

**Issue by KenHaggerty** [thednp/bootstrap.native#423]
Bootstrap v5.1.0 and BSN v4.0.5. The backdrop should not be displayed when data-bs-backdrop="false" is applied. No backdrop is displayed when implementing Bootstrap's bootstrap.bundle.js .

**Comment by thednp** [comment]
I"m looking at it, thanks for reporting.

**Comment by thednp** [comment]
@KenHaggerty please give the master a test and let me know how it works.

**Comment by KenHaggerty** [comment]
Latest master works as expected for the backdrop and keyboard options. Good job. My issue is resolved with latest master. Thank you for the bootstrap,native library and all of your hard work!

**Comment by thednp** [comment]
Alright, thanks for the report and test. Let's publish this into the clouds then.

Cheers :)
