### ISSUE TITLE
Remove bootstrap.native-loader mention from the FAQ

### ISSUE THREAD

**Issue by netsensei** [thednp/bootstrap.native#424]
The FAQ still refers to [bootstrap.native-loader](https://github.com/fleck/bootstrap.native-loader) implying that you need this loader for BSN to work with Webpack.

However, fleck/bootstrap.native-loader#23 states that the loader isn't necessary anymore since BSN is fully ES compliant, nor that that module is actively maintained. Moreover, bootstrap.native-loader will install BSN 2 as a peer dependency causing version conflicts.

Would it be possible to remove this from the FAQ as it leads to confusion?

**Comment by thednp** [comment]
Sure, and thanks for reporting.

**Comment by netsensei** [comment]
Thanks! :-)
