### ISSUE TITLE
Setting popover content or template without using innerHTML

### ISSUE THREAD

**Issue by jcorporation** [thednp/bootstrap.native#426]
Is it an option for you to refactor the popover component to not use innerHTML?

Background is: I would implement a Trusted Types csp policy in my bootstrap.native based project without exceptions or sanitize library.

**Comment by thednp** [comment]
Yes we know that, but I mean what for? The reason I ask is because once initialized, Popper/Tooltip instances, their contents are pretty much static, they won't handle dynamic content.

**Comment by thednp** [comment]
After checking the [append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append) in detail, I believe this one might be suitable in most situations.

**Comment by thednp** [comment]
@jcorporation please test latest master and check how new code (src/util/setHtml.js) works.

**Comment by jcorporation** [comment]
Code for setHtml looks good, but you use innerHTML to set the template. In my understanding the template.innerHTML could be replaced with setHtml also?

**Comment by thednp** [comment]
Ah that's a good idea, lemme do some tests.

**Comment by jcorporation** [comment]
I have now checked with enabled trusted types csp policy:

1. using your template causes a trusted types error: DOMParser is not allowed. That is no issue - we can define a own template as a dom element.

2. using a self defined template as dom element causes a trusted types error: innerHTML is not allowed
I had to change the following:
```
//    setHtml(popover, htmlMarkup.innerHTML);
    setHtml(popover, htmlMarkup);
```

3. I created the title with document.createTextNode to not use a string
I had to change the following:
```
//if (content instanceof Element) { 
if (content instanceof Object) { 
```
instanceof detects the textNode not as an element.

**Comment by thednp** [comment]
```
//    setHtml(popover, htmlMarkup.innerHTML);
    setHtml(popover, htmlMarkup);
```
This would create a popover inside a popover, which produces the positioning issue you're talking about. There has to be a way to be able to use `innerHTML` in this case.

**Comment by jcorporation** [comment]
We could iterate through the childNodes of htmlMarkup and add it one by one?

**Comment by thednp** [comment]
That would not work with the following: `"Some <span>text</span> element."`, it will only add the span element.

**Comment by jcorporation** [comment]
Right, other idea:
- in line 101 you create the popover element with document.createElement
- if the template is a dom element we can assign it or clone it and we do not need copy the content from the template in the new created element

**Comment by thednp** [comment]
The `cloneNode(true)` is very interesting, perhaps best in this case. However, the `if (content instanceof Object)` condition won't be good enough, it should throw an error when content is a JavaScript object (EG `{a: 1, b: 2}`).

Let me test the `cloneNode(true)` first.

**Comment by thednp** [comment]
@jcorporation please test latest master and let me know how it works.

**Comment by jcorporation** [comment]
It works now like a charm with enabled trusted types policy. Thanks for this great piece of software!
