### ISSUE TITLE
IE11 broken

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#428]
Hi,

using latest polyfill I realized there is an issue with Number.isNaN() on IE11. We should include https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#polyfill to fix this.

Would be happy to open a PR for this.

Have a nice week
midzer

**Comment by thednp** [comment]
To make it easy for you, check the [polyfill setup](https://github.com/thednp/bootstrap.native/blob/master/src/util/polyfill.js) and the [sources here](https://github.com/thednp/minifill/tree/master/src).

Have fun.

**Comment by midzer** [comment]
https://github.com/thednp/minifill/blob/master/src/Number.isNaN.js is already there, so we just have to import it. Great!
