### ISSUE TITLE
Modal init from javascript

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#43]
Is there a way to launch the modals dynamically (not with data attributes) (eg: $('.modal').modal();) but in Vanilla JS? I couldn't find anything about it.

**Comment by IngwiePhoenix** [comment]
Sure can o.o

https://github.com/thednp/bootstrap.native/blob/master/lib/modal-native.js#L24

**Comment by warreb1** [comment]
I'm not a rockstar in Vanilla JS yet. :( Care to show me how to launch it exactly?

**Comment by thednp** [comment]
Actually it's this way
https://github.com/thednp/bootstrap.native/blob/master/lib/modal-native.js#L287
