### ISSUE TITLE
BSN 4.1 Feedback Required

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#430]
I [recently updated the BSN code base](https://github.com/thednp/bootstrap.native/commit/54af63b6768c70c31e843e5f498c8be187f061be) (click the link for a complete changelog) everybody is invited to test and provide feedback. I'm mostly interested to know any issue with Safari/Chrome on iOS, as I've tested everything on WIndows already.

@fmasa @midzer @cvaize @webstaurantstore @dtognazzini @PaulBGD and anyone else

Thank you and have a good one!

**Comment by lekoala** [comment]
dropdown positioning has improved dramatically! i had many issues with dropdowns in a sidebar, with this new version, it's more consistent to what i get with regular bootstrap 5 and popper.

**Comment by jcorporation** [comment]
I upgraded to current master to help testing and I get a javascript error on loading:
` Uncaught DOMException: Document.querySelector: '#' is not a valid selector`

Error  is in the last line of this function:
```
  function querySelector(selector, parent) {
    const selectorIsString = typeof selector === 'string';
    const lookUp = parent && parentNodes.some((x) => parent instanceof x)
      ? parent : getDocument();

    if (!selectorIsString && elementNodes.some((x) => selector instanceof x)) {
      return selector;
    }
    // @ts-ignore -- `ShadowRoot` is also a node
    return selectorIsString ? lookUp.querySelector(selector) : null;
  }
```

Any hints how I can debug this? Site works with BSN 4.0 flawlessly.

**Comment by thednp** [comment]
@jcorporation I've tested ID selectors on my setup and everything is fine, waiting for your confirmation and perhaps some sample code I can test with.

**Comment by jcorporation** [comment]
Found the error: 
`<a data-phrase="Move an output to this partition" class="dropdown-item featPartitions" data-bs-toggle="modal" href="#" data-bs-target"#modalPartitionOutputs"></a>`

Must be:
`<a data-phrase="Move an output to this partition" class="dropdown-item featPartitions" data-bs-toggle="modal" href="#modalPartitionOutputs"></a>`

**Comment by thednp** [comment]
Yes, that is a breaking change mentioned with each commit on the v4.1 branch. So we good now?

**Comment by thednp** [comment]
May I suggest using this markup:

```html
<a data-phrase="Move an output to this partition" class="dropdown-item featPartitions" data-bs-toggle="modal" href="#modalPartitionOutputs"></a>
```

and

```html
<button data-phrase="Move an output to this partition" class="dropdown-item featPartitions" data-bs-toggle="modal" data-bs-target="#modalPartitionOutputs"></button>
```

Makes a lot more sense to keep consistency with each component markup requirements.

**Comment by jcorporation** [comment]
I missed this breaking change. Its now all good for me, many thanks!

**Comment by jcorporation** [comment]
Other question: where are the reference to an initialized element are stored? In previous version I can access it via triggering element e.g. el.Popover, el.Modal. In 4.1 I see no such reference anymore.

**Comment by thednp** [comment]
That is another breaking change, you now have to do `BSN.Carousel.getInstance(selector | HTMLElement)`. Check the updated documentation/demo ;)

**Comment by jcorporation** [comment]
Is there a list of breaking changes?

**Comment by jcorporation** [comment]
Works all as described!

**Comment by jcorporation** [comment]
Yes, my script uses dropdown and popovers. I have some workarounds in place. I tested now without this workarounds.

There are the same positioning problems as in the old version:

Clipped popover:
![image](https://user-images.githubusercontent.com/765844/153752108-46906399-b73d-4885-83ff-a8481e19ddd0.png)
Workaround is to set a overflow:auto and resize the popover-body.

Clipped dropdowns:
![image](https://user-images.githubusercontent.com/765844/153752181-b91c769f-fb95-4edf-a483-690909767e9d.png)
Workaround is to set dynamically the `dropdown-menu-end` classes.

**Comment by jcorporation** [comment]
This is exactly what my workaround does. I hopped that the improved positioning feature sets the dropdown and popovers too prevent clipping through viewport.

**Comment by thednp** [comment]
That is true for tooltip / popover, it will try to find the best position so it's always visible within the viewport. However dropdown is much more simple since the `.dropdown-menu` is contained within the `.dropdown` element. With other words it might be impossible to code something that is RTL compliant and automatically position the `.dropdown-menu` with or without the `dropdown-menu-end` class, believe me I tried, you know what's the reason? One invalidates the other, completely.

The improvements for dropdown are mostly related to RTL as well as more consistent positioning, but again, the `dropdown-menu-end` class is for you to decide where and when to use.

**Comment by jcorporation** [comment]
Why not simply droping in the direction where is the most space? In my first screenshot the popover have more space below but it dropups.

Same with second screenshot, why the dropdown does not align to end? If I do not know the position of the dropdown button at coding time, I must determine the position at runtime and add the class accordingly. 

It would be more userfriendly if bsn handle this for me. Or what usecase do I miss?

**Comment by thednp** [comment]
That's what I have in mind. However, it already does that, exactly showing the dropdown-menu where it has the most space and reposition on window scroll/resize.

If you're using dropleft / dropright and it doesn't have space sideways, it will use either dropdown / dropup position, but it will not get from initial dropdown / dropup to dropleft / dropright as far as I can remember. Maybe here's something we could improve on.

I think you should use `dropdown-menu-end` class for the dropdown in the second screenshot. It would be consistent with the current scripting and also with the original library and I think shifting to the position of `dropdown-menu-end` without using the class would invalidate using the class in the first place.

**Comment by thednp** [comment]
Do you have a test site? I wanna have a look.

**Comment by jcorporation** [comment]
Not for the popover, but for the dropdown element.
https://spacepirates.jcgames.de/

- click on the search button on the top right, the search dropdown appears
- type "wa" to search
- close the dropdown and reopen it
- if the dropdown does not fit at the bottom it is positioned at top even if at the bottom are more space

**Comment by thednp** [comment]
That is alpha2, there have been a ton of changes since then.

**Comment by thednp** [comment]
This is how the latest works, and how it's supposed to work


https://user-images.githubusercontent.com/6761246/153760587-8e59ba37-029a-4634-9d2d-0e56b4e41fff.mp4

**Comment by thednp** [comment]
For some reason your test site is using the V4 version of BSN which doesn't include the changes I'm talking about.

**Comment by jcorporation** [comment]
Sorry, I updated to the wrong version...

**Comment by jcorporation** [comment]
Now it should run the latest code, behavior has not changed.

**Comment by thednp** [comment]
Your search on the site looks good to me, I've cleared the cache and the dropdown-menu is positioned where I expect it to go, except when you minimize to a mobile width and the dropdown is going into `.dropdown` position but doesn't adjust position.

That dropdown-menu is pretty large, if you want to use the `dropstart`, I would suggest giving the dropdown a `max-height` of about 350px and `overflow-y: auto`, or simply use `.dropdown` with the `.dropdown-menu-end` class.

**Comment by jcorporation** [comment]
Initial position is as described. But if the dropdown menu does not fit in the space below it always drops up?

**Comment by thednp** [comment]
If you want the dropdown-menu to be visible on mobile devices, makes sense to limit it's size somehow, right? There is no code to guess where an element larger than the screen should be displayed into.

**Comment by jcorporation** [comment]
Can I force it do always dropdown and not dropup?

**Comment by jcorporation** [comment]
I tested the different options, but I found no ideal way. What I wanted would be a combined dropdown and dropstart: open the menu at the left side of the button and always dropdown.

**Comment by thednp** [comment]
If you follow my advice, plus setting your search dropdown-menu `min-width: 20rem` to `@media (min-width: 768)` you should have an excellent outcome.

**Comment by jcorporation** [comment]
Many thanks for your help. Now I looking for popover positioning.

**Comment by jcorporation** [comment]
All other tings I tested: popovers, offcanvas, collapse, modals, carousel works without issues.

**Comment by jcorporation** [comment]
Noticed an javascript error. It occurs only in chromium if switched to mobile device view.

![image](https://user-images.githubusercontent.com/765844/153777041-0a125c45-d14e-49c5-beba-f9e2e4f1e7f4.png)

It occurs after closing an popover. I do it manually calling the hide() method.

**Comment by jcorporation** [comment]
I can confirm that ba090ff fixes the popover js error.
