### ISSUE TITLE
tab should not collapse content

### ISSUE THREAD

**Issue by lekoala** [thednp/bootstrap.native#433]
I see that the tab component is adjusting the content height by default. This is different (and maybe, not in a good way) than what bootstrap 5 does.
In my application, I have a tabbed form, and doing so adds an unnecessary animation that is not very fluid. In my opinion, it's better to leave the browser compute the content height.
At any rate, I wouldn't make it a default and offer a way to enable/disable it through a data attribute.

**Comment by thednp** [comment]
I've pushed a [PR](https://github.com/thednp/bootstrap.native/commit/be05a759581a860441bd40957c1e2efa40f014b4) to improve on this issue and we can close this one for now.
