### ISSUE TITLE
Closing Modal re-focuses wrong trigger element

### ISSUE THREAD

**Issue by AlexanderGH** [thednp/bootstrap.native#440]
I have a modal (using bsn 4.1.1) that can be triggered by two different elements: one at the top of the page, and one at the bottom, with at least one page of vertical space between them.

If I click the bottom element to launch the dialog and then close it, the top element is focused causing the page to scroll from the bottom to the top.

The cause, afaict, seems to be that this line will focus the first element in the page that can show the modal:
https://github.com/thednp/bootstrap.native/blob/f647e9a7bcf1c8241b7f218a7c2711de62bb7645/src/components/modal-native.js#L154

However, it seems like a better candidate for refocusing would be this:
https://github.com/thednp/bootstrap.native/blob/f647e9a7bcf1c8241b7f218a7c2711de62bb7645/src/components/modal-native.js#L239

**Comment by thednp** [comment]
Interesting find.

**Comment by thednp** [comment]
@AlexanderGH please test latest master and let me know how it goes

**Comment by AlexanderGH** [comment]
Works as expected now without the scrolling. Thanks for the quick fix!
