### ISSUE TITLE
Opening a modal after another modal doesn't always show backdrop

### ISSUE THREAD

**Issue by lekoala** [thednp/bootstrap.native#441]
I've discovered one issue when opening a modal after another. I have is that sometimes the backdrop doesn't get properly the show class. It happens a bit randomly, so i guess it's due to the transition from the previous modal that sometimes overlaps the transition of the new modal.

From what I can see, sometimes getCurrentOpen(element) returns the new modal as expected, but sometimes not, and therefore hides the backdrop even if there is a new modal being shown.

Actually, this is even more obvious if you do a setTimeout, then it almost always happen

```js
modal.addEventListener("hidden.bs.modal", () => {
  setTimeout(() => {
    // open modal here
  }, 10)
});
```

**Comment by lekoala** [comment]
example here https://codepen.io/lekoalabe/pen/wvPygrg click "bsn modal"

**Comment by thednp** [comment]
@lekoala can you please test the issues with latest master, I've changed where the `hidden.bs.modal` even is triggered.

**Comment by lekoala** [comment]
@thednp i don't see any update on master about this ?
https://thednp.github.io/bootstrap.native/ actually it's also the case in the docs, if you go to the next modal, the backdrop is gone

**Comment by thednp** [comment]
@lekoala ?

**Comment by lekoala** [comment]
@thednp it's not fixed as far as I can tell. The backdrop element is removed and therefore not visible on the second modal. It plays like this

beforeModalShow
modal-native.js:170 afterModalShow
modal-native.js:153 afterModalHide
modal-native.js:400 show => backdrop static
modal-native.js:184 beforeModalShow
modal-native.js:170 afterModalShow
modal-native.js:400 show => backdrop true
modal-native.js:153 afterModalHide
modal-native.js:184 beforeModalShow
modal-native.js:170 afterModalShow
modal-native.js:153 afterModalHide

the show call checks if the backdrop should be displayed (it's still there) but afterModalHide kills it.
I think it should be safe to move at least partially the backdrop to beforeModalShow or check again if it's still there

**Comment by lekoala** [comment]
ok i found a solution.

i had a global let modalIsShowing = false; flag. you set it to true or false in onbeforeshow/onaftershow and you don't remove the overlay is the flag is true.
i can make a PR if that works for you

**Comment by thednp** [comment]
Hold on, I have to check things.

**Comment by thednp** [comment]
We already have that code in the `show()` method.

**Comment by lekoala** [comment]
Well my use case is this:
- I have a modal with an input field
- I collect all the data from the field when confirming the modal (=> closing) => this is calling hide()
- Listening to the hidden event, I may (or may not) choose to display another modal

So while I could do something else than hiding the first modal (basically I could make a button that triggers properly the next modal without hiding the first one), it's less convenient as you need to build custom stuff instead.
For reference, what I do with regular bs5 javascript (i know i know, it's not the same, but still)

**Comment by lekoala** [comment]
My solution with the global flag is not too bad and only adds a couple of lines. I don't see any issue with offcanvas, it's just preventing a drop of the backdrop element between modals

**Comment by thednp** [comment]
I agree we have to make it work the same, but a global flag will not help. I will download your codepen and check myself, will provide a fix asap.

**Comment by thednp** [comment]
@lekoala there is an important thing for you to learn: BSN does not or try to emulate what jQuery does in terms of event listener memory leaks. It has a complicated event delegation system that's very good at handling this issue.

So let me explain: you add new Modal instances on click and remove them once `hidden.bs.hidden` is triggered, however you must also remove the `hidden.bs.modal` listener, so for your examples 3 and 4 this should be the code for you to use:

```js
let button3 = document.querySelector(".bsn-modal");
button3.addEventListener("click", (ev) => {
  console.log("click");
  var myModalInstance = new BSN.Modal("#myModal", {
    backdrop: "static",
    keyboard: false
  });
  myModalInstance.show();
  document.querySelector("#myModal").addEventListener("hidden.bs.modal", (ev) => {
    myModalInstance.show();
  }, { once: true });  // NOTICE THE EVENT LISTENER OPTIONS HERE
});

let button4 = document.querySelector(".bsn-modal-dispose");
button4.addEventListener("click", (ev) => {
  console.log("click");
  var myModalInstance = new BSN.Modal("#myModal", {
    backdrop: "static",
    keyboard: false
  });
  document.querySelector("#myModal").addEventListener("hidden.bs.modal", (ev) => {
    myModalInstance.dispose();
    console.log(BSN.Modal.getInstance("#myModal"))
  }, {once: true}); // NOTICE THE EVENT LISTENER OPTIONS HERE
  myModalInstance.show();
});
```

Alternatively you can do the following:

```js
let button3 = document.querySelector(".bsn-modal");
button3.addEventListener("click", (ev) => {
  console.log("click");
  var myModalInstance = new BSN.Modal("#myModal", {
    backdrop: "static",
    keyboard: false
  });
  const eventListener3 = (ev) => {
    myModalInstance.show();
   document.querySelector("#myModal").removeEventListener("hidden.bs.modal", eventListener3);
  }
  myModalInstance.show();
  document.querySelector("#myModal").addEventListener("hidden.bs.modal", eventListener3 );
});

let button4 = document.querySelector(".bsn-modal-dispose");
button4.addEventListener("click", (ev) => {
  console.log("click");
  var myModalInstance = new BSN.Modal("#myModal", {
    backdrop: "static",
    keyboard: false
  });
  const eventListener4 = (ev) => {
    myModalInstance.dispose();
    document.querySelector("#myModal").removeEventListener("hidden.bs.modal", eventListener4)
  }
  document.querySelector("#myModal").addEventListener("hidden.bs.modal", eventListener4);
  myModalInstance.show();
});
```
The memory leak is gone, as well as ALL errors resulted in the broken relation between disposed instances and their original event listeners still available in the memory which still add up and trigger, with every click.

With this issue cleared I think these last two issues are practically solved.

Let me know if you spot any other issue.

**Comment by lekoala** [comment]
@thednp yes works fine on master indeed!
