### ISSUE TITLE
tab issues

### ISSUE THREAD

**Issue by newyhj** [thednp/bootstrap.native#444]
Scene 1
<div class="tab-pane content" id="customisation">
</div>

when tab-pane not have "fade" class, nav-link .active class cannot be set correctly

Scene 2
<div class="tab-pane fade content" id="customisation">
</div>
tab-pane has "fade" class,  when i quick click nav link,cant switch tab pane!

**Comment by newyhj** [comment]
` <h2>Scene 1</h2>
 <p>tab-pane not have fade cass,active class cannot be set correctly</p>
 <div class="content-wrapper">
   <ul class="nav nav-tabs">
     <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#a1">Specifications</a></li>
     <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#a2">Technical Parameters</a></li>
   </ul>
   <div class="tab-content">
     <div class="tab-pane show active" id="a1">
       tab1
     </div>
     <div class="tab-pane show" id="a2">
       tab2
     </div>
   </div>
 </div>
  <h2>Scene 2</h2>
 <p>tab-pane has "fade" class, when i quick click nav link,cant switch tab pane! </p>
 <div class="content-wrapper">
   <ul class="nav nav-tabs">
     <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#a11">Specifications</a></li>
     <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#a22">Technical Parameters</a></li>
   </ul>
   <div class="tab-content">
     <div class="tab-pane fadeshow active" id="a11">
       tab1
     </div>
     <div class="tab-pane fade show" id="a22">
       tab2
     </div>
   </div>
 </div>
 `

**Comment by newyhj** [comment]
<h2>Scene 1</h2>
 <p>tab-pane not have fade cass,active class cannot be set correctly</p>
 <div class="content-wrapper">
   <ul class="nav nav-tabs">
     <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#a1">Specifications</a></li>
     <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#a2">Technical Parameters</a></li>
   </ul>
   <div class="tab-content">
     <div class="tab-pane show active" id="a1">
       tab1
     </div>
     <div class="tab-pane show" id="a2">
       tab2
     </div>
   </div>
 </div>
  <h2>Scene 2</h2>
 <p>tab-pane has "fade" class, when i quick click nav link,cant switch tab pane! </p>
 <div class="content-wrapper">
   <ul class="nav nav-tabs">
     <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#a11">Specifications</a></li>
     <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#a22">Technical Parameters</a></li>
   </ul>
   <div class="tab-content">
     <div class="tab-pane fadeshow active" id="a11">
       tab1
     </div>
     <div class="tab-pane fade show" id="a22">
       tab2
     </div>
   </div>
 </div>

**Comment by newyhj** [comment]
[https://jsfiddle.net/newyhj/a9zcvfe6/11/](url)

please see above code

**Comment by thednp** [comment]
Thanks will have a look asap.

**Comment by thednp** [comment]
Just to let you know, the Tab issue is fixed, will let you know once I'm done with a new build, currently doing a major code revisit.

**Comment by newyhj** [comment]
> 

good.

**Comment by thednp** [comment]
@newyhj please test the latest master.

**Comment by newyhj** [comment]
it's seems ok,prefect

**Comment by thednp** [comment]
Alright, we can close this one and release 4.2.0.
