### ISSUE TITLE
types location needs to be fixed in package.json

### ISSUE THREAD

**Issue by yogeshlonkar** [thednp/bootstrap.native#448]
Types have been moved to [types/](https://github.com/thednp/bootstrap.native/tree/master/types) from src. But in released package it still points to old location

```json
"types": "src/index.d.ts",
```

Because of this typescript fails to load types

Correct location should be `types/index.d.ts`

```diff
- "types": "src/index.d.ts",
+ "types": "types/index.d.ts",
```

**Comment by thednp** [comment]
@yogeshlonkar can you please confirm the master branch in regards to types please?

Thank you
