### ISSUE TITLE
Accordion - slidedown animation issue Safari (mac)

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#45]
(only safari issue)

Slidedown animation is not working properly
See video: http://recordit.co/K1MDbKaIlS (fps is pretty low tho, but it explains the issue properly). THe animation pops over the content in one frame. This only happens on Safari (mac).

**Comment by warreb1** [comment]
[video.zip](https://github.com/thednp/bootstrap.native/files/182706/video.zip)
Better quality video.

**Comment by thednp** [comment]
Confirmed.

**Comment by thednp** [comment]
This one is a pretty nasty one, I didn't expect Safari to be so out of game.

**Comment by thednp** [comment]
Please try this:
* find the CSS I recommended for `.collapse` 
* comment out the `-webkit-transition: height .3s ease-out`
* try and let me know

If this fixes the issue, I will write a note into the documentation on this Safari bug: it seems Safari is just trying to apply both un-preffixed and preffixed `transition` driven height animation at the same time.

**Comment by thednp** [comment]
Ok I updated demo, please check now, and see updated documentation regarding additional styling.
