### ISSUE TITLE
Navbar with off-canvas drawer is hidden by backdrop

### ISSUE THREAD

**Issue by trucksmart** [thednp/bootstrap.native#458]
If you have a navbar with an [off-canvas](https://getbootstrap.com/docs/5.3/components/navbar/#offcanvas) drawer, the backdrop hides it. The official Bootstrap backdrop is appended to the [navbar](https://github.com/twbs/bootstrap/blob/main/js/src/offcanvas.js#L184) while Bootstrap.Native backdrop is appended to the [document body](https://github.com/thednp/bootstrap.native/blob/master/src/util/backdrop.ts#L60).

**Comment by thednp** [comment]
Can you have a codepen link or something to see the diffrence?

**Comment by trucksmart** [comment]
[Bootstrap Official](https://codepen.io/trucksmart/pen/bGjqmjG)
[Bootstrap Native](https://codepen.io/trucksmart/pen/eYjvPLv)

**Comment by trucksmart** [comment]
The backdrop utility has the document body hardcoded in. Adding an option for a mounting point then defaulting to the document body if none is provided seems like an excellent addition.

**Comment by thednp** [comment]
What if you move the offcanvas outside of the navbar, it should work as expected. The point I'm trying to make is that less configuration for more functionality is best, sounds good?

**Comment by trucksmart** [comment]
That's perfectly reasonable. Thanks!
