### ISSUE TITLE
Tooltip & popover not shown on focus

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#46]
The tooltips & popovers only work on hover, not on focus. In terms of usability this should be something that needs to be added.

**Comment by thednp** [comment]
Please also paste some console errors if any. 

Thank you so much.

**Comment by warreb1** [comment]
Will do, but there aren't any. I think the effect just needs to be applied too on the "focus" event.

**Comment by thednp** [comment]
This one is fixed. Closing it down :)
