### ISSUE TITLE
about source code

### ISSUE THREAD

**Issue by newyhj** [thednp/bootstrap.native#463]
bootstrap-native.js  Whether an uncompressed version can be provided?

**Comment by thednp** [comment]
The source is Typescript. Unfortunately Vite doesn't provide much flexibility in terms of build options. I tried to figure out how to get our traditional distribution packaging but I figured it's not needed in this day and age.

**Comment by newyhj** [comment]
i need know build process details.how to pack?

**Comment by thednp** [comment]
open bsn root folder in console and run 'npm run build'.

**Comment by newyhj** [comment]
I try to delete some unnecessary components, and then compile, but always report an error, how to deal with it?

error info:
  13:9  error  Replace `⏎··Alert,⏎··Button,⏎··Collapse,⏎··Dropdown,⏎··Modal,⏎··Offcanvas,⏎··ScrollSpy,⏎··Tab,⏎··Toast,⏎··initCallback,⏎··removeDataAPI,⏎` with `·Alert,·Button,·Collapse,·Dropdown,·Modal,·Offcanvas,·ScrollSpy,·Tab,·Toast,·initCallback,·removeDataAPI·`  prettier/prettier

F:\bootstrap.native-master\src\util\init.ts
  26:44  error  Replace `·Offcanvas,··ScrollSpy,·` with `Offcanvas,·ScrollSpy,`  prettier/prettier

**Comment by thednp** [comment]
Here's a quick how to build your own:

* Create a new folder in your BSN root called "custom-builds"
* create a new file inside called "vite.config.ts" with the following code
```ts
import { resolve } from 'path';
import UserCfg from "../vite.config";

export default { ...UserCfg, 
  ...UserCfg,
  build: {
    // @ts-ignore
    ...(UserCfg.build ),
    lib: {
      // @ts-ignore
      ...UserCfg.build.lib,
      entry: resolve(__dirname, './index.ts'),
    },
    outDir: 'custom-builds/dist',
  },
}
```
* copy `src/index.ts` to `custom-builds/index.ts` and customize to your needs, remember to update the import paths, here is an example
```ts
import Alert from '../src/components/alert'; // import is now "../src" instead of "./src"
import Button from '../src/components/button';
import Carousel from '../src/components/carousel';

import { initCallback, removeDataAPI } from '../src/util/init';

export {
  Alert,
  Button,
  Carousel,
  initCallback,
  removeDataAPI,
};
```
* in your console at the ROOT of BSN, run `npx vite --config custom-builds/vite.config.ts`
* check our 'custom-builds/dist' folder
![Screenshot from 2023-09-02 08-25-19](https://github.com/thednp/bootstrap.native/assets/6761246/e7c12a00-c22c-4a75-af9c-0fe73114f594)

Have fun!
