### ISSUE TITLE
Dropdown menu closes instantly if user clickes on a span element inside the triggering button

### ISSUE THREAD

**Issue by jcorporation** [thednp/bootstrap.native#464]
If the user clicks a span element inside a dropdown menu triggering button the dropdown closes instantly. Clicking outside the span elements but inside the button works.

I added a show and a hide event handler to the dropdown and both events are triggered correctly, but the dropdown menu closes instantly. 

Following markup produces this issue:

```
<div class="btn-group">
  <button id="volumeMenu" class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside">
    <span class="mi">volume_up</span><span class="featVolumeLevel ms-1">50</span>
  </button>
  <div id="outputsDropdown" class="dropdown-menu">
    ...
  </div>
</div>
```

**Comment by thednp** [comment]
Currently we don't support `data-bs-auto-close="outside"` functionality.

**Comment by jcorporation** [comment]
Thanks for that hint. Issue occurs also without this attribute.

**Comment by thednp** [comment]
I can confirm the issue.

**Comment by thednp** [comment]
For some reason I removed `stopPropagation` from the Dropdown click listener and this happened. I'm reverting that change and you can go ahead and test latest master. Once we're ok, we can push the next release.

**Comment by jcorporation** [comment]
It works now, many thanks for the quick fix!

**Comment by thednp** [comment]
v5.0.6 is now live, thanks for the report and the testing.
