### ISSUE TITLE
Modal close buttons not working when launching via instance.show()

### ISSUE THREAD

**Issue by jxlarrea** [thednp/bootstrap.native#473]
This issue can be seen even on the Modal wiki page at: https://thednp.github.io/bootstrap.native/

![Screenshot 2023-11-09 025853](https://github.com/thednp/bootstrap.native/assets/309902/53a1086d-9a10-427a-b91c-18c8bf7c827f)

When using the "Open Modal" button, it is impossible to close the opened modal using the X icon, "Close" button or by clicking on the backdrop.

**Comment by thednp** [comment]
Thanks for reporting and sorry for the late reply. Will have a look into it.

**Comment by jxlarrea** [comment]
@thednp thank you! Any idea when the fix will be available via npm?

**Comment by thednp** [comment]
Like [an hour ago](https://www.npmjs.com/package/bootstrap.native/v/5.0.10)
