### ISSUE TITLE
ESM default export missing

### ISSUE THREAD

**Issue by verheyenkoen** [thednp/bootstrap.native#477]
The [How to use wiki](https://github.com/thednp/bootstrap.native/wiki/How-to-use#basic-example) demonstrates this example on how to import BSN in an ESM type project.

```js
import BSN from "bootstrap.native";

let myBtnInit = new BSN.Button('#myBtnID');
```

This doesn't work for me (at least not using esbuild) as there doesn't seem to be a default export. This can be fixed using the `* as BSN` syntax (but that cannot be combined with named imports).

```js
import * as BSN from "bootstrap.native";

let myBtnInit = new BSN.Button('#myBtnID');
```

I guess it might be better to provide it as a default export as well, or if not update the examples (unless this is a pure esbuild issue).

**Comment by thednp** [comment]
I guess something happened to Vite 4.5 -> 5.X the build is different again.

**Comment by thednp** [comment]
@verheyenkoen so we update the Wiki as suggested?

**Comment by verheyenkoen** [comment]
@thednp That's your call really. Don't know a lot about how Vite and if this is an intended (breaking) change.
