### ISSUE TITLE
Dropdowns don't close on Safari

### ISSUE THREAD

**Issue by crcastle** [thednp/bootstrap.native#48]
In Safari, the dropdown menu stays open
1) after clicking an item and
2) on clicking outside of the dropdown menu

You can test it here http://thednp.github.io/bootstrap.native/#exampleDropdown

In Chrome, the dropdown closes in these two scenarios which I'm guessing is the expected behavior?

p.s. thanks for this.  nice to be able to use some simple bootstrap elements without having to add jQuery / giant gorilla.

**Comment by crcastle** [comment]
Just saw that the most recent commit 36bf934864dc7a9a70bc459820297ecdeca1cd92 may have fixed this.  Apologies and please close if so.

**Comment by thednp** [comment]
It's ok, please also [test this](https://github.com/thednp/bootstrap.native/issues/45).

**Comment by thednp** [comment]
I updated demo and code, preparing for 1.0.2 release now.

**Comment by crcastle** [comment]
Thanks!  1.0.2 fixes the issue without having to apply [this](https://github.com/thednp/bootstrap.native/issues/45#issuecomment-201085407) CSS fix.

**Comment by thednp** [comment]
@crcastle the issue depends very much on the Safari version, I've updated demo/doc with a quick note about that. As an example Safari 5.1.7 for Windows doesn't work with both the prefixed `-webkit-transition` and `transition`. Other MAC OS versions sporting older versions of Safari could be in the same situation.
