### ISSUE TITLE
Prepare for BSN v5.1.0

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#481]
Hi folks, glad to announce a new and important update, v5.1.0 (almost complete).

## What changed

* :battery: added a new [PositionObserver](https://github.com/thednp/position-observer) for Tooltip, Popover, Dropdown and ScrollSpy to replace the legacy scroll and/or resize event listeners, for top notch performance;
* :pager:  Modal  and Offcanvas now make use of [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API) with the same effect;
* :world_map:  Tooltip and Popover use a different positioning system based on `position: absolute`;
* :metro: improved accessibility for Modal and Offcanvas by implementing a focus trap, if at least one focusable element is inside your modal/offcanvas, users cannot focus outside of it;   
* :100: replaced Cypress tests with Vitest, it's not just better but it works perfect on my Linux machine;
* :rescue_worker_helmet: removed many tools like eslint and prettier with Deno 2.0 powered tools; we only update dependencies that actually matter;
* :bullettrain_side: performance improvements: early `return`s instead of long `if`s, improved logic, code cleanup;
* :key: updated Types, in some cases more strict in others more flexible;
* :man_dancing: all interaction event listeners now check for target `disabled` status;
* :heavy_check_mark: fixed Tab event listener for the cases where `currentTarget` is a child element of the event target (possibly a result of incorrect code mergers in the past);

## What you can do

* test the code in the repo (`npm install github:thednp/bootstrap.native`)
* [report](https://github.com/thednp/bootstrap.native/issues) any issue you encounter, your feedback is valuable
* there should be no breaking change so nothing major is expected of you to do

Have a good one!

I'm tagging some of you, hope you don't mind :+1: 

@cvaize @jcorporation @PaulBGD @midzer

**Comment by jcorporation** [comment]
Sounds great, I will gladly test the upcoming version in the next days!

**Comment by jcorporation** [comment]
First tests are showing no issues.

**Comment by thednp** [comment]
Thanks, keep an eye on the repo in the following days, got some new ScrollSpy working on.

**Comment by newyhj** [comment]
look forward
 hope samller complied file

**Comment by thednp** [comment]
> look forward hope samller complied file

We've added functionality, the minified build is around 1.5kb larger.

**Comment by jcorporation** [comment]
I keep my updated with the repository here and it works so far without problems. Looking forward to the release.

**Comment by thednp** [comment]
@jcorporation [v5.1.0](https://www.npmjs.com/package/bootstrap.native) is now live.
