### ISSUE TITLE
Contact author 

### ISSUE THREAD

**Issue by XhmikosR** [thednp/bootstrap.native#49]
Hi, there.

I'm personally very interested in backporting this.

I'm willing to help back porting this to v4.

Can you contact me via email if you are interested?

**Comment by thednp** [comment]
Hi. If you're talking about [this v4](http://v4-alpha.getbootstrap.com/), I'm also interested, I actually consider developing a v4 version, but realistically I would like to see v4 stable first so I'm planning on it.

**Comment by XhmikosR** [comment]
Can you contact via email (see my profile)?

To be honest I personally dislike the ES6 change and I doubt that will
change. If we are going to do it I guess I will have to read more about it.
:)

**Comment by thednp** [comment]
Frankly instead of working with v4 I would rather make v3 greater than already is, [here's](http://getfuelux.com/javascript.html) what I have in mind.

**Comment by thednp** [comment]
http://thednp.github.io/bootstrap.native/v4.html
