### ISSUE TITLE
This thing rocks.

### ISSUE THREAD

**Issue by IngwiePhoenix** [thednp/bootstrap.native#5]
ref: https://github.com/tagawa/bootstrap-without-jquery/issues/43#issuecomment-102387101

Thanks for the heads-up. This is totally amazing and I can't believe this isn't part of upstream... xD At least, I am definitively going to dump jQuery and "the original" Bootstrap JS. It eats up too much JS anyway...

Also. Will you add bower and/or NPM support?

**Comment by thednp** [comment]
Those things are out of my skill range, you can pull a PR anytime you see fit.

**Comment by IngwiePhoenix** [comment]
Okay! Expect something in a few hours…this is too cool to let sit aside! :)

**Comment by IngwiePhoenix** [comment]
Done!! Verififying and reviewing my changes and seeing if everything is right. Then i'll PR it to you! :)

**Comment by IngwiePhoenix** [comment]
And, done.

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/bootstrap.native $ bower register bootstrap.native https://github.com/thednp/bootstrap.native.git
bower                          convert Converted https://github.com/thednp/bootstrap.native.git to git://github.com/thednp/bootstrap.native.git
bower bootstrap.native#*       resolve git://github.com/thednp/bootstrap.native.git#*
bower bootstrap.native#*      download https://github.com/thednp/bootstrap.native/archive/0.9.6.tar.gz
bower bootstrap.native#*       extract archive.tar.gz
bower bootstrap.native#*  invalid-meta bootstrap.native is missing "main" entry in bower.json
bower bootstrap.native#*  invalid-meta bootstrap.native is missing "ignore" entry in bower.json
bower bootstrap.native#*      resolved git://github.com/thednp/bootstrap.native.git#0.9.6
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower bootstrap.native        register git://github.com/thednp/bootstrap.native.git

Package bootstrap.native registered successfully!
All valid semver tags on git://github.com/thednp/bootstrap.native.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info bootstrap.native to list the available versions.
Ingwie@Ingwies-Macbook-Pro.local ~/W/bootstrap.native $ npm publish
npm http request PUT https://registry.npmjs.org/bootstrap.native
npm http 200 https://registry.npmjs.org/bootstrap.native
+ bootstrap.native@0.9.7
```

Currently, the NPM package is in my account. If you made a NPM account, I can transfer the ownership to you so you dont depend on me in this one. For Bower, if you release a tag, it also becomes a version available via its package manager! Now, to send the PR itself.

**Comment by thednp** [comment]
Please check PR comments :)

**Comment by thednp** [comment]
PR Merged, thank you so much :)

[Details here](https://github.com/thednp/bootstrap.native/pull/6)

**Comment by thednp** [comment]
> This is totally amazing and I can't believe this isn't part of upstream..

I forgot to comment this, the trend is going fine for Native Javascript, the thing is, many more new developers enter the Javascript realm via jQuery.

**Comment by thednp** [comment]
@IngwiePhoenix I need your help, please if you have some time, add me to collaborators list on npm for KUTE.js, I will try to publish a new version.

Thank you.
