### ISSUE TITLE
Close current modal and open new one

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#52]
I came across the following issue. In Bootstrap it's possible to close a modal window and open up the next one triggered by the html data attributes. It however doesn't seem to work in bootstrap.native. Since it's quite an important item (used in login modal -> forgot your pasword modal)

I made a working version in codepen with the default bootstrap, so you get the idea. http://codepen.io/studiotwist/pen/zqdrKR

**Comment by thednp** [comment]
This has been [reported before](https://github.com/thednp/bootstrap.native/issues/30) and I haven't got convinced this should be implemented. But if you read the previous issue to the end you'll find a good way to [work around this](http://jsfiddle.net/pzmk50tf/).

**Comment by thednp** [comment]
Thinking about it a bit, shit should be easy to implement. I will have a look asap.

**Comment by thednp** [comment]
Update: I found a quick solution for this, [please check this demo](http://jsfiddle.net/pzmk50tf/1/).
