### ISSUE TITLE
Event bubbling on dropdowns

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#53]
Since the last update the event bubbling on dropdown buttons broke. Possible to take a look at that?

**Comment by thednp** [comment]
Can you write a guide with steps to replicate please?

**Comment by warreb1** [comment]
http://codepen.io/studiotwist/pen/VazXez

Here you go. It's a copy paste of my code so might not be super clear in terms of html classes but you'll get the idea. If you click on the border of the button it works, if you click on the image it doesn't.

**Comment by thednp** [comment]
If you delete the `<div>` wrapper around the image should work. Try to use dropdown only for dropdowns where the event trigger is only one level deeper from `data-toggle="dropdown"` element, the latest fix should handle that.

**Comment by warreb1** [comment]
I honestly think something is up with the event bubbling in general. I just tried to initiate a modal from an anchor. On the a text it works, but not on the <span> within.

-> http://codepen.io/studiotwist/pen/VazXez

**Comment by thednp** [comment]
There is no problem anyway. The only thing is: the event handlers are only bound to the specific triggers: `data-toggle="modal"` or `data-toggle="dropdown"` and in some cases ONLY THE FIRST child element (dropdown, button and carousel if I remember correctly).

You can try to add same specific attributes from the trigger to the last level element and check again.

**Comment by warreb1** [comment]
I know when I add it to the last level element (spans in this case) that it works, but it should work on all it's children in any case no? In the regular bootstrap js it certainly does.

**Comment by thednp** [comment]
If it works with jQuery, use jQuery, I don't find it useful to look for all
elements and I think I gave you a good solution already.

**Comment by warreb1** [comment]
Well it's clear that you don't want to give it a look that's for sure. In a huge amount of cases the trigger needs to be on the parent + all it's children elements (eg: a button with an image and a label for a profile picture change). If you put the data-toggle="dropdown" on the parent + children elements the dropdown simply opens and closes again because it's triggered twice. -> long story short it doesn't work.

I was in the assumption this is a worthy equivalent to the Bootstrap 3 jQuery library and therefor I could contribute by posting issues if there were any. Agreed there are some edge cases but nevertheless they are pretty game-changing (like event bubbling).

In any way, all we did was test out the provided library (very) extensively and reported the issues we've had over here. There's no need to get buggered about it.
