### ISSUE TITLE
Any instance of the string 'in' in a collapse's class attribute breaks Collapse

### ISSUE THREAD

**Issue by lcannon** [thednp/bootstrap.native#54]
Presumably this would be fixed by changing the regex to match `/\bin\b/` instead of `/in/` in the toggle function.

**Comment by thednp** [comment]
Do you have a test scenario with the issue please?

**Comment by lcannon** [comment]
Sure. The situation that brought this up was a collapse

`<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-warning-collapse">`

that targeted this

```
<div class="navbar-collapse collapse navbar-warning-collapse">
    ...
</div>
```

Because `/in/` matches against 'navbar-warning-collapse' the toggle method always tries to close the collapse.

**Comment by lcannon** [comment]
Thanks for the library, by the way, was exactly what I was looking for!

**Comment by thednp** [comment]
Does the `\bin` RegExp work with IE8? I will probably have to update all code to this, I didn't expect other cases could be touched.

**Comment by thewisenerd** [comment]
this issue still isn't fixed.

```1. \bin```: http://regexr.com/3euta
```2. \bin\b```: http://regexr.com/3eutm
```3. (^|\s)in($|\s)```: http://regexr.com/3eutg

1. matches words like ```navbar-inverse-collapse``` and ```inverse-class```
2. matches words like ```navbar-in-example```
3. checks if string begins ```in``` or there is a space before ```in```, and ensures that either string ends with ```in``` or a space comes after.

**Comment by thednp** [comment]
I think we will have a new `hasClass(element,className)` to work with a proper regex.

**Comment by thewisenerd** [comment]
@thednp cool!

at this point i have to manually patch javascript because i have a div with class name ```navbar-inverse-collapse``` :P

hoping this gets patched soon.

**Comment by dgt41** [comment]
Why not use classList.contains('class-name') and polyfill ie?

**Comment by thednp** [comment]
To keep polyfill dependency to as low as possible. I noticed some users haven't even heard of them.

**Comment by dgt41** [comment]
@thednp according to Microsoft: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
EOL is in 3 weeks for IE 9, 10.
I guess people could either include ft polyfill service: https://polyfill.io/v2/docs/
or your version pumped with classList.
For me is better to have a clean ES5 code (and polyfill whatever missing) than try to make it "one fits all". But that's my 2c...

**Comment by RyanZim** [comment]
I think we're all looking forward to bootstrap v4; then we won't have to support IE8.

**Comment by dgt41** [comment]
@RyanZim BS v4 host dropped IE 9: https://github.com/twbs/bootstrap/issues/21387

**Comment by thednp** [comment]
yes, our v4 version will be IE9+ of course.

**Comment by RyanZim** [comment]
@dgt41 Thanks for pointing that out. If bootstrap is dropping IE 8 & 9, we should too IMO @thednp.

**Comment by thednp** [comment]
@RyanZim we only need a proper `Event.prototype` + dispatcher polyfill for IE9+, so why just not, the same polyfill is required for IE10+ and I believe also for Ms Edge. (for future BSN4 I mean)

**Comment by RyanZim** [comment]
@thednp BS v4's css will be totally broken in IE9, why support IE9 for the JS?

**Comment by thednp** [comment]
https://v4-alpha.getbootstrap.com/migration/

>Dropped IE8 and iOS 6 support. v4 is now only IE9+ and iOS 7+. For sites needing either of those, use v3.
Added official support for Android v5.0 Lollipop’s Browser and WebView. Earlier versions of the Android Browser and WebView remain only unofficially supported.

**Comment by RyanZim** [comment]
Hosted docs are out of date with the alpha development branch. Actual latest docs are here: https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md#browser-support.

> Dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+. For sites needing either of those, use v3.

**Comment by thednp** [comment]
Ah great, so people will have to fork or look for other frameworks ;)

**Comment by dgt41** [comment]
If you don't mind I will create some custom components based on your code (@thednp )

**Comment by thednp** [comment]
Why should I? As long as the MIT license is all the way, we're all happy :)

**Comment by dgt41** [comment]
> Off topic: I have had some ideas on hot to make a better HTML5 framework with plain JS 


@thednp there is https://frend.co but doesn't fulfilled most cases...

**Comment by thednp** [comment]
Indeed, that's a bit too "one purpose".

In my mind I think of a good typography + an improved&simplified bsn + some grid + some content light design.

**Comment by thednp** [comment]
I was thinking about it and I wish to have a final note in regards to @RyanZim & @dgt41 remarks: our bsn here is for BS3 and will continue to support be old browsers, just as the original script. The future version will be also BS4 like browser support.

@thewisenerd I started implementing a `hasClass(element,classNAME)` utility in all scripts, the new code will be commit later today.

Happy New Year!!

**Comment by dgt41** [comment]
Happy new year @thednp 🎉

Reasonable decision, I like it!
