### ISSUE TITLE
Dropdown should not close when clicking a form element

### ISSUE THREAD

**Issue by waywaaard** [thednp/bootstrap.native#55]
Bootstraps implementation prevents the closing of the dropdown when the user has clicked on an element inside a form.

To get the same behavior the following change is sufficent and is basically what the original bootstrap dropdown code is doing.

```javascript
      this.handle = function(e) { // fix some Safari bug with <button>
        var target = e.target || e.currentTarget;
        if ( target === self.menu || target.parentNode === self.menu ) {
          self.toggle(e);
        } else if (target.closest('.dropdown form')) {
          // this prevents the dropdown from closing, when there was a click
          // in a form
          e.preventDefault();
          return;
        } else {
          self.close(200);
        }
        /\#$/g.test(target.href) && e.preventDefault();
      };
```

I wanted to share this as your library is really create.

**Comment by thednp** [comment]
Thanks for the fix, but we would need something that doesn't require a polyfill for `closest` in the `if (target.closest('.dropdown form')) `.

**Comment by waywaaard** [comment]
The `closest` polyfill requires `element.matches`. We can write a custom function for the closest functionality (which is basically a polyfill with a different name), or just pass in a polyfill.

```javascript
if (!Element.prototype.matches) Element.prototype.matches = Element.prototype.msMatchesSelector;
if (!Element.prototype.closest) Element.prototype.closest = function (selector) {
  var el = this;
  while (el) {
    if (el.matches(selector)) {
      return el;
    }
    el = el.parentElement;
  }
};
```

**Comment by thednp** [comment]
No no, we need something more simple, something like this:
```javascript
if (el.querySelector(selector)) {}
```
also we need to only prevent closing the dropdown if ONLY any child `.form-control` is actually `document.activeElement`, basically:
```javascript
var formElement = el.querySelector('.form-control');
if (formElement  && formElement ===document.activeElement) {
  e.preventDefault();
}
```

Now try this out ;)

**Comment by thednp** [comment]
DO you mean that your form is somehow inside the dropdown or the dropdown is inside another dropdown?

**Comment by waywaaard** [comment]
I am talking about a `form` inside the dropdown. See [`dropdown.js#L160`](https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L160) for the original bootstrap source.

**Comment by thednp** [comment]
Alright, (sorry for the delay, Easter is really serious here), I'm now looking at this, going to try to find an alternative `.closest()` method... and will let you know what's my find.

**Comment by thednp** [comment]
Done. Check https://github.com/thednp/bootstrap.native/commit/a5d60185ae4b39df836b72ce4f4de47d4d541293
