### ISSUE TITLE
Dropdown not closing properly

### ISSUE THREAD

**Issue by Aspie96** [thednp/bootstrap.native#56]
Hi!
I tried the "Form dropdown" component.
It works fine, but when I click elsewhere, it does not close immediately (it takes like half a second).
I tried using Bootstrap and jQuery and it closes immediately.
Also, I inserted it in a menu like this:
```html
<header class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-menu">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="/">
				<img src="logo/small.png" alt="Image" id="logo" class="pull-left" />
			</a>
		</div>
		<div class="navbar-right">
			<div class="collapse navbar-collapse" id="main-menu">
			  <ul class="nav navbar-nav">
				<li><a href="#">Route1</a></li>
				<li><a href="#">Route2</a></li>
				<li><a href="#">Route3</a></li>
				<li><a href="#">Route4</a></li>
				<li class="dropdown">
					<a href="#" data-toggle="dropdown">Form Dropdown</a>
					<form class="form-vertical dropdown-menu" style="padding:15px">
						<div class="form-group">
							<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
							<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
						</div>
						<div class="checkbox">
							<label><input type="checkbox"> Remember me</label>
						</div>
						<button type="submit" class="btn btn-default">Login</button>
					</form>
				</li>
			  </ul>
			</div>
		</div>
	</div>
</header>
```

If I do this, the dropdown form doesn't close at all when I click elsewhere.
Still, it does work if I use Bootstrap with jQuery.

Is that a bug or am I doing something wrong?
Thank you in advance.

**Comment by thednp** [comment]
This feature have been recently implemented as suggested by [previous issue](https://github.com/thednp/bootstrap.native/issues/55) so it might not work perfect in all cases.

**Comment by Aspie96** [comment]
> Also note we aren't trying to do exactly same as for the jQuery version, only the most essential.
Yeah, of course, but the fact that it didn't work in that specific case (when implemented in a menu) is a bit unexpected, so I wanted to point it out.
Thanks for your work.

**Comment by Aspie96** [comment]
On line 916 I turned:
`if (closest && closest === self.menu.parentNode.querySelector('.dropdown-menu') )`

Into:
`if (closest && closest === self.menu.querySelector('.dropdown-menu') )`

And it now works just fine.

It is still a bit slow, but it does close when in the menu.


Hope that helps.
Thank you again.

**Comment by thednp** [comment]
It is a bit slow so that the links inside the dropdown still work, otherwise they will simply dismiss it.

**Comment by Aspie96** [comment]
I will do some tests as well.
If I manage to solve the issue, I will post my changes here.

**Comment by Aspie96** [comment]
Ok, I managed to solve the problem.
`It is a bit slow so that the links inside the dropdown still work, otherwise they will simply dismiss it.`
Would you kindly make an example of when this happens?
I would like to see the problem and try solving it in some other way.

Meanwhile, I will make a pull-request with my changes.
Thank you again!

**Comment by Aspie96** [comment]
Here you have it:
https://github.com/thednp/bootstrap.native/pull/57

I also tried it with neasted Dropdowns:
```html
<header class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-menu">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="/">
				<img src="logo/small.png" alt="Image" id="logo" class="pull-left" />
			</a>
		</div>
		<div class="navbar-right">
			<div class="collapse navbar-collapse" id="main-menu">
			  <ul class="nav navbar-nav">
				<li><a href="#">Route1</a></li>
				<li><a href="#">Route2</a></li>
				<li><a href="#">Route3</a></li>
				<li><a href="#">Route4</a></li>
				<li class="dropdown">
					<a href="#" data-toggle="dropdown">Form Dropdown</a>
					<form class="form-vertical dropdown-menu" style="padding:15px">
						<div class="form-group">
							<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
							<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
						</div>
						<div class="checkbox">
							<label><input type="checkbox"> Remember me</label>
						</div>
						<button type="submit" class="btn btn-default">Login</button>
						<div class="dropdown">
						  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
						  <span class="caret"></span></button>
						  <ul class="dropdown-menu">
							<li><a href="#">HTML</a></li>
							<li><a href="#">CSS</a></li>
							<li><a href="#">JavaScript</a></li>
						  </ul>
						</div>
					</form>
				</li>
			  </ul>
			</div>
		</div>
	</div>
</header>
```

And it now works just fine, without any delay.

**Comment by thednp** [comment]
Nope, that delay has to stay, it was a known issue and the delay is there to make sure links inside dropdown can still follow.

**Comment by Aspie96** [comment]
Ok, I understand, but the way I did links inside the dropdown (and dropdowns inside others) work just fine without the delay.
The different check probably solves that problem as well.

**Comment by thednp** [comment]
OK, I cannot do "probably", I have to check the code myself asap.

**Comment by Aspie96** [comment]
Of course.
I said "probaby" because I could not create any situation generating the issue.
Both inserting links inside dropdowns and inserting dropdowns inside other ones work just fine.

**Comment by thednp** [comment]
Also we won't do `.contains()` because it would need a polyfill for IE8 and I don't want that.

**Comment by Aspie96** [comment]
Yeah, that is very true.
I see the problem and I solved it.

I also did some other minor changes.

**Comment by thednp** [comment]
Well, after a few minutes of testing and stuff, the main issue is the nesting of the dropdown component, as of now, the code works pretty much alright, except nesting. I am personally against component nesting, on most components, but I think dropdown might have to be an exception.

I have a much better solution for menus, it's called [navbar.js](https://github.com/thednp/navbar.js), check it out.

**Comment by thednp** [comment]
I think I fixed the issue and also added nested dropdown menu support.
https://github.com/thednp/bootstrap.native/commit/f62079cc82531d96c3c8daf5f861eadc9e8c89cf

**Comment by Aspie96** [comment]
Thank you very much.
I'll download the new version.

**Comment by thednp** [comment]
Also let me know if the new script is bullet proof ;)

**Comment by Aspie96** [comment]
It is working fine, but I have a little doubt.

It works almost exactly like my last version (not the one of the pull request. I made a few other changes since then), but there is a difference.
If I click another link whose "href" is "#", it doesn't work.

No, of course I do know that the reason for that is line 921:
`/\#$/g.test(target.href) && e.preventDefault();`

But I thought this was intended to happen only when clicking on the dropdown button.

Hopefully, I just didn't understand it and this behaviour is intended.
I am not saying it is a problem.
I just wonder if it is what you intended to do.

**Comment by thednp** [comment]
That's only to stop jumping up and down the page scroll for the `#` links, nothing more.

**Comment by Aspie96** [comment]
Ok, thank you very much for your help (and for your library).

If I may suggest just a very little thing, on the next commit (it is not even worth one), on line 936, you may want to replace:
`if (e.which == 27) {self.close(0);}`

With:
`if (e.which == 27) {self.close();}`

Removing the (now) unused parameter.

Of course it has no effect, but a non-used parameter is a bit "weird".


I hope I didn't bother you too much.
Thank you again, very much.

**Comment by thednp** [comment]
Done.

**Comment by wifiextender** [comment]
@Aspie96 no need to use any external lib/polyfill when you can solve it in 5 lines, literary.

```javascript
const classChildren = x => document.getElementsByClassName(`navbar-${x}`)[0];

classChildren('toggle').addEventListener('click', () => {
    classChildren('collapse').classList.toggle('collapse');
}, false);
```

Here's working demo with your html http://www.bootply.com/Vpm3ySQkh4#

**Comment by thednp** [comment]
I will investigate this asap and propose a fix. Will let you know.

**Comment by thednp** [comment]
Hey @wifiextender I see your demo on bootply is using the jQuery version and you're using it in the header which means it may not work if inside the code `.ready()` is used.

I cannot see how my code isn't working, the demos shown [here](http://thednp.github.io/bootstrap.native/#exampleDropdown) are working as expected.

**Comment by wifiextender** [comment]
@thednp I joined this issue to summon the author with [es6](https://www.google.com/search?q=javascript+es6) solution, instead relying on 3rd party scripts to do such a simple task.

I made NO mentions about you, your project code/quality and so on.

Used bootply because it was some of the first page results returned by the search engine.

Hope this clears the confusion.

Cheers
