### ISSUE TITLE
Dropdown adds hash to url

### ISSUE THREAD

**Issue by henninga** [thednp/bootstrap.native#58]
Hi

Great alternative to jquery. 

I've noticed a bug (?) in the click handler for dropdowns. If you have children in your dropdown link, f.ex a span, and you happen to click on that span the regex `/\#$/g.test(target.href) && e.preventDefault();` does not trigger since the target is not the anchor tag itself but one of its children.

Its not a huge issue, but annoying nontheless

For a demo, click on the caret in the Github dropdown on your own project site and watch it add a hash to the url.
http://thednp.github.io/bootstrap.native/

**Comment by thednp** [comment]
The `e.preventDefault();` is only to prevent 'jumpy' links, if you need a different behavior, try using void `href="javascript:void(0)"`.

The hash added to the URL is default behavior in all browsers, I don't see how it can influence other apps.

**Comment by thednp** [comment]
So is it a real problem we can solve or we can close it right here?
