### ISSUE TITLE
Alerts added with JS cannot be dismissed

### ISSUE THREAD

**Issue by squarefractal** [thednp/bootstrap.native#60]
Alerts added to the document using DOM operations in JS cannot be dismissed. A testcase is attached below:

```
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
  <div id="user-messages" class="container col-sm-12">
   <!-- <div class="alert alert-danger fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
    {message 1}
   </div> -->
  </div>
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.native/1.0.2/bootstrap-native.min.js"></script>
  <script type="text/javascript">
  function showMessage (html_msg) {
    var a = document.createElement("div");
    a.classList.add("alert", "alert-danger", "fade", "in");
    a.innerHTML = '<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
    a.innerHTML += html_msg;
    var x = document.getElementById("user-messages");
    x.appendChild(a);
  }
  showMessage("{message 2}");
  </script>
</body>
</html>
```

In addition, and quite strangely in fact, if you remove the commented out section in the above testcase, the alerts can be dismissed for the `user-messages` div (but not for any other div).

**Comment by thednp** [comment]
My demo showcases that later added alerts work properly, but please download the latest version and test, the SVN is not up to latest version, to make sure we're talking the same thing.

**Comment by squarefractal** [comment]
@thednp It is also an issue in the latest version.

**Comment by thednp** [comment]
OK then, please provide a test demo I can check.

**Comment by squarefractal** [comment]
@thednp Please check my first post, it contains a testcase and other details.

I initially didn't want to provide a JSFiddle since dismissible alerts do not work at all there at all (unlike the workaround I described in my first post) but [here](https://jsfiddle.net/qgc1oox9/) it is anyway.

**Comment by thednp** [comment]
jsfiddle doesn't work because it always adds js to the `<head>`. Here's your example on [codepen](http://codepen.io/thednp/pen/EyNEOZ).

**Comment by squarefractal** [comment]
Please read carefully what I said in the first post; but if it was not clear:

* I'm trying to add a dismissible alert using JS. 
* When I try to do this in an div that doesn't have an alert already in it as part of the HTML source (e.g. `<div class="user-messages"></div>`, the alert that's added with JS can't be dismissed.
* As a workaround to this, I can put an alert into the `div` (as shown in the commented section of my source), but this workaround shouldn't be needed, right?

**Comment by thednp** [comment]
Of course not. The Alert component can handle later added alerts on the fly as long as you have the right JS at the right place.

**Comment by squarefractal** [comment]
But then it's not working as intended! Please take the above file and try running it in a browser, first as is (i.e. no preexisting alert) and then with the commenting removed (i.e. with a preexisting alert), I hope you will understand what this issue is all about.

**Comment by thednp** [comment]
It seems Alert does not work in that case, when no alert component found and initialized.

Bu here's an easy fix, when you append the alert to your wrapper, also initialize it, here's the fixed [example](http://codepen.io/thednp/pen/pbNVRb). I added `new Alert(a);` to initialize after the append.

**Comment by squarefractal** [comment]
Thank you for looking into this and providing a workaround.

However, are there any plans to resolve this issue in bootstrap.native itself?

**Comment by thednp** [comment]
What I gave you isn't a workaround, it's the right way to do.
