### ISSUE TITLE
Modal buton in navbar

### ISSUE THREAD

**Issue by Aspie96** [thednp/bootstrap.native#61]
Hi!

I tried this snippet:
http://www.bootply.com/98624

And I noticed a difference in behaviour between this and the original Bootstrap.

Now, I know they don't have to be exactly the same, but in this case the behaviour of Bootstrap is probably better.

If I am using Bootstrap Native, when I click on a link to a modal button, I get redirected to whatever anchor there is in that tag.
This already is not really nice to see, but is per se no big deal.
The problem is when the button is, like in that example, embedded in a navbar: in this case, the modal window get closed immediately.

What is needed (I just tried) is `e.preventDefault()` in modal-native.js where you add the events to the triggers:
```javascript
var triggers = document.querySelectorAll('[data-toggle="modal"]'), tgl = triggers.length, i = 0;
for ( i;i<tgl;i++ ) {
	triggers[i].addEventListener('click', function(e) {
		e.preventDefault();
		var b = e.target,
		s = b.getAttribute('data-target') && b.getAttribute('data-target').replace('#','')
		|| b.getAttribute('href') && b.getAttribute('href').replace('#','');
		if ( document.getElementById( s ) === self.modal ) {
			self.open()
		}
	})
}
```

Thank you very much for your library.

**Comment by thednp** [comment]
Thanks commit done, I will also check asap.

**Comment by Aspie96** [comment]
Thank you very much.
Please, let me know!

**Comment by thednp** [comment]
Check out the new release, I think I also included this improvement.
