### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by Aspie96** [thednp/bootstrap.native#62]
Hi, still me.
I know it would require some major modifications, but is support for dynamic content planned to be implemented?

The code contains scripts like:
```javascript
var Tooltips = document.querySelectorAll('[data-toggle=tooltip]'), i = 0, tpl = Tooltips.length;
for (i;i<tpl;i++){  
	var item = Tooltips[i], options = {};
	options.animation = item.getAttribute('data-animation');
	options.placement = item.getAttribute('data-placement');
	options.duration = item.getAttribute('data-duration');
	options.delay = item.getAttribute('data-delay');
	new Tooltip(item,options);
}
```

The problem with that is that it will not work with dinamically added content (which many sites use).

There are already some events attached to `document`, such as in:
```javascript
document.addEventListener('click', this.close, false);
```

There should be only one event handler for clicks, attached to the document, so that it can work with dynamic content as well.

Although the code would need to be modified in different places, it should not be a big problem per se.
The problem is when there is a FOR cycle like the one I quoted before (which, of course, could not be done), but there should be some kind of work-around for each specific case.

Thank you very much in advance!

**Comment by thednp** [comment]
It has been [discussed before](https://github.com/thednp/bootstrap.native/issues/60#issuecomment-227832430), this cannot work.

**Comment by Aspie96** [comment]
In my case, thouhg, I have to edit the content of the page using innerHTML (because I use templates).

Is there any workaround to make it work in this case?

**Comment by thednp** [comment]
There is no workaround, there's only the hard way, re-init the functions you need via

```javascript
new Tooltip('selector');
```

and you are fine.

**Comment by Aspie96** [comment]
Just in case someone wants to check it out too:

https://github.com/Aspie96/bootstrap.native.dynamic

**Comment by mathieuleclaire** [comment]
@Aspie96 You're lib is really cool, thanks ! I had typically the problem of generating tabs dynamically and I did find any options to run them properly at runtime. This work properly without any modification of my code.

**Comment by Aspie96** [comment]
Thank you, mate!

As for the reasons NOT to use my library, read this:
https://github.com/thednp/bootstrap.native/issues/102#issuecomment-274920136

I am not suggesting that you should not use it, of course (I shared it precisely so that you could use it), but I am saying that you should check that out first.

**Comment by mathieuleclaire** [comment]
What do you mean, it renders the page slower ?

**Comment by thednp** [comment]
No, but the JavaScript runtime is much slower, and gets even slower the more elements you append to the document, a quick info on that [here](http://stackoverflow.com/questions/6576853/jquery-delegate-performance-on-the-click-event-on-large-lists-slows-down-if-yo) (I hope I didn't missclick the link)

**Comment by Aspie96** [comment]
Still, I am using my version on my own website and it works perfectly (and, of course, many many people use jQuery or other libraries), so it might be a completely fine solution from what you wanna do.
