### ISSUE TITLE
Carousel + Modal Issues with Internet Explorer 11

### ISSUE THREAD

**Issue by UtilityNetwork** [thednp/bootstrap.native#66]
Hi,

Currently, we are using the bootstrap.native.js and we found a few issues involving Internet Explorer 11. 

With the bootstrap carousel, it doesn't work at all in Internet Explorer 11. It works only if we insert this polyfill code along with the native javascript.

`

	if ( typeof window.CustomEvent === "function" ) return false;

	function CustomEvent ( event, params ) {
		     params = params || { bubbles: false, cancelable: false, detail: undefined };
			 var evt = document.createEvent( 'CustomEvent' );
			 evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
			 return evt;
			 }

	CustomEvent.prototype = window.Event.prototype;

	window.CustomEvent = CustomEvent;
`

Also, we are using a modal that opens up an audio dialog. The modal works when clicking on it to open it up but when it is closed, the audio keeps on playing. Alas, we fixed it via:
`	

```
function pauseReset(){
		var sounds = document.getElementsByTagName('audio');
		  for(var i=0; i<sounds.length; i++) {
			sounds[i].pause();
		    sounds[i].currentTime = 0;
		  }
	}
```

```
	document.onkeydown = function(evt) {
	    evt = evt || window.event;
	    if (evt.keyCode == 27) {
	    	pauseReset();
	    }
	};
	
	
   document.addEventListener('click', function(e){ 	
     if (document.querySelector('.modal-content').contains(e.target)){
      	// inside box
      } else{
    	 //outside box 
    	  pauseReset();
      }
    });`
```

Just wondering if these issues on Internet Explorer 11 will be fixed with the next release instead of having to use these polyfill javascript to fix it.

Thanks

**Comment by thednp** [comment]
> With the bootstrap carousel, it doesn't work at all in Internet Explorer 11. It works only if we insert this polyfill code along with the native javascript.

IE11 works with my minifill just fine. Go for it.

About the other issue, that's already custom build, you should use a fork of your own to do the tricks you need, I won't include such stuff in the code, very few would use it.

**Comment by roura356a** [comment]
I confirm this, we are developing a large application and carousel is not working for IE10 & IE11 users. Thanks @UtilityNetwork for mentioning the polyfill. I'll try it.

**Comment by thednp** [comment]
@roura356a try minifill.

**Comment by roura356a** [comment]
Thanks @thednp!
