### ISSUE TITLE
Are there any plans to support bootstrap v4 any time soon ?

### ISSUE THREAD

**Issue by Avcajaraville** [thednp/bootstrap.native#67]
I know bootstrap v4 still in alpha. Im planning to deploy an e commerce app in the next two months using bootstrap v4 alpha-3 and was wondering if I could get rid of jQuery (we only needed it for god damn selectors and jQuery plugins...).

Thanks !

**Comment by thednp** [comment]
https://github.com/thednp/bootstrap.native/issues/37

**Comment by thednp** [comment]
http://thednp.github.io/bootstrap.native/v4.html
