### ISSUE TITLE
dropdown menu only allows nesting of two children

### ISSUE THREAD

**Issue by Martlark** [thednp/bootstrap.native#68]
Can you allow arbitrary depth of nested children?  At the moment the menu only checks for 
`target === self.menu || target.parentNode === self.menu || target.parentNode.parentNode === self.menu`
a depth of two.  I have some complicated menu buttons that are formatted using many nested divs.

**Comment by thednp** [comment]
If you have an idea on how to achieve that with almost the same amount of code, please feel free to submit a PR.

**Comment by Martlark** [comment]
could cheat and just have a very long list of .parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode; anyways, I'll think on it.

**Comment by thednp** [comment]
I think working on a menu with a deep structure `dropdown-native.js` may not be the solution, please try my other script here https://github.com/thednp/navbar.js, it's quite the thing.

**Comment by thednp** [comment]
Update: I just tested level 3 menu nesting and it works as expected, I think as long as you use the proper Bootstrap markup you can go deep with no limit.

FYI: `target === self.menu || target.parentNode === self.menu || target.parentNode.parentNode === self.menu` has another use, it checks whether you clicked on a button icon.

I believe your markup is not valid HTML5 in the first place.

**Comment by Martlark** [comment]
It was not valid HTML5, well spotted.
