### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by mathieuleclaire** [thednp/bootstrap.native#69]
Hi,
Is it possible to generate a version in .ts or in d.ts of the bootstrap-native.js ?
Thanks

Mathieu

**Comment by thednp** [comment]
Hi. I'm not doing TypeScript, but if this would help community, please feel free to post a PR.
Thank you

**Comment by mathieuleclaire** [comment]
Hi, I do not do TypeScript neither :). I work with scala-js, and to use javascript libs, I need to build a wrapping file. A converter enables to convert a ts.d file to the expected wrapping file. This [repo](https://github.com/DefinitelyTyped/DefinitelyTyped) list them.

**Comment by thednp** [comment]
I see, well, I will close this down until we have someone to deliver in that regard.

**Comment by itbrandonsilva** [comment]
@thednp I may be interested in tackling this (providing an entry for us in @types). Let me know if you'd support this.

**Comment by thednp** [comment]
If this involves drastically rewriting the code we may not be interested in this stuff.

**Comment by itbrandonsilva** [comment]
I spent some time reevaluating my needs for this lib, and it doesn't seem I'll be needing it, ultimately.

But it actually wouldn't require any changes _at all_ to the lib itself before contributing type definitions to DefinitelyTyped.
