### ISSUE TITLE
Dropdown menu does not close

### ISSUE THREAD

**Issue by egmen** [thednp/bootstrap.native#72]
Dropdown menu does not close after clicking any meny item.
This happens even on example [http://thednp.github.io/bootstrap.native/#exampleDropdown](http://thednp.github.io/bootstrap.native/#exampleDropdown) in every browser, I've checked IE11, Chrome and Firefox.
Original bootstrap javascript has such behavior and works well [http://getbootstrap.com/javascript/#dropdowns](http://getbootstrap.com/javascript/#dropdowns)

**Comment by thednp** [comment]
Indeed, our implementation here is a bit different, slightly more simple, it handles forms inside `dropdown-menu` and when the when the click target is a link, it goes to that link.

**Comment by pors** [comment]
Hi @thednp, awesome library! Saves me many bytes :)

So what is the solution if you want it to close on clicking a menu item? E.g. in case you use named anchors?

**Comment by thednp** [comment]
@pors You can always fork the script and do something like this:

```
    if ( target === self.menu || target.parentNode === self.menu || target.parentNode.parentNode === self.menu || (/\#/.test(target.href) || /\#/.test(target.parentNode.href)) ) {
      self.toggle(e);
    }  else if ( children && children.indexOf(target) > -1  ) {
      return;
    } else { self.close(); }
```

Haven't tested but you probably get the point.

**Comment by pors** [comment]
Wow, that's a fast answer :)

Will do what you propose, thanks!

**Comment by thednp** [comment]
@pors and @egmen the future version will have an option to control this behavior. 

By default the new option will be disabled `false` which will make the Dropdown same as before, but when `true`, it will not close, as you know it is now, and even better.
