### ISSUE TITLE
Carousel Events are incorrect

### ISSUE THREAD

**Issue by RyanZim** [thednp/bootstrap.native#73]
The carousel emits two events: `slide` and `slid`.

The official bootstrap docs state that the `slide` event should fire first: http://getbootstrap.com/javascript/#carousel-events. (This makes sense, since `slid` is the past tense of `slide`.)

In bootstrap.native, the `slid` event fires first. This is incorrect.

Here are JSBins demonstrating the problem:

- jQuery bootstrap: http://jsbin.com/tapekeyata/edit?js,console,output
- bootstrap.native: http://jsbin.com/hutibawuyi/1/edit?js,console,output

Notice the order that the events fire. This is a bug.

@thednp Urgent :exclamation:

**Comment by RyanZim** [comment]
I'm working on a PR.

**Comment by thednp** [comment]
OK, looking at it.

**Comment by RyanZim** [comment]
@thednp Done, #74.
