### ISSUE TITLE
span in modal trigger button on chrome

### ISSUE THREAD

**Issue by nivoliev** [thednp/bootstrap.native#77]
I have a problem to trigger a modal with a button when the button contains a span (glyphicon). On chromium, when the span is clicked, the click event is triggered on the span, which has no `data-target` attribute, and therefore the modal is not opened. I am not very skilled with bootstrap or web development in general so the bug may lie between the chair and the keyboard and my fix is maybe not the right one, but modifying

```javascript
this.trigger = function() {
  var triggers = document.querySelectorAll('[data-toggle="modal"]'), tgl = triggers.length, i = 0;
  for ( i;i<tgl;i++ ) {
    triggers[i].addEventListener('click', function(e) {
      e.preventDefault();
      var b = e.target,
      s = b.getAttribute('data-target') && b.getAttribute('data-target').replace('#','')
      || b.getAttribute('href') && b.getAttribute('href').replace('#','');
      if ( document.getElementById( s ) === self.modal ) {
        self.open()
      }
    })
  }
}
```
using `b = event.currentTarget` instead of `b = target` does the trick for me.

**Comment by thednp** [comment]
I will investigate the issue and post a fix asap. Thanks for reporting.

**Comment by thednp** [comment]
Have you tried with `var b = this`? This seems to work for me.

**Comment by RyanZim** [comment]
`this` should work as well, as long as you don't accidentally add a `bind()` call down the road for some reason. However, I would favor `e.currentTarget` since it's more clear what the value actually is.

**Comment by thednp** [comment]
I will commit with `this` and will also add this for the close handler.

**Comment by thednp** [comment]
@nivoliev please check the demo.

**Comment by nivoliev** [comment]
thanks for the fix, however using `this` neither the button nor the icon triggers the modal.

**Comment by thednp** [comment]
@nivoliev https://sendvid.com/5tkvc3zy

**Comment by nivoliev** [comment]
Seems like my bootstrap-native version was too old, and using `this` in that version didn't do. Using a fresh bootstrap-native, it works, many thanks.

**Comment by thednp** [comment]
Good.
