### ISSUE TITLE
In dist/bootstrap.native.js, window.Modal instead of window.Dropdown

### ISSUE THREAD

**Issue by serge-kilimoff** [thednp/bootstrap.native#79]
https://github.com/thednp/bootstrap.native/blob/master/dist/bootstrap-native.js#L666

`var Dropdown = window.Modal = function( element) {`

instead of

`var Dropdown = window.Dropdown = function( element) {`

Therefore, Dropdown does not work because further crushed:

`var Modal = window.Modal = function(element, options) {`

Thanks !

**Comment by thednp** [comment]
Wow thanks for the find.
https://github.com/thednp/bootstrap.native/commit/905754f427c32a908b2d16d515b05078e2a255a9
