### ISSUE TITLE
Carousel prev/next slide navigation with keyboard arrows keys doesn't work

### ISSUE THREAD

**Issue by mgiulio** [thednp/bootstrap.native#83]
The relative code is implemented, but pressing the left or arrow key when the component has the keyboard focus nothing happens.

**Comment by RyanZim** [comment]
@mgiulio Do you have `data-keyboard="true"` set? http://thednp.github.io/bootstrap.native/#exampleCarousel. Keyboard navigation is not turned on by default.

**Comment by mgiulio** [comment]
Oops, missed that one! I was assuming keyboard navigation was on by default as in BS. Sorry:)

**Comment by RyanZim** [comment]
No problem, we all do that sometimes. :wink:

**Comment by TusharFelix** [comment]
Could you tell me how should i enable carousel-slide for touch displays , carousel slider using mobile left/right swipe ? by just using vanilla javascript? i have searched a lot but am unable to find a solution for this issue ..

**Comment by thednp** [comment]
This feature is planned to be added into the original BS4 plugin so we will implement that too.
