### ISSUE TITLE
minified version doesn't work with webpack

### ISSUE THREAD

**Issue by eldyvoon** [thednp/bootstrap.native#84]
I use webpack for bundling. When I do import '../node_modules/bootstrap.native/dist/bootstrap-native.min.js'; it says 

`Error in ./~/bootstrap.native/dist/bootstrap-native.min.js
Module parse failed: /Users/Documents/practice/node_modules/bootstrap.native/dist/bootstrap-native.min.js Unexpected token (3:0)`

but it's working with the non minified version, I wonder.

**Comment by thednp** [comment]
I believe @RyanZim would take a look at that anytime now.

**Comment by RyanZim** [comment]
OK, will look into it.

**Comment by RyanZim** [comment]
@eldyvoon Are you using v1.0.4 or the latest `master`? If you're using v1.0.4, try using `master` and see if that works. (Uninstall `bootstrap.native` and run `npm install thednp/bootstrap.native` to install from the latest master.)

It does look like the minified build for v1.0.4 might have an error (fixed in `master`).

**Comment by thednp** [comment]
Soon we have it online on npm.

**Comment by RyanZim** [comment]
@thednp Hang on, make sure @eldyvoon can get master working before we push a release.

**Comment by eldyvoon** [comment]
yup the master has no error, it's working now.

**Comment by RyanZim** [comment]
@thednp It looks like v1.0.4's minification was buggy, could you publish a new release?

**Comment by RyanZim** [comment]
P.S. Make sure to run `npm run build` before publishing.

**Comment by thednp** [comment]
Yes Ryan. Thanks :)

**Comment by eldyvoon** [comment]
Thank you for the lighting fixes guy, appreciate that!

**Comment by RyanZim** [comment]
@eldyvoon When @thednp makes a new release, you will want to uninstall `thednp/bootstrap.native` and install `bootstrap.native` again.

**Comment by thednp** [comment]
@RyanZim I will tag a new release and publish from the release, by the way do you think we should go with a new release right away?

**Comment by RyanZim** [comment]
> by the way do you think we should go with a new release right away?

Not sure what you mean; we should make a release today IMO.

**Comment by thednp** [comment]
@eldyvoon Please test the new release. Thank you.
