### ISSUE TITLE
A much practical example showing how let bootstrap.native works with npm, browserify, babelify.

### ISSUE THREAD

**Issue by Gfast2** [thednp/bootstrap.native#86]
```
var bsn = require("bootstrap.native");
var browser = require("mock-browser");
global.window = browser.createWindow();
global.document = browser.createDocument();

// Now it's safe to use bootstrap.native and expecting the properties to be the actual component classes.
var Button = bsn.Button(); // Create the button class and return it.

var $btn = document.createElement("button");
var myButton = new Button(... $btn and options ...); // Create a button and do a test.
```
Hi, 
Right now I'm working on the Webinterface of a device. Because I've gone a long way with browserify, npm and babelify only (without Bootstrap or JQuery). And need the rocking feature that bootstrap.native delivered. After about 3 hours brain burning, I even can not add a dummy button from it. The code above is part of the howto. It just not helpful enough for me. 

Is there someone would like to give me a more practical example?

**Comment by thednp** [comment]
I believe @RyanZim has an idea about that, I'm not with this stuff anyways ;)

**Comment by RyanZim** [comment]
Yeah, docs need updated. Will do a PR.

Try this:

```
// Load bootstrap.native
var bsn = require("bootstrap.native");
// This will get the data- attributes working

// If you need custom code:
var myButton = new bsn.Button(document.getElementById('button')); // etc.
```

You probably won't need custom code unless you're dynamically adding elements to the DOM.

**Comment by thednp** [comment]
Thanks @RyanZim, a life saver ;)

**Comment by Gfast2** [comment]
Super Cool!, Thanks @RyanZim !

I write acutally modules in Javascript. And call them when I need them. All coponents are defined in javascript like:
```
let btn = document.creatElement("button"); 
btn.innerHTML = "Hey thednp";
mainDom.appendChild(btn);
```

So when I do the trick like you said: I can't just `appenChild()` the from `new bsn.Button(btn)` wrapped `myButton` anymore. Chrome told me:

`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

It's pretty interesting! Because of the state-of-the-art javascript stuffs, I just get less interest in web developing... : (

**Comment by RyanZim** [comment]
OK, if you're creating elements, you'll want to do something like:

```
let btn = document.creatElement("button"); 
btn.innerHTML = "Hey thednp";
btn.id = "myBtn";
mainDom.appendChild(btn);
var myButton = new bsn.Button(document.getElementById("myBtn"));
```

That should work.

I'm not sure if `new bsn.Button(btn)` would work before calling `appendChild()`; try this and see if it works:

```
let btn = document.creatElement("button"); 
btn.innerHTML = "Hey thednp";
btn.id = "myBtn";
var myButton = new bsn.Button(btn);
mainDom.appendChild(btn);
```
If both methods work, the second one is preferable.

**Comment by Gfast2** [comment]
Hi @RyanZim @thednp ,
you are awesome! Since the project I'm working on have to run with hardwares that only available in my working places. I will tell you the result morning...

Thanks again for the support! Hopefully I can use bootstrap.native in it.

**Comment by thednp** [comment]
@Gfast2 we're glad we could help

**Comment by Gfast2** [comment]
```
	let bsn = require('bootstrap.native');

	let button = document.createElement('button');
	button.id = 'btnTest';
	button.className = 'btn btn-default';
	button.innerHTML = 'Hello Bootstrap.Native';

	rows[10].appendChild(button);
	containerDom.appendChild(rows[10]);
	dom.appendChild(containerDom);

	// Create a button:
	var btn = new bsn.Button( /*document.getElementById("btnTest")*/button );
	btn.className = 'btn btn-danger';

	/*
	<button type="button" id="myButton" data-toggle="button" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">
  		Loading state
	</button>
	*/
```

After about 20 minute exploration. I figure out, I have to `append` the elements on the site first, then I am permitted to wrap it into `new bsn.Button()`. By the way I've to define some css class for this button before, If not chrome will give me other Errors, too.
After the initialization, I've tried to change the class of the bootstrap.native button. But without success.

I'm thinking about trying other frameworks, but I need bootstrap stuff a lot. So I just can't actually write them all...

So thank you again. I'll keep on tuning.

**Comment by thednp** [comment]
@Gfast2 you actually have access to the button, but your lines should look like this:

```javascript
    // Create a button:
    var btn = new bsn.Button( /*document.getElementById("btnTest")*/button );
   btn..btn.className = 'btn btn-danger'; // notice the additional btn
```

The `this` of your invocation holds track the element in `this.btn`, I think you can investigate the code and learn more what you can actually do.

**Comment by Gfast2** [comment]
@thednp thanks again! It WORKS beautifully!!!
Now I'm start to trying arguments to the button, to let it do the trick like in the example...
```
<button type="button" id="myButton" data-toggle="button" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">
        Loading state
</button>
```
If you have time, you can write it here. If not, I'd try to figure it out myself.

**Comment by thednp** [comment]
Can you clarify your question, I cannot figure out what you're after.

**Comment by Gfast2** [comment]
Yes. My question is:
if you define a button within the `<>` fashion. The parameter like `data-toggle="button"` or `data-loading-text="Loading..."` will have no problem what so ever. But if you do it in other way like we said:
`btn.btn.className = 'btn btn-default';`
You don't have the chance to define the others. For instance:
`btn.btn.data-toggle = "button";` will be not comipled.

So I'm still tunning around...

**Comment by thednp** [comment]
The `Button` script has 2 features: 
* set button state
* toggle radios and checkboxes

It doesn't have, also the original script to my knowledge, a way to toggle classes.

**Comment by Gfast2** [comment]
@thednp Thanks. I'm still fighting with it.If I get the answer eventually. I'd write here.

**Comment by Gfast2** [comment]
After such a long time. I decided to not use this framework. 

I even try to _**inject**_ a button into a `td` of the table. It still not works at all. Pretty frustrated.
```
let bsn = require('bootstrap.native');
let newLine = createTD();
newLine.innerHTML = "<button type='button' id='myButton' data-toggle='button' data-loading-text='Loading...' class='btn btn-success' autocomplete='off'>Loading state</button>";	
rows[10].appendChild(newLine);
	
dom.appendChild(containerDom);
```

**Comment by thednp** [comment]
It's not most fascinating thing in the world, it's an open source project. If you can find a way to make it work share it with us, because there's nothing else like it.
