### ISSUE TITLE
DropDown Class

### ISSUE THREAD

**Issue by mathieuleclaire** [thednp/bootstrap.native#88]
Hi,
I need to instanciate a Dropdown class to be abble to call the close() method on it (in order to call it programatically). But I cannot instanciate the Dropdown class: ``` Uncaught TypeError: $g.Dropdown is not a constructor```

Thanks

**Comment by thednp** [comment]
You have some code to look at?

**Comment by mathieuleclaire** [comment]
I call the javascript from a scala mapping (thanks to the scala-js lib). It works perfeclty with the Modal where my wrapping is written this way (js.native means that the function implementation is taken from the bootstrap-native.js itself ): 
```scala
@JSName("Modal")
@js.native
class Modal(element: Element) extends js.Object {

  def open(): Unit = js.native
  def close(): Unit = js.native
}
```
But it does not with for Dropdowns with the following code: 
```scala
@JSName("Dropdown")
@js.native
class Dropdown(element: Element) extends js.Object {

  def close(): Unit = js.native
}
```
It seems from the doc that both classes APIs are very similar, so that I thought it would be straight forward to achieve the same for the Dropdowns. But it does not. Any idea why ?
Thanks

**Comment by thednp** [comment]
ATM I have no idea. 

I am not familiar with `scala-js`, I suggest investigating yourself or look for solutions at `scala-js` devs/docs.

**Comment by mathieuleclaire** [comment]
But do you confirm, that I am supposed to be abble to instanciate the Dropdown class and to invoke the close function on it ?

**Comment by thednp** [comment]
If your script is at the bottom along with the `Dropdown` script AND your button is actually present within an HTML page, it should work fine.
