### ISSUE TITLE
Cannot set property 'Affix' of undefined

### ISSUE THREAD

**Issue by micahstubbs** [thednp/bootstrap.native#90]
thanks for `bootstrap.native` - it's saved me from hours of terrible jQuery debugging. have a friendly bug report, along with a fix that worked for me.

![screen shot 2016-10-21 at 5 42 34 pm](https://cloud.githubusercontent.com/assets/2119400/19615567/d036f078-97b5-11e6-860c-2b3df11e80dd.png)
![screen shot 2016-10-21 at 5 42 41 pm](https://cloud.githubusercontent.com/assets/2119400/19615568/d1b20c8a-97b5-11e6-9be6-112fee1e10cb.png)

this error appears when I install `npm install --save bootstrap.native` then bundle it up with the rest of [my project](https://github.com/micahstubbs/d3-voronoi-scatterplot) using [rollup](http://rollupjs.org/?version=0.36.3)

**Comment by thednp** [comment]
I don't know about this, I think @RyanZim would disagree.

**Comment by RyanZim** [comment]
@micahstubbs @thednp `root` is `this`, which is usually `window`, perhaps rollup's bundles work differently. I've worked with rollup in the past, though I never used `bootstrap.native` with it.

I'll do a bit of investigation and report back.

**Comment by RyanZim** [comment]
@micahstubbs Thanks for reporting! Doing a little research, rollup does quite a bit of transformations to the bootstrap.native code. Can you make a commit on a separate branch in your repo that demonstrates the problem? Sorry for the bother, but I'm not sure if this is a rollup bug.

**Comment by RyanZim** [comment]
@micahstubbs I can't really investigate this without a commit that demonstrates the issue. I cloned your repo, switched the bootstrap.native dependency back to the normal npm version, recompiled, and received no such error.

Also, that line of code should only run in a browser global environment; rollup runs non-es6 modules in a commonjs environment. Perhaps you weren't using `rollup-plugin-commonjs` when you encountered this error?

**Comment by micahstubbs** [comment]
@RyanZim your last guess is spot on.  in the meantime, I've figured out how to use `rollup-plugin-commonjs`.  I just changed `window` back to `root` in my custom build of `bootstrap.native` and verified that the error message doesn't appear.  thanks for the comments!

**Comment by RyanZim** [comment]
Glad I could help!

**Comment by midzer** [comment]
Bundling bootstrap.native using Webpack 3 + Babel [env] preset, i encounter `new Modal` being undefined on call https://github.com/midzer/eisolzried/blob/master/_tasks/scripts.js

Already tried playing around with some parameter...any1 know what i am missing?

**Comment by thednp** [comment]
I'm not an experienced webpack user, but @midzer are you trying to build BSN into your codebase or are you importing it built in altogether?

**Comment by midzer** [comment]
@thednp Basically i want to merge compiled `bootstrap.native.js` together with some other libraries and own code into `main.js` which serves as bundle for every page

**Comment by thednp** [comment]
So make sure your link `dist/boostrap.native.js` properly into your bundle. That's the only thing I can think of.
