### ISSUE TITLE
Example page totally broken due to mixed content

### ISSUE THREAD

**Issue by pitaj** [thednp/bootstrap.native#92]
> Mixed Content: The page at 'https://thednp.github.io/bootstrap.native/' was loaded over HTTPS, but requested an insecure stylesheet 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.

I suggest switching to using `https://` or just `//` in the URLs for external resources. Cheers!

**Comment by RyanZim** [comment]
Should be `https://`. @thednp I don't have time to fix this ATM, can you?

**Comment by thednp** [comment]
Thanks for reporting.
