### ISSUE TITLE
jsdelivr.net CDN link on homepage returns 404

### ISSUE THREAD

**Issue by MuffinMan10110** [thednp/bootstrap.native#93]
Just letting you know in case you weren't aware. On the home page under the section "Load from the CDN"  there is a code snippet for two CDN's, the first one: Jsdelivr cdn returns 404, but the other one works fine.

http://thednp.github.io/bootstrap.native/

**Comment by thednp** [comment]
Please try

```markup
<script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.native/1.0.5/bootstrap-native.min.js"></script>
```

**Comment by MuffinMan10110** [comment]
@thednp Looks good! 👍

**Comment by thednp** [comment]
Sorry for the confusion, please allow me to explain: latest master branch 1.0.5 is equivalent to latest npm branch 1.1.0 due to some updates pushed into npm for build testing purposes.
