### ISSUE TITLE
[question] regarding the build script

### ISSUE THREAD

**Issue by thednp** [thednp/bootstrap.native#95]
This probably goes to @RyanZim but also anyone who knows this stuff: how do you actually use the build.js script to create a custom build? 

The basic usage says:
```
'node build.js [--minify] [--ignore=<modules>...|--only=<modules>...]'
```
could I use this for instance?

```
'node build.js --minify --ignore=['modal-native.js']'
```
or

```
'node build.js --minify --only=['modal-native.js']'
```

**Comment by RyanZim** [comment]
@thednp The build script is pretty loose about what arguments it accepts.

Both of the examples you posted work correctly; there are many more ways that it will accept them.

The script doesn't care if you include the `-native.js` part; this will also work:

    node build.js --minify --ignore=['modal']

The argument parser doesn't care about your formatting; this will bundle just the `alert` and `modal` modules:

    node build.js --minify --only alert modal

These are just a few examples of the arguments it will accept. If you're not sure if something will work, just try it! In most cases it will work. You can check the `Included modules:` list in the output to confirm that the correct modules are being compiled.

**Comment by thednp** [comment]
Thank you @RyanZim
