### ISSUE TITLE
'className' is null or not an object

### ISSUE THREAD

**Issue by duffyg** [thednp/bootstrap.native#96]
I'm getting this in the _resize function at statement 898. Overlay is undefined as opposed to null, but the statement is only checking for not null:
if ( overlay !== null && /\bin/.test(overlay.className) ) 
if I change it to truthy instead the problem goes away:
if ( overlay && /\bin/.test(overlay.className) ) 
 
I'm using the default polyfill.min.js with getComputedStyle. Problem occurs on IE8 running on XP.

**Comment by thednp** [comment]
Thanks for the report, I will do some test on my virtual machine asap.

**Comment by thednp** [comment]
Please try the latest minifill or the online demo on your testing environment and let me know if that solves it.

**Comment by duffyg** [comment]
Sorry, where can I find the latest minifill? Also why minifill and not bootstrap-native? I'm using _cdn.polyfill.io/v2/polyfill.min.js_

**Comment by thednp** [comment]
http://www.jsdelivr.com/projects/minifill

**Comment by duffyg** [comment]
If I move to minifill I'll need a polyfill for querySelector. What's the recommended solution?

**Comment by thednp** [comment]
You don't need a polyfill for `querySelector`, unless you address <IE8, see http://caniuse.com/#search=querySelector

Did the minifill work?

**Comment by duffyg** [comment]
See [quirksmode](http://quirksmode.org/dom/core/#t13) where it says the support is incomplete in IE8. Without a polyfill I get _Object doesn't support this property or method_ but with the polyfill from _https://cdn.polyfill.io/v2/polyfill.min.js?features=default,getComputedStyle_ everything's fine (I'm running in IE8 standards mode). I'm converting an existing jquery project so some of the queries are complex. I've no problem patching in the querySelect from polyfill.io into my own code if you think that's the way to go. I was just hoping to get all the polyfills from one source and with one call, if possible.

**Comment by duffyg** [comment]
Quick update:
1. Without a polyfill I get _Invalid argument_ and not the error reported above. I can confirm that querySelector/querySelectorAll are present in IE8 but they can't handle complex selectors.
2. Mixing the querySelector polyfill with minifill doesn't seem to work. It gives a _Member not found_ error while trying to set a constructor. 

I removed the complex selector and the polyfill and tested it with minifill. It works perfectly.

**Comment by thednp** [comment]
Good!! that's the way to go, and we finally close this.
