### ISSUE TITLE
Article on Sitepoint

### ISSUE THREAD

**Issue by mgiulio** [thednp/bootstrap.native#97]
Hi @thednp , I was not able to find you on Twitter so I am (ab)using the GH issue tracker to inform you about an [article on Sitepoint](https://www.sitepoint.com/use-bootstrap-components-without-jquery/) on this project. 

Cheers,
mg

**Comment by thednp** [comment]
I thank you so much for the article, I just got to my PC and will get to reading. I will post feedback asap.

**Comment by thednp** [comment]
@mgiulio can you edit that post? We need to make some things clear. (I am now starting to write to you in this post)

**Comment by mgiulio** [comment]
Hey @thednp , thanks for your feedback!
 
I cannot directly edit the post, but as soon I've 'digested' your findings I can talk to my editor about some editing. 
But please notice that the article is only a 'Quick Tip', that is, a short piece that cannot go into much deep. So, for instance, a deeper explanation about the polyfills as you report in the 'More Usage instructions' would be a bit overkill. Infact, a similar suggestion was reported by a peer reviewer but then it was decided to not include it, referring to your documentation for further details. 
Consider it as an intro/presentation of the project. 
Also, remember that it is even possible to discuss something in the comments.
 
I'll be back here ASAP, thanks,
mg

**Comment by thednp** [comment]
Right. I will leave this "issue" open until we got some necessary fixes to the article.

Until then, stay awesome ;)

**Comment by mgiulio** [comment]
Hi @thednp , here I am!

I'm going to submit to the editor the fixes about the 'itself' typo and the bsn.js abbreviation(yes, it is a bit misleading: the intention it wasn't to refer to the script file but to use it just as an abbreviation, like jq; infact, initially we had bs.js instead of bootstrap.js).

For the other topics, please feel free to expose them in the comments for now.

Thanks again for your review, keep up the good work,
mg

**Comment by thednp** [comment]
@mgiulio you really have to do some article edits, the new version coming soon is going to fix most issues and missings, but most importantly size improvements and feature wise.

Stay in touch with the next commit.
