### ISSUE TITLE
'Next' & 'Prev'

### ISSUE THREAD

**Issue by malcocerGit** [thednp/bootstrap.native#99]
I want to get the original events as 'next' and 'prev', but I don't know how exactly add this on the script, someone have a example or help me. I remember someone post a example but I don't find it.

This is for use with Hammer with touch events.

**Comment by thednp** [comment]
Hey what are you talking about? Can you try to be more explicit?

**Comment by malcocerGit** [comment]
Sure, I'm trying to expose ".carousel('prev')", but I don't know how or where add the code.

**Comment by thednp** [comment]
http://thednp.github.io/bootstrap.native/#exampleCarousel

The script doesn't do exactly like the original, the next and prev actions are applied to elements having the `data-slide="next"` attribute and that's it.

Why don't you inspect the code a bit? Maybe you can find the answer.

**Comment by malcocerGit** [comment]
Sure, I have done it along the day, the problem is I want to do something like this

```
		var carousel = document.getElementById('carouselHtml');

		Hammer(carousel).on('swipleft', function(){
			carousel.bsn.Carousel('prev');
		});
```

**Comment by thednp** [comment]
I would do this:

* remove the `data-ride="carousel"` attribute
* init carousel manually

```
var carousel = document.getElementById('carouselHtml');
var myBSNCarousel = new bsn.Carousel(carousel);

Hammer(carousel).on('swipleft', function(e){ // we need to pass the eventObject
  myBSNCarousel.direction = 'left'; // override the direction based on swipe direction
  var active = myBSNCarousel._getActiveIndex(); // the current active
  var allSlides = this.total; // this is the total number of slides
  var newSlide = active + 1 > allSlides - 1 ? 0 : active + 1; // determine the index for new slide

  myBSNCarousel._slideTo(newSlide,e);
});

Hammer(carousel).on('swipright', function(e){ // we need to pass the eventObject
  myBSNCarousel.direction = 'right'; // override the direction based on swipe direction
  var active = myBSNCarousel._getActiveIndex(); // the current active
  var allSlides = this.total; // this is the total number of slides
  var newSlide = active === 0 ?  allSlides - 1  : active - 1; // determine the index for new slide

  myBSNCarousel._slideTo(newSlide,e);
});
```

Try it and let me know. But I'm sure you'll figure it out, especially if you would read the code a little bit.

**Comment by malcocerGit** [comment]
Oh! thanks, I had not thought about that idea. I'm will try and back post my feedback. Regards.
